ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Das Skript unterstützt nur 64-Bit-Windows
UnsupportedOSBuild                        = \nDas Skript unterstützt Windows 10 Enterprise LTSC 2019
UpdateWarning                             = \nDas kumulative Windows 10-Update wurde installiert: {0}. Unterstütztes kumulatives Update: 4131 und höher. Führen Sie Windows Update aus und versuchen Sie es erneut
UnsupportedLanguageMode                   = \nDie PowerShell-Sitzung wird in einem eingeschränkten Sprachmodus ausgeführt
LoggedInUserNotAdmin                      = \nDer angemeldete Benutzer hat keine Administratorrechte
UnsupportedPowerShell                     = \nSie versuchen ein Skript über PowerShell {0}.{1} auszuführen. Das Skript in der entsprechenden PowerShell-Version ausführen
UnsupportedHost                           = \nDas Skript unterstützt nicht die Ausführung über {0}
Win10TweakerWarning                       = \nWahrscheinlich wurde Ihr Betriebssystem über die Win 10 Tweaker-Hintertür infiziert
TweakerWarning                            = \nDie Stabilität des Windows-Betriebssystems kann durch die Verwendung des {0} beeinträchtigt worden sein. Installieren Sie Windows vorsichtshalber neu
bin                                       = \nIm Ordner "bin" befinden sich keine Dateien. Bitte das Archiv erneut herunterladen
RebootPending                             = \nDer PC wartet darauf, neu gestartet zu werden
UnsupportedRelease                        = \nNeue Version gefunden
CustomizationWarning                      = \nHaben Sie alle Funktionen in der voreingestellten Datei {0} angepasst, bevor Sie Sophia Script ausführen?
DefenderBroken                            = \nMicrosoft Defender defekt oder aus dem Betriebssystem entfernt
UpdateDefender                            = \nDie Microsoft Defender-Definitionen sind veraltet. Führen Sie Windows Update aus und versuchen Sie es erneut.
ControlledFolderAccessDisabled            = Kontrollierter Ordnerzugriff deaktiviert
ScheduledTasks                            = Geplante Aufgaben
WindowsFeaturesTitle                      = Windows-Features
OptionalFeaturesTitle                     = Optionale Features
EnableHardwareVT                          = Virtualisierung in UEFI aktivieren
UserShellFolderNotEmpty                   = Im Ordner "{0}" befinden sich noch Dateien \nVerschieben Sie sie manuell an einen neuen Ort
RetrievingDrivesList                      = Laufwerksliste abrufen…
DriveSelect                               = Wählen Sie das Laufwerk aus, in dessen Stammverzeichnis der Ordner "{0}" erstellt werden soll
CurrentUserFolderLocation                 = Der aktuelle Speicherort des Ordners "{0}" lautet: "{1}"
UserFolderRequest                         = Möchten Sie den Speicherort des Ordners "{0}" ändern?
UserFolderSelect                          = Wählen Sie einen Ordner für den Ordner "{0}"
UserDefaultFolder                         = Möchten Sie den Speicherort des Ordners "{0}" auf den Standardwert ändern?
GraphicsPerformanceTitle                  = Bevorzugte Grafikleistung
GraphicsPerformanceRequest                = Möchten Sie die Einstellung der Grafikleistung einer App Ihrer Wahl auf "Hohe Leistung" einstellen?
ScheduledTaskPresented                    = Die Funktion "{0}" wurde bereits als "{1}" angelegt
CleanupTaskNotificationTitle              = Windows aufräumen
CleanupTaskNotificationEvent              = Aufgabe zum Bereinigen nicht verwendeter Windows-Dateien und -Updates ausführen?
CleanupTaskDescription                    = Bereinigung von nicht verwendeten Windows-Dateien und Updates mit der integrierten Festplattenbereinigung
CleanupNotificationTaskDescription        = Popup-Benachrichtigung zur Erinnerung an die Bereinigung von nicht verwendeten Windows-Dateien und Updates
SoftwareDistributionTaskNotificationEvent = Der Windows Update-Cache wurde erfolgreich gelöscht
TempTaskNotificationEvent                 = Der Ordner mit den temporären Dateien wurde erfolgreich bereinigt
FolderTaskDescription                     = Ordner "{0}" bereinigen
EventViewerCustomViewName                 = Prozesserstellung
EventViewerCustomViewDescription          = Prozesserstellungen und Befehlszeilen-Auditing-Ereignisse
RestartWarning                            = Sicherstellen, dass Sie Ihren PC neu starten
ErrorsLine                                = Zeile
ErrorsMessage                             = Fehler/Warnungen
DialogBoxOpening                          = Anzeigen des Dialogfensters…
Disable                                   = Deaktivieren
EXEFilesFilter                            = *.exe|*.exe|Alle Dateien (*.*)|*.*
FolderSelect                              = Einen Ordner auswählen
FilesWontBeMoved                          = Dateien werden nicht verschoben
Install                                   = Installieren
NoData                                    = Nichts anzuzeigen
NoInternetConnection                      = Keine Internetverbindung
RestartFunction                           = Bitte die Funktion "{0}" neustarten
NoResponse                                = Eine Verbindung mit {0} konnte nicht hergestellt werden
Restore                                   = Wiederherstellen
Run                                       = Starten
Skipped                                   = Übersprungen
GPOUpdate                                 = GPO-Aktualisierung...
TelegramGroupTitle                        = Treten Sie unserer offiziellen Telegram-Gruppe bei
TelegramChannelTitle                      = Treten Sie unserem offiziellen Telegram-Kanal bei
DiscordChannelTitle                       = Treten Sie unserem offiziellen Discord-Kanal bei
Uninstall                                 = Deinstallieren
'@
