ConvertFrom-StringData -StringData @'
NewSophiaScriptFound                      = Hay una nueva versión disponible: Sophia Script for Windows {0}. Por favor, actualiza.
UnsupportedPowerShell                     = Estás intentando ejecutar el script a través de PowerShell {0}.{1}. Por favor, ejecuta el script en PowerShell {2}.
CodeCompilationFailed                     = La compilación del código ha fallado.
UnsupportedWindowsBitness                 = El script solo es compatible con Windows de 64 bits.
KeyboardArrows                            = Utiliza las flechas {0} y {1} de tu teclado para seleccionar la respuesta
UnsupportedLanguageMode                   = La sesión de PowerShell se está ejecutando en un modo de lenguaje limitado.
LoggedInUserNotAdmin                      = El usuario "{0}" que ha iniciado sesión no tiene derechos de administrador. El script se ha ejecutado en nombre de "{1}". Inicia sesión en una cuenta con derechos de administrador y vuelve a ejecutar el script.
UnsupportedHost                           = El script no es compatible con la ejecución a través de {0}.
HarmfulTweakerFound                       = La estabilidad del sistema operativo Windows puede haberse visto comprometida al utilizar el {0}.
HostsEntriesFound                         = Entradas de terceros encontradas en el archivo %SystemRoot%\\System32\\drivers\\etc\\hosts. Pueden bloquear la conexión a los recursos utilizados en el script. ¿Deseas continuar?
UWPComponentsMissing                      = Falta el componente UWP "{0}".
DefenderComponentsMissing                 = Falta el componente "{0}" de Microsoft Defender.
WindowsComponentStabilityDisrupted        = Se ha detectado un problema de inestabilidad en el componente "{0}".
DisableControlledFolderAccess             = Tienes activado el acceso controlado a carpetas. Desactívalo y vuelve a ejecutar el script.
RebootPending                             = Tu PC está esperando a que lo reinicies.
SystemDriveEncryptedBitLockerDisabled     = La unidad C está cifrada, aunque BitLocker está desactivado. ¿Deseas descifrar la unidad?
WrongSophiaScriptVersion                  = El script solo es compatible con Windows 10 22H2. Estás usando {0} {1}. Ejecuta el script adecuado según la edición de Windows.
UpdateWindowsBuild                        = El script es compatible con Windows 10 22H2 {0}.{1} y versiones posteriores. Estás utilizando {2} {3} {4}.{5}. Ejecuta Windows Update e inténtalo de nuevo.
ESUProgramEnrollment                      = Windows 10 dejó de recibir soporte técnico el 14 de octubre de 2025. Tu PC podría ser vulnerable a software malicioso, troyanos y vulnerabilidades de día cero. ¿Deseas inscribirte en el programa de Actualizaciones de Seguridad Extendidas para Consumidores (ESU) para recibir actualizaciones hasta 2028 utilizando TSforge de Microsoft Activation Scripts (MAS)?
AskQuestion                               = Si tienes alguna duda, abre un issue en GitHub o pregúntale a la comunidad.
CheckSophiaScriptPreset                   = ¿Has personalizado todas las funciones del archivo de preajustes {0} antes de ejecutar Sophia Script for Windows?
ReinstallWindows                          = Reinstala Windows utilizando solo una imagen ISO original.
CreatingRestorePoint                      = Se está creando un punto de restauración...
WindowsServiceNotFound                    = No se ha encontrado el servicio "{0}".
NoScheduledTasksFound                     = No se han encontrado tareas programadas.
ScheduledTasks                            = Tareas programadas
BingSearchDisabled                        = La búsqueda web ya está desactivada en Inicio.
TaskbarSmallIcons                         = Utilizas botones pequeños en la barra de tareas.
SearchHighlightsDisabled                  = Los resultados destacados de la búsqueda ya están ocultos en Inicio.
CustomStartMenuFound                      = Se ha instalado un menú de inicio de terceros.
OneDriveNotInstalled                      = OneDrive ya está desinstalado.
OneDriveAccountUsageFound                 = Antes de desinstalar OneDrive, cierra sesión en tu cuenta de Microsoft en OneDrive.
OneDriveInstalled                         = OneDrive ya está instalado.
UninstallingApplication                   = Se está desinstalando {0}...
InstallingApplication                     = Se está instalando {0}...
NoWindowsFeaturesFound                    = No se han encontrado características de Windows.
WindowsFeaturesTitle                      = Características de Windows
NoOptionalFeaturesFound                   = No se han encontrado características opcionales.
OptionalFeaturesTitle                     = Características opcionales
NoSupportedNetworkAdaptersFound           = No hay adaptadores de red que admitan la función "Permitir que el equipo apague este dispositivo para ahorrar energía".
LocationServicesDisabled                  = Los comandos de shell de red necesitan permiso de ubicación para acceder a la información de la red WLAN. Activa los servicios de ubicación en la página Ubicación de la configuración de Privacidad y seguridad.
UserFolderLocationMove                    = No deberías cambiar la ubicación de la carpeta de usuario a la raíz de la unidad C.
DriveSelect                               = Selecciona la unidad en cuyo directorio raíz se creará la carpeta "{0}".
CurrentUserFolderLocation                 = La ubicación actual de la carpeta "{0}": "{1}".
FilesWontBeMoved                          = Los archivos no se moverán.
UserFolderMoveSkipped                     = Has omitido cambiar la ubicación de la carpeta "{0}" del usuario.
UserShellFolderNotEmpty                   = Quedan algunos archivos en la carpeta "{0}". Muévelos manualmente a la nueva ubicación.
FolderSelect                              = Selecciona una carpeta
UserFolderRequest                         = ¿Quieres cambiar la ubicación de la carpeta "{0}"?
UserDefaultFolder                         = ¿Quieres cambiar la ubicación de la carpeta "{0}" al valor predeterminado?
ReservedStorageIsInUse                    = El espacio de almacenamiento reservado está en uso.
ProgramPathNotExists                      = La ruta "{0}" no existe.
ProgIdNotExists                           = La ProgId "{0}" no existe.
AllFilesFilter                            = Todos los archivos
JSONNotValid                              = El archivo JSON "{0}" no es válido.
PackageNotInstalled                       = La aplicación "{0}" no está instalada.
PackageIsInstalled                        = La última versión de {0} ya está instalada.
UWPAppsTitle                              = Aplicaciones UWP
UninstallUWPForAll                        = Para todos los usuarios
NoUWPAppsFound                            = No hay aplicaciones UWP que desinstalar.
WDDMVersionUnsupported                    = La versión de WDDM compatible es la 2.7 o superior. La versión actual de WDDM es la {0}.
CleanupTaskNotificationTitle              = Limpieza de Windows
CleanupTaskNotificationEvent              = ¿Ejecutar la tarea de limpiar los archivos no utilizados y actualizaciones de Windows?
CleanupTaskDescription                    = Limpieza de archivos y actualizaciones de Windows no utilizados mediante la aplicación integrada Liberador de espacio en disco.
CleanupNotificationTaskDescription        = Notificación emergente de recordatorio sobre la limpieza de archivos y actualizaciones de Windows no utilizados.
SoftwareDistributionTaskNotificationEvent = La caché de actualizaciones de Windows se ha eliminado correctamente.
SoftwareDistributionTaskDescription       = Limpieza de la carpeta de caché de actualizaciones de Windows "{0}".
TempTaskNotificationEvent                 = La carpeta temporal se ha limpiado correctamente.
TempTaskDescription                       = Limpieza de la carpeta temporal "{0}" (%TEMP%).
ScheduledTaskLoggedInUserNotification     = La tarea programada solo puede ejecutarse si el usuario "{0}" ha iniciado sesión en el sistema.
CleanupTaskCLIDescription                 = La tarea programada "Sophia\\Windows Cleanup Notification" se ha creado en el Programador de tareas para limpiar los archivos y las actualizaciones de Windows no utilizados.
SoftwareDistributionTaskCLIDescription    = La tarea programada "Sophia\\SoftwareDistribution" se ha creado en el Programador de tareas para limpiar la carpeta de caché de actualizaciones de Windows "{0}".
TempTaskCLIDescription                    = La tarea programada "Sophia\\Temp" se ha creado en el Programador de tareas para limpiar la carpeta temporal "{0}" (%TEMP%).
EventViewerCustomViewName                 = Creación de proceso
EventViewerCustomViewDescription          = Rastrear los procesos iniciados y la actividad de PowerShell
EventViewerCustomViewNotification         = La vista personalizada "Vistas personalizadas\\{0}" se ha creado en el Visor de eventos para rastrear los procesos iniciados y la actividad de PowerShell.
ThirdPartyAVInstalled                     = Se ha instalado un antivirus de terceros.
NoHomeWindowsEditionSupport               = La edición Windows Home no es compatible con la función "{0}".
EnableHardwareVT                          = Activa la virtualización en la UEFI.
PhotosNotInstalled                        = La aplicación "Fotos" no está instalada.
HEVCInstalled                             = Las Extensiones de vídeo HEVC del fabricante del dispositivo ya están instaladas.
HEVCInstallingApplication                 = Se están instalando las Extensiones de vídeo HEVC del fabricante del dispositivo...
ThirdPartyArchiverInstalled               = Se ha instalado un archivador de terceros.
gpeditNotSupported                        = La edición Windows Home no es compatible con el complemento Editor de directivas de grupo local (gpedit.msc).
RestartWarning                            = Asegúrate de reiniciar tu PC.
RestorePointVolume                        = Los puntos de restauración de la unidad C ocupan {0} GB.
ErrorsLine                                = Línea
ErrorsMessage                             = Errores, advertencias y notificaciones
Disable                                   = Desactivar
Enable                                    = Activar
Install                                   = Instalar
Uninstall                                 = Desinstalar
RestartFunction                           = Por favor, vuelve a ejecutar la función "{0}".
NoConnectionEstablished                   = No se pudo establecer una conexión con {0}.
Run                                       = Iniciar
FunctionSkipped                           = Función "{0}" omitida.
DonateToastTitle                          = ¡Se aceptan donaciones! ❤
DotSourceFunction                         = Por favor, "dot-source" la función (con un punto al principio):\n. .\\Import-TabCompletion.ps1
'@
