ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Le script n'est compatible qu'avec Windows 64 bits.
UnsupportedOSBuild                        = Le script ne supporte que Windows 10 Enterprise LTSC 2021. Vous utilisez {0} {1}. Mettez à jour votre système d'exploitation Windows et réessayez.
UnsupportedWindowsTerminal                = La version de Windows Terminal est inférieure à 1.23. Veuillez la mettre à jour dans le Microsoft Store et réessayer.
UpdateWarning                             = Vous utilisez Windows 10 {0}.{1}. La version prise en charge est Windows 10 {0}.{2} et supérieure. Exécutez Windows Update et réessayez.
UnsupportedLanguageMode                   = La session PowerShell s'exécute dans un mode de langue limité.
LoggedInUserNotAdmin                      = L'utilisateur connecté n'a pas de droits d'administrateur.
UnsupportedPowerShell                     = Vous essayez d'exécuter le script via PowerShell {0}.{1}. Veuillez exécuter le script en PowerShell {2}.
CodeCompilationFailedWarning              = Échec de la compilation du code.
UnsupportedHost                           = Le script ne supporte pas l'exécution via {0}.
Win10TweakerWarning                       = Votre système d'exploitation a probablement été infecté par la porte dérobée Win 10 Tweaker.
TweakerWarning                            = La stabilité de l'OS Windows peut avoir été compromise par l'utilisation du {0}. Réinstallez Windows en utilisant uniquement une image ISO authentique.
HostsWarning                              = Entrées tierces trouvées dans le fichier {0}. Elles peuvent bloquer les connexions aux ressources utilisées dans le script. Voulez-vous continuer?
RebootPending                             = Le PC attend d'être redémarré.
BitLockerWarning                          = Le chiffrement BitLocker est en cours. Terminez la configuration du lecteur BitLocker et réessayez.
UnsupportedRelease                        = Une nouvelle version de Sophia Script a été trouvée: {0}. Veuillez télécharger la dernière version.
KeyboardArrows                            = Veuillez utiliser les touches fléchées {0} et {1} de votre clavier pour sélectionner votre réponse
CustomizationWarning                      = Avez-vous personnalisé chaque fonction du fichier de préréglage {0} avant d'exécuter Sophia Script?
WindowsComponentBroken                    = {0} cassé ou supprimé du système d'exploitation. Réinstallez Windows en utilisant uniquement une image ISO authentique.
ControlledFolderAccessDisabled            = Contrôle d'accès aux dossiers désactivé.
ScheduledTasks                            = Tâches planifiées
WindowsFeaturesTitle                      = Fonctionnalités
OptionalFeaturesTitle                     = Fonctionnalités optionnelles
EnableHardwareVT                          = Activer la virtualisation dans UEFI.
UserShellFolderNotEmpty                   = Certains fichiers laissés dans le dossier "{0}". Déplacer les manuellement vers un nouvel emplacement.
UserFolderLocationMove                    = Vous ne devez pas changer l'emplacement du dossier de l'utilisateur pour la racine du lecteur C.
DriveSelect                               = Sélectionnez le disque à la racine dans lequel le dossier "{0}" sera créé.
CurrentUserFolderLocation                 = L'emplacement actuel du dossier "{0}": "{1}".
UserFolderRequest                         = Voulez vous changer où est placé le dossier "{0}" ?
UserDefaultFolder                         = Voulez vous changer où est placé le dossier "{0}" à sa valeur par défaut?
ReservedStorageIsInUse                    = Cette opération n'est pas suppportée le stockage réservé est en cours d'utilisation\nVeuillez réexécuter la fonction "{0}" après le redémarrage du PC.
ShortcutPinning                           = Le raccourci "{0}" est épinglé sur Démarrer...
GraphicsPerformanceTitle                  = Souhaitez-vous définir le paramètre de performances graphiques d'une application de votre choix sur "Haute performance"?
ScheduledTaskPresented                    = La fonction "{0}" a déjà été créée en tant que "{1}".
CleanupTaskNotificationTitle              = Nettoyer Windows
CleanupTaskNotificationEvent              = Exécuter la tâche pour nettoyer les fichiers et les mises à jour inutilisés de Windows?
CleanupTaskDescription                    = Nettoyage des fichiers Windows inutilisés et des mises à jour à l'aide de l'application intégrée pour le nettoyage de disque. La tâche programmée ne peut être exécutée que si l'utilisateur "{0}" est connecté au système.
CleanupNotificationTaskDescription        = Rappel de notification contextuelle sur le nettoyage des fichiers et des mises à jour inutilisés de Windows. La tâche programmée ne peut être exécutée que si l'utilisateur "{0}" est connecté au système.
SoftwareDistributionTaskNotificationEvent = Le cache de mise à jour Windows a bien été supprimé.
TempTaskNotificationEvent                 = Le dossier des fichiers temporaires a été nettoyé avec succès.
FolderTaskDescription                     = Nettoyage du dossier "{0}". La tâche programmée ne peut être exécutée que si l'utilisateur "{0}" est connecté au système.
EventViewerCustomViewName                 = Création du processus
EventViewerCustomViewDescription          = Audit des événements de création du processus et de ligne de commande.
RestartWarning                            = Assurez-vous de redémarrer votre PC.
ErrorsLine                                = Ligne
ErrorsMessage                             = Erreurs/Avertissements
DialogBoxOpening                          = Afficher la boîte de dialogue...
Disable                                   = Désactiver
Enable                                    = Activer
AllFilesFilter                            = Tous les Fichiers
FolderSelect                              = Sélectionner un dossier
FilesWontBeMoved                          = Les fichiers ne seront pas déplacés.
Install                                   = Installer
Uninstall                                 = Désinstaller
NoData                                    = Rien à afficher.
RestartFunction                           = Veuillez redémarrer la fonction "{0}".
NoResponse                                = Une connexion n'a pas pu être établie avec {0}.
Restore                                   = Restaurer
Run                                       = Démarrer
Skipped                                   = Fonction "{0}" ignorée.
ThankfulToastTitle                        = Merci d'avoir utilisé Sophia Script ❤️
DonateToastTitle                          = Vous pouvez faire un don ci-dessous 🕊
DotSourcedWarning                         = Veuillez "dot-source" la fonction (avec un point au début):\n. .\\Import-TabCompletion.ps1
'@
