ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Le script n'est compatible qu'avec Windows 64 bits.
UnsupportedOSBuild                        = Le script ne supporte que Windows 10 Enterprise LTSC 2021. Vous utilisez {0} {1}. Mettez à jour votre système d'exploitation Windows et réessayez.
UnsupportedWindowsTerminal                = La version de Windows Terminal est inférieure à 1.23. Veuillez la mettre à jour dans le Microsoft Store et réessayer.
UpdateWarning                             = Vous utilisez Windows 10 {0}.{1}. La version prise en charge est Windows 10 {0}.{2} et supérieure. Exécutez Windows Update et réessayez.
UnsupportedLanguageMode                   = La session PowerShell s'exécute dans un mode de langue limité.
LoggedInUserNotAdmin                      = L'utilisateur connecté {0} ne dispose pas des droits d'administrateur. Le script a été exécuté au nom d'{1}. Veuillez vous connecter à un compte disposant des droits d'administrateur et relancer le script.
UnsupportedPowerShell                     = Vous essayez d'exécuter le script via PowerShell {0}.{1}. Veuillez exécuter le script en PowerShell {2}.
CodeCompilationFailedWarning              = Échec de la compilation du code.
UnsupportedHost                           = Le script ne supporte pas l'exécution via {0}.
Win10TweakerWarning                       = Votre système d'exploitation a probablement été infecté par la porte dérobée Win 10 Tweaker.
TweakerWarning                            = La stabilité de l'OS Windows peut avoir été compromise par l'utilisation du {0}. Réinstallez Windows en utilisant uniquement une image ISO authentique.
HostsWarning                              = Entrées tierces trouvées dans le fichier %SystemRoot%\\System32\\drivers\\etc\\hosts. Elles peuvent bloquer la connexion aux ressources utilisées dans le script. Voulez-vous continuer?
RebootPending                             = Votre PC attend d'être redémarré.
BitLockerInOperation                      = BitLocker est en cours d'exécution. Votre lecteur C est crypté à {0}%. Terminez la configuration du lecteur BitLocker et réessayez.
BitLockerAutomaticEncryption              = Le lecteur C est chiffré, bien que BitLocker soit désactivé. Voulez-vous déchiffrer votre lecteur?
UnsupportedRelease                        = Une nouvelle version de Sophia Script for Windows a été trouvée: {0}. Veuillez télécharger la dernière version.
KeyboardArrows                            = Veuillez utiliser les touches fléchées {0} et {1} de votre clavier pour sélectionner votre réponse
CustomizationWarning                      = Avez-vous personnalisé chaque fonction du fichier de préréglage {0} avant d'exécuter Sophia Script for Windows?
WindowsComponentBroken                    = {0} cassé ou supprimé du système d'exploitation. Réinstallez Windows en utilisant uniquement une image ISO authentique.
ControlledFolderAccessEnabledWarning      = Vous avez activé le contrôle d'accès aux dossiers. Veuillez le désactiver et relancer le script.
NoScheduledTasks                          = Aucune tâche planifiée à désactiver.
ScheduledTasks                            = Tâches planifiées
TaskbarSmallIcons                         = Vous utilisez les petits boutons de la barre des tâches.
InstallNotification                       = {0} est en cours d'installation...
NoWindowsFeatures                         = Aucune fonctionnalité Windows à désactiver.
WindowsFeaturesTitle                      = Fonctionnalités
NoOptionalFeatures                        = Aucune fonctionnalité optionnelle à désactiver.
NoSupportedNetworkAdapters                = Aucun adaptateur réseau ne prend en charge la fonction "Autoriser l'ordinateur à éteindre ce périphérique pour économiser l'énergie ".
LocationServicesDisabled                  = Los comandos de shell de red necesitan permiso de ubicación para acceder a la información de la red WLAN. Active los servicios de ubicación en la página Ubicación de la configuración de Privacidad y seguridad.
OptionalFeaturesTitle                     = Fonctionnalités optionnelles
UserShellFolderNotEmpty                   = Certains fichiers laissés dans le dossier "{0}". Déplacer les manuellement vers un nouvel emplacement.
UserFolderLocationMove                    = Vous ne devez pas changer l'emplacement du dossier de l'utilisateur pour la racine du lecteur C.
DriveSelect                               = Sélectionnez le disque à la racine dans lequel le dossier "{0}" sera créé.
CurrentUserFolderLocation                 = L'emplacement actuel du dossier "{0}": "{1}".
FilesWontBeMoved                          = Les fichiers ne seront pas déplacés.
UserFolderMoveSkipped                     = Vous avez oublié de modifier l'emplacement du dossier "{0}" de l'utilisateur.
FolderSelect                              = Sélectionnez un dossier
UserFolderRequest                         = Voulez vous changer où est placé le dossier "{0}"?
UserDefaultFolder                         = Voulez vous changer où est placé le dossier "{0}" à sa valeur par défaut?
ReservedStorageIsInUse                    = Le stockage réservé est utilisé.
ProgramPathNotExists                      = Le chemin "{0}" n'existe pas.
ProgIdNotExists                           = ProgId "{0}" n'existe pas.
AllFilesFilter                            = Tous les fichiers
JSONNotValid                              = Le fichier JSON "{0}" n'est pas valide.
PackageNotInstalled                       = {0} n'est pas installé.
PackageIsInstalled                        = La dernière version de {0} est déjà installée.
ScheduledTaskCreatedByAnotherUser         = La tâche planifiée "{0}" a déjà été créée par l'utilisateur "{1}".
CleanupTaskNotificationTitle              = Nettoyer Windows
CleanupTaskNotificationEvent              = Exécuter la tâche pour nettoyer les fichiers et les mises à jour inutilisés de Windows?
CleanupTaskDescription                    = Nettoyage des fichiers Windows inutilisés et des mises à jour à l'aide de l'application intégrée pour le nettoyage de disque. La tâche programmée ne peut être exécutée que si l'utilisateur "{0}" est connecté au système.
CleanupNotificationTaskDescription        = Rappel de notification contextuelle sur le nettoyage des fichiers et des mises à jour inutilisés de Windows. La tâche programmée ne peut être exécutée que si l'utilisateur "{0}" est connecté au système.
SoftwareDistributionTaskNotificationEvent = Le cache de mise à jour Windows a bien été supprimé.
TempTaskNotificationEvent                 = Le dossier des fichiers temporaires a été nettoyé avec succès.
FolderTaskDescription                     = Nettoyage du dossier "{0}". La tâche programmée ne peut être exécutée que si l'utilisateur "{0}" est connecté au système.
EventViewerCustomViewName                 = Création du processus
EventViewerCustomViewDescription          = Audit des événements de création du processus et de ligne de commande.
ThirdPartyAVInstalled                     = Un antivirus tiers est installé.
GeoIdNotSupported                         = La fonction "{0}" n'est applicable qu'en Russie.
EnableHardwareVT                          = Activer la virtualisation dans UEFI.
ThirdPartyArchiverInstalled               = Un programme d'archivage tiers est installé.
RestartWarning                            = Assurez-vous de redémarrer votre PC.
ErrorsLine                                = Ligne
ErrorsMessage                             = Erreurs, avertissements et notifications
Disable                                   = Désactiver
Enable                                    = Activer
Install                                   = Installer
Uninstall                                 = Désinstaller
RestartFunction                           = Veuillez redémarrer la fonction "{0}".
NoResponse                                = Une connexion n'a pas pu être établie avec {0}.
Run                                       = Démarrer
Skipped                                   = Fonction "{0}" ignorée.
ThankfulToastTitle                        = Merci d'avoir utilisé Sophia Script for Windows ❤️
DonateToastTitle                          = Vous pouvez faire un don ci-dessous 🕊
DotSourcedWarning                         = Veuillez "dot-source" la fonction (avec un point au début):\n. .\\Import-TabCompletion.ps1
'@
