ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Le script n'est compatible qu'avec Windows 64 bits.
UnsupportedOSBuild                        = Le script supporte les versions Windows 10 Enterprise LTSC 2021.
UpdateWarning                             = Votre version de Windows 10: {0}.{1}. Versions prises en charge: {2}+. Exécutez Windows Update et réessayez.
UnsupportedLanguageMode                   = La session PowerShell s'exécute dans un mode de langue limité.
LoggedInUserNotAdmin                      = L'utilisateur connecté n'a pas de droits d'administrateur.
UnsupportedPowerShell                     = Vous essayez d'exécuter le script via PowerShell {0}.{1}. Exécutez le script dans la version appropriée de PowerShell.
PowerShellx86Warning                      = Vous essayez d'exécuter le script via PowerShell (x86). Exécutez le script dans PowerShell (x64).
UnsupportedHost                           = Le script ne supporte pas l'exécution via {0}.
Win10TweakerWarning                       = Votre système d'exploitation a probablement été infecté par la porte dérobée Win 10 Tweaker.
TweakerWarning                            = La stabilité de l'OS Windows peut avoir été compromise par l'utilisation du {0}. Au cas où, réinstallez Windows.
Bin                                       = Il n'y a pas de fichiers dans le dossier bin. Veuillez retélécharger l'archive.
RebootPending                             = Le PC attend d'être redémarré.
UnsupportedRelease                        = Nouvelle version trouvée.
KeyboardArrows                            = Veuillez utiliser les touches fléchées {0} et {1} de votre clavier pour sélectionner votre réponse
CustomizationWarning                      = Avez-vous personnalisé chaque fonction du fichier de préréglage {0} avant d'exécuter Sophia Script?
WindowsComponentBroken                    = {0} cassé ou supprimé du système d'exploitation.
UpdateDefender                            = Les définitions de Microsoft Defender ne sont pas à jour. Exécutez Windows Update et réessayez.
ControlledFolderAccessDisabled            = Contrôle d'accès aux dossiers désactivé.
InitialActionsCheckFailed                 = La fonction "InitialActions" ne peut pas être chargée à partir du fichier de présélection {0}.
ScheduledTasks                            = Tâches planifiées
WindowsFeaturesTitle                      = Fonctionnalités
OptionalFeaturesTitle                     = Fonctionnalités optionnelles
EnableHardwareVT                          = Activer la virtualisation dans UEFI.
UserShellFolderNotEmpty                   = Certains fichiers laissés dans le dossier "{0}". Déplacer les manuellement vers un nouvel emplacement.
UserFolderLocationMove                    = Vous ne devez pas changer l'emplacement du dossier de l'utilisateur pour la racine du lecteur C.
RetrievingDrivesList                      = Récupération de la liste des lecteurs...
DriveSelect                               = Sélectionnez le disque à la racine dans lequel le dossier "{0}" sera créé.
CurrentUserFolderLocation                 = L'emplacement actuel du dossier "{0}": "{1}".
UserFolderRequest                         = Voulez vous changer où est placé le dossier "{0}" ?
UserDefaultFolder                         = Voulez vous changer où est placé le dossier "{0}" à sa valeur par défaut?
ReservedStorageIsInUse                    = Cette opération n'est pas suppportée le stockage réservé est en cours d'utilisation\nVeuillez réexécuter la fonction "{0}" après le redémarrage du PC.
ShortcutPinning                           = Le raccourci "{0}" est épinglé sur Démarrer...
GraphicsPerformanceTitle                  = Souhaitez-vous définir le paramètre de performances graphiques d'une application de votre choix sur "Haute performance"?
ActionCenter                              = Pour utiliser la fonction "{0}", vous devez activer le Centre d'action.
WindowsScriptHost                         = L'accès à Windows Script Host est désactivé sur cette machine. Pour utiliser la fonction "{0}", vous devez activer Windows Script Host.
ScheduledTaskPresented                    = La fonction "{0}" a déjà été créée en tant que "{1}".
CleanupTaskNotificationTitle              = Nettoyer Windows
CleanupTaskNotificationEvent              = Exécuter la tâche pour nettoyer les fichiers et les mises à jour inutilisés de Windows?
CleanupTaskDescription                    = Nettoyage des fichiers Windows inutilisés et des mises à jour à l'aide de l'application intégrée pour le nettoyage de disque.
CleanupNotificationTaskDescription        = Rappel de notification contextuelle sur le nettoyage des fichiers et des mises à jour inutilisés de Windows.
SoftwareDistributionTaskNotificationEvent = Le cache de mise à jour Windows a bien été supprimé.
TempTaskNotificationEvent                 = Le dossier des fichiers temporaires a été nettoyé avec succès.
FolderTaskDescription                     = Nettoyage du dossier "{0}".
EventViewerCustomViewName                 = Création du processus
EventViewerCustomViewDescription          = Audit des événements de création du processus et de ligne de commande.
RestartWarning                            = Assurez-vous de redémarrer votre PC.
ErrorsLine                                = Ligne
ErrorsMessage                             = Erreurs/Avertissements
DialogBoxOpening                          = Afficher la boîte de dialogue...
Disable                                   = Désactiver
Enable                                    = Activer
UserChoiceWarning                         = Microsoft a bloqué l'accès en écriture à la clé UserChoice pour l'extension .pdf et le protocole http/https avec la version KB5034765.
AllFilesFilter                            = Tous les Fichiers
FolderSelect                              = Sélectionner un dossier
FilesWontBeMoved                          = Les fichiers ne seront pas déplacés.
Install                                   = Installer
NoData                                    = Rien à afficher.
NoInternetConnection                      = Pas de connexion Internet.
RestartFunction                           = Veuillez redémarrer la fonction "{0}".
NoResponse                                = Une connexion n'a pas pu être établie avec {0}.
Restore                                   = Restaurer
Run                                       = Démarrer
Skipped                                   = Passé.
GPOUpdate                                 = Mise à jour de la GPO...
TelegramGroupTitle                        = Rejoignez notre groupe Telegram officiel.
TelegramChannelTitle                      = Rejoignez notre canal Telegram officiel.
DiscordChannelTitle                       = Rejoignez notre canal Discord officiel.
Uninstall                                 = Désinstaller
'@
