ConvertFrom-StringData -StringData @'
NewSophiaScriptFound                      = A new version is available: Sophia Script for Windows {0}. Please update.
UnsupportedPowerShell                     = You're trying to run script via PowerShell {0}.{1}. Please run the script in PowerShell {2}.
CodeCompilationFailed                     = Code compilation failed.
UnsupportedWindowsBitness                 = The script only supports 64-bit Windows.
KeyboardArrows                            = Please use the arrow keys {0} and {1} on your keyboard to select your answer
UnsupportedLanguageMode                   = The PowerShell session is running in a limited language mode.
LoggedInUserNotAdmin                      = The logged-in user "{0}" doesn't have admin rights. Script was ran on behalf of "{1}". Please log into account which has admin rights and run script again.
UnsupportedHost                           = Script doesn't support running via {0}.
HarmfulTweakerFound                       = Windows stability may have been compromised by using {0}.
HostsEntriesFound                         = Third-party entries found in the %SystemRoot%\\System32\\drivers\\etc\\hosts file. They may block connection to resources used in the script. Do you want to continue?
WindowsComponentStabilityDisrupted        = An instability issue has been detected in the "{0}" component.
DisableControlledFolderAccess             = You have Сontrolled folder access enabled. Please disable it and run script again.
RebootPending                             = Your PC is waiting to be restarted.
SystemDriveEncryptedBitLockerDisabled     = C drive is encrypted, although BitLocker is turned off. Do you want to decrypt your drive?
WrongSophiaScriptVersion                  = Script supports only Windows 10 22H2. You're using {0} {1}. Run correct script based on Windows edition.
UpdateWindowsBuild                        = You're using Windows 10 {0}.{1}. Supported builds are Windows 10 {0}.{2} and higher. Run Windows Update and try again.
ESUProgramEnrollment                      = Windows 10 reached the end of support on October 14, 2025. Your PC may be vulnerable to malicious software, trojans, and zero-day exploits. Do you want to enroll in Consumer Extended Security Updates (ESU) program to receive updates until 2028 using TSforge from Microsoft Activation Scripts (MAS)?
CheckSophiaScriptPreset                   = Have you customized every function in the {0} preset file before running Sophia Script for Windows?
ReinstallWindows                          = Reinstall Windows using only a genuine ISO image.
CreatingRestorePoint                      = Restore point is being created...
UWPComponentsMissing                      = The "{0}" UWP component is missing.
DefenderComponentsMissing                 = The "{0}" component of Microsoft Defender is missing.
DiagTrackServiceNotFound                  = "DiagTrackService" service was not found.
NoScheduledTasksFound                     = No scheduled tasks to disable.
ScheduledTasks                            = Scheduled tasks
TaskbarSmallIcons                         = You use small taskbar buttons.
SearchHighlightsDisabled                  = Search highlights are already hidden on Start.
CustomStartMenuFound                      = A third-party Start Menu is installed.
OneDriveNotInstalled                      = OneDrive is already uninstalled.
OneDriveAccountUsageFound                 = Before uninstalling OneDrive, sign out of your Microsoft account in OneDrive.
OneDriveInstalled                         = OneDrive is already installed.
UninstallingApplication                   = {0} is being uninstalled...
InstallingApplication                     = {0} is being installed...
NoWindowsFeaturesFound                    = No Windows Features to disable.
WindowsFeaturesTitle                      = Windows features
NoOptionalFeaturesFound                   = No Optional Features to disable.
NoSupportedNetworkAdaptersFound           = No network adapters which support function "Allow the computer to turn off this device to save power".
LocationServicesDisabled                  = Network shell commands need location permission to access WLAN information. Turn on Location services on the Location page in Privacy & security settings.
OptionalFeaturesTitle                     = Optional features
UserShellFolderNotEmpty                   = Some files left in the "{0}" folder. Move them manually to a new location.
UserFolderLocationMove                    = You shouldn't change user folder location to C drive root.
DriveSelect                               = Select the drive where the "{0}" folder will be created in the root directory.
CurrentUserFolderLocation                 = The current "{0}" folder location: "{1}".
FilesWontBeMoved                          = Files will not be moved.
UserFolderMoveSkipped                     = You skipped changing the location of the user's "{0}" folder.
FolderSelect                              = Select a folder
UserFolderRequest                         = Would you like to change the location of the "{0}" folder?
UserDefaultFolder                         = Would you like to change the location of the "{0}" folder to the default value?
ReservedStorageIsInUse                    = Reserved storage is in use.
ProgramPathNotExists                      = Path "{0}" does not exist.
ProgIdNotExists                           = ProgId "{0}" does not exist.
AllFilesFilter                            = All Files
JSONNotValid                              = JSON file "{0}" is not valid.
PackageNotInstalled                       = "{0}" app is not installed.
PackageIsInstalled                        = The latest version of {0} is already installed.
UninstallUWPForAll                        = For all users
NoUWPAppsFound                            = No UWP apps to uninstall.
UWPAppsTitle                              = UWP Apps
ScheduledTaskCreatedByAnotherUser         = Scheduled task "{0}" was already created by "{1}" user.
CleanupTaskNotificationTitle              = Windows clean up
CleanupTaskNotificationEvent              = Run task to clean up Windows unused files and updates?
CleanupTaskDescription                    = Cleaning up Windows unused files and updates using built-in Disk cleanup app.
CleanupNotificationTaskDescription        = Pop-up notification reminder about cleaning up Windows unused files and updates.
SoftwareDistributionTaskNotificationEvent = Windows update cache successfully deleted.
SoftwareDistributionTaskDescription       = Cleaning up Windows update cache folder "{0}".
TempTaskNotificationEvent                 = Temporary files folder successfully cleaned up.
TempTaskDescription                       = Cleaning up temporary folder "{0}" (%TEMP%).
ScheduledTaskLoggedInUserNotification     = Scheduled task can be run only if user "{0}" logged into the system.
ScheduledTaskCreatedNotification          = Scheduled task "{0}" was created.
CleanupTaskCLIDescription                 = Go to "Sophia" folder in Task Scheduler and run "Windows Cleanup Notification" task to start cleaning up Windows unused files and updates.
SoftwareDistributionTaskCLIDescription    = Go to "Sophia" folder in Task Scheduler and run "SoftwareDistribution" task to start cleaning up Windows update cache folder "{0}". 
TempTaskCLIDescription                    = Go to "Sophia" folder in Task Scheduler and run "Temp" task to start cleaning up temporary files folder "{0}" (%TEMP%).
EventViewerCustomViewName                 = Process Creation
EventViewerCustomViewDescription          = Process creation and command-line auditing events.
ThirdPartyAVInstalled                     = A third-party antivirus is installed.
NoHomeWindowsEditionSupport               = Windows Home edition doesn't support function "{0}".
EnableHardwareVT                          = Enable Virtualization in UEFI.
PhotosNotInstalled                        = "Photos" application is not installed.
HEVCInstalled                             = HEVC Video Extensions from Device Manufacturer is already installed.
HEVCInstallingApplication                 = HEVC Video Extensions from Device Manufacturer is being installed...
ThirdPartyArchiverInstalled               = A third-party archiver is installed.
gpeditNotSupported                        = Windows Home edition doesn't support the Local Group Policy Editor snap-in (gpedit.msc).
RestartWarning                            = Make sure to restart your PC.
RestorePointVolume                        = Restore points for C drive take up {0}GB.
ErrorsLine                                = Line
ErrorsMessage                             = Errors, warnings, and notifications
Disable                                   = Disable
Enable                                    = Enable
Install                                   = Install
Uninstall                                 = Uninstall
RestartFunction                           = Please rerun the "{0}" function.
NoConnectionEstablished                   = Connection could not be established with {0}.
Run                                       = Run
FunctionSkipped                           = Function "{0}" skipped.
DonateToastTitle                          = Donations welcome!❤
DotSourcedFunction                        = Please dot-source the function (with a dot at the beginning):\n. .\\Import-TabCompletion.ps1
'@
