ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Script supports Windows only.
UnsupportedOSBuild                        = Script supports only Windows 10 22H2. You're using {0} {1}. Upgrade your Windows and try again.
UnsupportedWindowsTerminal                = Windows Terminal version is lower than 1.23. Please update it in the Microsoft Store and try again.
UpdateWarning                             = You're using Windows 10 {0}.{1}. Supported builds are Windows 10 {0}.{2} and higher. Run Windows Update and try again.
UnsupportedLanguageMode                   = The PowerShell session is running in a limited language mode.
LoggedInUserNotAdmin                      = The logged-in user {0} doesn't have admin rights. Script was ran on behalf of {1}. Please log into account which has admin rights and run script again.
UnsupportedPowerShell                     = You're trying to run script via PowerShell {0}.{1}. Please run the script in PowerShell {2}.
CodeCompilationFailedWarning              = Code compilation failed.
UnsupportedHost                           = Script doesn't support running via {0}.
Win10TweakerWarning                       = Windows has been infected with a trojan via a Win 10 Tweaker backdoor. Reinstall Windows using only a genuine ISO image.
TweakerWarning                            = Windows stability may have been compromised by using {0}. Reinstall Windows using only a genuine ISO image.
HostsWarning                              = Third-party entries found in the %SystemRoot%\\System32\\drivers\\etc\\hosts file. They may block connection to resources used in the script. Do you want to continue?
RebootPending                             = Your PC is waiting to be restarted.
BitLockerInOperation                      = BitLocker encryption is in progress. Complete BitLocker drive configuration and try again.
BitLockerAutomaticEncryption              = C drive is encrypted, although BitLocker is turned off. Do you want to decrypt your drive?
UnsupportedRelease                        = A newer Sophia Script version found: {0}. Please download the latest version.
KeyboardArrows                            = Please use the arrow keys {0} and {1} on your keyboard to select your answer
CustomizationWarning                      = Have you customized every function in the {0} preset file before running Sophia Script?
WindowsComponentBroken                    = {0} broken or removed from Windows. Reinstall Windows using only a genuine ISO image.
ControlledFolderAccessEnabledWarning      = You have controlled folder access enabled. Please disable it and run script again.
NoScheduledTasks                          = No scheduled tasks to disable.
ScheduledTasks                            = Scheduled tasks
TaskbarSmallIcons                         = You use small taskbar buttons.
SearchHighlightsDisabled                  = Search highlights are already hidden in Start.
CustomStartMenu                           = A third-party Start Menu is installed.
OneDriveNotInstalled                      = OneDrive is already uninstalled.
OneDriveAccountWarning                    = Before uninstalling OneDrive, sign out of your Microsoft account in OneDrive.
OneDriveInstalled                         = OneDrive is already installed.
UninstallNotification                     = {0} is being uninstalled...
InstallNotification                       = {0} is being installed...
NoWindowsFeatures                         = No Windows Features to disable.
WindowsFeaturesTitle                      = Windows features
NoOptionalFeatures                        = No Optional Features to disable.
NoSupportedNetworkAdapters                = No network adapters which support function "Allow the computer to turn off this device to save power".
OptionalFeaturesTitle                     = Optional features
EnableHardwareVT                          = Enable Virtualization in UEFI.
UserShellFolderNotEmpty                   = Some files left in the "{0}" folder. Move them manually to a new location.
UserFolderLocationMove                    = You shouldn't change user folder location to C drive root.
DriveSelect                               = Select the drive within the root of which the "{0}" folder will be created.
CurrentUserFolderLocation                 = The current "{0}" folder location: "{1}".
FilesWontBeMoved                          = Files will not be moved.
FolderSelect                              = Select a folder
UserFolderRequest                         = Would you like to change the location of the "{0}" folder?
UserDefaultFolder                         = Would you like to change the location of the "{0}" folder to the default value?
ReservedStorageIsInUse                    = Reserved storage is being used.
ProgramPathNotExists                      = Path "{0}" does not exist.
ProgIdNotExists                           = ProgId "{0}" does not exist.
AllFilesFilter                            = All Files
JSONNotValid                              = JSON file "{0}" is not valid.
PackageNotInstalled                       = {0} is not installed.
PackageIsInstalled                        = The latest version of {0} is already installed.
UninstallUWPForAll                        = For all users
NoUWPApps                                 = No UWP apps to uninstall.
UWPAppsTitle                              = UWP Apps
ScheduledTaskCreatedByAnotherUser         = Scheduled task "{0}" was already created by "{1}" user.
CleanupTaskNotificationTitle              = Windows clean up
CleanupTaskNotificationEvent              = Run task to clean up Windows unused files and updates?
CleanupTaskDescription                    = Cleaning up Windows unused files and updates using built-in Disk cleanup app. Scheduled task can be run only if user "{0}" logged into the system.
CleanupNotificationTaskDescription        = Pop-up notification reminder about cleaning up Windows unused files and updates. Scheduled task can be run only if user "{0}" logged into the system.
SoftwareDistributionTaskNotificationEvent = Windows update cache successfully deleted.
TempTaskNotificationEvent                 = Temporary files folder successfully cleaned up.
FolderTaskDescription                     = {0} folder cleanup. Scheduled task can be run only if user "{0}" logged into the system.
EventViewerCustomViewName                 = Process Creation
EventViewerCustomViewDescription          = Process creation and command-line auditing events.
ThirdPartyAVInstalled                     = A third-party antivirus is installed.
NoHomeWindowsEditionSupport               = Windows Home edition doesn't support function "{0}".
GeoIdNotSupported                         = Function "{0}" is applicable for Russia only.
PhotosNotInstalled                        = Photos application is not installed.
HEVCInstalled                             = HEVC Video Extensions from Device Manufacturer is already installed.
HEVCInstallNotification                   = HEVC Video Extensions from Device Manufacturer is being installed...
ThirdPartyArchiverInstalled               = A third-party archiver is installed.
gpeditNotSupported                        = Windows Home edition doesn't support the Local Group Policy Editor snap-in (gpedit.msc).
RestartWarning                            = Make sure to restart your PC.
ErrorsLine                                = Line
ErrorsMessage                             = Errors, warnings, and notifications
Disable                                   = Disable
Enable                                    = Enable
Install                                   = Install
Uninstall                                 = Uninstall
RestartFunction                           = Please re-run the "{0}" function.
NoResponse                                = Connection could not be established with {0}.
Run                                       = Run
Skipped                                   = Function "{0}" skipped.
ThankfulToastTitle                        = Thank you for using Sophia Script ❤️
DonateToastTitle                          = You may donate below 🕊
DotSourcedWarning                         = Please dot-source the function (with a dot at the beginning):\n. .\\Import-TabCompletion.ps1
'@
