ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = The script supports 64-bit Windows only
UnsupportedOSBuild                        = \nThe script supports Windows 10 22H2+
UpdateWarning                             = \nWindows 10 cumulative update installed: {0}. Supported cumulative updates: 2728 and higher. Run Windows Update and try again
UnsupportedLanguageMode                   = \nThe PowerShell session in running in a limited language mode
LoggedInUserNotAdmin                      = \nThe logged-on user doesn't have admin rights
UnsupportedPowerShell                     = \nYou're trying to run script via PowerShell {0}.{1}. Run the script in the appropriate PowerShell version
UnsupportedHost                           = \nThe script doesn't support running via {0}
Win10TweakerWarning                       = \nProbably your OS was infected via the Win 10 Tweaker backdoor
TweakerWarning                            = \nThe Windows stability may have been compromised by using {0}. Just in case, reinstall Windows
bin                                       = \nThere are no files in the bin folder. Please, re-download the archive
RebootPending                             = \nThe PC is waiting to be restarted
UnsupportedRelease                        = \nA new version found
CustomizationWarning                      = \nHave you customized every function in the {0} preset file before running Sophia Script?
WindowsComponentBroken                    = \n{0} broken or removed from the OS
UpdateDefender                            = \nMicrosoft Defender definitions are out-of-date. Run Windows Update and try again
ControlledFolderAccessDisabled            = Controlled folder access disabled
ScheduledTasks                            = Scheduled tasks
OneDriveUninstalling                      = Uninstalling OneDrive...
OneDriveInstalling                        = Installing OneDrive...
OneDriveDownloading                       = Downloading OneDrive... ~33 MB
OneDriveWarning                           = The "{0}" function will be applied only if the preset is configured to remove OneDrive (or the app was already removed), otherwise the backup functionality for the "Desktop" and "Pictures" folders in OneDrive breaks
WindowsFeaturesTitle                      = Windows features
OptionalFeaturesTitle                     = Optional features
EnableHardwareVT                          = Enable Virtualization in UEFI
UserShellFolderNotEmpty                   = Some files left in the "{0}" folder. Move them manually to a new location
RetrievingDrivesList                      = Retrieving drives list...
DriveSelect                               = Select the drive within the root of which the "{0}" folder will be created
CurrentUserFolderLocation                 = The current "{0}" folder location: "{1}"
UserFolderRequest                         = Would you like to change the location of the "{0}" folder?
UserFolderSelect                          = Select a folder for the "{0}" folder
UserDefaultFolder                         = Would you like to change the location of the "{0}" folder to the default value?
ReservedStorageIsInUse                    = This operation is not supported when reserved storage is in use\nPlease re-run the "{0}" function again after PC restart
ShortcutPinning                           = The "{0}" shortcut is being pinned to Start...
UninstallUWPForAll                        = For all users
UWPAppsTitle                              = UWP Apps
HEVCDownloading                           = Downloading HEVC Video Extensions from Device Manufacturer... ~2,8 MB
GraphicsPerformanceTitle                  = Graphics performance preference
GraphicsPerformanceRequest                = Would you like to set the graphics performance setting of an app of your choice to "High performance"?
ScheduledTaskPresented                    = The "{0}" function was already created as "{1}"
CleanupTaskNotificationTitle              = Windows clean up
CleanupTaskNotificationEvent              = Run task to clean up Windows unused files and updates?
CleanupTaskDescription                    = Cleaning up Windows unused files and updates using built-in Disk cleanup app
CleanupNotificationTaskDescription        = Pop-up notification reminder about cleaning up Windows unused files and updates
SoftwareDistributionTaskNotificationEvent = Windows update cache successfully deleted
TempTaskNotificationEvent                 = Temporary files folder successfully cleaned up
FolderTaskDescription                     = The {0} folder cleanup
EventViewerCustomViewName                 = Process Creation
EventViewerCustomViewDescription          = Process creation and command-line auditing events
RestartWarning                            = Make sure to restart your PC
ErrorsLine                                = Line
ErrorsMessage                             = Errors/Warnings
DialogBoxOpening                          = Displaying the dialog box...
Disable                                   = Disable
EXEFilesFilter                            = *.exe|*.exe|All Files (*.*)|*.*
FolderSelect                              = Select a folder
FilesWontBeMoved                          = Files will not be moved
Install                                   = Install
NoData                                    = Nothing to display
NoInternetConnection                      = No Internet connection
RestartFunction                           = Please re-run the "{0}" function
NoResponse                                = A connection could not be established with {0}
Restore                                   = Restore
Run                                       = Run
Skipped                                   = Skipped
GPOUpdate                                 = Updating GPO...
TelegramGroupTitle                        = Join our official Telegram group
TelegramChannelTitle                      = Join our official Telegram channel
DiscordChannelTitle                       = Join our official Discord channel
Uninstall                                 = Uninstall
'@
