ConvertFrom-StringData -StringData @'
UnsupportedOSBuild                        = \nKomut dosyası Windows 11 22H2+'yı destekler
UpdateWarning                             = \nWindows 11 yapınız: {0}.{1}. Desteklenen yapılar: 22621.1413 ve üstünü destekliyor. Windows Update'i çalıştırın ve tekrar deneyin
UnsupportedLanguageMode                   = \nSınırlı bir dil modunda çalışan PowerShell oturumu
LoggedInUserNotAdmin                      = \nOturum açan kullanıcının yönetici hakları yok
UnsupportedPowerShell                     = \nKomut dosyasını PowerShell {0}.{1} aracılığıyla çalıştırmaya çalışıyorsunuz. Komut dosyasını uygun PowerShell sürümünde çalıştırın
UnsupportedHost                           = \nKomut dosyası, {0} üzerinden çalıştırmayı desteklemiyor
Win10TweakerWarning                       = \nMuhtemelen işletim sisteminize Win 10 Tweaker arka kapısı yoluyla bulaştı
TweakerWarning                            = \nWindows işletim sistemi kararlılığı, {0} betiği kullanılarak tehlikeye atılmış olabilir. Her ihtimale karşı, Windows'u yeniden yükleyin
bin                                       = \nbin klasöründe dosya yok. Lütfen arşivi yeniden indirin
RebootPending                             = \nPC yeniden başlatılmayı bekliyor
UnsupportedRelease                        = \nYeni sürüm bulundu
CustomizationWarning                      = \nSophia Script'i çalıştırmadan önce {0} ön ayar dosyasındaki her işlevi özelleştirdiniz mi?
WindowsComponentBroken                    = \n{0} bozuk veya işletim sisteminden kaldırıldı
UpdateDefender                            = \nMicrosoft Defender tanımları güncel değil. Windows Update'i çalıştırın ve tekrar deneyin
ControlledFolderAccessDisabled            = Kontrollü klasör erişimi devre dışı bırakıldı
ScheduledTasks                            = Zamanlanan görevler
OneDriveUninstalling                      = OneDrive kaldırılıyor...
OneDriveInstalling                        = OneDrive kuruluyor...
OneDriveDownloading                       = OneDrive indiriliyor... ~33 MB
OneDriveWarning                           = "{0}" işlevi yalnızca ön ayar OneDrive'ı kaldıracak şekilde yapılandırılırsa uygulanır (veya uygulama zaten kaldırılmışsa), aksi takdirde OneDrive'daki "Masaüstü" ve "Resimler" klasörleri için yedekleme işlevi bozulur
WindowsFeaturesTitle                      = Características do Windows
OptionalFeaturesTitle                     = Opsiyonel özellikler
EnableHardwareVT                          = UEFI'dan sanallaştırmayı aktifleştirin
UserShellFolderNotEmpty                   = "{0}" klasöründe bazı dosyalar kaldı. \nKendiniz yeni konuma taşıyın
RetrievingDrivesList                      = Sürücü listesi alınıyor...
DriveSelect                               = "{0}" klasörünün oluşturulacağı kök içindeki sürücüyü seçin
CurrentUserFolderLocation                 = Geçerli "{0}" klasör konumu: "{1}"
UserFolderRequest                         = "{0}" klasörünün yerini değiştirmek ister misiniz?
UserFolderSelect                          = "{0}" klasörü için bir klasör seçin
UserDefaultFolder                         = "{0}" klasörünün konumunu varsayılan değerle değiştirmek ister misiniz?
ReservedStorageIsInUse                    = Ayrılmış depolama kullanımdayken bu işlem desteklenmez\nBilgisayar yeniden başlatıldıktan sonra lütfen "{0}" işlevini yeniden çalıştırın
ShortcutPinning                           = "{0}" kısayolu Başlangıç sekmesine sabitlendi...
SSDRequired                               = Android™ için Windows Alt Sistemi'ni cihazınızda kullanmak için bilgisayarınızda Katı Hal Sürücüsü (SSD) yüklü olmalıdır
UninstallUWPForAll                        = Bütün kullanıcılar için
UWPAppsTitle                              = UWP Uygulamaları
HEVCDownloading                           = "Cihaz Üreticisinden HEVC Video Uzantıları" İndiriliyor... ~2,8 MB
GraphicsPerformanceTitle                  = Grafik performans tercihi
GraphicsPerformanceRequest                = Seçtiğiniz bir uygulamanın grafik performansı ayarını "Yüksek performans" olarak belirlemek ister misiniz?
ScheduledTaskPresented                    = "{0}" işlevi zaten "{1}" olarak oluşturulmuştu
CleanupTaskNotificationTitle              = Windows temizliği
CleanupTaskNotificationEvent              = Windows kullanılmayan dosyaları ve güncellemeleri temizlemek için görev çalıştırılsın mı?
CleanupTaskDescription                    = Kullanılmayan Windows dosyaları ve güncellemeleri yerleşik Disk Temizleme uygulaması ile temizleniyor
CleanupNotificationTaskDescription        = Windows kullanılmayan dosyaları ve güncellemeleri temizleme hakkında açılır bildirim hatırlatıcısı
SoftwareDistributionTaskNotificationEvent = Windows güncelleme önbelleği başarıyla silindi
TempTaskNotificationEvent                 = Geçici dosyalar klasörü başarıyla temizlendi
FolderTaskDescription                     = "{0}" klasörü temizleniyor
EventViewerCustomViewName                 = Süreç Oluşturma
EventViewerCustomViewDescription          = Süreç oluşturma ve komut satırı denetleme olayları
RestartWarning                            = Bilgisayarınızı yeniden başlattığınızdan emin olun
ErrorsLine                                = Satır
ErrorsMessage                             = Hatalar/Uyarılar
DialogBoxOpening                          = İletişim kutusu görüntüleniyor...
Disable                                   = Devre dışı bırak
EXEFilesFilter                            = *.exe|*.exe|Tüm Dosyalar (*.*)|*.*
FolderSelect                              = Klasör seç
FilesWontBeMoved                          = Dosyalar taşınmayacak
Install                                   = Yükle
NoData                                    = Görüntülenecek bir şey yok
NoInternetConnection                      = İnternet bağlantısı yok
RestartFunction                           = Lütfen "{0}" işlevini yeniden çalıştırın
NoResponse                                = {0} ile bağlantı kurulamadı
Restore                                   = Onar
Run                                       = Başlat
Skipped                                   = Atlandı
GPOUpdate                                 = GPO Güncelleniyor...
TelegramGroupTitle                        = Resmi Telegram grubumuza katılın
TelegramChannelTitle                      = Resmi Telegram kanalımıza katılın
DiscordChannelTitle                       = Resmi Discord kanalımıza katılın
Uninstall                                 = Kaldır
'@
