ConvertFrom-StringData -StringData @'
UnsupportedOSBuild                        = Komut dosyası Windows 11 23H2+'yı destekler.
UpdateWarning                             = Windows 11 yapınız: {0}.{1}. Desteklenen yapılar: {2}+. Windows Update'i çalıştırın ve tekrar deneyin.
UnsupportedLanguageMode                   = Sınırlı bir dil modunda çalışan PowerShell oturumu.
LoggedInUserNotAdmin                      = Oturum açan kullanıcının yönetici hakları yok.
UnsupportedPowerShell                     = Komut dosyasını PowerShell {0}.{1} aracılığıyla çalıştırmaya çalışıyorsunuz. Komut dosyasını uygun PowerShell sürümünde çalıştırın.
PowerShellx86Warning                      = Komut dosyasını PowerShell (x86) üzerinden çalıştırmaya çalışıyorsunuz. Komut dosyasını PowerShell'de (x64) çalıştırın.
UnsupportedHost                           = Komut dosyası, {0} üzerinden çalıştırmayı desteklemiyor.
Win10TweakerWarning                       = Muhtemelen işletim sisteminize Win 10 Tweaker arka kapısı yoluyla bulaştı.
TweakerWarning                            = Windows işletim sistemi kararlılığı, {0} betiği kullanılarak tehlikeye atılmış olabilir. Her ihtimale karşı, Windows'u yeniden yükleyin.
Bin                                       = bin klasöründe dosya yok. Lütfen arşivi yeniden indirin.
RebootPending                             = PC yeniden başlatılmayı bekliyor.
UnsupportedRelease                        = Yeni sürüm bulundu.
KeyboardArrows                            = Lütfen cevabınızı seçmek için klavyenizdeki {0} ve {1} ok tuşlarını kullanın
CustomizationWarning                      = Sophia Script'i çalıştırmadan önce {0} ön ayar dosyasındaki her işlevi özelleştirdiniz mi?
WindowsComponentBroken                    = {0} bozuk veya işletim sisteminden kaldırıldı.
UpdateDefender                            = Microsoft Defender tanımları güncel değil. Windows Update'i çalıştırın ve tekrar deneyin.
ControlledFolderAccessDisabled            = Kontrollü klasör erişimi devre dışı bırakıldı.
InitialActionsCheckFailed                 = "InitialActions" fonksiyonu {0} ön ayar dosyasından yüklenemez.
ScheduledTasks                            = Zamanlanan görevler
OneDriveUninstalling                      = OneDrive kaldırılıyor...
OneDriveInstalling                        = OneDrive kuruluyor...
OneDriveDownloading                       = OneDrive indiriliyor...
OneDriveWarning                           = "{0}" işlevi yalnızca ön ayar OneDrive'ı kaldıracak şekilde yapılandırılırsa uygulanır (veya uygulama zaten kaldırılmışsa), aksi takdirde OneDrive'daki "Masaüstü" ve "Resimler" klasörleri için yedekleme işlevi bozulur.
WindowsFeaturesTitle                      = Características do Windows
OptionalFeaturesTitle                     = Opsiyonel özellikler
EnableHardwareVT                          = UEFI'dan sanallaştırmayı aktifleştirin.
UserShellFolderNotEmpty                   = "{0}" klasöründe bazı dosyalar kaldı. \nKendiniz yeni konuma taşıyın.
UserFolderLocationMove                    = Kullanıcı klasörü konumunu C sürücüsü kökü olarak değiştirmemelisiniz.
RetrievingDrivesList                      = Sürücü listesi alınıyor...
DriveSelect                               = "{0}" klasörünün oluşturulacağı kök içindeki sürücüyü seçin.
CurrentUserFolderLocation                 = Geçerli "{0}" klasör konumu: "{1}".
UserFolderRequest                         = "{0}" klasörünün yerini değiştirmek ister misiniz?
UserDefaultFolder                         = "{0}" klasörünün konumunu varsayılan değerle değiştirmek ister misiniz?
ReservedStorageIsInUse                    = Ayrılmış depolama kullanımdayken bu işlem desteklenmez\nBilgisayar yeniden başlatıldıktan sonra lütfen "{0}" işlevini yeniden çalıştırın.
ShortcutPinning                           = "{0}" kısayolu Başlangıç sekmesine sabitlendi...
SSDRequired                               = Android™ için Windows Alt Sistemi'ni cihazınızda kullanmak için bilgisayarınızda Katı Hal Sürücüsü (SSD) yüklü olmalıdır.
UninstallUWPForAll                        = Bütün kullanıcılar için
UWPAppsTitle                              = UWP Uygulamaları
GraphicsPerformanceTitle                  = Seçtiğiniz bir uygulamanın grafik performansı ayarını "Yüksek performans" olarak belirlemek ister misiniz?
ActionCenter                              = "{0}" işlevini kullanmak için Eylem Merkezi'ni etkinleştirmeniz gerekir.
WindowsScriptHost                         = Windows Kod Merkezi erişimi bu makineden devre dışı. "{0}" işlevini kullanmak için Windows Kod Merkezi'u etkinleştirmeniz gerekir.
ScheduledTaskPresented                    = "{0}" işlevi zaten "{1}" olarak oluşturulmuştu.
CleanupTaskNotificationTitle              = Windows temizliği
CleanupTaskNotificationEvent              = Windows kullanılmayan dosyaları ve güncellemeleri temizlemek için görev çalıştırılsın mı?
CleanupTaskDescription                    = Kullanılmayan Windows dosyaları ve güncellemeleri yerleşik Disk Temizleme uygulaması ile temizleniyor.
CleanupNotificationTaskDescription        = Windows kullanılmayan dosyaları ve güncellemeleri temizleme hakkında açılır bildirim hatırlatıcısı.
SoftwareDistributionTaskNotificationEvent = Windows güncelleme önbelleği başarıyla silindi.
TempTaskNotificationEvent                 = Geçici dosyalar klasörü başarıyla temizlendi.
FolderTaskDescription                     = "{0}" klasörü temizleniyor.
EventViewerCustomViewName                 = Süreç Oluşturma
EventViewerCustomViewDescription          = Süreç oluşturma ve komut satırı denetleme olayları.
RestartWarning                            = Bilgisayarınızı yeniden başlattığınızdan emin olun.
ErrorsLine                                = Satır
ErrorsMessage                             = Hatalar/Uyarılar
DialogBoxOpening                          = İletişim kutusu görüntüleniyor...
Disable                                   = Devre dışı bırak
Enable                                    = Aktif et
UserChoiceWarning                         = Microsoft, KB5034765 sürümü ile .pdf uzantısı ve http/https protokolü için UserChoice anahtarına yazma erişimini engellemiştir.
AllFilesFilter                            = Tüm Dosyalar
FolderSelect                              = Klasör seç
FilesWontBeMoved                          = Dosyalar taşınmayacak.
Install                                   = Yükle
NoData                                    = Görüntülenecek bir şey yok.
NoInternetConnection                      = İnternet bağlantısı yok.
RestartFunction                           = Lütfen "{0}" işlevini yeniden çalıştırın.
NoResponse                                = {0} ile bağlantı kurulamadı.
Restore                                   = Onar
Run                                       = Başlat
Skipped                                   = Atlandı.
GPOUpdate                                 = GPO Güncelleniyor...
TelegramGroupTitle                        = Resmi Telegram grubumuza katılın.
TelegramChannelTitle                      = Resmi Telegram kanalımıza katılın.
DiscordChannelTitle                       = Resmi Discord kanalımıza katılın.
Uninstall                                 = Kaldır
'@
