ConvertFrom-StringData -StringData @'
UnsupportedArchitecture                   = Ön "{0}" alapú architektúrájú CPU-t használ. Ez a szkript csak x64 architektúrájú CPU-kat támogat. Töltse le és futtassa az Ön architektúrájához megfelelő szkript verziót.
UnsupportedOSBuild                        = A szkript csak a Windows 11 Enterprise LTSC 2024 rendszert támogatja. {0} {1}-et használsz. Frissítse a Windows-t, és próbálja meg újra.
UnsupportedWindowsTerminal                = A Windows Terminal verziója alacsonyabb, mint 1.23. Kérjük, frissítse azt a Microsoft Store-ban, és próbálja meg újra.
UpdateWarning                             = Vous utilisez Windows 11 {0}.{1}. La version prise en charge est Windows 11 {0}.{2} et supérieure. Exécutez Windows Update et réessayez.
UnsupportedLanguageMode                   = A PowerShell munkamenet korlátozott nyelvi üzemmódban fut.
LoggedInUserNotAdmin                      = A bejelentkezett felhasználó, {0}, nem rendelkezik rendszergazdai jogokkal. A szkript {1} nevében futott. Kérjük, jelentkezzen be egy rendszergazdai jogokkal rendelkező fiókba, és futtassa újra a szkriptet.
UnsupportedPowerShell                     = A PowerShell {0}.{1} segítségével próbálja futtatni a szkriptet. Kérjük, futtassa a szkriptet a PowerShell {2}-ben.
CodeCompilationFailedWarning              = A kód fordítása sikertelen volt.
UnsupportedHost                           = A szkript nem támogatja a {0} futtatását.
Win10TweakerWarning                       = Valószínűleg az operációs rendszerét a Win 10 Tweaker backdoor segítségével fertőzték meg.
TweakerWarning                            = A Windows operációs rendszer stabilitását veszélyeztethette a {0}. Ponovno instalirajte Windows koristeći samo originalnu ISO sliku.
HostsWarning                              = Harmadik féltől származó bejegyzések találhatóak a %SystemRoot%\\System32\\drivers\\etc\\hosts fájlban. Ezek blokkolhatják a szkriptben használt erőforrásokhoz való csatlakozást. Folytatni kívánja?
RebootPending                             = A számítógép újraindításra vár.
BitLockerInOperation                      = A BitLocker titkosítás folyamatban van. Végezze el a BitLocker meghajtó konfigurálását, majd próbálkozzon újra.
BitLockerAutomaticEncryption              = A C meghajtó titkosítva van, bár a BitLocker ki van kapcsolva. Szeretné dekódolni a meghajtót?
UnsupportedRelease                        = Újabb Sophia Script verzió található: {0}. Kérjük, töltse le a legújabb verziót.
KeyboardArrows                            = Kérjük, használja a billentyűzet {0} és {1} nyílbillentyűit a válasz kiválasztásához
CustomizationWarning                      = Személyre szabott minden opciót a {0} preset fájlban, mielőtt futtatni kívánja a Sophia szkriptet?
WindowsComponentBroken                    = A {0} elromlott vagy eltávolították az operációs rendszerből. Ponovno instalirajte Windows koristeći samo originalnu ISO sliku.
ControlledFolderAccessEnabledWarning      = A mappákhoz való hozzáférés ellenőrzése engedélyezve van. Kérjük, tiltsa le, és futtassa újra a szkriptet.
NoScheduledTasks                          = Nincs letiltandó ütemezett feladat. 
ScheduledTasks                            = Ütemezett feladatok
SearchHighlightsDisabled                  = A keresési kiemelt elemek már el vannak rejtve a Start menüben.
CustomStartMenu                           = Egy harmadik fél Start menüje van telepítve.
InstallNotification                       = A {0} telepítése folyamatban van...
NoWindowsFeatures                         = Nincs letiltandó Windows-funkció.
WindowsFeaturesTitle                      = Windows szolgáltatások
NoOptionalFeatures                        = Nincs letiltható opcionális funkció.
NoSupportedNetworkAdapters                = Nincs olyan hálózati adapter, amely támogatná az "Engedélyezze a számítógépnek, hogy energiatakarékossági okokból kikapcsolja ezt az eszközt" funkciót.
OptionalFeaturesTitle                     = Opcionális szolgáltatások
EnableHardwareVT                          = Virtualizáció engedélyezése UEFI-ben.
UserShellFolderNotEmpty                   = Néhány fájl maradt a "{0}" könyvtárban. Kérem helyezze át ezeket egy új helyre.
UserFolderLocationMove                    = Nem szabad megváltoztatni a felhasználói mappa helyét a C meghajtó gyökerére.
DriveSelect                               = Válassza ki a meghajtó jelét a gyökérkönyvtárban ahol a "{0}" könyvtár létre lesz hozva.
CurrentUserFolderLocation                 = Az aktuális "{0}" mappa helye: "{1}".
FilesWontBeMoved                          = A fájlok nem kerülnek áthelyezésre.
FolderSelect                              = Válasszon ki egy mappát
UserFolderRequest                         = Kívánja megváltoztatni a "{0}" könyvtár helyét?
UserDefaultFolder                         = Szeretné visszaállítani a "{0}" könyvtár helyét a gyári értékekre?
ReservedStorageIsInUse                    = A fenntartott tárhely használatban van.
ProgramPathNotExists                      = A "{0}" elérési út nem létezik.
ProgIdNotExists                           = A ProgId "{0}" nem létezik.
AllFilesFilter                            = Minden fájl
JSONNotValid                              = A JSON fájl "{0}" érvénytelen.
PackageNotInstalled                       = A {0} nincs telepítve.
PackageIsInstalled                        = A {0} legújabb verziója már telepítve van.
UninstallUWPForAll                        = Minden felhasználó számára
NoUWPApps                                 = Nincs eltávolítandó UWP-alkalmazás.
UWPAppsTitle                              = Nincs eltávolítandó UWP-alkalmazás.
ScheduledTaskCreatedByAnotherUser         = A "{0}" ütemezett feladatot már létrehozta a "{1}" felhasználó.
CleanupTaskNotificationTitle              = Windows tisztítása
CleanupTaskNotificationEvent              = Szeretné a nem használt fájlokat es frissitéseket eltávolítani?
CleanupTaskDescription                    = A nem használt Windows fájlok és frissítések eltávolítása a beépített lemezkarbantartó alkalmazással. Az ütemezett feladat csak akkor futtatható, ha "{0}" felhasználó bejelentkezett a rendszerbe.
CleanupNotificationTaskDescription        = Előugró emlékeztető figyelmeztetés a nem használt Windows fájlok és frissítések törléséről. Az ütemezett feladat csak akkor futtatható, ha "{0}" felhasználó bejelentkezett a rendszerbe.
SoftwareDistributionTaskNotificationEvent = A Windows frissités számára fenntartott ideiglenes tárhely sikeresen megtisztítva.
TempTaskNotificationEvent                 = Az ideiglenes fájlok tárolására szolgáló könyvtár tisztítása sikeresen megtörtént.
FolderTaskDescription                     = A {0} könyvtár tisztítása. Az ütemezett feladat csak akkor futtatható, ha "{0}" felhasználó bejelentkezett a rendszerbe.
EventViewerCustomViewName                 = Folyamatok
EventViewerCustomViewDescription          = Folyamatok létrehozása és parancssor ellenőrző események.
ThirdPartyAVInstalled                     = Harmadik féltől származó vírusirtó van telepítve.
GeoIdNotSupported                         = A "{0}" funkció csak Oroszországban alkalmazható.
ThirdPartyArchiverInstalled               = Egy harmadik fél által készített archívum van telepítve.
RestartWarning                            = Indítsa újra a számítógépet.
ErrorsLine                                = Sor
ErrorsMessage                             = Hibák, figyelmeztetések és értesítések
Disable                                   = Kikapcsolás
Enable                                    = Engedélyezés
Install                                   = Telepítés
Uninstall                                 = Eltávolít
RestartFunction                           = Ponovo pokrenite funkciju "{0}".
NoResponse                                = Nem hozható létre kapcsolat a {0} weboldallal.
Run                                       = Futtatás
Skipped                                   = Az "{0}" funkció kihagyva.
ThankfulToastTitle                        = Köszönjük, hogy használta a Sophia Script ❤️
DonateToastTitle                          = Az alábbi linken keresztül adományozhat 🕊
DotSourcedWarning                         = Kérjük, "dot-source"-olja a függvényt (egy ponttal az elején):\n. .\\Import-TabCompletion.ps1
'@
