ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                   = Le script supporte uniquement Windows 10 x64
UnsupportedOSBuild                     = Le script supporte les versions Windows 10 1809 Enterprise LTSC
UnsupportedRelease                     = Nouvelle version trouvée
ControlledFolderAccessDisabled         = Contrôle d'accès aux dossiers désactivé
ScheduledTasks                         = Tâches planifiées
ClearFolder                            = Supprimer tous les fichiers dans le dossier "{0}"?
FilesBlocked                           = Les fichiers suivants sont bloqués par une application tierce `nRetirer les manuellement et continuer
TempNotEmpty                           = Le dossier "{0}" n'est pas vide. L'effacer manuellement
WindowsFeaturesWindowTitle             = Fonctionnalités
FODWindowTitle                         = Fonctionnalités optionnelles (FODv2)
EnableHardwareVT                       = Activer la virtualisation dans UEFI
UserShellFolderNotEmpty                = Certains fichiers laissés dans le dossier "{0}"  `nDéplacer les manuellement vers un nouvel emplacement
RetrievingDrivesList                   = Récupération de la liste des lecteurs...
NewUserShellFolderLocation             = Nouvel emplacement: "{0}"
DesktopDriveSelect                     = Sélectionnez le lecteur à la racine duquel le dossier Bureau sera créé
DocumentsDriveSelect                   = Sélectionnez le lecteur à la racine duquel le dossier Documents sera créé
DownloadsDriveSelect                   = Sélectionnez le lecteur à la racine duquel le dossier Téléchargements sera créé
MusicDriveSelect                       = Sélectionnez le lecteur à la racine duquel le dossier Musique sera créé
PicturesDriveSelect                    = Sélectionnez le lecteur à la racine duquel le dossier Images sera créé
VideosDriveSelect                      = Sélectionnez le lecteur à la racine duquel le dossier Vidéos sera créé
DesktopRequest                         = Souhaitez-vous changer l'emplacement du dossier Bureau?
DocumentsRequest                       = Souhaitez-vous changer l'emplacement du dossier Documents?
DownloadsRequest                       = Souhaitez-vous changer l'emplacement du dossier Téléchargements?
MusicRequest                           = Souhaitez-vous changer l'emplacement du dossier Musique?
PicturesRequest                        = Souhaitez-vous changer l'emplacement du dossier Images?
VideosRequest                          = Souhaitez-vous changer l'emplacement du dossier Vidéos?
DesktopFolderSelect                    = Sélectionner un dossier pour le dossier Bureau
DocumentsFolderSelect                  = Sélectionner un dossier pour le dossier Documents
DownloadsFolderSelect                  = Sélectionner un dossier pour le dossier Téléchargements
MusicFolderSelect                      = Sélectionner un dossier pour le dossier Musique
PicturesFolderSelect                   = Sélectionner un dossier pour le dossier Images
VideosFolderSelect                     = Sélectionner un dossier pour le dossier Vidéos
DesktopDefaultFolder                   = Souhaitez-vous changer l'emplacement du dossier Bureau à la valeur par défaut?
DocumentsDefaultFolder                 = Souhaitez-vous changer l'emplacement du dossier Documents à la valeur par défaut?
DownloadsDefaultFolder                 = Souhaitez-vous changer l'emplacement du dossier Téléchargements à la valeur par défaut?
MusicDefaultFolder                     = Souhaitez-vous changer l'emplacement du dossier Musique à la valeur par défaut?
PicturesDefaultFolder                  = Souhaitez-vous changer l'emplacement du dossier Images à la valeur par défaut?
VideosDefaultFolder                    = Souhaitez-vous changer l'emplacement du dossier Vidéos à la valeur par défaut?
GraphicsPerformanceTitle               = Préférence de performances graphiques
GraphicsPerformanceRequest             = Souhaitez-vous définir le paramètre de performances graphiques d'une application de votre choix sur "Haute performance"?
CleanUpTaskToast                       = Le nettoyage des fichiers Windows inutilisés et des mises à jour débute dans une minute
CleanUpTaskDescription                 = Nettoyage des fichiers Windows inutilisés et des mises à jour à l'aide de l'application intégrée pour le nettoyage de disque
FolderTaskDescription                  = Nettoyage du dossier "{0}"
ControlledFolderAccess                 = Contrôle d'accès aux dossiers
ProtectedFoldersRequest                = Souhaitez-vous activer le contrôle d'accès aux dossiers et spécifier le dossier que Microsoft Defender protégera contre les applications malveillantes et les menaces?
ProtectedFoldersListRemoved            = Dossiers supprimés
AppControlledFolderRequest             = Souhaitez-vous spécifier une application autorisée via le contrôle d'accès aux dossiers?
AllowedControlledFolderAppsRemoved     = Applications autorisées supprimées
DefenderTitle                          = Microsoft Defender
DefenderExclusionFolderRequest         = Souhaitez-vous spécifier un dossier à exclure des analyses de logiciels malveillants de Microsoft Defender?
DefenderExclusionFoldersListRemoved    = Dossiers exclus supprimés
AddDefenderExclusionFileRequest        = Souhaitez-vous spécifier un fichier à exclure des analyses de logiciels malveillants de Microsoft Defender?
DefenderExclusionFilesRemoved          = Fichiers exclus supprimés
EventViewerCustomViewName              = Création du processus
EventViewerCustomViewDescription       = Audit des événements de création du processus et de ligne de commande
RestartWarning                         = Assurez-vous de redémarrer votre PC
ErrorsLine                             = Ligne
ErrorsFile                             = Fichier
ErrorsMessage                          = Erreurs/Avertissements
Add                                    = Ajouter
AllFilesFilter                         = Tous les Fichiers (*.*)|*.*
Change                                 = Changer
Continue                               = Continuer
DialogBoxOpening                       = Afficher la boîte de dialogue...
Disable                                = Désactiver
Enable                                 = Activer
EXEFilesFilter                         = *.exe|*.exe|Tous les Fichiers (*.*)|*.*
FolderSelect                           = Sélectionner un dossier
FilesWontBeMoved                       = Les fichiers ne seront pas déplacés
NoData                                 = Rien à afficher
NoInternetConnection                   = Pas de connexion Internet
Patient                                = Veuillez patienter...
Select                                 = Sélectionner
Skip                                   = Passer
Skipped                                = Passé
SymbolicSkipped                        = La création d'un lien symbolique a été ignorée
Uninstall                              = Désinstaller
Install                                = Installer
'@
