ConvertFrom-StringData -StringData @'
UnsupportedArchitecture                   = Sie verwenden eine CPU mit "{0}"-basierter Architektur. Dieses Skript unterstützt nur CPUs mit x64-Architektur. Laden Sie die für Ihre Architektur geeignete Skriptversion herunter und führen Sie sie aus.
NewSophiaScriptFound                      = Es ist eine neue Version verfügbar: Sophia Script for Windows {0}. Bitte führen Sie ein Update durch.
UnsupportedPowerShell                     = Sie versuchen, das Skript über PowerShell {0}.{1} auszuführen. Bitte führen Sie das Skript in PowerShell {2} aus.
CodeCompilationFailed                     = Die Code-Kompilierung ist fehlgeschlagen.
KeyboardArrows                            = Bitte verwenden Sie die Pfeiltasten {0} und {1} auf Ihrer Tastatur, um Ihre Antwort auszuwählen
UnsupportedLanguageMode                   = Die PowerShell-Sitzung wird in einem eingeschränkten Sprachmodus ausgeführt.
LoggedInUserNotAdmin                      = Der angemeldete Benutzer "{0}" hat keine Administratorrechte. Das Skript wurde im Namen von "{1}" ausgeführt. Bitte melden Sie sich bei einem Konto mit Administratorrechten an und führen Sie das Skript erneut aus.
UnsupportedHost                           = Das Skript unterstützt keine Ausführung über {0}.
HarmfulTweakerFound                       = Die Stabilität des Windows-Betriebssystems kann durch die Verwendung des {0} beeinträchtigt worden sein.
HostsEntriesFound                         = In der Datei %SystemRoot%\\System32\\drivers\\etc\\hosts wurden Einträge von Drittanbietern gefunden. Diese können die Verbindung zu den im Skript verwendeten Ressourcen blockieren. Möchten Sie fortfahren?
UWPComponentsMissing                      = Die UWP-Komponente "{0}" fehlt.
DefenderComponentsMissing                 = Die Komponente "{0}" von Microsoft Defender fehlt.
WindowsComponentStabilityDisrupted        = In der Komponente "{0}" wurde ein Stabilitätsproblem festgestellt.
DisableControlledFolderAccess             = Sie haben den kontrollierten Ordnerzugriff aktiviert. Bitte deaktivieren Sie ihn und führen Sie das Skript erneut aus.
RebootPending                             = Ihr PC wartet darauf, neu gestartet zu werden.
SystemDriveEncryptedBitLockerDisabled     = Das Laufwerk C ist verschlüsselt, obwohl BitLocker deaktiviert ist. Möchten Sie Ihr Laufwerk entschlüsseln?
UpdateUEFICertificates                    = Das Secure-Boot-Zertifikat "Microsoft Windows Production PCA 2011" läuft im Jahr 2026 ab. Ihr Gerät hat die aktualisierten "Windows UEFI CA 2023"-Zertifikate noch nicht erhalten. Möchten Sie die "Microsoft Windows UEFI CA 2023"-Zertifikate manuell installieren?
EnableSecureBoot                          = Aktivieren Sie Secure Boot.
WrongSophiaScriptVersion                  = Das Skript unterstützt ausschließlich Windows 11 Enterprise LTSC 2024. Sie verwenden {0} {1}. Führen Sie das für Ihre Windows-Edition geeignete Skript aus.
UpdateWindowsBuild                        = Das Skript unterstützt Windows 11 Enterprise LTSC 2024 {0}.{1} und höher. Sie verwenden {2} {3} {4}.{5}. Führen Sie Windows Update aus und versuchen Sie es erneut.
AskQuestion                               = Falls Sie eine Frage haben, erstellen Sie bitte ein Ticket auf GitHub oder wenden Sie sich an die Community.
CheckSophiaScriptPreset                   = Haben Sie alle Funktionen in der Voreinstellungsdatei {0} angepasst, bevor Sie Sophia Script for Windows ausführen?
ReinstallWindows                          = Installieren Sie Windows nur mit einem Original-ISO-Abbild neu.
CreatingRestorePoint                      = Ein Wiederherstellungspunkt wird erstellt...
WindowsServiceNotFound                    = Der Dienst "{0}" wurde nicht gefunden.
NoScheduledTasksFound                     = Keine geplanten Aufgaben gefunden.
ScheduledTasks                            = Geplante Aufgaben
SearchHighlightsDisabled                  = Die Suchhighlights sind im Startmenü bereits ausgeblendet.
CustomStartMenuFound                      = Ein Startmenü eines Drittanbieters ist installiert.
InstallingApplication                     = {0} wird installiert...
NoWindowsFeaturesFound                    = Keine Windows-Features gefunden.
WindowsFeaturesTitle                      = Windows-Features
NoOptionalFeaturesFound                   = Keine optionalen Features gefunden.
OptionalFeaturesTitle                     = Optionale Features
NoSupportedNetworkAdaptersFound           = Keine Netzwerkadapter, die die Funktion "Computer kann dieses Gerät ausschalten, um Energie zu sparen" unterstützen.
LocationServicesDisabled                  = Netzwerkshellbefehle benötigen die Berechtigung für den Standortzugriff, um WLAN-Informationen abzurufen. Aktivieren Sie die Ortungsdienste auf der Seite Standort in den Einstellungen unter Datenschutz & Sicherheit.
UserFolderLocationMove                    = Sie sollten den Speicherort des Benutzerordners nicht in das Stammverzeichnis des Laufwerks C ändern.
DriveSelect                               = Wählen Sie das Laufwerk aus, auf dem der Ordner "{0}" im Stammverzeichnis angelegt werden soll.
CurrentUserFolderLocation                 = Der aktuelle Speicherort des Ordners "{0}" lautet: "{1}".
FilesWontBeMoved                          = Die Dateien werden nicht verschoben.
UserFolderMoveSkipped                     = Sie haben das Ändern des Speicherorts des Benutzerordners "{0}" übersprungen.
UserShellFolderNotEmpty                   = Im Ordner "{0}" befinden sich noch Dateien. Verschieben Sie sie manuell an einen neuen Ort.
FolderSelect                              = Wählen Sie einen Ordner aus
UserFolderRequest                         = Möchten Sie den Speicherort des Ordners "{0}" ändern?
UserDefaultFolder                         = Möchten Sie den Speicherort des Ordners "{0}" auf den Standardwert ändern?
ReservedStorageIsInUse                    = Der reservierte Speicher wird genutzt.
ProgramPathNotExists                      = Der Pfad "{0}" existiert nicht.
ProgIdNotExists                           = Die ProgId "{0}" existiert nicht.
AllFilesFilter                            = Alle Dateien
JSONNotValid                              = Die JSON-Datei "{0}" ist ungültig.
PackageNotInstalled                       = Die Anwendung "{0}" ist nicht installiert.
PackageIsInstalled                        = Die neueste Version von {0} ist bereits installiert.
WDDMVersionUnsupported                    = Unterstützte WDDM-Version: 2.7 und höher. Aktuelle WDDM-Version: {0}.
CleanupTaskNotificationTitle              = Windows-Bereinigung
CleanupTaskNotificationEvent              = Aufgabe zum Bereinigen nicht verwendeter Windows-Dateien und -Updates ausführen?
CleanupTaskDescription                    = Bereinigen nicht verwendeter Windows-Dateien und -Updates mithilfe der integrierten Datenträgerbereinigungs-App.
CleanupNotificationTaskDescription        = Popup-Benachrichtigung zur Erinnerung an die Bereinigung nicht verwendeter Windows-Dateien und -Updates.
SoftwareDistributionTaskNotificationEvent = Der Windows Update-Cache wurde erfolgreich gelöscht.
SoftwareDistributionTaskDescription       = Bereinigung des Windows Update-Cacheordners "{0}".
TempTaskNotificationEvent                 = Der temporäre Ordner wurde erfolgreich bereinigt.
TempTaskDescription                       = Bereinigung des temporären Ordners "{0}" (%TEMP%).
ScheduledTaskLoggedInUserNotification     = Die geplante Aufgabe kann nur ausgeführt werden, wenn der Benutzer "{0}" im System angemeldet ist.
CleanupTaskCLIDescription                 = Die geplante Aufgabe "Sophia\\Windows Cleanup Notification" wurde in der Aufgabenplanung erstellt, um nicht verwendete Windows-Dateien und -Updates zu bereinigen.
SoftwareDistributionTaskCLIDescription    = Die geplante Aufgabe "Sophia\\SoftwareDistribution" wurde in der Aufgabenplanung erstellt, um den Windows Update-Cacheordner "{0}" zu bereinigen.
TempTaskCLIDescription                    = Die geplante Aufgabe "Sophia\\Temp" wurde in der Aufgabenplanung erstellt, um den temporären Ordner "{0}" (%TEMP%) zu bereinigen.
EventViewerCustomViewName                 = Prozesserstellung
EventViewerCustomViewDescription          = Gestartete Prozesse und PowerShell-Aktivitäten verfolgen
EventViewerCustomViewNotification         = Die benutzerdefinierte Ansicht "Benutzerdefinierte Ansichten\\{0}" wurde in der Ereignisanzeige erstellt, um gestartete Prozesse und PowerShell-Aktivitäten zu verfolgen.
ThirdPartyAVInstalled                     = Ein Antivirenprogramm eines Drittanbieters ist installiert.
EnableHardwareVT                          = Aktivieren Sie die Virtualisierung im UEFI.
ActiveNetworkAdapterNotFound              = Der derzeit verwendete Netzwerkadapter konnte nicht ermittelt werden: Es wurde keine aktive Netzwerkverbindung gefunden. Stellen Sie eine Verbindung mit einem Netzwerk her.
ThirdPartyArchiverInstalled               = Ein Archivierungsprogramm eines Drittanbieters ist installiert.
RestartWarning                            = Stellen Sie sicher, dass Sie Ihren PC neu starten.
RestorePointVolume                        = Die Wiederherstellungspunkte für das Laufwerk C belegen {0} GB.
ErrorsLine                                = Zeile
ErrorsMessage                             = Fehler, Warnungen und Benachrichtigungen
Disable                                   = Deaktivieren
Enable                                    = Aktivieren
Install                                   = Installieren
Uninstall                                 = Deinstallieren
RestartFunction                           = Bitte führen Sie die Funktion "{0}" erneut aus.
NoConnectionEstablished                   = Verbindung zu {0} konnte nicht hergestellt werden.
Run                                       = Starten
FunctionSkipped                           = Funktion "{0}" übersprungen.
DonateToastTitle                          = Spenden sind willkommen! ❤
DotSourceFunction                         = Bitte "dot-source" die Funktion (mit einem Punkt am Anfang):\n. .\\Import-TabCompletion.ps1
'@
