ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Skrypt obsługuje tylko system Windows 10 x64
UnsupportedOSBuild                        = Skrypt obsługuje system Windows 10 21H2/22H2+
UpdateWarning                             = Zainstalowano zbiorczą aktualizację systemu Windows 10: {0}. Obsługiwane aktualizacje zbiorcze: 2364 i nowsze. Uruchom aktualizację systemu Windows i spróbuj ponownie.
UnsupportedLanguageMode                   = Sesja PowerShell działa w trybie ograniczonego języka
LoggedInUserNotAdmin                      = Zalogowany użytkownik nie posiada uprawnień administratora
UnsupportedPowerShell                     = Próbujesz uruchomić skrypt przy użyciu PowerShell {0}.{1}. Uruchom skrypt używając odpowiedniej wersji PowerShell
UnsupportedISE                            = Skrypt nie może być uruchamiany w Windows PowerShell ISE
Win10TweakerWarning                       = Prawdopodobnie twój system operacyjny został zainfekowany przez backdoora pochodzącego z Win 10 Tweaker
SycnexWarning                             = Stabilność systemu Windows mogła zostać naruszona przez użycie skryptu Windows10Debloater od Sycnex. Zapobiegawczo zainstaluj ponownie Windows
Fs00Warning                               = Stabilność systemu Windows mogła zostać naruszona przez użycie "Windows 10 Bloat Remover and Tweaker". Zapobiegawczo zainstaluj ponownie Windows
bin                                       = W folderze bin nie ma żadnych plików. Proszę pobrać archiwum ponownie
RebootPending                             = Komputer oczekuje na ponowne uruchomienie
UnsupportedRelease                        = Znaleziono nową wersję
CustomizationWarning                      = \nCzy dostosowałeś funkcje w predefiniowanym pliku {0} przed uruchomieniem Sophia Script?
DefenderBroken                            = Microsoft Defender jest uszkodzony lub usunięty z systemu operacyjnego
UpdateDefender                            = Definicje programu Microsoft Defender są nieaktualne. Uruchom aktualizację systemu Windows i spróbuj ponownie.
ControlledFolderAccessDisabled            = Kontrolowany dostęp do folderów został wyłączony
ScheduledTasks                            = Zaplanowane zadania
OneDriveUninstalling                      = Odinstalowywanie OneDrive...
OneDriveInstalling                        = Instalowanie OneDrive...
OneDriveDownloading                       = Pobieranie OneDrive... ~33 MB
OneDriveWarning                           = Funkcja "{0}" zostanie zastosowana tylko wtedy, gdy ustawienie wstępne są skonfigurowane do usunięcia OneDrive (lub aplikacja została już usunięta), w przeciwnym razie funkcja tworzenia kopii zapasowych folderów "Pulpit" i "Obrazy" w usłudze OneDrive ulegnie awarii
WindowsFeaturesTitle                      = Funkcje Windows
OptionalFeaturesTitle                     = Funkcje opcjonalne
EnableHardwareVT                          = Włącz wirtualizację w UEFI
UserShellFolderNotEmpty                   = Niektóre pliki pozostały w folderze "{0}". Przenieś je ręcznie w nowe miejsce
RetrievingDrivesList                      = Pobieranie listy dysków...
DriveSelect                               = Wybierz dysk w katalogu głównym, w którym zostanie utworzony folder "{0}".
CurrentUserFolderLocation                 = Lokalizacja folderu "{0}": "{1}"
UserFolderRequest                         = Czy chcesz zmienić lokalizację folderu "{0}"?
UserFolderSelect                          = Wybierz folder dla folderu "{0}".
UserDefaultFolder                         = Czy chcesz zmienić lokalizację folderu "{0}" na wartość domyślną?
ReservedStorageIsInUse                    = Ta operacja nie jest obsługiwana, gdy używana jest zarezerwowana pamięć\nProszę ponownie uruchomić funkcję "{0}" po ponownym uruchomieniu komputera
ShortcutPinning                           = Skrót "{0}" jest przypinany do Start...
UninstallUWPForAll                        = Dla wszystkich użytkowników
UWPAppsTitle                              = Aplikacje UWP
HEVCDownloading                           = Pobieranie rozszerzeń wideo HEVC od producenta urządzenia... ~2,8 MB
GraphicsPerformanceTitle                  = Preferencje dotyczące wydajności grafiki
GraphicsPerformanceRequest                = Czy chcesz ustawić wydajność grafiki wybranej aplikacji na "Wysoka wydajność"?
ScheduledTaskPresented                    = Funkcja "{0}" została już utworzona jako "{1}"
CleanupTaskNotificationTitle              = Oczyszczanie system Windows
CleanupTaskNotificationEvent              = Uruchomić zadanie w celu usunięcia nieużywanych plików i aktualizacji systemu Windows?
CleanupTaskDescription                    = Czyszczenie nieużywanych plików i aktualizacji systemu Windows za pomocą wbudowanej aplikacji do czyszczenia dysku
CleanupNotificationTaskDescription        = Powiadomienie przypominające o czyszczeniu nieużywanych plików i aktualizacji systemu Windows
SoftwareDistributionTaskNotificationEvent = Pomyślnie usunięto pamięć podręczną aktualizacji systemu Windows
TempTaskNotificationEvent                 = Folder plików tymczasowych został pomyślnie wyczyszczony
FolderTaskDescription                     = Czyszczenie folderu {0}
EventViewerCustomViewName                 = Tworzenie procesu
EventViewerCustomViewDescription          = Tworzenie procesu i zdarzeń audytu
RestartWarning                            = Pamiętaj o ponownym uruchomieniu komputera
ErrorsLine                                = Linia
ErrorsFile                                = Plik
ErrorsMessage                             = Błędy/Ostrzeżenia
Add                                       = Dodaj
AllFilesFilter                            = Wszystkie pliki (*.*)|*.*
Browse                                    = Przeglądaj
DialogBoxOpening                          = Wyświetlanie okna dialogowego...
Disable                                   = Wyłączyć
Enable                                    = Włączać
EXEFilesFilter                            = *.exe|*.exe|Wszystkie pliki (*.*)|*.*
FolderSelect                              = Wybierz folder
FilesWontBeMoved                          = Pliki nie zostaną przeniesione
Install                                   = Zainstalluj
NoData                                    = Nic do wyświetlenia
NoInternetConnection                      = Brak połączenia z internetem
RestartFunction                           = Uruchom ponownie funkcję "{0}".
NoResponse                                = Nie można nawiązać połączenia z {0}
No                                        = Nie
Yes                                       = Tak
Open                                      = Otwórz
Patient                                   = Proszę czekać...
Restore                                   = Przywróć
Run                                       = Uruchom
SelectAll                                 = Zaznacz wszystko
Skipped                                   = Pominięto
GPOUpdate                                 = Aktualizowanie GPO...
TelegramGroupTitle                        = Dołącz do naszej oficjalnej grupy na Telegramie
TelegramChannelTitle                      = Dołącz do naszego oficjalnego kanału Telegram
DiscordChannelTitle                       = Dołącz do naszego oficjalnego kanału na Discordzie
Uninstall                                 = Odinstaluj
'@
