ConvertFrom-StringData -StringData @'
UnsupportedArchitecture                   = Ви використовуєте процесор з архітектурою "{0}". Скрипт підтримує процесори з архітектурою x64. Завантажте та запустіть версію скрипту для вашої архітектури.
UnsupportedOSBuild                        = Скрипт підтримує тільки Windows 11 Enterprise LTSC 2024. Ви використовуєте {0} {1}. Оновіть Windows і спробуйте ще раз.
UnsupportedWindowsTerminal                = Версія Windows Terminal нижча за 1.23. Будь ласка, оновіть його в Microsoft Store і спробуйте заново.
UpdateWarning                             = Ви використовуєте Windows 11 {0}.{1}. Підтримувані збірки: Windows 11 {0}.{2} і вище. Запустіть оновлення Windows і спробуйте ще раз.
UnsupportedLanguageMode                   = Сесія PowerShell працює в обмеженому режимі.
LoggedInUserNotAdmin                      = Користувач {0}, що увійшов, не має прав адміністратора. Скрипт був запущений від імені {1}. Будь ласка, увійдіть в профіль, що має права адміністратора, і запустіть скрипт заново.
UnsupportedPowerShell                     = Ви намагаєтеся запустити скрипт в PowerShell {0}.{1}. Запустіть скрипт в PowerShell {2}.
CodeCompilationFailedWarning              = Компіляція коду завершилася з помилкою.
UnsupportedHost                           = Скрипт не підтримує роботу через {0}.
Win10TweakerWarning                       = Windows була заражена трояном через бекдор у Win 10 Tweaker. Перевстановіть Windows, використовуючи тільки справжній ISO-образ.
TweakerWarning                            = Стабільність вашої ОС могла бути порушена використанням {0}. Перевстановіть Windows, використовуючи тільки справжній ISO-образ.
HostsWarning                              = У файлі %SystemRoot%\\System32\\drivers\\etc\\hosts виявлено сторонні записи. Вони можуть блокувати з'єднання з ресурсами, що використовуються в роботі скрипта. Хочете продовжити?
RebootPending                             = Ваш комп'ютер очікує перезавантаження.
BitLockerInOperation                      = BitLocker працює. Ваш диск C зашифровано на {0} %. Завершіть налаштування диска BitLocker і спробуйте ще раз.
BitLockerAutomaticEncryption              = Диск C зашифрований, хоча BitLocker вимкнено. Хочете розшифрувати диск?
UnsupportedRelease                        = Виявлено нову версію Sophia Script for Windows: {0}. Будь ласка, завантажте останню версію.
KeyboardArrows                            = Для вибору відповіді використовуйте на клавіатурі стрілки  {0} і {1}
CustomizationWarning                      = Ви налаштували всі функції в пресет-файлі {0} перед запуском Sophia Script for Windows?
WindowsComponentBroken                    = {0} пошкоджено або видалено з ОС. Перевстановіть Windows, використовуючи тільки справжній ISO-образ.
ControlledFolderAccessEnabledWarning      = У вас увімкнено контрольований доступ. Будь ласка, вимкніть його та спробуйте ще раз.
NoScheduledTasks                          = Немає запланованих завдань, які необхідно вимкнути.
ScheduledTasks                            = Заплановані задачі
SearchHighlightsDisabled                  = Основні результати пошуку в меню "Пуск" вже приховані.
CustomStartMenu                           = Встановлено стороннє меню "Пуск".
InstallNotification                       = {0} встановлюється...
NoWindowsFeatures                         = Немає компонентів Windows, які необхідно вимкнути.
WindowsFeaturesTitle                      = Компоненти Windows
NoOptionalFeatures                        = Немає компонентів Windows, які необхідно вимкнути.
NoSupportedNetworkAdapters                = Немає мережевих адаптерів, що підтримують функцію "Дозволити комп'ютеру відключати цей пристрій для економії енергії".
LocationServicesDisabled                  = Командам мережевої оболонки потрібен дозвіл на доступ до відомостей бездротової мережі. Увімкніть служби визначення місцезнаходження на сторінці "Розташування" в параметрах конфіденційності та захисту.
OptionalFeaturesTitle                     = Додаткові компоненти
UserShellFolderNotEmpty                   = У папці "{0}" залишилися файли. Перемістіть їх вручну в нове розташування.
UserFolderLocationMove                    = Не слід переміщати користувацькі папки в корінь диска C.
DriveSelect                               = Виберіть диск, в корні якого буде створена папка для "{0}".
CurrentUserFolderLocation                 = Поточне розташування папки "{0}": "{1}".
FilesWontBeMoved                          = Файли не будуть перенесені.
UserFolderMoveSkipped                     = Ви пропустили зміну розташування папки користувача "{0}".
FolderSelect                              = Виберіть папку
UserFolderRequest                         = Бажаєте змінити розташування папки "{0}"?
UserDefaultFolder                         = Бажаєте змінити розташування папки "{0}" на значення за замовчуванням?
ReservedStorageIsInUse                    = Використовується зарезервоване сховище.
ProgramPathNotExists                      = Шлях "{0}" не існує.
ProgIdNotExists                           = ProgId "{0}" не існує.
AllFilesFilter                            = Всі файли
JSONNotValid                              = Файл JSON "{0}" недійсний.
PackageNotInstalled                       = {0} не встановлено.
PackageIsInstalled                        = Остання версія {0} вже встановлена.
UninstallUWPForAll                        = Для всіх користувачів
NoUWPApps                                 = Немає UWP-додатків, які необхідно видалити.
UWPAppsTitle                              = UWP-додатки
ScheduledTaskCreatedByAnotherUser         = Функцію "{0}" уже було створено від імені "{1}".
CleanupTaskNotificationTitle              = Очищення Windows
CleanupTaskNotificationEvent              = Запустити завдання з очищення невикористовуваних файлів і оновлень Windows?
CleanupTaskDescription                    = Очищення невикористовуваних файлів і оновлень Windows, використовуючи вбудовану програму Очищення диска. Завдання може бути запущено, тільки якщо користувач "{0}" увійшов у систему.
CleanupNotificationTaskDescription        = Спливаюче повідомлення з нагадуванням про очищення невикористовуваних файлів і оновлень Windows. Завдання може бути запущено, тільки якщо користувач "{0}" увійшов у систему.
SoftwareDistributionTaskNotificationEvent = Кеш оновлень Windows успішно видалено.
TempTaskNotificationEvent                 = Папка тимчасових файлів успішно очищена.
FolderTaskDescription                     = Очищення папки "{0}". Завдання може бути запущено, тільки якщо користувач "{0}" увійшов у систему.
EventViewerCustomViewName                 = Створення процесу
EventViewerCustomViewDescription          = Події створення нового процесу і аудит командного рядка.
ThirdPartyAVInstalled                     = Встановлено сторонній антивірус.
GeoIdNotSupported                         = Функція "{0}" застосовується тільки для Росії.
EnableHardwareVT                          = Увімкніть віртуалізацію в UEFI.
ThirdPartyArchiverInstalled               = Встановлено сторонній архіватор.
RestartWarning                            = Обов'язково перезавантажте ваш ПК.
ErrorsLine                                = Рядок
ErrorsMessage                             = Помилки, попередження та повідомлення
Disable                                   = Вимкнути
Enable                                    = Увімкнути
Install                                   = Встановити
Uninstall                                 = Видалити
RestartFunction                           = Будь ласка, повторно запустіть функцію "{0}".
NoResponse                                = Не вдалося встановити зв’язок із {0}.
Run                                       = Запустити
Skipped                                   = Функцію "{0}" пропущено.
ThankfulToastTitle                        = Дякуємо за використання Sophia Script for Windows ❤️
DonateToastTitle                          = Ви можете зробити пожертву нижче 🕊️
DotSourcedWarning                         = Будь ласка, запустіть функцію через дот-сорсинг (з крапкою на початку):\n. .\\Import-TabCompletion.ps1
'@
