ConvertFrom-StringData -StringData @'
NewSophiaScriptFound                      = Виявлено нову версію: Sophia Script for Windows {0}. Будь ласка, завантажте останню версію.
UnsupportedPowerShell                     = Ви намагаєтеся запустити скрипт в PowerShell {0}.{1}. Запустіть скрипт в PowerShell {2}.
CodeCompilationFailed                     = Компіляція коду завершилася з помилкою.
UnsupportedWindowsBitness                 = Скрипт підтримує тільки 64-розрядну версію Windows.
KeyboardArrows                            = Для вибору відповіді використовуйте на клавіатурі стрілки {0} і {1}
UnsupportedLanguageMode                   = Сесія PowerShell працює в обмеженому режимі.
LoggedInUserNotAdmin                      = Користувач "{0}", що увійшов, не має прав адміністратора. Скрипт був запущений від імені "{1}". Будь ласка, увійдіть в профіль, що має права адміністратора, і запустіть скрипт заново.
UnsupportedHost                           = Скрипт не підтримує роботу через {0}.
HarmfulTweakerFound                       = Стабільність Windows могла бути порушена використанням {0}.
HostsEntriesFound                         = У файлі %SystemRoot%\\System32\\drivers\\etc\\hosts виявлено сторонні записи. Вони можуть блокувати з'єднання з ресурсами, що використовуються в роботі скрипту. Хочете продовжити?
UWPComponentsMissing                      = Відсутній UWP-компонент "{0}".
DefenderComponentsMissing                 = Відсутній компонент "{0}" для Microsoft Defender.
WindowsComponentStabilityDisrupted        = Виявлено порушення стабільності роботи компонента "{0}".
DisableControlledFolderAccess             = У вас увімкнено контрольований доступ до папок. Будь ласка, вимкніть його та спробуйте ще раз.
RebootPending                             = Ваш комп'ютер очікує перезавантаження.
SystemDriveEncryptedBitLockerDisabled     = Диск C зашифрований, хоча BitLocker вимкнено. Хочете розшифрувати диск?
WrongSophiaScriptVersion                  = Скрипт підтримує тільки Windows 10 Enterprise LTSC 2019. Ви використовуєте {0} {1}. Запустіть скрипт відповідно до вашої версії Windows.
UpdateWindowsBuild                        = Скрипт підтримує Windows 10 Enterprise LTSC 2019 {0}.{1} та новіші версії. Ви використовуєте {2} {3} {4}.{5}. Запустіть оновлення Windows і спробуйте ще раз.
AskQuestion                               = Якщо у вас виникнуть запитання, створіть issue на GitHub або зверніться до спільноти.
CheckSophiaScriptPreset                   = Ви налаштували всі функції в пресет-файлі {0} перед запуском Sophia Script for Windows?
ReinstallWindows                          = Перевстановіть Windows, використовуючи тільки справжній ISO-образ.
CreatingRestorePoint                      = Створюється точка відновлення...
WindowsServiceNotFound                    = Відсутня служба "{0}".
NoScheduledTasksFound                     = Заплановані завдання не знайдено.
ScheduledTasks                            = Заплановані завдання
TaskbarSmallIcons                         = Ви використовуєте маленькі кнопки панелі завдань.
CustomStartMenuFound                      = Встановлено стороннє меню "Пуск".
InstallingApplication                     = {0} встановлюється...
NoWindowsFeaturesFound                    = Компоненти Windows не знайдено.
WindowsFeaturesTitle                      = Компоненти Windows
NoOptionalFeaturesFound                   = Додаткові компоненти не знайдено.
OptionalFeaturesTitle                     = Додаткові компоненти
NoSupportedNetworkAdaptersFound           = Немає мережевих адаптерів, що підтримують функцію "Дозволити комп'ютеру відключати цей пристрій для економії енергії".
LocationServicesDisabled                  = Командам мережевої оболонки потрібен дозвіл на визначення місцезнаходження для доступу до відомостей бездротової мережі. Увімкніть служби визначення місцезнаходження на сторінці "Розташування" в параметрах конфіденційності та захисту.
UserFolderLocationMove                    = Не слід переміщати користувацькі папки в корінь диска C.
DriveSelect                               = Виберіть диск, у корені якого буде створено папку "{0}".
CurrentUserFolderLocation                 = Поточне розташування папки "{0}": "{1}".
FilesWontBeMoved                          = Файли не будуть перенесені.
UserFolderMoveSkipped                     = Ви пропустили зміну розташування папки користувача "{0}".
UserShellFolderNotEmpty                   = У папці "{0}" залишилися файли. Перемістіть їх вручну в нове розташування.
FolderSelect                              = Виберіть папку
UserFolderRequest                         = Бажаєте змінити розташування папки "{0}"?
UserDefaultFolder                         = Бажаєте змінити розташування папки "{0}" на значення за замовчуванням?
ProgramPathNotExists                      = Шлях "{0}" не існує.
ProgIdNotExists                           = ProgId "{0}" не існує.
AllFilesFilter                            = Всі файли
JSONNotValid                              = Файл JSON "{0}" недійсний.
PackageIsInstalled                        = Остання версія {0} вже встановлена.
CleanupTaskNotificationTitle              = Очищення Windows
CleanupTaskNotificationEvent              = Запустити завдання з очищення невикористовуваних файлів і оновлень Windows?
CleanupTaskDescription                    = Очищення невикористовуваних файлів та оновлень Windows за допомогою вбудованої програми "Очищення диска".
CleanupNotificationTaskDescription        = Спливаюче повідомлення з нагадуванням про очищення невикористовуваних файлів і оновлень Windows.
SoftwareDistributionTaskNotificationEvent = Кеш оновлень Windows успішно видалено.
SoftwareDistributionTaskDescription       = Очищення папки кешу оновлень Windows "{0}".
TempTaskNotificationEvent                 = Тимчасову папку успішно очищено.
TempTaskDescription                       = Очищення тимчасової папки "{0}" (%TEMP%).
ScheduledTaskLoggedInUserNotification     = Завдання можна запустити лише в тому випадку, якщо користувач "{0}" увійшов у систему.
CleanupTaskCLIDescription                 = Заплановане завдання "Sophia\\Windows Cleanup Notification" створено в Планувальнику завдань для очищення невикористовуваних файлів та оновлень Windows.
SoftwareDistributionTaskCLIDescription    = Заплановане завдання "Sophia\\SoftwareDistribution" створено в Планувальнику завдань для очищення папки кешу оновлень Windows "{0}".
TempTaskCLIDescription                    = Заплановане завдання "Sophia\\Temp" створено в Планувальнику завдань для очищення тимчасової папки "{0}" (%TEMP%).
EventViewerCustomViewName                 = Створення процесу
EventViewerCustomViewDescription          = Відстеження запущених процесів та активності PowerShell
EventViewerCustomViewNotification         = Настроюване подання "Настроювані подання\\{0}" створено в "Перегляді подій" для відстеження запущених процесів та активності PowerShell.
ThirdPartyAVInstalled                     = Встановлено сторонній антивірус.
EnableHardwareVT                          = Увімкніть віртуалізацію в UEFI.
ThirdPartyArchiverInstalled               = Встановлено сторонній архіватор.
RestartWarning                            = Обов'язково перезавантажте ваш ПК.
RestorePointVolume                        = Точки відновлення на диску C займають {0} ГБ.
ErrorsLine                                = Рядок
ErrorsMessage                             = Помилки, попередження та повідомлення
Disable                                   = Вимкнути
Enable                                    = Увімкнути
Install                                   = Встановити
Uninstall                                 = Видалити
RestartFunction                           = Будь ласка, повторно запустіть функцію "{0}".
NoConnectionEstablished                   = Не вдалося встановити зв'язок із {0}.
Run                                       = Запустити
FunctionSkipped                           = Функцію "{0}" пропущено.
DonateToastTitle                          = Ви можете зробити пожертву! ♥
DotSourceFunction                         = Будь ласка, запустіть функцію через дот-сорсинг (з крапкою на початку):\n. .\\Import-TabCompletion.ps1
'@
