ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Das Skript unterstützt nur Windows 10 x64
UnsupportedOSBuild                        = Das Skript unterstützt Windows 10 2004/20H2/21H1-Versionen und höher
UnsupportedLanguageMode                   = Die PowerShell-Sitzung wird in einem eingeschränkten Sprachmodus ausgeführt
LoggedInUserNotAdmin                      = Der angemeldete Benutzer hat keine Administratorrechte
UnsupportedISE                            = Das Skript unterstützt nicht die Ausführung über Windows PowerShell ISE
Win10TweakerWarning                       = Wahrscheinlich wurde Ihr Betriebssystem über die Win 10 Tweaker-Hintertür infiziert
UpdateWarning                             = Ihr Windows 10-Build: {0}.{1}.{2}.{3}. Unterstützter Build: 10.0.19043.1052 und höher
UnsupportedRelease                        = Neue Version gefunden
CustomizationWarning                      = \nHaben Sie alle Funktionen in der voreingestellten Datei Sophia.ps1 angepasst, bevor Sie Sophia Script ausführen?
ControlledFolderAccessDisabled            = Kontrollierter Ordnerzugriff deaktiviert
ScheduledTasks                            = Geplante Aufgaben
OneDriveUninstalling                      = Deinstalliere OneDrive...
OneDriveInstalling                        = OneDrive wird installiert...
OneDriveDownloading                       = OneDrive herunterladen... ~33 MB
WindowsFeaturesTitle                      = Windows Eigenschaften
OptionalFeaturesTitle                     = Optionale Eigenschaften
EnableHardwareVT                          = Virtualisierung in UEFI aktivieren
UserShellFolderNotEmpty                   = Einige im Ordner "{0}" verbliebene Dateien \nVerschieben Sie sie manuell an einen neuen Ort
RetrievingDrivesList                      = Abrufen der Laufwerksliste...
DriveSelect                               = Wählen Sie das Laufwerk, in dessen Stammverzeichnis der "{0}"-Ordner erstellt werden soll
UserFolderRequest                         = Möchten Sie den Speicherort des "{0}"-Ordners ändern?
UserFolderSelect                          = Wählen Sie einen Ordner für den Ordner "{0}"
UserDefaultFolder                         = Möchten Sie den Speicherort des "{0}"-Ordners auf den Standardwert ändern?
ReservedStorageIsInUse                    = Dieser Vorgang wird nicht unterstützt, wenn reservierter Speicher verwendet wird \nBitte warten Sie, bis alle Wartungsvorgänge abgeschlossen sind, und versuchen Sie es dann später erneut
ShortcutPinning                           = Die Verknüpfung "{0}" wird an Start angeheftet
UninstallUWPForAll                        = Für alle Benutzer
UWPAppsTitle                              = UWP-Pakete
WSLUpdateDownloading                      = Herunterladen des Update-Pakets für den Linux-Kernel... ~14 MB
WSLUpdateInstalling                       = Installation des Aktualisierungspakets für den Linux-Kernel...
HEVCDownloading                           = Herunterladen von HEVC-Videoerweiterungen vom Gerätehersteller... ~2,8 MB
GraphicsPerformanceTitle                  = Bevorzugte Grafikleistung
GraphicsPerformanceRequest                = Möchten Sie die Einstellung der Grafikleistung einer App Ihrer Wahl auf "Hohe Leistung" setzen?
TaskNotificationTitle                     = Benachrichtigung
CleanupTaskNotificationTitle              = Wichtige informationen
CleanupTaskDescription                    = Bereinigung ungenutzter Windows-Dateien und -Updates mit der integrierten Festplatten-Bereinigungsanwendung
CleanupTaskNotificationEventTitle         = Aufgabe ausführen, um nicht verwendete Windows-Dateien und -Updates zu bereinigen?
CleanupTaskNotificationEvent              = Die Windows-Bereinigung dauert nicht lange. Das nächste Mal wird die Benachrichtigung in 30 Tagen angezeigt
CleanupTaskNotificationSnoozeInterval     = Wählen Sie ein Erinnerungsintervall
CleanupNotificationTaskDescription        = Bereinigung ungenutzter Windows-Dateien und -Updates mit der integrierten Festplatten-Bereinigungsanwendung
SoftwareDistributionTaskNotificationEvent = Der Windows Update-Cache wurde erfolgreich gelöscht
TempTaskNotificationEvent                 = Der Ordner mit den temporären Dateien wurde erfolgreich bereinigt
FolderTaskDescription                     = Die Bereinigung des Ordners "{0}"
EventViewerCustomViewName                 = Prozess-Erstellung
EventViewerCustomViewDescription          = Ereignisse zur Prozesserstellung und Befehlszeilen-Auditierung
RestartWarning                            = \nAchten Sie darauf, Ihren PC neu zu starten
ErrorsLine                                = Zeile
ErrorsFile                                = Datei
ErrorsMessage                             = Fehler/Warnungen
Add                                       = Hinzufügen
AllFilesFilter                            = Alle Dateien (*.*)|*.*
Browse                                    = Durchsuche
Change                                    = Ändern
DialogBoxOpening                          = Anzeigen des Dialogfensters...
Disable                                   = Deaktivieren
Enable                                    = Aktivieren
EXEFilesFilter                            = *.exe|*.exe|Alle Dateien (*.*)|*.*
FolderSelect                              = Wählen Sie einen Ordner aus
FilesWontBeMoved                          = Dateien werden nicht verschoben
FourHours                                 = 4 Stunden
HalfHour                                  = 30 Minuten
Install                                   = Installieren
Minute                                    = 1 Minute
NoData                                    = Nichts anzuzeigen
NoInternetConnection                      = Keine Internetverbindung
NoResponse                                = Eine Verbindung mit https://store.rg-adguard.net konnte nicht hergestellt werden
No                                        = Nein
Yes                                       = Ja
Open                                      = Öffnen
Patient                                   = Bitte Warten...
Restore                                   = Wiederherstellen
Run                                       = Starten
SelectAll                                 = Wählen Sie Alle
Skip                                      = Überspringen
Skipped                                   = Übersprungen
TelegramTitle                             = Abonniere doch unseren offiziellen Kanal telegram
Uninstall                                 = Deinstallieren
'@
