ConvertFrom-StringData -StringData @'
NewSophiaScriptFound                      = Está disponível uma nova versão: Sophia Script for Windows {0}. Por favor, atualize.
UnsupportedPowerShell                     = Você está tentando executar o script via PowerShell {0}.{1}. Execute o script no PowerShell {2}.
CodeCompilationFailed                     = Falha na compilação do código.
UnsupportedWindowsBitness                 = O guião suporta apenas Windows de 64 bits.
KeyboardArrows                            = Use as teclas de seta {0} e {1} do teclado para selecionar sua resposta
UnsupportedLanguageMode                   = A sessão PowerShell em funcionamento em um modo de linguagem limitada.
LoggedInUserNotAdmin                      = O usuário conectado "{0}" não possui direitos de administrador. O script foi executado em nome de "{1}". Faça login em uma conta com direitos de administrador e execute o script novamente.
UnsupportedHost                           = O guião não suporta a execução através do {0}.
HarmfulTweakerFound                       = A estabilidade do sistema operacional Windows pode ter sido comprometida pela utilização do {0}.
HostsEntriesFound                         = Entradas de terceiros encontradas no arquivo %SystemRoot%\\System32\\drivers\\etc\\hosts. Elas podem bloquear a conexão com recursos usados no script. Deseja continuar?
WindowsComponentStabilityDisrupted        = Foi detectado um problema de instabilidade no componente "{0}".
DisableControlledFolderAccess             = Você tem o acesso controlado a pastas ativado. Desative-o e execute o script novamente.
RebootPending                             = Seu computador está aguardando para ser reiniciado.
SystemDriveEncryptedBitLockerDisabled     = A unidade C está criptografada, embora o BitLocker esteja desativado. Deseja descriptografar sua unidade?
WrongSophiaScriptVersion                  = O script é compatível apenas com o Windows 10 Enterprise LTSC 2021. Você está usando o {0} {1}. Execute o script correto de acordo com a edição do Windows.
UpdateWindowsBuild                        = Windows 10 Enterprise LTSC 2021 {0}.{1} rendszert használ. A támogatott verzió Windows 10 Enterprise LTSC 2021 {0}.{2} vagy újabb. Futtassa a Windows Update programot, majd próbálja meg újra.
CheckSophiaScriptPreset                   = Você personalizou todas as funções no arquivo de predefinição {0} antes de executar o Sophia Script for Windows?
ReinstallWindows                          = Reinstale o Windows usando apenas uma imagem ISO genuína.
CreatingRestorePoint                      = O ponto de restauração está sendo criado...
UWPComponentsMissing                      = O componente UWP "{0}" está faltando.
DefenderComponentsMissing                 = O componente "{0}" do Microsoft Defender está faltando.
DiagTrackServiceNotFound                  = O serviço "DiagTrackService" não foi encontrado.
NoScheduledTasksFound                     = Não há tarefas agendadas para desativar.
ScheduledTasks                            = Tarefas agendadas
TaskbarSmallIcons                         = Você usa botões pequenos na barra de tarefas.
InstallingApplication                     = O {0} está sendo instalado...
NoWindowsFeaturesFound                    = Não há recursos do Windows para desativar.
WindowsFeaturesTitle                      = Recursos do Windows
NoOptionalFeaturesFound                   = Não há recursos opcionais para desativar.
NoSupportedNetworkAdaptersFound           = Nenhum adaptador de rede que suporte a função "Permitir que o computador desligue este dispositivo para economizar energia".
LocationServicesDisabled                  = Os comandos do shell de rede precisam de permissão de localização para acessar as informações da WLAN. Ative os serviços de localização na página Localização nas configurações de Privacidade e segurança.
OptionalFeaturesTitle                     = Recursos opcionais
UserShellFolderNotEmpty                   = Alguns arquivos deixados na pasta "{0}". Movê-los manualmente para um novo local.
UserFolderLocationMove                    = Você não deve alterar o local da pasta do usuário para a raiz da unidade C.
DriveSelect                               = Selecione a unidade na qual a pasta "{0}" será criada no diretório raiz.
CurrentUserFolderLocation                 = A localização actual da pasta "{0}": "{1}".
FilesWontBeMoved                          = Os arquivos não serão movidos.
UserFolderMoveSkipped                     = Você não alterou a localização da pasta "{0}" do usuário.
FolderSelect                              = Selecione uma pasta
UserFolderRequest                         = Gostaria de alterar a localização da pasta "{0}"?
UserDefaultFolder                         = Gostaria de alterar a localização da pasta "{0}" para o valor padrão?
ReservedStorageIsInUse                    = O espaço de armazenamento reservado está em uso.
ProgramPathNotExists                      = O caminho "{0}" não existe.
ProgIdNotExists                           = O ProgId "{0}" não existe.
AllFilesFilter                            = Todos os arquivos
JSONNotValid                              = O arquivo JSON "{0}" não é válido.
PackageNotInstalled                       = O aplicativo "{0}" não está instalado.
PackageIsInstalled                        = A versão mais recente do {0} já está instalada.
ScheduledTaskCreatedByAnotherUser         = A tarefa agendada "{0}" já foi criada pelo usuário "{1}".
CleanupTaskNotificationTitle              = Limpeza do Windows
CleanupTaskNotificationEvent              = Executar tarefa para limpar arquivos e atualizações não utilizados do Windows?
CleanupTaskDescription                    = Limpando o Windows arquivos não utilizados e atualizações usando o aplicativo de limpeza aplicativo de limpeza embutido no disco.
CleanupNotificationTaskDescription        = Pop-up lembrete de notificação sobre a limpeza do Windows arquivos não utilizados e actualizações.
SoftwareDistributionTaskNotificationEvent = O cache de atualização do Windows excluído com sucesso.
SoftwareDistributionTaskDescription       = Limpeza da pasta de cache de atualizações do Windows "{0}".
TempTaskNotificationEvent                 = Os arquivos da pasta Temp limpos com sucesso.
TempTaskDescription                       = Limpeza da pasta temporária "{0}" (%TEMP%).
ScheduledTaskLoggedInUserNotification     = A tarefa programada só pode ser executada se o usuário "{0}" estiver conectado ao sistema.
ScheduledTaskCreatedNotification          = A tarefa agendada "{0}" foi criada.
CleanupTaskCLIDescription                 = Vá até a pasta "Sophia" no Agendador de Tarefas e execute a tarefa "Windows Cleanup Notification" para iniciar a limpeza dos arquivos e atualizações não utilizados do Windows.
SoftwareDistributionTaskCLIDescription    = Vá até a pasta "Sophia" no Agendador de Tarefas e execute a tarefa "SoftwareDistribution" para iniciar a limpeza da pasta de cache de atualizações do Windows "{0}".
TempTaskCLIDescription                    = Vá até a pasta "Sophia" no Agendador de Tarefas e execute a tarefa "Temp" para iniciar a limpeza da pasta de arquivos temporários "{0}" (%TEMP%).
EventViewerCustomViewName                 = Criação de processo
EventViewerCustomViewDescription          = Criação de processos e eventos de auditoria de linha de comando.
ThirdPartyAVInstalled                     = Um antivírus de terceiros está instalado.
EnableHardwareVT                          = Habilitar virtualização em UEFI.
ThirdPartyArchiverInstalled               = Um arquivador de terceiros está instalado.
RestartWarning                            = Certifique-se de reiniciar o PC.
RestorePointVolume                        = Os pontos de restauração da unidade C ocupam {0} GB.
ErrorsLine                                = Linha
ErrorsMessage                             = Erros, avisos e notificações
Disable                                   = Desativar
Enable                                    = Habilitar
Install                                   = Instalar
Uninstall                                 = Desinstalar
RestartFunction                           = Favor reiniciar a função "{0}".
NoConnectionEstablished                   = Uma conexão não pôde ser estabelecida com {0}.
Run                                       = Executar
FunctionSkipped                           = A função "{0}" foi ignorada.
DonateToastTitle                          = Doações são bem-vindas!❤
DotSourcedFunction                        = Faça o "dot-source" da função (com um ponto no início):\n. .\\Import-TabCompletion.ps1
'@
