ConvertFrom-StringData -StringData @'
UnsupportedArchitecture                   = 您正在使用基于"{0}"架构的CPU。此脚本仅支持基于x64架构的CPU。请下载并运行适用于您架构的脚本版本。
UnsupportedOSBuild                        = 腳本支援 Windows 11 25H2 及更高版本。您正在使用 {0} {1}。根据 Windows 版本运行相应的脚本。
UnsupportedWindowsTerminal                = Windows Terminal版本低於1.23。請在Microsoft商店更新後再試。
UpdateWarning                             = 您当前使用的是 Windows 11 {0}.{1} 版本。支持的版本为 Windows 11 {0}.{2} 及更高版本。请运行 Windows 更新并重新尝试。
UnsupportedLanguageMode                   = PowerShell会话在有限的语言模式下运行。
LoggedInUserNotAdmin                      = 已登录用户{0}没有管理员权限。脚本是以{1}的名义运行的。请登录具有管理员权限的账户并重新运行脚本。
UnsupportedPowerShell                     = 你想通过PowerShell {0}.{1}运行脚本。请在PowerShell {2}中运行脚本。
CodeCompilationFailedWarning              = 代码编译失败。
UnsupportedHost                           = 该脚本不支持通过{0}运行。
Win10TweakerWarning                       = 可能你的操作系统是通过Win 10 Tweaker后门感染的。
TweakerWarning                            = Windows的稳定性可能已被{0}所破坏。僅使用正版 ISO 映像重新安裝 Windows。
HostsWarning                              = 在 %SystemRoot%\\System32\\drivers\\etc\\hosts 文件中发现的第三方条目。它们可能会阻止连接脚本中使用的资源。是否继续?
RebootPending                             = 您的电脑正在等待重启。
BitLockerInOperation                      = BitLocker正在运行。您的C盘已加密{0}%。请完成BitLocker驱动器配置后重试。
BitLockerAutomaticEncryption              = C盘已加密, 尽管BitLocker已关闭。是否要解密您的驱动器?
UnsupportedRelease                        = 发现新版Sophia Script for Windows: {0}。请下载最新版本。
KeyboardArrows                            = 请使用键盘上的方向键{0}和{1}选择您的答案
CustomizationWarning                      = 在运行Sophia Script for Windows之前, 您是否已自定义{0}预设文件中的每个函数?
WindowsComponentBroken                    = {0} 损坏或从操作系统中删除。僅使用正版 ISO 映像重新安裝 Windows。
ControlledFolderAccessEnabledWarning      = 您已启用受控文件夹访问功能。请将其禁用后重新运行脚本。
NoScheduledTasks                          = 没有计划任务需要禁用。
ScheduledTasks                            = 计划任务
WidgetNotInstalled                        = 小部件未安装。
SearchHighlightsDisabled                  = 搜索亮点已在开始菜单中隐藏。
CustomStartMenu                           = 已安装第三方开始菜单。
OneDriveNotInstalled                      = 已安装第三方开始菜单。
OneDriveAccountWarning                    = 在卸载 OneDrive 之前, 请先在 OneDrive 中退出您的 Microsoft 帐户。
OneDriveInstalled                         = OneDrive 已安装。
UninstallNotification                     = 正在卸载{0}。。。。。。
InstallNotification                       = {0}正在安装中。。。。。。
NoWindowsFeatures                         = 没有可禁用的Windows功能。
WindowsFeaturesTitle                      = Windows 功能
NoOptionalFeatures                        = 没有可禁用的可选功能。
NoSupportedNetworkAdapters                = 没有支持"允许计算机为节省电力关闭此设备"功能的网卡适配器。
LocationServicesDisabled                  = 网络外壳命令需要位置权限才能访问无线局域网信息。请在隐私与安全设置的"位置"页面开启位置服务。
OptionalFeaturesTitle                     = 可选功能
UserShellFolderNotEmpty                   = 一些文件留在了"{0}"文件夹。请手动将它们移到一个新位置。
UserFolderLocationMove                    = 不应将用户文件夹位置更改为 C 盘根目录。
DriveSelect                               = 选择将在其根目录中创建"{0}"文件夹的驱动器。
CurrentUserFolderLocation                 = 当前"{0}"文件夹的位置:"{1}"。
FilesWontBeMoved                          = 文件不会被移动。
UserFolderMoveSkipped                     = 您跳过了更改用户"{0}"文件夹位置的步骤。
FolderSelect                              = 选择一个文件夹
UserFolderRequest                         = 是否要更改"{0}"文件夹位置?
UserDefaultFolder                         = 您想将"{0}"文件夹的位置更改为默认值吗?
ReservedStorageIsInUse                    = 已使用预留存储空间。
ProgramPathNotExists                      = 路径"{0}"不存在。
ProgIdNotExists                           = ProgId"{0}"不存在。
AllFilesFilter                            = 所有文件
JSONNotValid                              = JSON文件"{0}"无效。
PackageNotInstalled                       = 未安装"{0}"应用程序。
PackageIsInstalled                        = 最新版本的{0}已安装。
CopilotPCSupport                          = 您的电脑未内置 AI 加速器(NPU), 因此不支持 Windows 的 AI 相关功能。无需通过 Windows 策略禁用任何功能。仅会移除 Recall 功能和 Copilot 应用程序。
UninstallUWPForAll                        = 所有用户
NoUWPApps                                 = 没有可卸载的UWP应用。
UWPAppsTitle                              = UWP应用
ScheduledTaskCreatedByAnotherUser         = 计划任务"{0}"已由用户"{1}"创建。
CleanupTaskNotificationTitle              = Windows清理
CleanupTaskNotificationEvent              = 运行任务以清理Windows未使用的文件和更新?
CleanupTaskDescription                    = 使用内置磁盘清理工具清理未使用的Windows文件和更新。
CleanupNotificationTaskDescription        = 关于清理Windows未使用的文件和更新的弹出通知提醒。
SoftwareDistributionTaskNotificationEvent = Windows更新缓存已成功删除。
SoftwareDistributionTaskDescription       = 清理 Windows 更新缓存文件夹"{0}"。
TempTaskNotificationEvent                 = 临时文件文件夹已成功清理。
TempTaskDescription                       = 正在清理临时文件夹"{0}"（%TEMP%）。
ScheduledTaskLoggedInUserNotification     = 只有登入使用者"{0}"才能啟動任務。
ScheduledTaskCreatedNotification          = 已创建计划任务"{0}"。
CleanupTaskCLIDescription                 = 在"任务计划程序"中进入"Sophia"文件夹，运行"Windows Cleanup Notification"任务，开始清理 Windows 中的未使用文件和更新。
SoftwareDistributionTaskCLIDescription    = 在"任务计划程序"中转到"Sophia"文件夹，并运行"SoftwareDistribution"任务，以开始清理 Windows 更新缓存文件夹"{0}"。
TempTaskCLIDescription                    = 在"任务计划程序"中进入"Sophia"文件夹，运行"Temp"任务以开始清理临时文件夹"{0}"（%TEMP%）。
EventViewerCustomViewName                 = 进程创建
EventViewerCustomViewDescription          = 进程创建和命令行审核事件。
ThirdPartyAVInstalled                     = 已安装第三方杀毒软件。
NoHomeWindowsEditionSupport               = Windows 家庭版不支持"{0}"功能。
GeoIdNotSupported                         = 函数"{0}"仅适用于俄罗斯。
EnableHardwareVT                          = UEFI中开启虚拟化。
PhotosNotInstalled                        = 照片应用程序未安装。
ThirdPartyArchiverInstalled               = 已安装第三方归档工具。
gpeditNotSupported                        = Windows 家庭版不支持本地组策略编辑器管理单元 (gpedit.msc)。
RestartWarning                            = 请务必重新启动您的电脑。
ErrorsLine                                = 行
ErrorsMessage                             = 错误、警告和通知
Disable                                   = 禁用
Enable                                    = 启用
Install                                   = 安装
Uninstall                                 = 卸载
RestartFunction                           = 请重新运行"{0}"函数。
NoResponse                                = 无法建立{0}。
Run                                       = 运行
Skipped                                   = 跳过函数"{0}"。
DonateToastTitle                          = 欢迎捐赠!❤
DotSourcedWarning                         = 請"點源"功能（開頭有點）:\n. .\\Import-TabCompletion.ps1
'@
