ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = O script suporta somente Windows 10 x64
UnsupportedOSBuild                        = O script suporta versões Windows 10 2004 / 20H1 e superior
UnsupportedRelease                        = Nova versão encontrada
ControlledFolderAccessDisabled            = Acesso controlado a pasta desativada
ScheduledTasks                            = Tarefas agendadas
OneDriveUninstalling                      = Desinstalar OneDrive...
OneDriveInstalling                        = OneDrive está instalando...
OneDriveDownloading                       = Baixando OneDrive... ~33 MB
WindowsFeaturesTitle                      = Recursos do Windows
OptionalFeaturesTitle                     = Recursos opcionais
EnableHardwareVT                          = Habilitar virtualização em UEFI
UserShellFolderNotEmpty                   = Alguns arquivos deixados na pasta "{0}". Movê-los manualmente para um novo local
RetrievingDrivesList                      = Recuperando lista de unidades...
DriveSelect                               = Selecione a unidade dentro da raiz da qual a pasta "{0}" será criada
UserFolderRequest                         = Gostaria de alterar a localização da pasta "{0}"?
UserFolderSelect                          = Selecione uma pasta para a pasta "{0}"
UserDefaultFolder                         = Gostaria de alterar a localização da pasta "{0}" para o valor padrão?
ReservedStorageIsInUse                    = Esta operação não é suportada quando o armazenamento reservada está em uso \ nAguarde para quaisquer operações de manutenção para ser concluído e, em seguida, tente novamente mais tarde
ShortcutPinning                           = O atalho "{0}" está sendo fixado no Iniciar
UninstallUWPForAll                        = Para todos os usuários
UWPAppsTitle                              = Apps UWP
WSLUpdateDownloading                      = Baixando o pacote de atualização do kernel Linux... ~14 MB
WSLUpdateInstalling                       = Instalando o pacote de atualização do kernel Linux...
HEVCDownloading                           = Baixando HEVC Vídeo Extensões de Dispositivo Fabricante... ~ 2,8 MB
GraphicsPerformanceTitle                  = Preferência de desempenho gráfico
GraphicsPerformanceRequest                = Gostaria de definir a configuração de performance gráfica de um app de sua escolha para "alta performance"?
TaskNotificationTitle                     = Notificação
CleanupTaskNotificationTitle              = Informação importante
CleanupTaskDescription                    = Limpando o Windows arquivos não utilizados e atualizações usando o aplicativo de limpeza aplicativo de limpeza embutido no disco
CleanupTaskNotificationEventTitle         = Executar tarefa para limpar arquivos e atualizações não utilizados do Windows?
CleanupTaskNotificationEvent              = Limpeza de janelas não vai demorar muito. Da próxima vez que esta notificação será exibida em 30 dias
CleanupTaskNotificationSnoozeInterval     = Selecione um lembrete de intervalo
CleanupNotificationTaskDescription        = Pop-up lembrete de notificação sobre a limpeza do Windows arquivos não utilizados e actualizações
SoftwareDistributionTaskNotificationEvent = O cache de atualização do Windows excluído com sucesso
TempTaskNotificationEvent                 = Os arquivos da pasta Temp limpos com sucesso
FolderTaskDescription                     = A limpeza da pasta "{0}"
ControlledFolderAccess                    = Acesso à pasta controlada
ProtectedFoldersRequest                   = Gostaria de permitir o acesso à pasta controlada e especificar a pasta que Microsoft Defender irá proteger de aplicativos maliciosos e ameaças?
ProtectedFoldersListRemoved               = Pastas removidas
AppControlledFolderRequest                = Gostaria de especificar um aplicativo que é permitido através do acesso pasta controlada?
AllowedControlledFolderAppsRemoved        = Aplicações permitidas removidas
DefenderExclusionFolderRequest            = Gostaria de especificar uma pasta a ser excluído da Microsoft Defender scans de malware?
DefenderExclusionFoldersListRemoved       = Pastas excluídas removidas
AddDefenderExclusionFileRequest           = Gostaria de especificar um arquivo a ser excluído do Microsoft Defender scans de malware?
DefenderExclusionFilesRemoved             = Arquivos excluídos removidos
EventViewerCustomViewName                 = Criação de processo
EventViewerCustomViewDescription          = Criação de processos e eventos de auditoria de linha de comando
RestartWarning                            = Certifique-se de reiniciar o PC
ErrorsLine                                = Linha
ErrorsFile                                = Arquivo
ErrorsMessage                             = Erros/Avisos
Add	                                  = Adicionar
AllFilesFilter                            = Todos os arquivos (*.*)|*.*
Change                                    = Mudar
DialogBoxOpening                          = Exibindo a caixa de diálogo...
Disable                                   = Desativar
Enable                                    = Habilitar
EXEFilesFilter                            = *.exe|*.exe| Todos os arquivos (*.*)|*.*
FolderSelect                              = Escolha uma pasta
FilesWontBeMoved                          = Os arquivos não serão transferidos
FourHours                                 = 4 horas
HalfHour                                  = 30 minutos
Install                                   = Instalar
Minute                                    = 1 minuto
NoData        	                          = Nada à exibir
NoInternetConnection                      = Sem conexão à Internet
NoResponse                                = Uma conexão não pôde ser estabelecida com https://store.rg-adguard.net
Open                                      = Abrir
Patient                                   = Por favor, espere...
Restore                                   = Restaurar
Run                                       = Executar
Select                                    = Selecione
SelectAll                                 = Selecionar tudo
Skip                                      = Pular
Skipped                                   = Ignorados
TelegramTitle                             = Entre no canal oficial do Telegram
Uninstall                                 = Desinstalar
'@
