ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Skrypt obsługuje tylko 64-bitowe systemy Windows
UnsupportedOSBuild                        = \nSkrypt obsługuje system Windows 10 Enterprise LTSC 2021
UpdateWarning                             = \nZainstalowano zbiorczą aktualizację systemu Windows 10: {0}. Obsługiwane aktualizacje zbiorcze: 2728 i nowsze. Uruchom aktualizację systemu Windows i spróbuj ponownie
UnsupportedLanguageMode                   = \nSesja PowerShell działa w trybie ograniczonego języka
LoggedInUserNotAdmin                      = \nZalogowany użytkownik nie posiada uprawnień administratora
UnsupportedPowerShell                     = \nPróbujesz uruchomić skrypt przy użyciu PowerShell {0}.{1}. Uruchom skrypt używając odpowiedniej wersji PowerShell
UnsupportedHost                           = \nSkrypt nie może być uruchamiany w {0}
Win10TweakerWarning                       = \nPrawdopodobnie twój system operacyjny został zainfekowany przez backdoora pochodzącego z Win 10 Tweaker
TweakerWarning                            = \nStabilność systemu Windows mogła zostać naruszona przez użycie {0}. Na wszelki wypadek przeinstaluj system Windows
bin                                       = \nW folderze bin nie ma żadnych plików. Proszę pobrać archiwum ponownie
RebootPending                             = \nKomputer oczekuje na ponowne uruchomienie
UnsupportedRelease                        = \nZnaleziono nową wersję
CustomizationWarning                      = \nCzy dostosowałeś funkcje w predefiniowanym pliku {0} przed uruchomieniem Sophia Script?
DefenderBroken                            = \nMicrosoft Defender jest uszkodzony lub usunięty z systemu operacyjnego
UpdateDefender                            = \nDefinicje programu Microsoft Defender są nieaktualne. Uruchom aktualizację systemu Windows i spróbuj ponownie.
ControlledFolderAccessDisabled            = Kontrolowany dostęp do folderów został wyłączony
ScheduledTasks                            = Zaplanowane zadania
WindowsFeaturesTitle                      = Funkcje Windows
OptionalFeaturesTitle                     = Funkcje opcjonalne
EnableHardwareVT                          = Włącz wirtualizację w UEFI
UserShellFolderNotEmpty                   = Niektóre pliki pozostały w folderze "{0}". Przenieś je ręcznie w nowe miejsce
RetrievingDrivesList                      = Pobieranie listy dysków...
DriveSelect                               = Wybierz dysk w katalogu głównym, w którym zostanie utworzony folder "{0}".
CurrentUserFolderLocation                 = Lokalizacja folderu "{0}": "{1}"
UserFolderRequest                         = Czy chcesz zmienić lokalizację folderu "{0}"?
UserFolderSelect                          = Wybierz folder dla folderu "{0}".
UserDefaultFolder                         = Czy chcesz zmienić lokalizację folderu "{0}" na wartość domyślną?
ReservedStorageIsInUse                    = Ta operacja nie jest obsługiwana, gdy używana jest zarezerwowana pamięć\nProszę ponownie uruchomić funkcję "{0}" po ponownym uruchomieniu komputera
ShortcutPinning                           = Skrót "{0}" jest przypinany do Start...
GraphicsPerformanceTitle                  = Preferencje dotyczące wydajności grafiki
GraphicsPerformanceRequest                = Czy chcesz ustawić wydajność grafiki wybranej aplikacji na "Wysoka wydajność"?
ScheduledTaskPresented                    = Funkcja "{0}" została już utworzona jako "{1}"
CleanupTaskNotificationTitle              = Oczyszczanie system Windows
CleanupTaskNotificationEvent              = Uruchomić zadanie w celu usunięcia nieużywanych plików i aktualizacji systemu Windows?
CleanupTaskDescription                    = Czyszczenie nieużywanych plików i aktualizacji systemu Windows za pomocą wbudowanej aplikacji do czyszczenia dysku
CleanupNotificationTaskDescription        = Powiadomienie przypominające o czyszczeniu nieużywanych plików i aktualizacji systemu Windows
SoftwareDistributionTaskNotificationEvent = Pomyślnie usunięto pamięć podręczną aktualizacji systemu Windows
TempTaskNotificationEvent                 = Folder plików tymczasowych został pomyślnie wyczyszczony
FolderTaskDescription                     = Czyszczenie folderu {0}
EventViewerCustomViewName                 = Tworzenie procesu
EventViewerCustomViewDescription          = Tworzenie procesu i zdarzeń audytu
RestartWarning                            = Pamiętaj o ponownym uruchomieniu komputera
ErrorsLine                                = Linia
ErrorsMessage                             = Błędy/Ostrzeżenia
DialogBoxOpening                          = Wyświetlanie okna dialogowego...
Disable                                   = Wyłączyć
EXEFilesFilter                            = *.exe|*.exe|Wszystkie pliki (*.*)|*.*
FolderSelect                              = Wybierz folder
FilesWontBeMoved                          = Pliki nie zostaną przeniesione
Install                                   = Zainstalluj
NoData                                    = Nic do wyświetlenia
NoInternetConnection                      = Brak połączenia z internetem
RestartFunction                           = Uruchom ponownie funkcję "{0}".
NoResponse                                = Nie można nawiązać połączenia z {0}
Restore                                   = Przywróć
Run                                       = Uruchom
Skipped                                   = Pominięto
GPOUpdate                                 = Aktualizowanie GPO...
TelegramGroupTitle                        = Dołącz do naszej oficjalnej grupy na Telegramie
TelegramChannelTitle                      = Dołącz do naszego oficjalnego kanału Telegram
DiscordChannelTitle                       = Dołącz do naszego oficjalnego kanału na Discordzie
Uninstall                                 = Odinstaluj
'@
