ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Skrypt obsługuje tylko 64-bitowe systemy Windows.
UnsupportedOSBuild                        = Skrypt obsługuje system Windows 10 Enterprise LTSC 2021.
UpdateWarning                             = Twoja wersja systemu Windows 10: {0}.{1}. Obsługiwane kompilacje: {2}+. Uruchom aktualizację systemu Windows i spróbuj ponownie.
UnsupportedLanguageMode                   = Sesja PowerShell działa w trybie ograniczonego języka.
LoggedInUserNotAdmin                      = Zalogowany użytkownik nie posiada uprawnień administratora.
UnsupportedPowerShell                     = Próbujesz uruchomić skrypt przy użyciu PowerShell {0}.{1}. Uruchom skrypt używając odpowiedniej wersji PowerShell.
PowerShellx86Warning                      = Próbujesz uruchomić skrypt przez PowerShell (x86). Uruchom skrypt w PowerShell (x64).
UnsupportedHost                           = Skrypt nie może być uruchamiany w {0}.
Win10TweakerWarning                       = Prawdopodobnie twój system operacyjny został zainfekowany przez backdoora pochodzącego z Win 10 Tweaker.
TweakerWarning                            = Stabilność systemu Windows mogła zostać naruszona przez użycie {0}. Na wszelki wypadek przeinstaluj system Windows.
Bin                                       = W folderze bin nie ma żadnych plików. Proszę pobrać archiwum ponownie.
RebootPending                             = Komputer oczekuje na ponowne uruchomienie.
UnsupportedRelease                        = Znaleziono nową wersję.
KeyboardArrows                            = Użyj klawiszy strzałek {0} i {1} na klawiaturze, aby wybrać odpowiedź
CustomizationWarning                      = Czy dostosowałeś funkcje w predefiniowanym pliku {0} przed uruchomieniem Sophia Script?
WindowsComponentBroken                    = {0} jest uszkodzony lub usunięty z systemu operacyjnego.
UpdateDefender                            = Definicje programu Microsoft Defender są nieaktualne. Uruchom aktualizację systemu Windows i spróbuj ponownie.
ControlledFolderAccessDisabled            = Kontrolowany dostęp do folderów został wyłączony.
InitialActionsCheckFailed                 = Funkcja "InitialActions" nie może zostać załadowana z pliku ustawień wstępnych {0}.
ScheduledTasks                            = Zaplanowane zadania
WindowsFeaturesTitle                      = Funkcje Windows
OptionalFeaturesTitle                     = Funkcje opcjonalne
EnableHardwareVT                          = Włącz wirtualizację w UEFI.
UserShellFolderNotEmpty                   = Niektóre pliki pozostały w folderze "{0}". Przenieś je ręcznie w nowe miejsce.
UserFolderLocationMove                    = Nie należy zmieniać lokalizacji folderu użytkownika na katalog główny dysku C.
RetrievingDrivesList                      = Pobieranie listy dysków...
DriveSelect                               = Wybierz dysk w katalogu głównym, w którym zostanie utworzony folder "{0}".
CurrentUserFolderLocation                 = Lokalizacja folderu "{0}": "{1}".
UserFolderRequest                         = Czy chcesz zmienić lokalizację folderu "{0}"?
UserDefaultFolder                         = Czy chcesz zmienić lokalizację folderu "{0}" na wartość domyślną?
ReservedStorageIsInUse                    = Ta operacja nie jest obsługiwana, gdy używana jest zarezerwowana pamięć\nProszę ponownie uruchomić funkcję "{0}" po ponownym uruchomieniu komputera.
ShortcutPinning                           = Skrót "{0}" jest przypinany do Start...
GraphicsPerformanceTitle                  = Czy chcesz ustawić wydajność grafiki wybranej aplikacji na "Wysoka wydajność"?
ActionCenter                              = Aby korzystać z funkcji "{0}" należy włączyć Action Center.
WindowsScriptHost                         = Dostęp do Hosta skryptów systemu Windows jest wyłączony na tym komputerze. Aby korzystać z funkcji "{0}" należy włączyć Windows Script Host.
ScheduledTaskPresented                    = Funkcja "{0}" została już utworzona jako "{1}".
CleanupTaskNotificationTitle              = Oczyszczanie system Windows
CleanupTaskNotificationEvent              = Uruchomić zadanie w celu usunięcia nieużywanych plików i aktualizacji systemu Windows?
CleanupTaskDescription                    = Czyszczenie nieużywanych plików i aktualizacji systemu Windows za pomocą wbudowanej aplikacji do czyszczenia dysku.
CleanupNotificationTaskDescription        = Powiadomienie przypominające o czyszczeniu nieużywanych plików i aktualizacji systemu Windows.
SoftwareDistributionTaskNotificationEvent = Pomyślnie usunięto pamięć podręczną aktualizacji systemu Windows.
TempTaskNotificationEvent                 = Folder plików tymczasowych został pomyślnie wyczyszczony.
FolderTaskDescription                     = Czyszczenie folderu {0}.
EventViewerCustomViewName                 = Tworzenie procesu
EventViewerCustomViewDescription          = Tworzenie procesu i zdarzeń audytu.
RestartWarning                            = Pamiętaj o ponownym uruchomieniu komputera.
ErrorsLine                                = Linia
ErrorsMessage                             = Błędy/Ostrzeżenia
DialogBoxOpening                          = Wyświetlanie okna dialogowego...
Disable                                   = Wyłączyć
Enable                                    = Włączać
UserChoiceWarning                         = Microsoft zablokował dostęp do zapisu klucza UserChoice dla rozszerzenia .pdf i protokołu http/https wraz z wydaniem KB5034765.
AllFilesFilter                            = Wszystkie pliki
FolderSelect                              = Wybierz folder
FilesWontBeMoved                          = Pliki nie zostaną przeniesione.
Install                                   = Zainstalluj
NoData                                    = Nic do wyświetlenia.
NoInternetConnection                      = Brak połączenia z internetem.
RestartFunction                           = Uruchom ponownie funkcję "{0}".
NoResponse                                = Nie można nawiązać połączenia z {0}.
Restore                                   = Przywróć
Run                                       = Uruchom
Skipped                                   = Pominięto.
GPOUpdate                                 = Aktualizowanie GPO...
TelegramGroupTitle                        = Dołącz do naszej oficjalnej grupy na Telegramie.
TelegramChannelTitle                      = Dołącz do naszego oficjalnego kanału Telegram.
DiscordChannelTitle                       = Dołącz do naszego oficjalnego kanału na Discordzie.
Uninstall                                 = Odinstaluj
'@
