ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                   = Este script solo soporta Windows 10 x64
UnsupportedOSBuild                     = Este script solo soporta Windows 10 2004/20H1 o superior
UnsupportedRelease                     = Nueva versión encontrada
ControlledFolderAccessDisabled         = Acceso a carpetas controlado desactivado
ScheduledTasks                         = Tareas programadas
OneDriveUninstalling                   = Desinstalando OneDrive...
OneDriveNotEmptyFolder                 = El directorio "{0}" no está vacío. Elimínelo manualmente
OneDriveFileSyncShell64dllBlocked      = "{0}" está bloqueado. Elimínelo manualmente
OneDriveInstalling                     = OneDrive se está instalando...
OneDriveDownloading                    = Descargando OneDrive... ~33 MB
ClearFolder                            = Elimine todos los archivos en la carpeta "{0}"?
FilesBlocked                           = Los siguientes archivos están siendo bloqueados por una aplicación de terceros. Elimínelos manualmente y continúe
TempNotEmpty                           = La carpeta "{0}" no está vacía. Límpiela manualmente
WindowsFeaturesWindowTitle             = Características de Windows
FODWindowTitle                         = Características opcionales (FODv2)
EnableHardwareVT                       = Activar virtualización en UEFI
UserShellFolderNotEmpty                = Quedan algunos archivos en  la carpeta "{0}". Muévalos manualmente a la nueva ubicación
RetrievingDrivesList                   = Recuperando lista de unidades de disco...
NewUserShellFolderLocation             = Nueva ubicación: "{0}"
DesktopDriveSelect                     = Selecciona la raíz del disco en la cual se creará la carpeta del Escritorio
DocumentsDriveSelect                   = Selecciona la raíz del disco en la cual se creará la carpeta de Documentos
DownloadsDriveSelect                   = Selecciona la raíz del disco en la cual se creará la carpeta de Descargas
MusicDriveSelect                       = Selecciona la raíz del disco en la cual se creará la carpeta de Música
PicturesDriveSelect                    = Selecciona la raíz del disco en la cual se creará la carpeta de Imágenes
VideosDriveSelect                      = Selecciona la raíz del disco en la cual se creará la carpeta de Vídeos
DesktopRequest                         = Quieres cambiar la ubicación de la carpeta del Escritorio?
DocumentsRequest                       = Quieres cambiar la ubicación de la carpeta de Documentos?
DownloadsRequest                       = Quieres cambiar la ubicación de la carpeta de Descargas?
MusicRequest                           = Quieres cambiar la ubicación de la carpeta de Música?
PicturesRequest                        = Quieres cambiar la ubicación de la carpeta de Imágenes?
VideosRequest                          = Quieres cambiar la ubicación de la carpeta de Vídeos?
DesktopFolderSelect                    = Selecciona una carpeta para la carpeta del Escritorio
DocumentsFolderSelect                  = Selecciona una carpeta para la carpeta de Documentos
DownloadsFolderSelect                  = Selecciona una carpeta para la carpeta de Descargas
MusicFolderSelect                      = Selecciona una carpeta para la carpeta de Música
PicturesFolderSelect                   = Selecciona una carpeta para la carpeta de Imágenes
VideosFolderSelect                     = Selecciona una carpeta para la carpeta de Vídeos
DesktopDefaultFolder                   = Quieres cambiar la ubicación de la carpeta del Escritorio por la de defecto?
DocumentsDefaultFolder                 = Quieres cambiar la ubicación de la carpeta de Documentos por la de defecto?
DownloadsDefaultFolder                 = Quieres cambiar la ubicación de la carpeta de Descargas por la de defecto?
MusicDefaultFolder                     = Quieres cambiar la ubicación de la carpeta de Música por la de defecto?
PicturesDefaultFolder                  = Quieres cambiar la ubicación de la carpeta de Imágenes por la de defecto?
VideosDefaultFolder                    = Quieres cambiar la ubicación de la carpeta de Vídeos por la de defecto?
ReservedStorageIsInUse                 = Esta operación no está disponible cuando el almacenamiento reservado está en uso\nPorfavor, espere a que se complete alguna operación de algún servicio e inténtelo de nuevo más tarde
syspinDownloading                      = Descargando syspin... ~20 KB
ShortcutPinning                        = El acceso directo "{0}" se está acoplando al inicio
UninstallUWPForAll                     = Desinstalar para todos los usuarios
UninstallUWPTitle                      = Paquetes UWP a desinstalar
WSLUpdateDownloading                   = Descargando el paquete de actualización del kernel de Linux... ~14 MB
WSLUpdateInstalling                    = Instalando el paquete de actualización del kernel de Linux...
GraphicsPerformanceTitle               = Preferencia de rendimiento de gráficos
GraphicsPerformanceRequest             = Quieres establecer el nivel de rendimiento de gráficos a "Alto rendimiento" en alguna aplicación?
CleanUpTaskToast                       = Limpiando archivos no usados y actualizaciones de Windows comienza en un minuto
CleanUpTaskDescription                 = Limpiando archivos de Windows no usados y actualizaciones usando la aplicación de limpieza de disco incorporada
FolderTaskDescription                  = Limpieza de la carpeta "{0}"
ControlledFolderAccess                 = Acceso controlado a carpetas
ProtectedFoldersRequest                = Quieres añadir control de acceso a carpeta y especificar que carpeta Microsoft Defender protegerá de aplicaciones maliciosas y amenazas?
ProtectedFoldersListRemoved            = Carpetas eliminadas
AppControlledFolderRequest             = Quieres especificar una aplicación para que sea permitida a través del acceso controlado de carpetas?
AllowedControlledFolderAppsRemoved     = Eliminar aplicaciones permitidas
DefenderTitle                          = Microsoft Defender
DefenderExclusionFolderRequest         = Quieres especificar una carpeta para ser excluida por Microsoft Defender?
DefenderExclusionFoldersListRemoved    = Quitadas carpetas excluidas
AddDefenderExclusionFileRequest        = Quieres especificar un archivo para ser excluido por Microsoft Defender?
DefenderExclusionFilesRemoved          = Quitados archivos excluidos
EventViewerCustomViewName              = Creación de procesos
EventViewerCustomViewDescription       = Creación de procesos y eventos de auditoria de línea de comandos
RestartWarning                         = Asegúrese de reiniciar su PC
ErrorsLine                             = Línea
ErrorsFile                             = Archivo
ErrorsMessage                          = Errores/Advertencias
Add                                    = Añadir
AllFilesFilter                         = Tutti i file (*.*)|*.*
Change                                 = Cambiar
Continue                               = Continuar
DialogBoxOpening                       = Mostrando caja de diálogo...
Disable                                = Desactivar
Enable                                 = Activar
EXEFilesFilter                         = *.exe|*.exe|Todos los Archivos (*.*)|*.*
FolderSelect                           = Seleccione una carpeta
FilesWontBeMoved                       = Los archivos no se moverán
NoData                                 = Nada que mostrar
NoInternetConnection                   = No hay conexión a Internet
Patient                                = Por favor espere...
Select                                 = Seleccionar
Skip                                   = Omitir
Skipped                                = Omitido
SymbolicSkipped                        = Se omitió la creación de un enlace simbólico
Uninstall                              = Desinstalar
Install                                = Instalar
'@
