ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                   = Скрипт поддерживает только Windows 10 x64
UnsupportedOSBuild                     = Скрипт поддерживает только Windows 10 версии 2004/20H1 и выше
UnsupportedRelease                     = Обнаружена новая версия
ControlledFolderAccessDisabled         = Контролируемый доступ к папкам выключен
ScheduledTasks                         = Запланированные задачи
OneDriveUninstalling                   = Удаление OneDrive...
OneDriveNotEmptyFolder                 = Папка "{0}" не пуста. Удалите ее вручную
OneDriveFileSyncShell64dllBlocked      = "{0}" заблокирован. Удалите его вручную
OneDriveInstalling                     = OneDrive устанавливается...
OneDriveDownloading                    = Скачивается OneDrive... ~33 МБ
ClearFolder                            = Удалить все файлы в папке "{0}"?
FilesBlocked                           = Следующие файлы блокируются сторонними приложениями. Удалите их вручную и продолжите
TempNotEmpty                           = Папка "{0}" не пуста. Очистите ее вручную
WindowsFeaturesWindowTitle             = Компоненты Windows
FODWindowTitle                         = Дополнительные компоненты (FODv2)
EnableHardwareVT                       = Включите виртуализацию в UEFI
UserShellFolderNotEmpty                = В папке "{0}" остались файлы. Переместите их вручную в новое расположение
RetrievingDrivesList                   = Получение списка дисков...
NewUserShellFolderLocation             = Новое расположение: "{0}"
DesktopDriveSelect                     = Выберите диск, в корне которого будет создана папка для "Рабочий стол"
DocumentsDriveSelect                   = Выберите диск, в корне которого будет создана папка для "Документы"
DownloadsDriveSelect                   = Выберите диск, в корне которого будет создана папка для "Загрузки"
MusicDriveSelect                       = Выберите диск, в корне которого будет создана папка для "Музыка"
PicturesDriveSelect                    = Выберите диск, в корне которого будет создана папка для "Изображения"
VideosDriveSelect                      = Выберите диск, в корне которого будет создана папка для "Видео"
DesktopRequest                         = Хотите изменить расположение папки "Рабочий стол"?
DocumentsRequest                       = Хотите изменить расположение папки "Документы"?
DownloadsRequest                       = Хотите изменить расположение папки "Загрузки"?
MusicRequest                           = Хотите изменить расположение папки "Музыка"?
PicturesRequest                        = Хотите изменить расположение папки "Изображения"?
VideosRequest                          = Хотите изменить расположение папки "Видео"?
DesktopFolderSelect                    = Выберите папку для "Рабочий стол"
DocumentsFolderSelect                  = Выберите папку для "Документы"
DownloadsFolderSelect                  = Выберите папку для "Загрузки"
MusicFolderSelect                      = Выберите папку для "Музыка"
PicturesFolderSelect                   = Выберите папку для "Изображения"
VideosFolderSelect                     = Выберите папку для "Видео"
DesktopDefaultFolder                   = Хотите изменить расположение папки "Рабочий стол" на значение по умолчанию?
DocumentsDefaultFolder                 = Хотите изменить расположение папки "Документы" на значение по умолчанию?
DownloadsDefaultFolder                 = Хотите изменить расположение папки "Загрузки" на значение по умолчанию?
MusicDefaultFolder                     = Хотите изменить расположение папки "Музыка" на значение по умолчанию?
PicturesDefaultFolder                  = Хотите изменить расположение папки "Изображения" на значение по умолчанию?
VideosDefaultFolder                    = Хотите изменить расположение папки "Видео" на значение по умолчанию?
ReservedStorageIsInUse                 = Операция не поддерживается, пока используется зарезервированное хранилище\nПожалуйста, дождитесь окончания всех обслуживающих операций и попробуйте заново
syspinDownloading                      = Скачивается syspin... ~20 КБ
ShortcutPinning                        = Ярлык "{0}" закрепляется на начальном экране
UninstallUWPForAll                     = Удалить для всех пользователей
UninstallUWPTitle                      = Удалить UWP-приложения
WSLUpdateDownloading                   = Скачивается пакет обновления ядра Linux... ~14 МБ
WSLUpdateInstalling                    = Установка пакета обновления ядра Linux...
GraphicsPerformanceTitle               = Настройка производительности графики
GraphicsPerformanceRequest             = Установить для любого приложения по вашему выбору настройки производительности графики на "Высокая производительность"?
CleanUpTaskToast                       = Очистка неиспользуемых файлов и обновлений Windows начнется через минуту
CleanUpTaskDescription                 = Очистка неиспользуемых файлов и обновлений Windows, используя встроенную программу Очистка диска
FolderTaskDescription                  = Очистка папки "{0}"
ControlledFolderAccess                 = Контролируемый доступ к папкам
ProtectedFoldersRequest                = Хотите включить контролируемый доступ к папкам и указать папку, которую Microsoft Defender будет защищать от вредоносных приложений и угроз?
ProtectedFoldersListRemoved            = Удаленные папки
AppControlledFolderRequest             = Указать приложение, которому разрешена работа через контролируемый доступ к папкам
AllowedControlledFolderAppsRemoved     = Удаленные разрешенные приложения
DefenderTitle                          = Microsoft Defender
DefenderExclusionFolderRequest         = Указать папку, чтобы исключить ее из списка сканирования Microsoft Defender?
DefenderExclusionFoldersListRemoved    = Исключенные папки удалены
AddDefenderExclusionFileRequest        = Указать файл, чтобы исключить его из списка сканирования Microsoft Defender?
DefenderExclusionFilesRemoved          = Исключенные файлы удалены
EventViewerCustomViewName              = Создание процесса
EventViewerCustomViewDescription       = События содания нового процесса и аудит командной строки
RestartWarning                         = Обязательно перезагрузите ваш ПК
ErrorsLine                             = Строка
ErrorsFile                             = Файл
ErrorsMessage                          = Ошибки/предупреждения
Add                                    = Добавить
AllFilesFilter                         = Все файлы (*.*)|*.*
Change                                 = Изменить
Continue                               = Продолжить
DialogBoxOpening                       = Диалоговое окно открывается...
Disable                                = Отключить
Enable                                 = Включить
EXEFilesFilter                         = *.exe|*.exe|Все файлы (*.*)|*.*
FolderSelect                           = Выберите папку
FilesWontBeMoved                       = Файлы не будут перенесены
NoData                                 = Отсутствуют данные
NoInternetConnection                   = Отсутствует интернет-соединение
Patient                                = Пожалуйста, подождите...
Select                                 = Выбрать
Skip                                   = Пропустить
Skipped                                = Пропущено
SymbolicSkipped                        = Пропущено создание символической ссылки
Uninstall                              = Удалить
Install                                = Установить
'@
