ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Bu betik sadece Windows 10 x64 destekliyor
UnsupportedOSBuild                        = Bu betik sadece Windows 10 1809 Enterprise LTSC
UnsupportedLanguageMode                   = Sınırlı bir dil modunda çalışan PowerShell oturumu
LoggedInUserNotAdmin                      = Oturum açan kullanıcının yönetici hakları yok
UnsupportedPowerShell                     = Komut dosyasını PowerShell {0}.{1} aracılığıyla çalıştırmaya çalışıyorsunuz. Komut dosyasını uygun PowerShell sürümünde çalıştırın
UnsupportedISE                            = Komut dosyası, Windows PowerShell ISE üzerinden çalıştırmayı desteklemiyor
Win10TweakerWarning                       = Muhtemelen işletim sisteminize Win 10 Tweaker arka kapısı yoluyla bulaştı
UnsupportedRelease                        = Yeni sürüm bulundu
CustomizationWarning                      = \nSophia Script'i çalıştırmadan önce Sophia.ps1 ön ayar dosyasındaki her işlevi özelleştirdiniz mi?
ControlledFolderAccessDisabled            = Kontrollü klasör erişimi devre dışı bırakıldı
ScheduledTasks                            = Zamanlanan görevler
WindowsFeaturesTitle                      = Windows özellikleri
OptionalFeaturesTitle                     = İsteğe bağlı özellikler
EnableHardwareVT                          = UEFI'dan sanallaştırmayı aktifleştirin
UserShellFolderNotEmpty                   = "{0}" klasöründe bazı dosyalar kaldı. \nKendiniz yeni konuma taşıyın
RetrievingDrivesList                      = Sürücü listesi alınıyor...
DriveSelect                               = "{0}" klasörünün oluşturulacağı kök içindeki sürücüyü seçin
CurrentUserFolderLocation                 = Geçerli "{0}" klasör konumu: "{1}"
UserFolderRequest                         = "{0}" klasörünün yerini değiştirmek ister misiniz?
UserFolderSelect                          = "{0}" klasörü için bir klasör seçin
UserDefaultFolder                         = "{0}" klasörünün konumunu varsayılan değerle değiştirmek ister misiniz?
GraphicsPerformanceTitle                  = Grafik performans tercihi
GraphicsPerformanceRequest                = Seçtiğiniz bir uygulamanın grafik performansı ayarını "Yüksek performans" olarak belirlemek ister misiniz?
TaskNotificationTitle                     = Bildirim
CleanupTaskNotificationTitle              = Önemli Bilgi
CleanupTaskDescription                    = Kullanılmayan Windows dosyaları ve güncellemeleri yerleşik Disk Temizleme uygulaması ile temizleniyor
CleanupTaskNotificationEventTitle         = Windows kullanılmayan dosyaları ve güncellemeleri temizlemek için görev çalıştırılsın mı?
CleanupTaskNotificationEvent              = Windows temizliği uzun sürmeyecek. Bir dahaki sefer bildirim 30 gün içinde görünecek
CleanupTaskNotificationSnoozeInterval     = Hatırlatma Aralığı Seçin
CleanupNotificationTaskDescription        = Windows kullanılmayan dosyaları ve güncellemeleri temizleme hakkında açılır bildirim hatırlatıcısı
SoftwareDistributionTaskNotificationEvent = Windows güncelleme önbelleği başarıyla silindi
TempTaskNotificationEvent                 = Geçici dosyalar klasörü başarıyla temizlendi
FolderTaskDescription                     = "{0}" klasörü temizleniyor
EventViewerCustomViewName                 = Süreç Oluşturma
EventViewerCustomViewDescription          = Süreç oluşturma ve komut satırı denetleme olayları
RestartWarning                            = Bilgisayarınızı yeniden başlattığınızdan emin olun
ErrorsLine                                = Satır
ErrorsFile                                = Dosya
ErrorsMessage                             = Hatalar/Uyarılar
Add                                       = Ekle
AllFilesFilter                            = Tüm Dosyalar (*.*)|*.*
Browse                                    = Gözat
Change                                    = Değiştir
DialogBoxOpening                          = İletişim kutusu görüntüleniyor...
Disable                                   = Devre dışı bırak
Enable                                    = Aktif et
EXEFilesFilter                            = *.exe|*.exe|Tüm Dosyalar (*.*)|*.*
FolderSelect                              = Klasör seç
FilesWontBeMoved                          = Dosyalar taşınmayacak
FourHours                                 = 4 Saat
HalfHour                                  = 30 Dakika
Install                                   = Yükle
Minute                                    = 1 Dakika
NoData                                    = Görüntülenecek bir şey yok
NoInternetConnection                      = İnternet bağlantısı yok
RestartFunction                           = Lütfen "{0}" işlevini yeniden çalıştırın
NoResponse                                = {0} ile bağlantı kurulamadı
No                                        = Hayır
Yes                                       = Evet
Open                                      = Açık
Patient                                   = Lütfen bekleyin...
Restore                                   = Onar
Run                                       = Başlat
SelectAll                                 = Hepsini seç
Skip                                      = Atla
Skipped                                   = Atlandı
FileExplorerRestartPrompt                 = \nBazen değişikliklerin geçerli olması için Dosya Gezgini işleminin yeniden başlatılması gerekir
TelegramGroupTitle                        = Resmi Telegram grubumuza katılın
TelegramChannelTitle                      = Resmi Telegram kanalımıza katılın
Uninstall                                 = Kaldır
'@