ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Скрипт поддерживает только Windows 10 x64
UnsupportedOSBuild                        = Скрипт поддерживает только Windows 10 версии 2004/20H1 и выше
UnsupportedRelease                        = Обнаружена новая версия
ControlledFolderAccessDisabled            = Контролируемый доступ к папкам выключен
ScheduledTasks                            = Запланированные задания
OneDriveUninstalling                      = Удаление OneDrive...
OneDriveInstalling                        = OneDrive устанавливается...
OneDriveDownloading                       = Скачивается OneDrive... ~33 МБ
WindowsFeaturesTitle                      = Компоненты Windows
OptionalFeaturesTitle                     = Дополнительные компоненты
EnableHardwareVT                          = Включите виртуализацию в UEFI
UserShellFolderNotEmpty                   = В папке "{0}" остались файлы. Переместите их вручную в новое расположение
RetrievingDrivesList                      = Получение списка дисков...
DriveSelect                               = Выберите диск, в корне которого будет создана папка "{0}"
UserFolderRequest                         = Хотите изменить расположение папки "{0}"?
UserFolderSelect                          = Выберите папку для "{0}"
UserDefaultFolder                         = Хотите изменить расположение папки "{0}" на значение по умолчанию?
ReservedStorageIsInUse                    = Операция не поддерживается, пока используется зарезервированное хранилище\nПожалуйста, дождитесь окончания всех обслуживающих операций и попробуйте заново
ShortcutPinning                           = Ярлык "{0}" закрепляется на начальном экране
UninstallUWPForAll                        = Для всех пользователей
UWPAppsTitle                              = UWP-приложения
WSLUpdateDownloading                      = Скачивается пакет обновления ядра Linux... ~14 МБ
WSLUpdateInstalling                       = Установка пакета обновления ядра Linux...
HEVCDownloading                           = Скачивается расширения для видео HEVC от производителя устройства... ~2,8 МБ
GraphicsPerformanceTitle                  = Настройка производительности графики
GraphicsPerformanceRequest                = Установить для любого приложения по вашему выбору настройки производительности графики на "Высокая производительность"?
TaskNotificationTitle                     = Уведомление
CleanupTaskNotificationTitle              = Важная информация
CleanupTaskDescription                    = Очистка неиспользуемых файлов и обновлений Windows, используя встроенную программу Очистка диска
CleanupTaskNotificationEventTitle         = Запустить задачу по очистке неиспользуемых файлов и обновлений Windows?
CleanupTaskNotificationEvent              = Очистка Windows не займет много времени. Следующий раз это уведомление появится через 30 дней
CleanupTaskNotificationSnoozeInterval     = Выберите интервал повтора уведомления
CleanupNotificationTaskDescription        = Всплывающее уведомление с напоминанием об очистке неиспользуемых файлов и обновлений Windows
SoftwareDistributionTaskNotificationEvent = Кэш обновлений Windows успешно удален
TempTaskNotificationEvent                 = Папка временных файлов успешно очищена
FolderTaskDescription                     = Очистка папки {0}
ControlledFolderAccess                    = Контролируемый доступ к папкам
ProtectedFoldersRequest                   = Хотите включить контролируемый доступ к папкам и указать папку, которую Microsoft Defender будет защищать от вредоносных приложений и угроз?
ProtectedFoldersListRemoved               = Удаленные папки
AppControlledFolderRequest                = Указать приложение, которому разрешена работа через контролируемый доступ к папкам
AllowedControlledFolderAppsRemoved        = Удаленные разрешенные приложения
DefenderExclusionFolderRequest            = Указать папку, чтобы исключить ее из списка сканирования Microsoft Defender?
DefenderExclusionFoldersListRemoved       = Исключенные папки удалены
AddDefenderExclusionFileRequest           = Указать файл, чтобы исключить его из списка сканирования Microsoft Defender?
DefenderExclusionFilesRemoved             = Исключенные файлы удалены
EventViewerCustomViewName                 = Создание процесса
EventViewerCustomViewDescription          = События содания нового процесса и аудит командной строки
RestartWarning                            = Обязательно перезагрузите ваш ПК
ErrorsLine                                = Строка
ErrorsFile                                = Файл
ErrorsMessage                             = Ошибки/предупреждения
Add                                       = Добавить
AllFilesFilter                            = Все файлы (*.*)|*.*
Change                                    = Изменить
DialogBoxOpening                          = Диалоговое окно открывается...
Disable                                   = Отключить
Enable                                    = Включить
EXEFilesFilter                            = *.exe|*.exe|Все файлы (*.*)|*.*
FolderSelect                              = Выберите папку
FilesWontBeMoved                          = Файлы не будут перенесены
FourHours                                 = 4 часа
HalfHour                                  = 30 минут
Install                                   = Установить
Minute                                    = 1 минута
NoData                                    = Отсутствуют данные
NoInternetConnection                      = Отсутствует интернет-соединение
NoResponse                                = Невозможно установить соединение с https://store.rg-adguard.net
Open                                      = Открыть
Patient                                   = Пожалуйста, подождите...
Restore                                   = Восстановить
Run                                       = Запустить
Select                                    = Выбрать
SelectAll                                 = Выбрать всё
Skip                                      = Пропустить
Skipped                                   = Пропущено
TelegramTitle                             = Присоединяйтесь к нашей официальной группе в Telegram
Uninstall                                 = Удалить
'@
