ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = O script suporta somente Windows 10 x64
UnsupportedOSBuild                        = O script suporta versões Windows 10 21H2/22H2+
UpdateWarning                             = Atualização cumulativa do Windows 10 instalado: {0}. Actualização acumulada suportada: 2364 e superior. Execute o Windows Update e tente novamente
UnsupportedLanguageMode                   = A sessão PowerShell em funcionamento em um modo de linguagem limitada
LoggedInUserNotAdmin                      = O usuário logado não tem direitos de administrador
UnsupportedPowerShell                     = Você está tentando executar o script via PowerShell {0}.{1}. Execute o script na versão apropriada do PowerShell
UnsupportedISE                            = O guião não suporta a execução através do Windows PowerShell ISE
Win10TweakerWarning                       = Probabilmente il tuo sistema operativo è stato infettato tramite la backdoor Win 10 Tweaker
SycnexWarning                             = A estabilidade do sistema operacional Windows pode ter sido comprometida pela utilização do script Windows10Debloater PowerShell da Sycnex. Preventivamente, reinstale todo o Windows
Fs00Warning                               = A estabilidade do sistema operacional Windows pode ter sido comprometida pela utilização do "Windows 10 Bloat Remover and Tweaker". Preventivamente, reinstale todo o Windows
bin                                       = Não existem ficheiros na pasta bin. Por favor, volte a descarregar o arquivo
RebootPending                             = O PC está esperando para ser reiniciado
UnsupportedRelease                        = Nova versão encontrada
CustomizationWarning                      = \nVocê personalizou todas as funções no arquivo de predefinição {0} antes de executar o Sophia Script?
DefenderBroken                            = Microsoft Defender quebrado ou removido do sistema operativo
UpdateDefender                            = As definições do Microsoft Defender estão desatualizadas. Execute o Windows Update e tente novamente
ControlledFolderAccessDisabled            = Acesso controlado a pasta desativada
ScheduledTasks                            = Tarefas agendadas
OneDriveUninstalling                      = Desinstalar OneDrive...
OneDriveInstalling                        = Instalar o OneDrive...
OneDriveDownloading                       = Baixando OneDrive... ~33 MB
OneDriveWarning                           = A função "{0}" será aplicada somente se a predefinição for configurada para remover o OneDrive (ou a aplicação já foi removida), caso contrário a funcionalidade de backup para as pastas "Desktop" e "Pictures" no OneDrive quebra
WindowsFeaturesTitle                      = Recursos do Windows
OptionalFeaturesTitle                     = Recursos opcionais
EnableHardwareVT                          = Habilitar virtualização em UEFI
UserShellFolderNotEmpty                   = Alguns arquivos deixados na pasta "{0}". Movê-los manualmente para um novo local
RetrievingDrivesList                      = Recuperando lista de unidades...
DriveSelect                               = Selecione a unidade dentro da raiz da qual a pasta "{0}" será criada
CurrentUserFolderLocation                 = A localização actual da pasta "{0}": "{1}"
UserFolderRequest                         = Gostaria de alterar a localização da pasta "{0}"?
UserFolderSelect                          = Selecione uma pasta para a pasta "{0}"
UserDefaultFolder                         = Gostaria de alterar a localização da pasta "{0}" para o valor padrão?
ReservedStorageIsInUse                    = Esta operação não é suportada quando o armazenamento reservada está em uso\nFavor executar novamente a função "{0}" após o reinício do PC
ShortcutPinning                           = O atalho "{0}" está sendo fixado no Iniciar...
UninstallUWPForAll                        = Para todos os usuários...
UWPAppsTitle                              = Apps UWP
HEVCDownloading                           = Baixando HEVC Vídeo Extensões de Dispositivo Fabricante... ~ 2,8 MB
GraphicsPerformanceTitle                  = Preferência de desempenho gráfico
GraphicsPerformanceRequest                = Gostaria de definir a configuração de performance gráfica de um app de sua escolha para "alta performance"?
ScheduledTaskPresented                    = A função "{0}" já foi criada como "{1}"
CleanupTaskNotificationTitle              = Limpeza do Windows
CleanupTaskNotificationEvent              = Executar tarefa para limpar arquivos e atualizações não utilizados do Windows?
CleanupTaskDescription                    = Limpando o Windows arquivos não utilizados e atualizações usando o aplicativo de limpeza aplicativo de limpeza embutido no disco
CleanupNotificationTaskDescription        = Pop-up lembrete de notificação sobre a limpeza do Windows arquivos não utilizados e actualizações
SoftwareDistributionTaskNotificationEvent = O cache de atualização do Windows excluído com sucesso
TempTaskNotificationEvent                 = Os arquivos da pasta Temp limpos com sucesso
FolderTaskDescription                     = A limpeza da pasta "{0}"
EventViewerCustomViewName                 = Criação de processo
EventViewerCustomViewDescription          = Criação de processos e eventos de auditoria de linha de comando
RestartWarning                            = Certifique-se de reiniciar o PC
ErrorsLine                                = Linha
ErrorsFile                                = Arquivo
ErrorsMessage                             = Erros/Avisos
Add                                       = Adicionar
AllFilesFilter                            = Todos os arquivos (*.*)|*.*
Browse                                    = Procurar
DialogBoxOpening                          = Exibindo a caixa de diálogo...
Disable                                   = Desativar
Enable                                    = Habilitar
EXEFilesFilter                            = *.exe|*.exe| Todos os arquivos (*.*)|*.*
FolderSelect                              = Escolha uma pasta
FilesWontBeMoved                          = Os arquivos não serão transferidos
Install                                   = Instalar
NoData                                    = Nada à exibir
NoInternetConnection                      = Sem conexão à Internet
RestartFunction                           = Favor reiniciar a função "{0}"
NoResponse                                = Uma conexão não pôde ser estabelecida com {0}
No                                        = Não
Yes                                       = Sim
Open                                      = Abrir
Patient                                   = Por favor, espere...
Restore                                   = Restaurar
Run                                       = Executar
SelectAll                                 = Selecionar tudo
Skipped                                   = Ignorados
GPOUpdate                                 = Actualização do GPO...
TelegramGroupTitle                        = Entre no grupo oficial do Telegram
TelegramChannelTitle                      = Entre no canal oficial do Telegram
DiscordChannelTitle                       = Entre no canal oficial do Discord
Uninstall                                 = Desinstalar
'@
