ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = O guião suporta apenas Windows de 64 bits.
UnsupportedOSBuild                        = O script é compatível apenas com o Windows 10 22H2. Você está usando o {0} {1}. Atualize seu Windows e tente novamente.
UnsupportedWindowsTerminal                = A versão do Windows Terminal é inferior a 1.23. Atualize-a na Microsoft Store e tente novamente.
UpdateWarning                             = Windows 10 {0}.{1} rendszert használ. A támogatott verzió Windows 10 {0}.{2} vagy újabb. Futtassa a Windows Update programot, majd próbálja meg újra.
UnsupportedLanguageMode                   = A sessão PowerShell em funcionamento em um modo de linguagem limitada.
LoggedInUserNotAdmin                      = O usuário conectado {0} não possui direitos de administrador. O script foi executado em nome de {1}. Faça login em uma conta com direitos de administrador e execute o script novamente.
UnsupportedPowerShell                     = Você está tentando executar o script via PowerShell {0}.{1}. Execute o script no PowerShell {2}.
CodeCompilationFailedWarning              = Falha na compilação do código.
UnsupportedHost                           = O guião não suporta a execução através do {0}.
Win10TweakerWarning                       = Probabilmente il tuo sistema operativo è stato infettato tramite la backdoor Win 10 Tweaker.
TweakerWarning                            = A estabilidade do sistema operacional Windows pode ter sido comprometida pela utilização do {0}. Reinstale o Windows usando apenas uma imagem ISO genuína.
HostsWarning                              = Entradas de terceiros encontradas no arquivo %SystemRoot%\\System32\\drivers\\etc\\hosts. Elas podem bloquear a conexão com recursos usados no script. Deseja continuar?
RebootPending                             = Seu computador está aguardando para ser reiniciado.
BitLockerInOperation                      = A criptografia do BitLocker está em andamento. Conclua a configuração da unidade do BitLocker e tente novamente.
BitLockerAutomaticEncryption              = A unidade C está criptografada, embora o BitLocker esteja desativado. Deseja descriptografar sua unidade?
UnsupportedRelease                        = Encontrada uma versão mais recente do Sophia Script: {0}. Faça o download da versão mais recente.
KeyboardArrows                            = Use as teclas de seta {0} e {1} do teclado para selecionar sua resposta
CustomizationWarning                      = Você personalizou todas as funções no arquivo de predefinição {0} antes de executar o Sophia Script?
WindowsComponentBroken                    = {0} quebrado ou removido do sistema operativo. Reinstale o Windows usando apenas uma imagem ISO genuína.
ControlledFolderAccessEnabledWarning      = Você tem o acesso controlado a pastas ativado. Desative-o e execute o script novamente.
NoScheduledTasks                          = Não há tarefas agendadas para desativar.
ScheduledTasks                            = Tarefas agendadas
TaskbarSmallIcons                         = Você usa botões pequenos na barra de tarefas.
SearchHighlightsDisabled                  = Os destaques da pesquisa já estão ocultos no Início.
CustomStartMenu                           = Um Menu Iniciar de terceiros está instalado.
OneDriveNotInstalled                      = O OneDrive já está desinstalado.
OneDriveAccountWarning                    = Antes de desinstalar o OneDrive, saia da sua conta da Microsoft no OneDrive.
OneDriveInstalled                         = O OneDrive já está instalado.
UninstallNotification                     = O {0} está sendo desinstalado...
InstallNotification                       = O {0} está sendo instalado...
NoWindowsFeatures                         = Não há recursos do Windows para desativar.
WindowsFeaturesTitle                      = Recursos do Windows
NoOptionalFeatures                        = Não há recursos opcionais para desativar.
NoSupportedNetworkAdapters                = Nenhum adaptador de rede que suporte a função "Permitir que o computador desligue este dispositivo para economizar energia".
OptionalFeaturesTitle                     = Recursos opcionais
EnableHardwareVT                          = Habilitar virtualização em UEFI.
UserShellFolderNotEmpty                   = Alguns arquivos deixados na pasta "{0}". Movê-los manualmente para um novo local.
UserFolderLocationMove                    = Você não deve alterar o local da pasta do usuário para a raiz da unidade C.
DriveSelect                               = Selecione a unidade dentro da raiz da qual a pasta "{0}" será criada.
CurrentUserFolderLocation                 = A localização actual da pasta "{0}": "{1}".
FilesWontBeMoved                          = Os arquivos não serão movidos.
FolderSelect                              = Selecione uma pasta
UserFolderRequest                         = Gostaria de alterar a localização da pasta "{0}"?
UserDefaultFolder                         = Gostaria de alterar a localização da pasta "{0}" para o valor padrão?
ReservedStorageIsInUse                    = O armazenamento reservado está sendo usado.
ProgramPathNotExists                      = O caminho "{0}" não existe.
ProgIdNotExists                           = O ProgId "{0}" não existe.
AllFilesFilter                            = Todos os arquivos
JSONNotValid                              = O arquivo JSON "{0}" não é válido.
PackageNotInstalled                       = {0} não está instalado.
PackageIsInstalled                        = A versão mais recente do {0} já está instalada.
UninstallUWPForAll                        = Para todos os usuários...
NoUWPApps                                 = Não há aplicativos UWP para desinstalar.
UWPAppsTitle                              = Apps UWP
ScheduledTaskCreatedByAnotherUser         = A tarefa agendada "{0}" já foi criada pelo usuário "{1}".
CleanupTaskNotificationTitle              = Limpeza do Windows
CleanupTaskNotificationEvent              = Executar tarefa para limpar arquivos e atualizações não utilizados do Windows?
CleanupTaskDescription                    = Limpando o Windows arquivos não utilizados e atualizações usando o aplicativo de limpeza aplicativo de limpeza embutido no disco. A tarefa programada só pode ser executada se o usuário "{0}" estiver conectado ao sistema.
CleanupNotificationTaskDescription        = Pop-up lembrete de notificação sobre a limpeza do Windows arquivos não utilizados e actualizações. A tarefa programada só pode ser executada se o usuário "{0}" estiver conectado ao sistema.
SoftwareDistributionTaskNotificationEvent = O cache de atualização do Windows excluído com sucesso.
TempTaskNotificationEvent                 = Os arquivos da pasta Temp limpos com sucesso.
FolderTaskDescription                     = A limpeza da pasta "{0}". A tarefa programada só pode ser executada se o usuário "{0}" estiver conectado ao sistema.
EventViewerCustomViewName                 = Criação de processo
EventViewerCustomViewDescription          = Criação de processos e eventos de auditoria de linha de comando.
ThirdPartyAVInstalled                     = Um antivírus de terceiros está instalado.
NoHomeWindowsEditionSupport               = A edição Windows Home não suporta a função "{0}".
GeoIdNotSupported                         = A função "{0}" é aplicável apenas à Rússia.
PhotosNotInstalled                        = O aplicativo Fotos não está instalado.
HEVCInstalled                             = O Extensões de vídeo HEVC do fabricante do dispositivo já está instalado.
HEVCInstallNotification                   = O Extensões de vídeo HEVC do fabricante do dispositivo está sendo instalado...
ThirdPartyArchiverInstalled               = Um arquivador de terceiros está instalado.
gpeditNotSupported                        = A edição Windows Home não suporta o snap-in Editor de Política de Grupo Local (gpedit.msc).
RestartWarning                            = Certifique-se de reiniciar o PC.
ErrorsLine                                = Linha
ErrorsMessage                             = Erros, avisos e notificações
Disable                                   = Desativar
Enable                                    = Habilitar
Install                                   = Instalar
Uninstall                                 = Desinstalar
RestartFunction                           = Favor reiniciar a função "{0}".
NoResponse                                = Uma conexão não pôde ser estabelecida com {0}.
Run                                       = Executar
Skipped                                   = A função "{0}" foi ignorada.
ThankfulToastTitle                        = Obrigado por usar o Sophia Script ❤️
DonateToastTitle                          = Você pode fazer sua doação abaixo 🕊
DotSourcedWarning                         = Faça o "dot-source" da função (com um ponto no início):\n. .\\Import-TabCompletion.ps1
'@
