ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = El script sólo es compatible con Windows 10 x64
UnsupportedOSBuild                        = El script es compatible con versión Windows 10 1809 Enterprise LTSC
UnsupportedLanguageMode                   = Sesión de PowerShell ejecutada en modo de lenguaje limitado
LoggedInUserNotAdmin                      = El usuario que inició sesión no tiene derechos de administrador
UnsupportedPowerShell                     = Estás intentando ejecutar el script a través de PowerShell {0}.{1}. Ejecute el script en la versión apropiada de PowerShell
UnsupportedISE                            = El script no es compatible con la ejecución a través de Windows PowerShell ISE
Win10TweakerWarning                       = Probablemente su sistema operativo fue infectado a través del backdoor Win 10 Tweaker
UnsupportedRelease                        = Una nueva versión encontrada
CustomizationWarning                      = \n¿Ha personalizado todas las funciones del archivo predeterminado Sophia.ps1 antes de ejecutar Sophia Script?
ControlledFolderAccessDisabled            = Acceso a la carpeta controlada deshabilitado
ScheduledTasks                            = Tareas programadas
WindowsFeaturesTitle                      = Características de Windows
OptionalFeaturesTitle                     = Características opcionales
EnableHardwareVT                          = Habilitar la virtualización en UEFI
UserShellFolderNotEmpty                   = Algunos archivos quedan en la carpeta "{0}". Moverlos manualmente a una nueva ubicación
RetrievingDrivesList                      = Recuperando lista de unidades...
DriveSelect                               = Seleccione la unidad dentro de la raíz de la cual se creó la carpeta "{0}"
CurrentUserFolderLocation                 = La ubicación actual de la carpeta "{0}": "{1}"
UserFolderRequest                         = ¿Le gustaría cambiar la ubicación de la "{0}" carpeta?
UserFolderSelect                          = Seleccione una carpeta para la carpeta "{0}"
UserDefaultFolder                         = ¿Le gustaría cambiar la ubicación de la carpeta "{0}" para el valor por defecto?
GraphicsPerformanceTitle                  = Preferencia de rendimiento gráfico
GraphicsPerformanceRequest                = ¿Le gustaría establecer la configuración de rendimiento gráfico de una aplicación de su elección a "alto rendimiento"?
TaskNotificationTitle                     = Notificación
CleanupTaskNotificationTitle              = Información importante
CleanupTaskDescription                    = La limpieza de Windows los archivos no utilizados y actualizaciones utilizando una función de aplicación de limpieza de discos
CleanupTaskNotificationEventTitle         = ¿Ejecutar la tarea de limpiar los archivos no utilizados y actualizaciones de Windows?
CleanupTaskNotificationEvent              = Ventanas de limpieza no tomará mucho tiempo. La próxima vez que esta notificación aparecerá en 30 días
CleanupTaskNotificationSnoozeInterval     = Seleccionar un recordatorio del intervalo
CleanupNotificationTaskDescription        = Pop-up recordatorio de notificaciones sobre la limpieza de archivos no utilizados de Windows y actualizaciones
SoftwareDistributionTaskNotificationEvent = La caché de actualización de Windows eliminado correctamente
TempTaskNotificationEvent                 = Los archivos de la carpeta Temp limpiados con éxito
FolderTaskDescription                     = La limpieza de la carpeta "{0}"
EventViewerCustomViewName                 = Creación de proceso
EventViewerCustomViewDescription          = Eventos de auditoría de línea de comandos y creación de procesos
RestartWarning                            = Asegúrese de reiniciar su PC
ErrorsLine                                = Línea
ErrorsFile                                = Archivo
ErrorsMessage                             = Errores/Advertencias
Add                                       = Agregar
AllFilesFilter                            = Todos los archivos (*.*)|*.*
Browse                                    = Examinar
Change                                    = Cambio
DialogBoxOpening                          = Viendo el cuadro de diálogo...
Disable                                   = Desactivar
Enable                                    = Habilitar
EXEFilesFilter                            = *.exe|*.exe|Todos los Archivos (*.*)|*.*
FolderSelect                              = Seleccione una carpeta
FilesWontBeMoved                          = Los archivos no se transferirán
FourHours                                 = 4 horas
HalfHour                                  = 30 minutos
Install                                   = Instalar
Minute                                    = 1 minuto
NoData                                    = Nada que mostrar
NoInternetConnection                      = No hay conexión a Internet
RestartFunction                           = Por favor, reinicie la función "{0}"
NoResponse                                = No se pudo establecer una conexión con {0}
No                                        = No
Yes                                       = Sí
Open                                      = Abierta
Patient                                   = Por favor espere...
Restore                                   = Restaurar
Run                                       = Iniciar
SelectAll                                 = Seleccionar todo
Skip                                      = Omitir
Skipped                                   = Omitido
FileExplorerRestartPrompt                 = \nA veces, para que los cambios surtan efecto, hay que reiniciar el proceso del Explorador de archivos
TelegramGroupTitle                        = Únete a nuestro grupo oficial de Telegram
TelegramChannelTitle                      = Únete a nuestro canal oficial de Telegram
Uninstall                                 = Desinstalar
'@
