ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                   = Bu betik sadece Windows 10 x64 destekliyor
UnsupportedOSBuild                     = Bu betik sadece Windows 10 1809 Enterprise LTSC
UnsupportedRelease                     = Yeni sürüm bulundu
ControlledFolderAccessDisabled         = Kontrollü klasör erişimi devre dışı bırakıldı
ScheduledTasks                         = Zamanlanan görevler
ClearFolder                            = "{0}" klasöründeki tüm dosyaları silin?
FilesBlocked                           = Aşağıdaki dosyalar 3. parti uygulamalar tarafından engelleniyor. `nKendiniz silin ve devam edin
TempNotEmpty                           = "{0}" klasörü boş değil. Kendiniz temizleyin
WindowsFeaturesWindowTitle             = Windows özellikleri
FODWindowTitle                         = İsteğe bağlı özellikler (FODv2)
EnableHardwareVT                       = UEFI'dan sanallaştırmayı aktifleştirin
UserShellFolderNotEmpty                = "{0}" klasöründe bazı dosyalar kaldı. `nKendiniz yeni konuma taşıyın
RetrievingDrivesList                   = Sürücü listesi alınıyor...
NewUserShellFolderLocation             = Yeni konum: "{0}"
DesktopDriveSelect                     = Masaüstü klasörün oluşturulacağı kök içindeki sürücüyü seçin
DocumentsDriveSelect                   = Belgeler klasörün oluşturulacağı kök içindeki sürücüyü seçin
DownloadsDriveSelect                   = İndirilenler klasörün oluşturulacağı kök içindeki sürücüyü seçin
MusicDriveSelect                       = Müzikler klasörün oluşturulacağı kök içindeki sürücüyü seçin
PicturesDriveSelect                    = Resimler klasörün oluşturulacağı kök içindeki sürücüyü seçin
VideosDriveSelect                      = Videolar klasörün oluşturulacağı kök içindeki sürücüyü seçin
DesktopRequest                         = Masaüstü klasörünün yerini değiştirmek ister misiniz?
DocumentsRequest                       = Belgeler klasörünün yerini değiştirmek ister misiniz?
DownloadsRequest                       = İndirilenler klasörünün yerini değiştirmek ister misiniz?
MusicRequest                           = Müzikler klasörünün yerini değiştirmek ister misiniz?
PicturesRequest                        = Resimler klasörünün yerini değiştirmek ister misiniz?
VideosRequest                          = Videolar klasörünün yerini değiştirmek ister misiniz?
DesktopFolderSelect                    = Masaüstü klasörü için bir klasör seçin.
DocumentsFolderSelect                  = Belgeler klasörü için bir klasör seçin.
DownloadsFolderSelect                  = İndirilenler klasörü için bir klasör seçin.
MusicFolderSelect                      = Müzikler klasörü için bir klasör seçin.
PicturesFolderSelect                   = Resimler klasörü için bir klasör seçin.
VideosFolderSelect                     = Videolar klasörü için bir klasör seçin.
DesktopDefaultFolder                   = Masaüstü klasörünün yerini eski haline getirmek ister misiniz?
DocumentsDefaultFolder                 = Belgeler klasörünün yerini eski haline getirmek ister misiniz?
DownloadsDefaultFolder                 = İndirilenler klasörünün yerini eski haline getirmek ister misiniz?
MusicDefaultFolder                     = Müzikler klasörünün yerini eski haline getirmek ister misiniz?
PicturesDefaultFolder                  = Resimler klasörünün yerini eski haline getirmek ister misiniz?
VideosDefaultFolder                    = Videolar klasörünün yerini eski haline getirmek ister misiniz?
GraphicsPerformanceTitle               = Grafik performans tercihi
GraphicsPerformanceRequest             = Seçtiğiniz bir uygulamanın grafik performansı ayarını "Yüksek performans" olarak belirlemek ister misiniz?
CleanUpTaskToast                       = Kullanılmayan Windows dosyalarının ve güncellemelerin temizlenmesi bir dakika içinde başlar
CleanUpTaskDescription                 = Kullanılmayan Windows dosyaları ve güncellemeleri yerleşik Disk Temizleme uygulaması ile temizleniyor
FolderTaskDescription                  = "{0}" klasörü temizleniyor
ControlledFolderAccess                 = Kontrollü klasör erişimi
ProtectedFoldersRequest                = Kontrollü klasör erişimini etkinleştirmek ve Microsoft Defender'ın kötü amaçlı uygulamalardan ve tehditlerden koruyacağı klasörü belirtmek ister misiniz?
ProtectedFoldersListRemoved            = Silinen klasörler
AppControlledFolderRequest             = Kontrollü Klasör erişimine izin verilen bir uygulama belirtmek ister misiniz?
AllowedControlledFolderAppsRemoved     = Tüm kaldırılan uygulamalar
DefenderTitle                          = Microsoft Defender
DefenderExclusionFolderRequest         = Microsoft Defender kötü amaçlı yazılım taramalarının dışında tutulacak bir klasör belirtmek ister misiniz?
DefenderExclusionFoldersListRemoved    = Hariç tutulan klasörler kaldırıldı
AddDefenderExclusionFileRequest        = Microsoft Defender kötü amaçlı yazılım taramalarının dışında bırakılacak bir dosya belirtmek ister misiniz?
DefenderExclusionFilesRemoved          = Hariç tutulan dosyalar kaldırıldı
EventViewerCustomViewName              = Süreç Oluşturma
EventViewerCustomViewDescription       = Süreç oluşturma ve komut satırı denetleme olayları
RestartWarning                         = Bilgisayarınızı yeniden başlattığınızdan emin olun
ErrorsLine                             = Satır
ErrorsFile                             = Dosya
ErrorsMessage                          = Hatalar/Uyarılar
Add                                    = Ekle
AllFilesFilter                         = Tüm Dosyalar (*.*)|*.*
Change                                 = Değiştir
Continue                               = Devam et
DialogBoxOpening                       = İletişim kutusu görüntüleniyor...
Disable                                = Devre dışı bırak
Enable                                 = Aktif et
EXEFilesFilter                         = *.exe|*.exe|Tüm Dosyalar (*.*)|*.*
FolderSelect                           = Klasör seç
FilesWontBeMoved                       = Dosyalar taşınmayacak
NoData                                 = Görüntülenecek bir şey yok
NoInternetConnection                   = İnternet bağlantısı yok
Patient                                = Lütfen bekleyin...
Select                                 = Seç
Skip                                   = Atla
Skipped                                = Atlandı
SymbolicSkipped                        = Sembolik bir bağlantı oluşturma atlandı
Uninstall                              = Kaldır
Install                                = Yüklemek
'@
