ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Bu betik sadece Windows 10 x64 destekliyor
UnsupportedOSBuild                        = Bu betik sadece Windows 10 1809 Enterprise LTSC
UnsupportedRelease                        = Yeni sürüm bulundu
ControlledFolderAccessDisabled            = Kontrollü klasör erişimi devre dışı bırakıldı
ScheduledTasks                            = Zamanlanan görevler
WindowsFeaturesTitle                      = Windows özellikleri
OptionalFeaturesTitle                     = İsteğe bağlı özellikler
EnableHardwareVT                          = UEFI'dan sanallaştırmayı aktifleştirin
UserShellFolderNotEmpty                   = "{0}" klasöründe bazı dosyalar kaldı. \nKendiniz yeni konuma taşıyın
RetrievingDrivesList                      = Sürücü listesi alınıyor...
DriveSelect                               = "{0}" klasörünün oluşturulacağı kök içindeki sürücüyü seçin
UserFolderRequest                         = "{0}" klasörünün yerini değiştirmek ister misiniz?
UserFolderSelect                          = "{0}" klasörü için bir klasör seçin
UserDefaultFolder                         = "{0}" klasörünün konumunu varsayılan değerle değiştirmek ister misiniz?
GraphicsPerformanceTitle                  = Grafik performans tercihi
GraphicsPerformanceRequest                = Seçtiğiniz bir uygulamanın grafik performansı ayarını "Yüksek performans" olarak belirlemek ister misiniz?
TaskNotificationTitle                     = Bildirim
CleanupTaskNotificationTitle              = Önemli bilgi
CleanupTaskDescription                    = Kullanılmayan Windows dosyaları ve güncellemeleri yerleşik Disk Temizleme uygulaması ile temizleniyor
CleanupTaskNotificationEventTitle         = Windows kullanılmayan dosyaları ve güncellemeleri temizlemek için görev çalıştırılsın mı?
CleanupTaskNotificationEvent              = Windows cleaning won't take long. Bir dahaki sefere bildirim 30 gün içinde görünecek
CleanupTaskNotificationSnoozeInterval     = Hatırlatma Aralığı Seçin
CleanupNotificationTaskDescription        = Windows kullanılmayan dosyaları ve güncellemeleri temizleme hakkında açılır bildirim hatırlatıcısı
SoftwareDistributionTaskNotificationEvent = Windows güncelleme önbelleği başarıyla silindi
TempTaskNotificationEvent                 = Geçici dosyalar klasörü başarıyla temizlendi
FolderTaskDescription                     = "{0}" klasörü temizleniyor
ControlledFolderAccess                    = Kontrollü klasör erişimi
ProtectedFoldersRequest                   = Kontrollü klasör erişimini etkinleştirmek ve Microsoft Defender'ın kötü amaçlı uygulamalardan ve tehditlerden koruyacağı klasörü belirtmek ister misiniz?
ProtectedFoldersListRemoved               = Silinen klasörler
AppControlledFolderRequest                = Kontrollü Klasör erişimine izin verilen bir uygulama belirtmek ister misiniz?
AllowedControlledFolderAppsRemoved        = Tüm kaldırılan uygulamalar
DefenderExclusionFolderRequest            = Microsoft Defender kötü amaçlı yazılım taramalarının dışında tutulacak bir klasör belirtmek ister misiniz?
DefenderExclusionFoldersListRemoved       = Hariç tutulan klasörler kaldırıldı
AddDefenderExclusionFileRequest           = Microsoft Defender kötü amaçlı yazılım taramalarının dışında bırakılacak bir dosya belirtmek ister misiniz?
DefenderExclusionFilesRemoved             = Hariç tutulan dosyalar kaldırıldı
EventViewerCustomViewName                 = Süreç Oluşturma
EventViewerCustomViewDescription          = Süreç oluşturma ve komut satırı denetleme olayları
RestartWarning                            = Bilgisayarınızı yeniden başlattığınızdan emin olun
ErrorsLine                                = Satır
ErrorsFile                                = Dosya
ErrorsMessage                             = Hatalar/Uyarılar
Add                                       = Ekle
AllFilesFilter                            = Tüm Dosyalar (*.*)|*.*
Change                                    = Değiştir
DialogBoxOpening                          = İletişim kutusu görüntüleniyor...
Disable                                   = Devre dışı bırak
Enable                                    = Aktif et
EXEFilesFilter                            = *.exe|*.exe|Tüm Dosyalar (*.*)|*.*
FolderSelect                              = Klasör seç
FilesWontBeMoved                          = Dosyalar taşınmayacak
FourHours                                 = 4 saat
HalfHour                                  = 30 dakika
Install                                   = Yüklemek
Minute                                    = 1 dakika
NoData                                    = Görüntülenecek bir şey yok
NoInternetConnection                      = İnternet bağlantısı yok
NoResponse                                = https://store.rg-adguard.net ile bağlantı kurulamadı
Open                                      = Açık
Patient                                   = Lütfen bekleyin...
Restore                                   = Onarmak
Run                                       = Başlat
Select                                    = Seç
SelectAll                                 = Hepsini seç
Skip                                      = Atla
Skipped                                   = Atlandı
TelegramTitle                             = Resmi Telegram kanalımıza katılın
Uninstall                                 = Kaldır
'@