ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Das Skript unterstützt nur Windows 10 x64
UnsupportedOSBuild                        = Das Skript unterstützt Windows 10 21H2/22H2+
UpdateWarning                             = Das kumulative Windows 10-Update wurde installiert: {0}. Unterstütztes kumulatives Update: 2364 und höher. Führen Sie Windows Update aus und versuchen Sie es erneut
UnsupportedLanguageMode                   = Die PowerShell-Sitzung wird in einem eingeschränkten Sprachmodus ausgeführt
LoggedInUserNotAdmin                      = Der angemeldete Benutzer hat keine Administratorrechte
UnsupportedPowerShell                     = Sie versuchen ein Skript über PowerShell {0}.{1} auszuführen. Das Skript in der entsprechenden PowerShell-Version ausführen
UnsupportedISE                            = Das Skript unterstützt nicht die Ausführung über Windows PowerShell ISE
Win10TweakerWarning                       = Wahrscheinlich wurde Ihr Betriebssystem über die Win 10 Tweaker-Hintertür infiziert
SycnexWarning                             = Die Stabilität des Windows-Betriebssystems kann durch die Verwendung des Windows10Debloater-Skripts beeinträchtigt worden sein. Installieren Sie Windows zur Vorbeugung neu.
Fs00Warning                               = Die Stabilität des Windows-Betriebssystems kann durch die Verwendung des "Windows 10 Bloat Remover and Tweaker" beeinträchtigt worden sein. Installieren Sie Windows zur Vorbeugung neu.
bin                                       = Im Ordner "bin" befinden sich keine Dateien. Bitte das Archiv erneut herunterladen
RebootPending                             = Der PC wartet darauf, neu gestartet zu werden
UnsupportedRelease                        = Neue Version gefunden
CustomizationWarning                      = \nHaben Sie alle Funktionen in der voreingestellten Datei {0} angepasst, bevor Sie Sophia Script ausführen?
DefenderBroken                            = Microsoft Defender defekt oder aus dem Betriebssystem entfernt
UpdateDefender                            = Die Microsoft Defender-Definitionen sind veraltet. Führen Sie Windows Update aus und versuchen Sie es erneut.
ControlledFolderAccessDisabled            = Kontrollierter Ordnerzugriff deaktiviert
ScheduledTasks                            = Geplante Aufgaben
OneDriveUninstalling                      = OneDrive deinstallieren…
OneDriveInstalling                        = OneDrive installieren…
OneDriveDownloading                       = OneDrive herunterladen… ~33 MB
OneDriveWarning                           = Die "{0}"-Funktion wird nur angewendet, wenn die Voreinstellung so konfiguriert ist, dass OneDrive entfernt wird (oder die App bereits entfernt wurde), andernfalls wird die Backup-Funktionalität für die Ordner "Desktop" und "Bilder" in OneDrive unterbrochen
WindowsFeaturesTitle                      = Windows-Features
OptionalFeaturesTitle                     = Optionale Features
EnableHardwareVT                          = Virtualisierung in UEFI aktivieren
UserShellFolderNotEmpty                   = Im Ordner "{0}" befinden sich noch Dateien \nVerschieben Sie sie manuell an einen neuen Ort
RetrievingDrivesList                      = Laufwerksliste abrufen…
DriveSelect                               = Wählen Sie das Laufwerk aus, in dessen Stammverzeichnis der Ordner "{0}" erstellt werden soll
CurrentUserFolderLocation                 = Der aktuelle Speicherort des Ordners "{0}" lautet: "{1}"
UserFolderRequest                         = Möchten Sie den Speicherort des Ordners "{0}" ändern?
UserFolderSelect                          = Wählen Sie einen Ordner für den Ordner "{0}"
UserDefaultFolder                         = Möchten Sie den Speicherort des Ordners "{0}" auf den Standardwert ändern?
ReservedStorageIsInUse                    = Dieser Vorgang wird nicht unterstützt, wenn reservierter Speicher verwendet wird\nBitte führen Sie die Funktion "{0}" nach dem PC-Neustart erneut aus
ShortcutPinning                           = Die Verknüpfung "{0}" wird an Start angeheftet…
UninstallUWPForAll                        = Für alle Benutzer
UWPAppsTitle                              = UWP-Apps
HEVCDownloading                           = HEVC-Videoerweiterungen vom Gerätehersteller herunterladen… ~2,8 MB
GraphicsPerformanceTitle                  = Bevorzugte Grafikleistung
GraphicsPerformanceRequest                = Möchten Sie die Einstellung der Grafikleistung einer App Ihrer Wahl auf "Hohe Leistung" einstellen?
ScheduledTaskPresented                    = Die Funktion "{0}" wurde bereits als "{1}" angelegt
CleanupTaskNotificationTitle              = Windows aufräumen
CleanupTaskNotificationEvent              = Aufgabe zum Bereinigen nicht verwendeter Windows-Dateien und -Updates ausführen?
CleanupTaskDescription                    = Bereinigung von nicht verwendeten Windows-Dateien und Updates mit der integrierten Festplattenbereinigung
CleanupNotificationTaskDescription        = Popup-Benachrichtigung zur Erinnerung an die Bereinigung von nicht verwendeten Windows-Dateien und Updates
SoftwareDistributionTaskNotificationEvent = Der Windows Update-Cache wurde erfolgreich gelöscht
TempTaskNotificationEvent                 = Der Ordner mit den temporären Dateien wurde erfolgreich bereinigt
FolderTaskDescription                     = Ordner "{0}" bereinigen
EventViewerCustomViewName                 = Prozesserstellung
EventViewerCustomViewDescription          = Prozesserstellungen und Befehlszeilen-Auditing-Ereignisse
RestartWarning                            = Sicherstellen, dass Sie Ihren PC neu starten
ErrorsLine                                = Zeile
ErrorsFile                                = Datei
ErrorsMessage                             = Fehler/Warnungen
Add                                       = Hinzufügen
AllFilesFilter                            = Alle Dateien (*.*)|*.*
Browse                                    = Durchsuchen
DialogBoxOpening                          = Anzeigen des Dialogfensters…
Disable                                   = Deaktivieren
Enable                                    = Aktivieren
EXEFilesFilter                            = *.exe|*.exe|Alle Dateien (*.*)|*.*
FolderSelect                              = Einen Ordner auswählen
FilesWontBeMoved                          = Dateien werden nicht verschoben
Install                                   = Installieren
NoData                                    = Nichts anzuzeigen
NoInternetConnection                      = Keine Internetverbindung
RestartFunction                           = Bitte die Funktion "{0}" neustarten
NoResponse                                = Eine Verbindung mit {0} konnte nicht hergestellt werden
No                                        = Nein
Yes                                       = Ja
Open                                      = Öffnen
Patient                                   = Bitte warten…
Restore                                   = Wiederherstellen
Run                                       = Starten
SelectAll                                 = Alle auswählen
Skipped                                   = Übersprungen
GPOUpdate                                 = GPO-Aktualisierung...
TelegramGroupTitle                        = Treten Sie unserer offiziellen Telegram-Gruppe bei
TelegramChannelTitle                      = Treten Sie unserem offiziellen Telegram-Kanal bei
DiscordChannelTitle                       = Treten Sie unserem offiziellen Discord-Kanal bei
Uninstall                                 = Deinstallieren
'@
