ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = 该脚本仅支持Windows 10 x64
UnsupportedOSBuild                        = 该脚本支持Windows 10版本2004/20H2/21H1/21H2和更高版本
UpdateWarning                             = 安装了Windows 10累积更新：{0}. 支持的累积更新：1151及以上
UnsupportedLanguageMode                   = PowerShell会话在有限的语言模式下运行
LoggedInUserNotAdmin                      = 登录的用户没有管理员的权利
UnsupportedPowerShell                     = 你想通过PowerShell {0}.{1}运行脚本。在适当的PowerShell版本中运行该脚本
UnsupportedISE                            = 该脚本不支持通过Windows PowerShell ISE运行
Win10TweakerWarning                       = 可能你的操作系统是通过“Win 10 Tweaker”后门感染的
PowerShellLibraries                       = Libraries文件夹中没有文件。请重新下载该档案
UnsupportedRelease                        = 找到新版本
CustomizationWarning                      = \n在运行Sophia Script之前，您是否已自定义Sophia.ps1预设文件中的每个函数？
ControlledFolderAccessDisabled            = “受控文件夹访问”已禁用
ScheduledTasks                            = 计划任务
OneDriveUninstalling                      = 卸载OneDrive……
OneDriveInstalling                        = OneDrive正在安装……
OneDriveDownloading                       = 正在下载OneDrive…… ~33 MB
WindowsFeaturesTitle                      = Windows功能
OptionalFeaturesTitle                     = 可选功能
EnableHardwareVT                          = UEFI中开启虚拟化
UserShellFolderNotEmpty                   = 一些文件留在了“{0}“文件夹。请手动将它们移到一个新位置
RetrievingDrivesList                      = 取得驱动器列表……
DriveSelect                               = 选择将在其根目录中创建“{0}“文件夹的驱动器
CurrentUserFolderLocation                 = 当前"{0}"文件夹的位置:"{1}"
UserFolderRequest                         = 是否要更改“{0}“文件夹位置？
UserFolderSelect                          = 为“{0}”文件夹选择一个文件夹
UserDefaultFolder                         = 您想将“{0}”文件夹的位置更改为默认值吗？
ReservedStorageIsInUse                    = 保留存储空间正在使用时不支持此操作\n请在电脑重启后重新运行"{0}"功能
ShortcutPinning                           = “{0}“快捷方式将被固定到开始菜单……
UninstallUWPForAll                        = 对于所有用户
UWPAppsTitle                              = UWP应用
HEVCDownloading                           = 下载”HEVC Video Extensions from Device Manufacturer”…… ~2,8 MB
GraphicsPerformanceTitle                  = 图形性能偏好
GraphicsPerformanceRequest                = 是否将所选应用程序的图形性能设置设为"高性能"？
TaskNotificationTitle                     = 通知
CleanupTaskNotificationTitle              = 重要信息
CleanupTaskDescription                    = 使用内置磁盘清理工具清理未使用的Windows文件和更新
CleanupTaskNotificationEventTitle         = 运行任务以清理Windows未使用的文件和更新？
CleanupTaskNotificationEvent              = Windows清理不会花很长时间。下次通知将在30天内显示
CleanupTaskNotificationSnoozeInterval     = 选择提醒间隔
CleanupNotificationTaskDescription        = 关于清理Windows未使用的文件和更新的弹出通知提醒
SoftwareDistributionTaskNotificationEvent = Windows更新缓存已成功删除
TempTaskNotificationEvent                 = 临时文件文件夹已成功清理
FolderTaskDescription                     = “{0}”文件夹清理
EventViewerCustomViewName                 = 进程创建
EventViewerCustomViewDescription          = 进程创建和命令行审核事件
RestartWarning                            = 确保重启电脑
ErrorsLine                                = 行
ErrorsFile                                = 文件
ErrorsMessage                             = 错误/警告
Add                                       = 添加
AllFilesFilter                            = 所有文件 (*.*)|*.*
Browse                                    = 浏览
Change                                    = 更改
DialogBoxOpening                          = 显示对话窗口……
Disable                                   = 禁用
Enable                                    = 启用
EXEFilesFilter                            = *.exe|*.exe|所有文件 (*.*)|*.*
FolderSelect                              = 选择一个文件夹
FilesWontBeMoved                          = 文件将不会被移动
FourHours                                 = 4个小时
HalfHour                                  = 30分钟
Install                                   = 安装
Minute                                    = 1分钟
NoData                                    = 无数据
NoInternetConnection                      = 无网络连接
RestartFunction                           = 请重新运行"{0}"函数
NoResponse                                = 无法建立{0}
No                                        = 不
Yes                                       = 是的
Open                                      = 打开
Patient                                   = 请等待……
Restore                                   = 恢复
Run                                       = 运行
SelectAll                                 = 全选
Skip                                      = 跳过
Skipped                                   = 已跳过
TelegramGroupTitle                        = 加入我们的官方Telegram 群
TelegramChannelTitle                      = 加入我们的官方Telegram 频道
Uninstall                                 = 卸载
'@
