ConvertFrom-StringData -StringData @'
UnsupportedOSBuild                        = Das Skript unterstützt Windows 11 2004/20H2/21H1-Versionen und höher
UpdateWarning                             = Ihr Windows 11-Build: {0}.{1}. Unterstützter Build: 22000.318 und höher
UnsupportedLanguageMode                   = Die PowerShell-Sitzung wird in einem eingeschränkten Sprachmodus ausgeführt
LoggedInUserNotAdmin                      = Der angemeldete Benutzer hat keine Administratorrechte
UnsupportedPowerShell                     = Sie versuchen ein Skript über PowerShell {0}.{1} auszuführen. Das Skript in der entsprechenden PowerShell-Version ausführen
UnsupportedISE                            = Das Skript unterstützt nicht die Ausführung über Windows PowerShell ISE
Win10TweakerWarning                       = Wahrscheinlich wurde Ihr Betriebssystem über die Win 10 Tweaker-Hintertür infiziert
PowerShellLibraries                       = Im Ordner "Libraries" befinden sich keine Dateien. Bitte das Archiv erneut herunterladen
UnsupportedRelease                        = Neue Version gefunden
CustomizationWarning                      = \nHaben Sie alle Funktionen in der voreingestellten Datei Sophia.ps1 angepasst, bevor Sie Sophia Script ausführen?
ControlledFolderAccessDisabled            = Kontrollierter Ordnerzugriff deaktiviert
ScheduledTasks                            = Geplante Aufgaben
OneDriveUninstalling                      = OneDrive deinstallieren…
OneDriveInstalling                        = OneDrive installieren…
OneDriveDownloading                       = OneDrive herunterladen… ~33 MB
OneDriveWarning                           = Die "{0}"-Funktion wird nur angewendet, wenn die Voreinstellung so konfiguriert ist, dass OneDrive entfernt wird, andernfalls wird die Backup-Funktionalität für die Ordner "Desktop" und "Bilder" in OneDrive unterbrochen
WindowsFeaturesTitle                      = Windows-Features
OptionalFeaturesTitle                     = Optionale Features
EnableHardwareVT                          = Virtualisierung in UEFI aktivieren
OpenInWindowsTerminalAdmin                = Im Windows-Terminal öffnen
UserShellFolderNotEmpty                   = Im Ordner "{0}" befinden sich noch Dateien \nVerschieben Sie sie manuell an einen neuen Ort
RetrievingDrivesList                      = Laufwerksliste abrufen…
DriveSelect                               = Wählen Sie das Laufwerk aus, in dessen Stammverzeichnis der Ordner "{0}" erstellt werden soll
CurrentUserFolderLocation                 = Der aktuelle Speicherort des Ordners "{0}" lautet: "{1}"
UserFolderRequest                         = Möchten Sie den Speicherort des Ordners "{0}" ändern?
UserFolderSelect                          = Wählen Sie einen Ordner für den Ordner "{0}"
UserDefaultFolder                         = Möchten Sie den Speicherort des Ordners "{0}" auf den Standardwert ändern?
ReservedStorageIsInUse                    = Dieser Vorgang wird nicht unterstützt, wenn reservierter Speicher verwendet wird\nBitte führen Sie die Funktion "{0}" nach dem PC-Neustart erneut aus
ShortcutPinning                           = Die Verknüpfung "{0}" wird an Start angeheftet…
UninstallUWPForAll                        = Für alle Benutzer
UWPAppsTitle                              = UWP-Apps
HEVCDownloading                           = HEVC-Videoerweiterungen vom Gerätehersteller herunterladen… ~2,8 MB
GraphicsPerformanceTitle                  = Bevorzugte Grafikleistung
GraphicsPerformanceRequest                = Möchten Sie die Einstellung der Grafikleistung einer App Ihrer Wahl auf "Hohe Leistung" einstellen?
TaskNotificationTitle                     = Benachrichtigung
CleanupTaskNotificationTitle              = Wichtige Informationen
CleanupTaskDescription                    = Bereinigung von nicht verwendeten Windows-Dateien und Updates mit der integrierten Festplattenbereinigung 
CleanupTaskNotificationEventTitle         = Aufgabe zum Bereinigen nicht verwendeter Windows-Dateien und -Updates ausführen?
CleanupTaskNotificationEvent              = Die Bereinigung von Windows wird nicht lange dauern. Das nächste Mal wird diese Benachrichtigung in 30 Tagen erscheinen
CleanupTaskNotificationSnoozeInterval     = Ein Erinnerungsintervall auswählen
CleanupNotificationTaskDescription        = Popup-Benachrichtigung zur Erinnerung an die Bereinigung von nicht verwendeten Windows-Dateien und Updates
SoftwareDistributionTaskNotificationEvent = Der Windows Update-Cache wurde erfolgreich gelöscht
TempTaskNotificationEvent                 = Der Ordner mit den temporären Dateien wurde erfolgreich bereinigt
FolderTaskDescription                     = Ordner "{0}" bereinigen
EventViewerCustomViewName                 = Prozesserstellung
EventViewerCustomViewDescription          = Prozesserstellungen und Befehlszeilen-Auditing-Ereignisse
RestartWarning                            = Sicherstellen, dass Sie Ihren PC neu starten
ErrorsLine                                = Zeile
ErrorsFile                                = Datei
ErrorsMessage                             = Fehler/Warnungen
Add                                       = Hinzufügen
AllFilesFilter                            = Alle Dateien (*.*)|*.*
Browse                                    = Durchsuchen
Change                                    = Ändern
DialogBoxOpening                          = Anzeigen des Dialogfensters…
Disable                                   = Deaktivieren
Enable                                    = Aktivieren
EXEFilesFilter                            = *.exe|*.exe|Alle Dateien (*.*)|*.*
FolderSelect                              = Einen Ordner auswählen
FilesWontBeMoved                          = Dateien werden nicht verschoben
FourHours                                 = 4 Stunden
HalfHour                                  = 30 Minuten
Install                                   = Installieren
Minute                                    = 1 Minute
NoData                                    = Nichts anzuzeigen
NoInternetConnection                      = Keine Internetverbindung
RestartFunction                           = Bitte die Funktion "{0}" neustarten
NoResponse                                = Eine Verbindung mit {0} konnte nicht hergestellt werden
No                                        = Nein
Yes                                       = Ja
Open                                      = Öffnen
Patient                                   = Bitte warten…
Restore                                   = Wiederherstellen
Run                                       = Starten
SelectAll                                 = Alle auswählen
Skip                                      = Überspringen
Skipped                                   = Übersprungen
FileExplorerRestartPrompt                 = \nManchmal muss der Datei-Explorer neu gestartet werden, damit die Änderungen wirksam werden
TelegramGroupTitle                        = Treten Sie unserer offiziellen Telegram-Gruppe bei
TelegramChannelTitle                      = Treten Sie unserem offiziellen Telegram-Kanal bei
Uninstall                                 = Deinstallieren
'@
