ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Das Skript unterstützt nur Windows 10 x64
UnsupportedOSBuild                        = Das Skript unterstützt Windows 10 1809 Enterprise LTSC
UnsupportedRelease                        = Neue Version gefunden
ControlledFolderAccessDisabled            = Kontrollierter Ordnerzugriff deaktiviert
ScheduledTasks                            = Geplante Aufgaben
WindowsFeaturesTitle                      = Windows Eigenschaften
OptionalFeaturesTitle                     = Optionale Eigenschaften
EnableHardwareVT                          = Virtualisierung in UEFI aktivieren
UserShellFolderNotEmpty                   = Einige im Ordner "{0}" verbliebene Dateien \nVerschieben Sie sie manuell an einen neuen Ort
RetrievingDrivesList                      = Abrufen der Laufwerksliste...
DriveSelect                               = Wählen Sie das Laufwerk, in dessen Stammverzeichnis der "{0}"-Ordner erstellt werden soll
UserFolderRequest                         = Möchten Sie den Speicherort des "{0}"-Ordners ändern?
UserFolderSelect                          = Wählen Sie einen Ordner für den Ordner "{0}"
UserDefaultFolder                         = Möchten Sie den Speicherort des "{0}"-Ordners auf den Standardwert ändern?
GraphicsPerformanceTitle                  = Bevorzugte Grafikleistung
GraphicsPerformanceRequest                = Möchten Sie die Einstellung der Grafikleistung einer App Ihrer Wahl auf "Hohe Leistung" setzen?
TaskNotificationTitle                     = Benachrichtigung
CleanupTaskNotificationTitle              = Wichtige informationen
CleanupTaskDescription                    = Bereinigung ungenutzter Windows-Dateien und -Updates mit der integrierten Festplatten-Bereinigungsanwendung
CleanupTaskNotificationEventTitle         = Aufgabe ausführen, um nicht verwendete Windows-Dateien und -Updates zu bereinigen?
CleanupTaskNotificationEvent              = Die Windows-Bereinigung dauert nicht lange. Das nächste Mal wird die Benachrichtigung in 30 Tagen angezeigt
CleanupTaskNotificationSnoozeInterval     = Wählen Sie ein Erinnerungsintervall
CleanupNotificationTaskDescription        = Bereinigung ungenutzter Windows-Dateien und -Updates mit der integrierten Festplatten-Bereinigungsanwendung
SoftwareDistributionTaskNotificationEvent = Der Windows Update-Cache wurde erfolgreich gelöscht
TempTaskNotificationEvent                 = Der Ordner mit den temporären Dateien wurde erfolgreich bereinigt
FolderTaskDescription                     = Die Bereinigung des Ordners "{0}"
ControlledFolderAccess                    = Kontrollierter Ordner-Zugriff
ProtectedFoldersRequest                   = Möchten Sie den kontrollierten Ordnerzugriff aktivieren und den Ordner angeben, den Microsoft Defender vor bösartigen Anwendungen und Bedrohungen schützen soll?
ProtectedFoldersListRemoved               = Gelöschte Ordner
AppControlledFolderRequest                = Möchten Sie eine Anwendung angeben, die über den Zugriff auf Kontrollierte Ordner erlaubt ist?
AllowedControlledFolderAppsRemoved        = Erlaubte Anwendungen entfernt
DefenderExclusionFolderRequest            = Möchten Sie einen Ordner angeben, der von den Malware-Scans von Microsoft Defender ausgeschlossen werden soll?
DefenderExclusionFoldersListRemoved       = Ausgeschlossene Ordner entfernt
AddDefenderExclusionFileRequest           = Möchten Sie eine Datei angeben, die von den Malware-Scans von Microsoft Defender ausgeschlossen werden soll?
DefenderExclusionFilesRemoved             = Ausgeschlossene Dateien entfernt
EventViewerCustomViewName                 = Prozess-Erstellung
EventViewerCustomViewDescription          = Ereignisse zur Prozesserstellung und Befehlszeilen-Auditierung
RestartWarning                            = Achten Sie darauf, Ihren PC neu zu starten
ErrorsLine                                = Zeile
ErrorsFile                                = Datei
ErrorsMessage                             = Fehler/Warnungen
Add                                       = Hinzufügen
AllFilesFilter                            = Alle Dateien (*.*)|*.*
Change                                    = Ändern
DialogBoxOpening                          = Anzeigen des Dialogfensters...
Disable                                   = Deaktivieren
Enable                                    = Aktivieren
EXEFilesFilter                            = *.exe|*.exe|Alle Dateien (*.*)|*.*
FolderSelect                              = Wählen Sie einen Ordner aus
FilesWontBeMoved                          = Dateien werden nicht verschoben
FourHours                                 = 4 Stunden
HalfHour                                  = 30 Minuten
Install                                   = Installieren
Minute                                    = 1 Minute
NoData                                    = Nichts anzuzeigen
NoInternetConnection                      = Keine Internetverbindung
NoResponse                                = Eine Verbindung mit https://store.rg-adguard.net konnte nicht hergestellt werden
Open                                      = Öffnen
Patient                                   = Bitte Warten...
Restore                                   = Wiederherstellen
Run                                       = Starten
Select                                    = Wählen Sie
SelectAll                                 = Wählen Sie Alle
Skip                                      = Überspringen
Skipped                                   = Übersprungen
TelegramTitle                             = Abonniere doch unseren offiziellen Kanal telegram
Uninstall                                 = Deinstallieren
'@