ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                   = Das Skript unterstützt nur Windows 10 x64
UnsupportedOSBuild                     = Das Skript unterstützt Windows 10 1809 Enterprise LTSC
UnsupportedRelease                     = Neue Version gefunden
ControlledFolderAccessDisabled         = Kontrollierter Ordnerzugriff deaktiviert
ScheduledTasks                         = Geplante Aufgaben
ClearFolder                            = Löscht alle Dateien im Ordner "{0}"?
FilesBlocked                           = Die folgenden Dateien werden von Apps von Drittanbietern blockiert. 'nEntfernen Sie sie manuell und fahren Sie fort
TempNotEmpty                           = Der Ordner "{0}" ist nicht leer. Löschen Sie ihn manuell
WindowsFeaturesWindowTitle             = Windows Eigenschaften
FODWindowTitle                         = Optionale eigenschaften (FODv2)
EnableHardwareVT                       = Virtualisierung in UEFI aktivieren
UserShellFolderNotEmpty                = Einige im Ordner "{0}" verbliebene Dateien `nVerschieben Sie sie manuell an einen neuen Ort
RetrievingDrivesList                   = Abrufen der Laufwerksliste...
NewUserShellFolderLocation             = Neuer Standort: "{0}"
DesktopDriveSelect                     = Wählen Sie das Laufwerk, in dessen Stammverzeichnis der Desktop-Ordner erstellt werden soll
DocumentsDriveSelect                   = Wählen Sie das Laufwerk, in dessen Stammverzeichnis der Ordner "Dokumente" erstellt werden soll
DownloadsDriveSelect                   = Wählen Sie das Laufwerk, in dessen Stammverzeichnis der Ordner Downloads erstellt wird
MusicDriveSelect                       = Wählen Sie das Laufwerk, in dessen Stammverzeichnis der Ordner "Musik" erstellt wird
PicturesDriveSelect                    = Wählen Sie das Laufwerk, in dessen Stammverzeichnis der Ordner "Bilder" erstellt werden soll
VideosDriveSelect                      = Wählen Sie das Laufwerk, in dessen Stammverzeichnis der Ordner Videos erstellt wird
DesktopRequest                         = Möchten Sie den Speicherort des Desktop-Ordners ändern?
DocumentsRequest                       = Möchten Sie den Speicherort des Ordners Dokumente ändern?
DownloadsRequest                       = Möchten Sie den Speicherort des Ordners Downloads ändern?
MusicRequest                           = Möchten Sie den Speicherort des Ordners Musik ändern?
PicturesRequest                        = Möchten Sie den Speicherort des Ordners Bilder ändern?
VideosRequest                          = Möchten Sie den Speicherort des Ordners Videos ändern?
DesktopFolderSelect                    = Wählen Sie einen Ordner für den Ordner Desktop
DocumentsFolderSelect                  = Wählen Sie einen Ordner für den Ordner Dokumente
DownloadsFolderSelect                  = Wählen Sie einen Ordner für den Ordner Downloads
MusicFolderSelect                      = Wählen Sie einen Ordner für den Ordner Musik
PicturesFolderSelect                   = Wählen Sie einen Ordner für den Ordner Bilder aus
VideosFolderSelect                     = Wählen Sie einen Ordner für den Ordner Videos
DesktopDefaultFolder                   = Möchten Sie den Speicherort des Desktop-Ordners auf den Standardwert ändern?
DocumentsDefaultFolder                 = Möchten Sie den Speicherort des Ordners Dokumente auf den Standardwert ändern?
DownloadsDefaultFolder                 = Möchten Sie den Speicherort des Ordners Downloads auf den Standardwert ändern?
MusicDefaultFolder                     = Möchten Sie den Speicherort des Ordners Musik auf den Standardwert ändern?
PicturesDefaultFolder                  = Möchten Sie den Speicherort des Ordners "Bilder" auf den Standardwert ändern?
VideosDefaultFolder                    = Möchten Sie den Speicherort des Ordners Videos auf den Standardwert ändern?
GraphicsPerformanceTitle               = Bevorzugte Grafikleistung
GraphicsPerformanceRequest             = Möchten Sie die Einstellung der Grafikleistung einer App Ihrer Wahl auf "Hohe Leistung" setzen?
CleanUpTaskToast                       = Das Bereinigen ungenutzter Windows-Dateien und Updates beginnt in einer Minute
CleanUpTaskDescription                 = Bereinigung ungenutzter Windows-Dateien und -Updates mit der integrierten Festplatten-Bereinigungsanwendung
FolderTaskDescription                  = Die "{0}"-Ordnerbereinigung
ControlledFolderAccess                 = Kontrollierter Ordner-Zugriff
ProtectedFoldersRequest                = Möchten Sie den kontrollierten Ordnerzugriff aktivieren und den Ordner angeben, den Microsoft Defender vor bösartigen Anwendungen und Bedrohungen schützen soll?
ProtectedFoldersListRemoved            = Gelöschte Ordner
AppControlledFolderRequest             = Möchten Sie eine Anwendung angeben, die über den Zugriff auf Kontrollierte Ordner erlaubt ist?
AllowedControlledFolderAppsRemoved     = Erlaubte Anwendungen entfernt
DefenderTitle                          = Microsoft Defender
DefenderExclusionFolderRequest         = Möchten Sie einen Ordner angeben, der von den Malware-Scans von Microsoft Defender ausgeschlossen werden soll?
DefenderExclusionFoldersListRemoved    = Ausgeschlossene Ordner entfernt
AddDefenderExclusionFileRequest        = Möchten Sie eine Datei angeben, die von den Malware-Scans von Microsoft Defender ausgeschlossen werden soll?
DefenderExclusionFilesRemoved          = Ausgeschlossene Dateien entfernt
EventViewerCustomViewName              = Prozess-Erstellung
EventViewerCustomViewDescription       = Ereignisse zur Prozesserstellung und Befehlszeilen-Auditierung
RestartWarning                         = Achten Sie darauf, Ihren PC neu zu starten
ErrorsLine                             = Zeile
ErrorsFile                             = Datei
ErrorsMessage                          = Fehler/Warnungen
Add                                    = Hinzufügen
AllFilesFilter                         = Alle Dateien (*.*)|*.*
Change                                 = Ändern
Continue                               = Fortfahren
DialogBoxOpening                       = Anzeigen des Dialogfensters...
Disable                                = Deaktivieren
Enable                                 = Aktivieren
EXEFilesFilter                         = *.exe|*.exe|Alle Dateien (*.*)|*.*
FolderSelect                           = Wählen Sie einen Ordner aus
FilesWontBeMoved                       = Dateien werden nicht verschoben
NoData                                 = Nichts anzuzeigen
NoInternetConnection                   = Keine Internetverbindung
Patient                                = Bitte Warten...
Select                                 = Wählen Sie
Skip                                   = Überspringen
Skipped                                = Übersprungen
SymbolicSkipped                        = Das Erstellen eines symbolischen Links wurde übersprungen
Uninstall                              = Deinstallieren
Install                                = Installieren
'@
