ConvertFrom-StringData -StringData @'
UnsupportedArchitecture                   = Korzystasz z procesora opartego na architekturze "{0}". Ten skrypt obsługuje wyłącznie procesory oparte na architekturze x64. Pobierz i uruchom wersję skryptu odpowiednią dla swojej architektury.
NewSophiaScriptFound                      = Dostępna jest nowa wersja: Sophia Script for Windows {0}. Prosimy o aktualizację.
UnsupportedPowerShell                     = Próbujesz uruchomić skrypt przy użyciu PowerShell {0}.{1}. Uruchom skrypt w PowerShell {2}.
CodeCompilationFailed                     = Kompilacja kodu nie powiodła się.
KeyboardArrows                            = Użyj klawiszy strzałek {0} i {1} na klawiaturze, aby wybrać odpowiedź
UnsupportedLanguageMode                   = Sesja PowerShell działa w trybie ograniczonego języka.
LoggedInUserNotAdmin                      = Zalogowany użytkownik "{0}" nie ma uprawnień administratora. Skrypt został uruchomiony w imieniu "{1}". Zaloguj się na konto z uprawnieniami administratora i uruchom skrypt ponownie.
UnsupportedHost                           = Skrypt nie może być uruchamiany w {0}.
HarmfulTweakerFound                       = Stabilność systemu Windows mogła zostać naruszona przez użycie {0}.
HostsEntriesFound                         = W pliku %SystemRoot%\\System32\\drivers\\etc\\hosts znaleziono wpisy stron trzecich. Mogą one blokować połączenie z zasobami używanymi w skrypcie. Czy chcesz kontynuować?
UWPComponentsMissing                      = Brakuje komponentu UWP "{0}".
DefenderComponentsMissing                 = Brakuje komponentu "{0}" programu Microsoft Defender.
WindowsComponentStabilityDisrupted        = W komponencie "{0}" wykryto problem związany z niestabilnością.
DisableControlledFolderAccess             = Masz włączony kontrolowany dostęp do folderów. Wyłącz go i uruchom skrypt ponownie.
RebootPending                             = Twój komputer czeka na ponowne uruchomienie.
SystemDriveEncryptedBitLockerDisabled     = Dysk C jest zaszyfrowany, mimo że funkcja BitLocker jest wyłączona. Czy chcesz odszyfrować dysk?
UpdateUEFICertificates                    = Certyfikat Secure Boot "Microsoft Windows Production PCA 2011" traci ważność w 2026 roku. Twoje urządzenie nie otrzymało jeszcze zaktualizowanych certyfikatów "Windows UEFI CA 2023". Czy chcesz ręcznie zainstalować certyfikaty "Microsoft Windows UEFI CA 2023"?
EnableSecureBoot                          = Włącz opcję Secure Boot.
WrongSophiaScriptVersion                  = Skrypt obsługuje wyłącznie system Windows 11 Enterprise LTSC 2024. Używasz systemu {0} {1}. Uruchom odpowiedni skrypt w zależności od wersji systemu Windows.
UpdateWindowsBuild                        = Skrypt obsługuje system Windows 11 Enterprise LTSC 2024 {0}.{1} i nowsze wersje. Używasz systemu {2} {3} {4}.{5}. Uruchom usługę Windows Update i spróbuj ponownie.
AskQuestion                               = Jeśli masz jakieś pytanie, zgłoś issue na GitHubie lub zapytaj społeczność.
CheckSophiaScriptPreset                   = Czy dostosowałeś wszystkie funkcje w pliku ustawień wstępnych {0} przed uruchomieniem Sophia Script for Windows?
ReinstallWindows                          = Zainstaluj ponownie system Windows, używając tylko oryginalnego obrazu ISO.
CreatingRestorePoint                      = Tworzony jest punkt przywracania...
WindowsServiceNotFound                    = Nie znaleziono usługi "{0}".
NoScheduledTasksFound                     = Nie znaleziono zaplanowanych zadań.
ScheduledTasks                            = Zaplanowane zadania
SearchHighlightsDisabled                  = Najważniejsze wyniki wyszukiwania są już ukryte w menu Start.
CustomStartMenuFound                      = Zainstalowano menu Start innej firmy.
InstallingApplication                     = Trwa instalowanie {0}...
NoWindowsFeaturesFound                    = Nie znaleziono funkcji Windows.
WindowsFeaturesTitle                      = Funkcje Windows
NoOptionalFeaturesFound                   = Nie znaleziono funkcji opcjonalnych.
OptionalFeaturesTitle                     = Funkcje opcjonalne
NoSupportedNetworkAdaptersFound           = Brak kart sieciowych obsługujących funkcję "Zezwól komputerowi na wyłączenie tego urządzenia w celu oszczędzania energii".
LocationServicesDisabled                  = Polecenia powłoki sieciowej wymagają uprawnień lokalizacyjnych, aby uzyskać dostęp do informacji o sieci WLAN. Włącz usługi lokalizacyjne na stronie Lokalizacja w ustawieniach prywatności i bezpieczeństwa.
UserFolderLocationMove                    = Nie należy zmieniać lokalizacji folderu użytkownika na katalog główny dysku C.
DriveSelect                               = Wybierz dysk, na którym w katalogu głównym zostanie utworzony folder "{0}".
CurrentUserFolderLocation                 = Bieżąca lokalizacja folderu "{0}": "{1}".
FilesWontBeMoved                          = Pliki nie zostaną przeniesione.
UserFolderMoveSkipped                     = Pominąłeś zmianę lokalizacji folderu użytkownika "{0}".
UserShellFolderNotEmpty                   = Niektóre pliki pozostały w folderze "{0}". Przenieś je ręcznie w nowe miejsce.
FolderSelect                              = Wybierz folder
UserFolderRequest                         = Czy chcesz zmienić lokalizację folderu "{0}"?
UserDefaultFolder                         = Czy chcesz zmienić lokalizację folderu "{0}" na wartość domyślną?
ReservedStorageIsInUse                    = Zarezerwowana przestrzeń dyskowa jest w użyciu.
ProgramPathNotExists                      = Ścieżka "{0}" nie istnieje.
ProgIdNotExists                           = ProgId "{0}" nie istnieje.
AllFilesFilter                            = Wszystkie pliki
JSONNotValid                              = Plik JSON "{0}" jest nieprawidłowy.
PackageNotInstalled                       = Aplikacja "{0}" nie jest zainstalowana.
PackageIsInstalled                        = Najnowsza wersja {0} jest już zainstalowana.
WDDMVersionUnsupported                    = Obsługiwana jest wersja WDDM 2.7 i nowsze. Aktualna wersja WDDM to {0}.
CleanupTaskNotificationTitle              = Oczyszczanie systemu Windows
CleanupTaskNotificationEvent              = Uruchomić zadanie w celu usunięcia nieużywanych plików i aktualizacji systemu Windows?
CleanupTaskDescription                    = Czyszczenie nieużywanych plików i aktualizacji systemu Windows za pomocą wbudowanej aplikacji do czyszczenia dysku.
CleanupNotificationTaskDescription        = Powiadomienie przypominające o czyszczeniu nieużywanych plików i aktualizacji systemu Windows.
SoftwareDistributionTaskNotificationEvent = Pomyślnie usunięto pamięć podręczną aktualizacji systemu Windows.
SoftwareDistributionTaskDescription       = Czyszczenie folderu pamięci podręcznej aktualizacji systemu Windows "{0}".
TempTaskNotificationEvent                 = Folder tymczasowy został pomyślnie wyczyszczony.
TempTaskDescription                       = Czyszczenie folderu tymczasowego "{0}" (%TEMP%).
ScheduledTaskLoggedInUserNotification     = Zaplanowane zadanie może zostać uruchomione tylko wtedy, gdy użytkownik "{0}" jest zalogowany do systemu.
CleanupTaskCLIDescription                 = Zaplanowane zadanie "Sophia\\Windows Cleanup Notification" zostało utworzone w Harmonogramie zadań w celu czyszczenia nieużywanych plików i aktualizacji systemu Windows.
SoftwareDistributionTaskCLIDescription    = Zaplanowane zadanie "Sophia\\SoftwareDistribution" zostało utworzone w Harmonogramie zadań w celu czyszczenia folderu pamięci podręcznej aktualizacji systemu Windows "{0}".
TempTaskCLIDescription                    = Zaplanowane zadanie "Sophia\\Temp" zostało utworzone w Harmonogramie zadań w celu czyszczenia folderu tymczasowego "{0}" (%TEMP%).
EventViewerCustomViewName                 = Tworzenie procesu
EventViewerCustomViewDescription          = Śledzenie uruchamianych procesów i aktywności PowerShell
EventViewerCustomViewNotification         = Widok niestandardowy "Widoki niestandardowe\\{0}" został utworzony w Podglądzie zdarzeń w celu śledzenia uruchamianych procesów i aktywności PowerShell.
ThirdPartyAVInstalled                     = Zainstalowano program antywirusowy innej firmy.
EnableHardwareVT                          = Włącz wirtualizację w UEFI.
ActiveNetworkAdapterNotFound              = Nie można określić aktualnie używanej karty sieciowej: nie znaleziono aktywnego połączenia sieciowego. Połącz się z siecią.
ThirdPartyArchiverInstalled               = Zainstalowano archiwizator innej firmy.
RestartWarning                            = Pamiętaj o ponownym uruchomieniu komputera.
RestorePointVolume                        = Punkty przywracania dla dysku C zajmują {0} GB.
ErrorsLine                                = Linia
ErrorsMessage                             = Błędy, ostrzeżenia i powiadomienia
Disable                                   = Wyłącz
Enable                                    = Włącz
Install                                   = Zainstaluj
Uninstall                                 = Odinstaluj
RestartFunction                           = Uruchom ponownie funkcję "{0}".
NoConnectionEstablished                   = Nie można nawiązać połączenia z {0}.
Run                                       = Uruchom
FunctionSkipped                           = Funkcja "{0}" pominięta.
DonateToastTitle                          = Darowizny są mile widziane! ❤
DotSourceFunction                         = Prosimy o "dot-source" funkcji (z kropką na początku):\n. .\\Import-TabCompletion.ps1
'@
