ConvertFrom-StringData -StringData @'
NewSophiaScriptFound                      = Виявлено нову версію: Sophia Script for Windows {0}. Будь ласка, завантажте останню версію.
UnsupportedPowerShell                     = Ви намагаєтеся запустити скрипт в PowerShell {0}.{1}. Запустіть скрипт в PowerShell {2}.
CodeCompilationFailed                     = Компіляція коду завершилася з помилкою.
MicrosoftStorePowerShellWarning           = PowerShell, завантажений з Microsoft Store, не підтримується. Будь ласка, запустіть MSI-версію.
PowerShellImportFailed                    = Імпорт моделей з PowerShell 5.1 завершився помилкою. Будь ласка, закрийте PowerShell 7 і запустіть скрипт знову.
UnsupportedWindowsBitness                 = Скрипт підтримує тільки 64-розрядну версію Windows.
KeyboardArrows                            = Для вибору відповіді використовуйте на клавіатурі стрілки  {0} і {1}
UnsupportedLanguageMode                   = Сесія PowerShell працює в обмеженому режимі.
LoggedInUserNotAdmin                      = Користувач "{0}", що увійшов, не має прав адміністратора. Скрипт був запущений від імені "{1}". Будь ласка, увійдіть в профіль, що має права адміністратора, і запустіть скрипт заново.
UnsupportedHost                           = Скрипт не підтримує роботу через {0}.
HarmfulTweakerFound                       = Стабільність вашої ОС могла бути порушена використанням {0}.
HostsEntriesFound                         = У файлі %SystemRoot%\\System32\\drivers\\etc\\hosts виявлено сторонні записи. Вони можуть блокувати з'єднання з ресурсами, що використовуються в роботі скрипта. Хочете продовжити?
WindowsComponentStabilityDisrupted        = Виявлено порушення стабільності роботи компонента "{0}".
DisableControlledFolderAccess             = У вас увімкнено контрольований доступ. Будь ласка, вимкніть його та спробуйте ще раз.
RebootPending                             = Ваш комп'ютер очікує перезавантаження.
SystemDriveEncryptedBitLockerDisabled     = Диск C зашифрований, хоча BitLocker вимкнено. Хочете розшифрувати диск?
ESUProgramEnrollment                      = Термін підтримки Windows 10 закінчився 14 жовтня 2025 року. Ваш комп’ютер може бути вразливим до шкідливого програмного забезпечення, троянських програм та вразливостей нульового дня. Хочете приєднатися до програми Розширених оновлень безпеки (ESU), щоб отримувати оновлення до 2028 року за допомогою TSforge з Microsoft Activation Scripts (MAS)?
WrongSophiaScriptVersion                  = Скрипт підтримує тільки Windows 10 22H2. Ви використовуєте {0} {1}. Запустіть скрипт відповідно до вашої версії Windows.
UpdateWindowsBuild                        = Ви використовуєте Windows 10 {0}.{1}. Підтримувані збірки: Windows 10 {0}.{2} і вище. Запустіть оновлення Windows і спробуйте ще раз.
CheckSophiaScriptPreset                   = Ви налаштували всі функції в пресет-файлі {0} перед запуском Sophia Script for Windows?
ReinstallWindows                          = Перевстановіть Windows, використовуючи тільки справжній ISO-образ.
CreatingRestorePoint                      = Створюється точка відновлення...
UWPComponentsMissing                      = Відсутній UWP-компонент "{0}".
DefenderComponentsMissing                 = Відсутній компонент "{0}" для Microsoft Defender.
DiagTrackServiceNotFound                  = Відсутня служба "DiagTrackService".
NoScheduledTasksFound                     = Немає запланованих завдань, які необхідно вимкнути.
ScheduledTasks                            = Заплановані задачі
TaskbarSmallIcons                         = Ви використовуєте маленькі кнопки панелі завдань.
SearchHighlightsDisabled                  = Основні результати пошуку в меню "Пуск" вже приховані.
CustomStartMenuFound                      = Встановлено стороннє меню "Пуск".
OneDriveNotInstalled                      = OneDrive вже видалено.
OneDriveAccountUsageFound                 = Перед видаленням OneDrive вийдіть з облікового запису Microsoft в OneDrive.
OneDriveInstalled                         = OneDrive вже встановлено.
UninstallingApplication                   = {0} видаляється...
InstallingApplication                     = {0} встановлюється...
NoWindowsFeaturesFound                    = Немає компонентів Windows, які необхідно вимкнути.
WindowsFeaturesTitle                      = Компоненти Windows
NoOptionalFeaturesFound                   = Немає компонентів Windows, які необхідно вимкнути.
NoSupportedNetworkAdaptersFound           = Немає мережевих адаптерів, що підтримують функцію "Дозволити комп'ютеру відключати цей пристрій для економії енергії".
LocationServicesDisabled                  = Командам мережевої оболонки потрібен дозвіл на доступ до відомостей бездротової мережі. Увімкніть служби визначення місцезнаходження на сторінці "Розташування" в параметрах конфіденційності та захисту.
OptionalFeaturesTitle                     = Додаткові компоненти
UserShellFolderNotEmpty                   = У папці "{0}" залишилися файли. Перемістіть їх вручну в нове розташування.
UserFolderLocationMove                    = Не слід переміщати користувацькі папки в корінь диска C.
DriveSelect                               = Виберіть диск, в корні якого буде створена папка для "{0}".
CurrentUserFolderLocation                 = Поточне розташування папки "{0}": "{1}".
FilesWontBeMoved                          = Файли не будуть перенесені.
UserFolderMoveSkipped                     = Ви пропустили зміну розташування папки користувача "{0}".
FolderSelect                              = Виберіть папку
UserFolderRequest                         = Бажаєте змінити розташування папки "{0}"?
UserDefaultFolder                         = Бажаєте змінити розташування папки "{0}" на значення за замовчуванням?
ReservedStorageIsInUse                    = Використовується зарезервоване сховище.
ProgramPathNotExists                      = Шлях "{0}" не існує.
ProgIdNotExists                           = ProgId "{0}" не існує.
AllFilesFilter                            = Всі файли
JSONNotValid                              = Файл JSON "{0}" недійсний.
PackageNotInstalled                       = Додаток "{0}" не встановлено.
PackageIsInstalled                        = Остання версія {0} вже встановлена.
UninstallUWPForAll                        = Для всіх користувачів
NoUWPAppsFound                            = Немає UWP-додатків, які необхідно видалити.
UWPAppsTitle                              = UWP-додатки
ScheduledTaskCreatedByAnotherUser         = Функцію "{0}" уже було створено від імені "{1}".
CleanupTaskNotificationTitle              = Очищення Windows
CleanupTaskNotificationEvent              = Запустити завдання з очищення невикористовуваних файлів і оновлень Windows?
CleanupTaskDescription                    = Очищення невикористовуваних файлів і оновлень Windows, використовуючи вбудовану програму Очищення диска.
CleanupNotificationTaskDescription        = Спливаюче повідомлення з нагадуванням про очищення невикористовуваних файлів і оновлень Windows.
SoftwareDistributionTaskNotificationEvent = Кеш оновлень Windows успішно видалено.
SoftwareDistributionTaskDescription       = Очищення папки кешу оновлень Windows "{0}".
TempTaskNotificationEvent                 = Папка тимчасових файлів успішно очищена.
TempTaskDescription                       = Очищення папки тимчасових файлів "{0}" (%TEMP%).
ScheduledTaskLoggedInUserNotification     = Завдання можна запустити лише в тому випадку, якщо користувач "{0}" увійшов у систему.
ScheduledTaskCreatedNotification          = У Планувальнику завдань створено завдання "{0}".
CleanupTaskCLIDescription                 = Перейдіть до папки "Sophia" у Планувальнику завдань і запустіть завдання "Windows Cleanup Notification", щоб розпочати очищення невикористовуваних файлів та оновлень Windows.
SoftwareDistributionTaskCLIDescription    = Перейдіть до папки "Sophia" у Планувальнику завдань і запустіть завдання "SoftwareDistribution", щоб розпочати очищення папки кешу оновлень Windows "{0}".
TempTaskCLIDescription                    = Перейдіть до папки "Sophia" у Планувальнику завдань і запустіть завдання "Temp", щоб розпочати очищення папки тимчасових файлів "{0}" (%TEMP%).
EventViewerCustomViewName                 = Створення процесу
EventViewerCustomViewDescription          = Події створення нового процесу і аудит командного рядка.
ThirdPartyAVInstalled                     = Встановлено сторонній антивірус.
NoHomeWindowsEditionSupport               = Редакція Windows Домашня не підтримує функцію "{0}".
EnableHardwareVT                          = Увімкніть віртуалізацію в UEFI.
PhotosNotInstalled                        = Додаток "Фотографії" не встановлено.
HEVCInstalled                             = Розширення відео HEVC від виробника пристрою вже встановлено.
HEVCInstallingApplication                   = Розширення відео HEVC від виробника пристрою встановлюється...
ThirdPartyArchiverInstalled               = Встановлено сторонній архіватор.
gpeditNotSupported                        = Редакція Windows Домашня не підтримує оснащення Редактора локальної групової політики (gpedit.msc).
RestartWarning                            = Обов'язково перезавантажте ваш ПК.
RestorePointVolume                        = Точки відновлення на диску C займають {0} ГБ.
ErrorsLine                                = Рядок
ErrorsMessage                             = Помилки, попередження та повідомлення
Disable                                   = Вимкнути
Enable                                    = Увімкнути
Install                                   = Встановити
Uninstall                                 = Видалити
RestartFunction                           = Будь ласка, повторно запустіть функцію "{0}".
NoConnectionEstablished                   = Не вдалося встановити зв’язок із {0}.
Run                                       = Запустити
FunctionSkipped                           = Функцію "{0}" пропущено.
DonateToastTitle                          = Ви можете зробити пожертву!❤
DotSourcedFunction                        = Будь ласка, запустіть функцію через дот-сорсинг (з крапкою на початку):\n. .\\Import-TabCompletion.ps1
'@
