ConvertFrom-StringData -StringData @'
UnsupportedArchitecture                   = Sie verwenden eine CPU mit "{0}"-basierter Architektur. Dieses Skript unterstützt nur CPUs mit x64-Architektur. Laden Sie die für Ihre Architektur geeignete Skriptversion herunter und führen Sie sie aus.
NewSophiaScriptFound                      = Es ist eine neue Version verfügbar: Sophia Script for Windows {0}. Bitte führen Sie ein Update durch.
UnsupportedPowerShell                     = Sie versuchen ein Skript über PowerShell {0}.{1} auszuführen. Bitte führen Sie das Skript in PowerShell {2} aus.
CodeCompilationFailed                     = Die Code-Kompilierung ist fehlgeschlagen.
KeyboardArrows                            = Bitte verwenden Sie die Pfeiltasten {0} und {1} auf Ihrer Tastatur, um Ihre Antwort auszuwählen
UnsupportedLanguageMode                   = Die PowerShell-Sitzung wird in einem eingeschränkten Sprachmodus ausgeführt.
LoggedInUserNotAdmin                      = Der angemeldete Benutzer "{0}" hat keine Administratorrechte. Das Skript wurde im Namen von "{1}" ausgeführt. Bitte melden Sie sich bei einem Konto mit Administratorrechten an und führen Sie das Skript erneut aus.
UnsupportedHost                           = Das Skript unterstützt keine Ausführung über {0}.
HarmfulTweakerFound                       = Die Stabilität des Windows-Betriebssystems kann durch die Verwendung des {0} beeinträchtigt worden sein.
HostsEntriesFound                         = In der Datei %SystemRoot%\\System32\\drivers\\etc\\hosts wurden Einträge von Drittanbietern gefunden. Diese können die Verbindung zu den im Skript verwendeten Ressourcen blockieren. Möchten Sie fortfahren?
WindowsComponentStabilityDisrupted        = In der Komponente "{0}" wurde ein Stabilitätsproblem festgestellt.
DisableControlledFolderAccess             = Sie haben den kontrollierten Ordnerzugriff aktiviert. Bitte deaktivieren Sie ihn und führen Sie das Skript erneut aus.
RebootPending                             = Ihr PC wartet darauf, neu gestartet zu werden.
SystemDriveEncryptedBitLockerDisabled     = Das Laufwerk C ist verschlüsselt, obwohl BitLocker deaktiviert ist. Möchten Sie Ihr Laufwerk entschlüsseln?
UpdateUEFICertificates                    = Das Secure-Boot-Zertifikat "Microsoft Windows Production PCA 2011" läuft im Jahr 2026 ab. Ihr Gerät hat die aktualisierten Windows-UEFI-CA-2023-Zertifikate noch nicht erhalten. Möchten Sie die "Microsoft Windows UEFI CA 2023"-Zertifikate manuell installieren?
UpdateWindowsTerminal                     = Die Windows Terminal-Version ist niedriger als 1.23. Bitte aktualisieren Sie es im Microsoft Store und versuchen Sie es erneut.
WrongSophiaScriptVersion                  = Das Skript unterstützt nur Windows 11 Enterprise LTSC 2024. Sie verwenden Windows {0} {1}. Führen Sie das für Ihre Windows-Version geeignete Skript aus.
UpdateWindowsBuild                        = Sie verwenden Windows 11 Enterprise LTSC 2024 {0}.{1}. Unterstützt wird Windows 11 Enterprise LTSC 2024 {0}.{2} und höher. Führen Sie Windows Update aus und versuchen Sie es erneut.
CheckSophiaScriptPreset                   = Haben Sie alle Funktionen in der voreingestellten Datei {0} angepasst, bevor Sie Sophia Script for Windows ausführen?
ReinstallWindows                          = Installieren Sie Windows nur mit einem Original-ISO-Abbild neu.
CreatingRestorePoint                      = Ein Wiederherstellungspunkt wird erstellt...
UWPComponentsMissing                      = Die UWP-Komponente "{0}" fehlt.
DefenderComponentsMissing                 = Die Komponente "{0}" von Microsoft Defender fehlt.
DiagTrackServiceNotFound                  = Der Dienst "DiagTrackService" wurde nicht gefunden.
NoScheduledTasksFound                     = Keine geplanten Aufgaben zum Deaktivieren.
ScheduledTasks                            = Geplante Aufgaben
SearchHighlightsDisabled                  = Die Suchergebnisse sind auf der Startseite bereits ausgeblendet.
CustomStartMenuFound                      = Ein Startmenü eines Drittanbieters ist installiert.
InstallingApplication                     = {0} wird installiert...
NoWindowsFeaturesFound                    = Keine Windows-Funktionen zum Deaktivieren.
WindowsFeaturesTitle                      = Windows-Features
NoOptionalFeaturesFound                   = Keine optionalen Funktionen zum Deaktivieren.
NoSupportedNetworkAdaptersFound           = Keine Netzwerkadapter, die die Funktion "Computer kann dieses Gerät ausschalten, um Energie zu sparen" unterstützen.
LocationServicesDisabled                  = Netzwerkshellbefehle benötigen die Berechtigung für den Standortzugriff, um WLAN-Informationen abzurufen. Aktivieren Sie die Ortungsdienste auf der Seite Standort in den Einstellungen unter Datenschutz & Sicherheit.
OptionalFeaturesTitle                     = Optionale Features
UserShellFolderNotEmpty                   = Im Ordner "{0}" befinden sich noch Dateien. Verschieben Sie sie manuell an einen neuen Ort.
UserFolderLocationMove                    = Sie sollten den Speicherort des Benutzerordners nicht in das Stammverzeichnis des Laufwerks C ändern.
DriveSelect                               = Wählen Sie das Laufwerk aus, auf dem der Ordner "{0}" im Stammverzeichnis angelegt werden soll.
CurrentUserFolderLocation                 = Der aktuelle Speicherort des Ordners "{0}" lautet: "{1}".
FilesWontBeMoved                          = Die Dateien werden nicht verschoben.
UserFolderMoveSkipped                     = Sie haben vergessen, den Speicherort des Ordners "{0}" des Benutzers zu ändern.
FolderSelect                              = Wählen Sie einen Ordner aus
UserFolderRequest                         = Möchten Sie den Speicherort des Ordners "{0}" ändern?
UserDefaultFolder                         = Möchten Sie den Speicherort des Ordners "{0}" auf den Standardwert ändern?
ReservedStorageIsInUse                    = Der reservierte Speicher wird genutzt.
ProgramPathNotExists                      = Der Pfad "{0}" existiert nicht.
ProgIdNotExists                           = Die ProgId "{0}" existiert nicht.
AllFilesFilter                            = Alle Dateien
JSONNotValid                              = Die JSON-Datei "{0}" ist ungültig.
PackageNotInstalled                       = Die Anwendung "{0}" ist nicht installiert.
PackageIsInstalled                        = Die neueste Version von {0} ist bereits installiert.
UninstallUWPForAll                        = Für alle Benutzer
NoUWPAppsFound                            = Keine UWP-Apps zum Deinstallieren.
UWPAppsTitle                              = UWP-Apps
ScheduledTaskCreatedByAnotherUser         = Die geplante Aufgabe "{0}" wurde bereits vom Benutzer "{1}" erstellt.
CleanupTaskNotificationTitle              = Windows aufräumen
CleanupTaskNotificationEvent              = Aufgabe zum Bereinigen nicht verwendeter Windows-Dateien und -Updates ausführen?
CleanupTaskDescription                    = Bereinigen ungenutzter Windows-Dateien und -Updates mithilfe der integrierten Datenträgerbereinigungs-App.
CleanupNotificationTaskDescription        = Popup-Benachrichtigung zur Erinnerung an die Bereinigung von nicht verwendeten Windows-Dateien und Updates.
SoftwareDistributionTaskNotificationEvent = Der Windows Update-Cache wurde erfolgreich gelöscht.
SoftwareDistributionTaskDescription       = Windows Update-Cache-Ordner "{0}" wird bereinigt.
TempTaskNotificationEvent                 = Der Ordner mit den temporären Dateien wurde erfolgreich bereinigt.
TempTaskDescription                       = Aufräumen des temporären Ordners "{0}" (%TEMP%).
ScheduledTaskLoggedInUserNotification     = Die geplante Aufgabe kann nur ausgeführt werden, wenn der Benutzer "{0}" im System angemeldet ist.
ScheduledTaskCreatedNotification          = Die geplante Aufgabe "{0}" wurde erstellt.
CleanupTaskCLIDescription                 = Wechseln Sie im Taskplaner zum Ordner "Sophia" und führen Sie die Aufgabe "Windows Cleanup Notification" aus, um mit der Bereinigung nicht mehr benötigter Windows-Dateien und Updates zu beginnen.
SoftwareDistributionTaskCLIDescription    = Wechseln Sie im Taskplaner zum Ordner "Sophia" und führen Sie die Aufgabe "SoftwareDistribution" aus, um die Bereinigung des Windows-Update-Cache-Ordners "{0}" zu starten.
TempTaskCLIDescription                    = Wechseln Sie im Taskplaner zum Ordner "Sophia" und führen Sie die Aufgabe "Temp" aus, um die Bereinigung des Ordners für temporäre Dateien "{0}" (%TEMP%) zu starten.
EventViewerCustomViewName                 = Prozesserstellung
EventViewerCustomViewDescription          = Prozesserstellungen und Befehlszeilen-Auditing-Ereignisse.
ThirdPartyAVInstalled                     = Ein Antivirenprogramm eines Drittanbieters ist installiert.
EnableHardwareVT                          = Virtualisierung in UEFI aktivieren.
ThirdPartyArchiverInstalled               = Ein Archivierungsprogramm eines Drittanbieters ist installiert.
RestartWarning                            = Sicherstellen, dass Sie Ihren PC neu starten.
RestorePointVolume                        = Die Wiederherstellungspunkte für das Laufwerk C belegen {0} GB.
ErrorsLine                                = Zeile
ErrorsMessage                             = Fehler, Warnungen und Benachrichtigungen
Disable                                   = Deaktivieren
Enable                                    = Aktivieren
Install                                   = Installieren
Uninstall                                 = Deinstallieren
RestartFunction                           = Bitte die Funktion "{0}" neustarten.
NoConnectionEstablished                   = Verbindung zu {0} konnte nicht hergestellt werden.
Run                                       = Starten
FunctionSkipped                           = Funktion "{0}" übersprungen.
DonateToastTitle                          = Spenden sind willkommen!❤
DotSourcedFunction                        = Bitte "dot-source" die Funktion (mit einem Punkt am Anfang):\n. .\\Import-TabCompletion.ps1
'@
