ConvertFrom-StringData -StringData @'
UnsupportedArchitecture                   = Sie verwenden eine CPU mit "{0}"-basierter Architektur. Dieses Skript unterstützt nur CPUs mit x64-Architektur. Laden Sie die für Ihre Architektur geeignete Skriptversion herunter und führen Sie sie aus.
UnsupportedOSBuild                        = Das Skript unterstützt nur Windows 11 Enterprise LTSC 2024. Sie verwenden Windows {0} {1}. Aktualisieren Sie Ihr Windows und versuchen Sie es erneut.
UnsupportedWindowsTerminal                = Die Windows Terminal-Version ist niedriger als 1.23. Bitte aktualisieren Sie es im Microsoft Store und versuchen Sie es erneut.
UpdateWarning                             = Sie verwenden Windows 11 {0}.{1}. Unterstützt wird Windows 11 {0}.{2} und höher. Führen Sie Windows Update aus und versuchen Sie es erneut.
UnsupportedLanguageMode                   = Die PowerShell-Sitzung wird in einem eingeschränkten Sprachmodus ausgeführt.
LoggedInUserNotAdmin                      = Der angemeldete Benutzer {0} hat keine Administratorrechte. Das Skript wurde im Namen von {1} ausgeführt. Bitte melden Sie sich bei einem Konto mit Administratorrechten an und führen Sie das Skript erneut aus.
UnsupportedPowerShell                     = Sie versuchen ein Skript über PowerShell {0}.{1} auszuführen. Bitte führen Sie das Skript in PowerShell {2} aus.
CodeCompilationFailedWarning              = Die Code-Kompilierung ist fehlgeschlagen.
UnsupportedHost                           = Das Skript unterstützt keine Ausführung über {0}.
Win10TweakerWarning                       = Wahrscheinlich wurde Ihr Betriebssystem über die Win 10 Tweaker-Hintertür infiziert.
TweakerWarning                            = Die Stabilität des Windows-Betriebssystems kann durch die Verwendung des {0} beeinträchtigt worden sein. Installieren Sie Windows nur mit einem Original-ISO-Abbild neu.
HostsWarning                              = In der Datei %SystemRoot%\\System32\\drivers\\etc\\hosts wurden Einträge von Drittanbietern gefunden. Diese können die Verbindung zu den im Skript verwendeten Ressourcen blockieren. Möchten Sie fortfahren?
RebootPending                             = Ihr PC wartet darauf, neu gestartet zu werden.
BitLockerInOperation                      = Die BitLocker-Verschlüsselung wird gerade durchgeführt. Schließen Sie die BitLocker-Laufwerkskonfiguration ab und versuchen Sie es erneut.
BitLockerAutomaticEncryption              = Das Laufwerk C ist verschlüsselt, obwohl BitLocker deaktiviert ist. Möchten Sie Ihr Laufwerk entschlüsseln?
UnsupportedRelease                        = Eine neuere Version von Sophia Script gefunden: {0}. Bitte laden Sie die neueste Version herunter.
KeyboardArrows                            = Bitte verwenden Sie die Pfeiltasten {0} und {1} auf Ihrer Tastatur, um Ihre Antwort auszuwählen
CustomizationWarning                      = Haben Sie alle Funktionen in der voreingestellten Datei {0} angepasst, bevor Sie Sophia Script ausführen?
WindowsComponentBroken                    = {0} defekt oder aus dem Betriebssystem entfernt.
ControlledFolderAccessEnabledWarning      = Sie haben den kontrollierten Ordnerzugriff aktiviert. Bitte deaktivieren Sie ihn und führen Sie das Skript erneut aus.
NoScheduledTasks                          = Keine geplanten Aufgaben zum Deaktivieren.
ScheduledTasks                            = Geplante Aufgaben
SearchHighlightsDisabled                  = Die Such-Highlights sind bereits in Start ausgeblendet.
CustomStartMenu                           = Ein Startmenü eines Drittanbieters ist installiert.
InstallNotification                       = {0} wird installiert...
NoWindowsFeatures                         = Keine Windows-Funktionen zum Deaktivieren.
WindowsFeaturesTitle                      = Windows-Features
NoOptionalFeatures                        = Keine optionalen Funktionen zum Deaktivieren.
NoSupportedNetworkAdapters                = Keine Netzwerkadapter, die die Funktion "Computer kann dieses Gerät ausschalten, um Energie zu sparen" unterstützen.
OptionalFeaturesTitle                     = Optionale Features
EnableHardwareVT                          = Virtualisierung in UEFI aktivieren.
UserShellFolderNotEmpty                   = Im Ordner "{0}" befinden sich noch Dateien. Verschieben Sie sie manuell an einen neuen Ort.
UserFolderLocationMove                    = Sie sollten den Speicherort des Benutzerordners nicht in das Stammverzeichnis des Laufwerks C ändern.
DriveSelect                               = Wählen Sie das Laufwerk aus, in dessen Stammverzeichnis der Ordner "{0}" erstellt werden soll.
CurrentUserFolderLocation                 = Der aktuelle Speicherort des Ordners "{0}" lautet: "{1}".
FilesWontBeMoved                          = Die Dateien werden nicht verschoben.
FolderSelect                              = Wählen Sie einen Ordner aus
UserFolderRequest                         = Möchten Sie den Speicherort des Ordners "{0}" ändern?
UserDefaultFolder                         = Möchten Sie den Speicherort des Ordners "{0}" auf den Standardwert ändern?
ReservedStorageIsInUse                    = Reservierter Speicher wird verwendet.
ProgramPathNotExists                      = Der Pfad "{0}" existiert nicht.
ProgIdNotExists                           = Die ProgId "{0}" existiert nicht.
AllFilesFilter                            = Alle Dateien
JSONNotValid                              = Die JSON-Datei "{0}" ist ungültig.
PackageNotInstalled                       = Das {0} ist nicht installiert.
PackageIsInstalled                        = Die neueste Version von {0} ist bereits installiert.
UninstallUWPForAll                        = Für alle Benutzer
NoUWPApps                                 = Keine UWP-Apps zum Deinstallieren.
UWPAppsTitle                              = UWP-Apps
ScheduledTaskCreatedByAnotherUser         = Die geplante Aufgabe "{0}" wurde bereits vom Benutzer "{1}" erstellt.
CleanupTaskNotificationTitle              = Windows aufräumen
CleanupTaskNotificationEvent              = Aufgabe zum Bereinigen nicht verwendeter Windows-Dateien und -Updates ausführen?
CleanupTaskDescription                    = Bereinigung von nicht verwendeten Windows-Dateien und Updates mit der integrierten Festplattenbereinigung. Die geplante Aufgabe kann nur ausgeführt werden, wenn der Benutzer "{0}" im System angemeldet ist.
CleanupNotificationTaskDescription        = Popup-Benachrichtigung zur Erinnerung an die Bereinigung von nicht verwendeten Windows-Dateien und Updates. Die geplante Aufgabe kann nur ausgeführt werden, wenn der Benutzer "{0}" im System angemeldet ist.
SoftwareDistributionTaskNotificationEvent = Der Windows Update-Cache wurde erfolgreich gelöscht.
TempTaskNotificationEvent                 = Der Ordner mit den temporären Dateien wurde erfolgreich bereinigt.
FolderTaskDescription                     = Ordner "{0}" bereinigen. Die geplante Aufgabe kann nur ausgeführt werden, wenn der Benutzer "{1}" im System angemeldet ist.
EventViewerCustomViewName                 = Prozesserstellung
EventViewerCustomViewDescription          = Prozesserstellungen und Befehlszeilen-Auditing-Ereignisse.
ThirdPartyAVInstalled                     = Ein Antivirenprogramm eines Drittanbieters ist installiert.
GeoIdNotSupported                         = Die Funktion "{0}" gilt nur für Russland.
ThirdPartyArchiverInstalled               = Ein Archivierungsprogramm eines Drittanbieters ist installiert.
RestartWarning                            = Sicherstellen, dass Sie Ihren PC neu starten.
ErrorsLine                                = Zeile
ErrorsMessage                             = Fehler, Warnungen und Benachrichtigungen
Disable                                   = Deaktivieren
Enable                                    = Aktivieren
Install                                   = Installieren
Uninstall                                 = Deinstallieren
RestartFunction                           = Bitte die Funktion "{0}" neustarten.
NoResponse                                = Verbindung zu {0} konnte nicht hergestellt werden.
Run                                       = Starten
Skipped                                   = Funktion "{0}" übersprungen.
ThankfulToastTitle                        = Vielen Dank, dass Sie Sophia Script verwenden ❤️
DonateToastTitle                          = Sie können unten spenden 🕊
DotSourcedWarning                         = Bitte "dot-source" die Funktion (mit einem Punkt am Anfang):\n. .\\Import-TabCompletion.ps1
'@
