ConvertFrom-StringData -StringData @'
PowerShellImportFailed                    = Impossibile importare i moduli da PowerShell 5.1. Chiudere la console PowerShell 7 e rieseguire lo script.
UnsupportedOSBitness                      = Lo script supporta solo Windows a 64 bit.
UnsupportedOSBuild                        = Lo script supporta solo Windows 10 22H2. Stai utilizzando {0} {1}. Aggiornare Windows e riprovare.
UnsupportedWindowsTerminal                = La versione di Windows Terminal è inferiore a 1.23. Aggiornarla nel Microsoft Store e riprovare.
UpdateWarning                             = Windows 10 {0}.{1} rendszert használ. A támogatott verzió Windows 10 {0}.{2} vagy újabb. Futtassa a Windows Update programot, majd próbálja meg újra.
UnsupportedLanguageMode                   = La sessione PowerShell è in esecuzione in modalità lingua limitata.
LoggedInUserNotAdmin                      = L'utente connesso {0} non dispone dei diritti di amministratore. Lo script è stato eseguito per conto di {1}. Accedi a un account con diritti di amministratore ed esegui nuovamente lo script.
UnsupportedPowerShell                     = Stai cercando di eseguire lo script tramite PowerShell {0}.{1}. Eseguire lo script in PowerShell {2}.
CodeCompilationFailedWarning              = Compilazione del codice non riuscita.
UnsupportedHost                           = Lo script non supporta l'esecuzione tramite {0}.
Win10TweakerWarning                       = Probabilmente il tuo sistema operativo è stato infettato tramite una backdoor in Win 10 Tweaker.
TweakerWarning                            = La stabilità del sistema operativo Windows potrebbe essere stata compromessa dall'utilizzo dello {0}. Reinstallare Windows utilizzando solo un'immagine ISO autentica.
HostsWarning                              = Voci di terze parti trovate nel file %SystemRoot%\\System32\\drivers\\etc\\hosts. Potrebbero bloccare la connessione alle risorse utilizzate nello script. Vuoi continuare?
RebootPending                             = Il tuo PC è in attesa di essere riavviato.
BitLockerInOperation                      = BitLocker è in funzione. L'unità C è crittografata all'{0}%. Completa la configurazione dell'unità BitLocker e riprova.
BitLockerAutomaticEncryption              = L'unità C è crittografata, anche se BitLocker è disattivato. Vuoi decrittografare l'unità?
UnsupportedRelease                        = È stata trovata una versione più recente di Sophia Script for Windows: {0}. Scarica l'ultima versione.
KeyboardArrows                            = Per selezionare la risposta, utilizzare i tasti freccia "{0}" e "{1}" della tastiera
CustomizationWarning                      = Sono state personalizzate tutte le funzioni nel file di configurazione {0} prima di eseguire Sophia Script for Windows?
WindowsComponentBroken                    = {0} rimosso dal sistema. Reinstallare Windows utilizzando solo un'immagine ISO autentica.
MicroSoftStorePowerShellWarning           = PowerShell scaricato dal Microsoft Store non è supportato. Eseguire una versione MSI.
ControlledFolderAccessEnabledWarning      = Hai attivato il controllo dell'accesso alle cartelle. Disattivalo ed esegui nuovamente lo script.
NoScheduledTasks                          = Nessuna attività pianificata da disabilitare.
ScheduledTasks                            = Attività pianificate
TaskbarSmallIcons                         = Si utilizzano piccoli pulsanti sulla barra delle applicazioni.
SearchHighlightsDisabled                  = I risultati della ricerca sono già nascosti in Start.
CustomStartMenu                           = È installato un menu Start di terze parti.
OneDriveNotInstalled                      = OneDrive è già stato disinstallato.
OneDriveAccountWarning                    = Prima di disinstallare OneDrive, esci dal tuo account Microsoft in OneDrive.
OneDriveInstalled                         = OneDrive è già installato.
UninstallNotification                     = {0} è in fase di disinstallazione...
InstallNotification                       = {0} è in fase di installazione...
NoWindowsFeatures                         = Nessuna funzionalità di Windows da disattivare.
WindowsFeaturesTitle                      = Funzionalità di Windows
NoOptionalFeatures                        = Nessuna funzione opzionale da disattivare.
NoSupportedNetworkAdapters                = Nessuna scheda di rete che supporti la funzione "Consenti al computer di spegnere questo dispositivo per risparmiare energia".
LocationServicesDisabled                  = I comandi della shell di rete richiedono l'autorizzazione alla localizzazione per accedere alle informazioni WLAN. Attiva i servizi di localizzazione nella pagina Localizzazione delle impostazioni Privacy e sicurezza.
OptionalFeaturesTitle                     = Caratteristiche opzionali
UserShellFolderNotEmpty                   = Alcuni file rimasti nella cartella "{0}". Spostali manualmente in una nuova posizione.
UserFolderLocationMove                    = Non si dovrebbe modificare la posizione della cartella utente nella radice dell'unità C.
DriveSelect                               = Selezionare l'unità all'interno della radice del quale verrà creato la cartella "{0}".
CurrentUserFolderLocation                 = La posizione attuale della cartella "{0}": "{1}".
FilesWontBeMoved                          = I file non verranno spostati.
UserFolderMoveSkipped                     = Hai saltato la modifica della posizione della cartella "{0}" dell'utente.
FolderSelect                              = Seleziona una cartella
UserFolderRequest                         = Volete cambiare la posizione della cartella "{0}"?
UserDefaultFolder                         = Volete cambiare la posizione della cartella "{0}" al valore di default?
ReservedStorageIsInUse                    = È in uso lo spazio di archiviazione riservato.
ProgramPathNotExists                      = Il percorso "{0}" non esiste.
ProgIdNotExists                           = ProgId "{0}" non esiste.
AllFilesFilter                            = Tutti i file
JSONNotValid                              = Il file JSON "{0}" non è valido.
PackageNotInstalled                       = {0} non è installato.
PackageIsInstalled                        = L'ultima versione di {0} è già installata.
UninstallUWPForAll                        = Per tutti gli utenti
NoUWPApps                                 = Nessuna app UWP da disinstallare.
UWPAppsTitle                              = UWP Apps
ScheduledTaskCreatedByAnotherUser         = La funzione "{0}" è già stata creata come "{1}".
CleanupTaskNotificationTitle              = Pulizia di Windows
CleanupTaskNotificationEvent              = Eseguire l'operazione di pulizia dei file inutilizzati e aggiornamenti di Windows?
CleanupTaskDescription                    = Pulizia di Windows e dei file inutilizzati degli aggiornamenti utilizzando l'app built-in ""pulizia disco". L'attività pianificata può essere eseguita solo se l'utente "{0}" ha effettuato l'accesso al sistema.
CleanupNotificationTaskDescription        = Pop-up promemoria di pulizia dei file inutilizzati e degli aggiornamenti di Windows. L'attività pianificata può essere eseguita solo se l'utente "{0}" ha effettuato l'accesso al sistema.
SoftwareDistributionTaskNotificationEvent = La cache degli aggiornamenti di Windows cancellata con successo.
TempTaskNotificationEvent                 = I file cartella Temp puliti con successo.
FolderTaskDescription                     = Pulizia della cartella "{0}". L'attività pianificata può essere eseguita solo se l'utente "{0}" ha effettuato l'accesso al sistema.
EventViewerCustomViewName                 = Creazione del processo
EventViewerCustomViewDescription          = Creazione del processi e degli eventi di controllo della riga di comando.
ThirdPartyAVInstalled                     = È installato un antivirus di terze parti.
NoHomeWindowsEditionSupport               = Windows Home Edition non supporta la funzione "{0}".
GeoIdNotSupported                         = La funzione "{0}" è applicabile solo per la Russia.
EnableHardwareVT                          = Abilita virtualizzazione in UEFI.
PhotosNotInstalled                        = L'applicazione Foto non è installata.
HEVCInstalled                             = Estensioni video HEVC dal produttore del dispositivo è già installato.
HEVCInstallNotification                   = Estensioni video HEVC dal produttore del dispositivo è in fase di installazione...
ThirdPartyArchiverInstalled               = È installato un programma di archiviazione di terze parti.
gpeditNotSupported                        = Windows Home Edition non supporta lo snap-in Editor criteri di gruppo locali (gpedit.msc).
RestartWarning                            = Assicurati di riavviare il PC.
ErrorsLine                                = Linea
ErrorsMessage                             = Errori, avvisi e notifiche
Disable                                   = Disattivare
Enable                                    = Abilitare
Install                                   = Installare
Uninstall                                 = Disinstallare
RestartFunction                           = Si prega di riavviare la funzione "{0}".
NoResponse                                = Non è stato possibile stabilire una connessione con {0}.
Run                                       = Eseguire
Skipped                                   = Funzione "{0}" saltata.
ThankfulToastTitle                        = Grazie per aver utilizzato Sophia Script for Windows ❤️
DonateToastTitle                          = Puoi effettuare una donazione qui sotto 🕊
DotSourcedWarning                         = Si prega di "dot-source" la funzione (con un punto all'inizio):\n. .\\Import-TabCompletion.ps1
'@
