ConvertFrom-StringData -StringData @'
UnsupportedArchitecture                   = Korzystasz z procesora opartego na architekturze "{0}". Ten skrypt obsługuje wyłącznie procesory oparte na architekturze x64. Pobierz i uruchom wersję skryptu odpowiednią dla swojej architektury.
NewSophiaScriptFound                      = Dostępna jest nowa wersja: Sophia Script for Windows {0}. Prosimy o aktualizację.
UnsupportedPowerShell                     = Próbujesz uruchomić skrypt przy użyciu PowerShell {0}.{1}. Uruchom skrypt w PowerShell {2}.
CodeCompilationFailed                     = Kompilacja kodu nie powiodła się.
MicrosoftStorePowerShellWarning           = PowerShell pobrany ze sklepu Microsoft Store nie jest obsługiwany. Należy uruchomić wersję MSI.
PowerShellImportFailed                    = Importowanie modułów z programu PowerShell 5.1 nie powiodło się. Zamknij konsolę programu PowerShell 7 i uruchom ponownie skrypt.
KeyboardArrows                            = Użyj klawiszy strzałek {0} i {1} na klawiaturze, aby wybrać odpowiedź
UnsupportedLanguageMode                   = Sesja PowerShell działa w trybie ograniczonego języka.
LoggedInUserNotAdmin                      = Zalogowany użytkownik "{0}" nie ma uprawnień administratora. Skrypt został uruchomiony w imieniu "{1}". Zaloguj się na konto z uprawnieniami administratora i uruchom skrypt ponownie.
UnsupportedHost                           = Skrypt nie może być uruchamiany w {0}.
HarmfulTweakerFound                       = Stabilność systemu Windows mogła zostać naruszona przez użycie {0}.
HostsEntriesFound                         = W pliku %SystemRoot%\\System32\\drivers\\etc\\hosts znaleziono wpisy stron trzecich. Mogą one blokować połączenie z zasobami używanymi w skrypcie. Czy chcesz kontynuować?
WindowsComponentStabilityDisrupted        = W komponencie "{0}" wykryto problem związany z niestabilnością.
DisableControlledFolderAccess             = Włączono kontrolę dostępu do folderów. Proszę ją wyłączyć i ponownie uruchomić skrypt.
RebootPending                             = Twój komputer czeka na ponowne uruchomienie.
SystemDriveEncryptedBitLockerDisabled     = Dysk C jest zaszyfrowany, mimo że funkcja BitLocker jest wyłączona. Czy chcesz odszyfrować dysk?
UpdateUEFICertificates                    = Certyfikat Secure Boot "Microsoft Windows Production PCA 2011" traci ważność w 2026 roku. Twoje urządzenie nie otrzymało jeszcze zaktualizowanych certyfikatów "Windows UEFI CA 2023". Czy chcesz ręcznie zainstalować certyfikaty "Microsoft Windows UEFI CA 2023"?
UpdateWindowsTerminal                     = Wersja Windows Terminal jest niższa niż 1.23. Zaktualizuj ją w Microsoft Store i spróbuj ponownie.
WrongSophiaScriptVersion                  = Skrypt obsługuje tylko system Windows 10 Enterprise LTSC 2021. Używasz systemu {0} {1}. Uruchom odpowiedni skrypt w zależności od wersji systemu Windows.
UpdateWindowsBuild                        = Windows 11 Enterprise LTSC 2024 {0}.{1} rendszert használ. A támogatott verzió Windows 11 Enterprise LTSC 2024 {0}.{2} vagy újabb. Futtassa a Windows Update programot, majd próbálja meg újra.
CheckSophiaScriptPreset                   = Czy dostosowałeś funkcje w predefiniowanym pliku {0} przed uruchomieniem Sophia Script for Windows?
ReinstallWindows                          = Zainstaluj ponownie system Windows, używając tylko oryginalnego obrazu ISO.
CreatingRestorePoint                      = Tworzony jest punkt przywracania...
UWPComponentsMissing                      = Brakuje komponentu UWP "{0}".
DefenderComponentsMissing                 = Brakuje komponentu "{0}" programu Microsoft Defender.
DiagTrackServiceNotFound                  = Nie znaleziono usługi "DiagTrackService".
NoScheduledTasksFound                     = Brak zaplanowanych zadań do wyłączenia.
ScheduledTasks                            = Zaplanowane zadania
SearchHighlightsDisabled                  = Najważniejsze wyniki wyszukiwania są już ukryte w menu Start.
CustomStartMenuFound                      = Zainstalowano menu Start innej firmy.
InstallingApplication                     = Trwa instalacja usługi {0}...
NoWindowsFeaturesFound                    = Nincs letiltandó Windows-funkció.
WindowsFeaturesTitle                      = Funkcje Windows
NoOptionalFeaturesFound                   = Nincs letiltható opcionális funkció.
NoSupportedNetworkAdaptersFound           = Brak kart sieciowych obsługujących funkcję "Zezwól komputerowi na wyłączenie tego urządzenia w celu oszczędzania energii".
LocationServicesDisabled                  = Polecenia powłoki sieciowej wymagają uprawnień lokalizacyjnych, aby uzyskać dostęp do informacji o sieci WLAN. Włącz usługi lokalizacyjne na stronie Lokalizacja w ustawieniach prywatności i bezpieczeństwa.
OptionalFeaturesTitle                     = Funkcje opcjonalne
UserShellFolderNotEmpty                   = Niektóre pliki pozostały w folderze "{0}". Przenieś je ręcznie w nowe miejsce.
UserFolderLocationMove                    = Nie należy zmieniać lokalizacji folderu użytkownika na katalog główny dysku C.
DriveSelect                               = Wybierz dysk, na którym w katalogu głównym zostanie utworzony folder "{0}".
CurrentUserFolderLocation                 = Lokalizacja folderu "{0}": "{1}".
FilesWontBeMoved                          = Pliki nie zostaną przeniesione.
UserFolderMoveSkipped                     = Pominąłeś zmianę lokalizacji folderu użytkownika "{0}".
FolderSelect                              = Wybierz folder
UserFolderRequest                         = Czy chcesz zmienić lokalizację folderu "{0}"?
UserDefaultFolder                         = Czy chcesz zmienić lokalizację folderu "{0}" na wartość domyślną?
ReservedStorageIsInUse                    = Lo spazio di archiviazione riservato è in uso.
ProgramPathNotExists                      = Ścieżka "{0}" nie istnieje.
ProgIdNotExists                           = ProgId "{0}" nie istnieje.
AllFilesFilter                            = Wszystkie pliki
JSONNotValid                              = Plik JSON "{0}" jest nieprawidłowy.
PackageNotInstalled                       = Aplikacja "{0}" nie jest zainstalowana.
PackageIsInstalled                        = Najnowsza wersja {0} jest już zainstalowana.
UninstallUWPForAll                        = Dla wszystkich użytkowników
NoUWPAppsFound                            = Brak aplikacji UWP do odinstalowania.
UWPAppsTitle                              = Aplikacje UWP
ScheduledTaskCreatedByAnotherUser         = Zaplanowane zadanie "{0}" zostało już utworzone przez użytkownika "{1}".
CleanupTaskNotificationTitle              = Oczyszczanie system Windows
CleanupTaskNotificationEvent              = Uruchomić zadanie w celu usunięcia nieużywanych plików i aktualizacji systemu Windows?
CleanupTaskDescription                    = Czyszczenie nieużywanych plików i aktualizacji systemu Windows za pomocą wbudowanej aplikacji do czyszczenia dysku.
CleanupNotificationTaskDescription        = Powiadomienie przypominające o czyszczeniu nieużywanych plików i aktualizacji systemu Windows.
SoftwareDistributionTaskNotificationEvent = Pomyślnie usunięto pamięć podręczną aktualizacji systemu Windows.
SoftwareDistributionTaskDescription       = Czyszczenie folderu pamięci podręcznej aktualizacji systemu Windows "{0}".
TempTaskNotificationEvent                 = Folder plików tymczasowych został pomyślnie wyczyszczony.
TempTaskDescription                       = Czyszczenie folderu tymczasowego "{0}" (%TEMP%).
ScheduledTaskLoggedInUserNotification     = Zaplanowane zadanie może zostać uruchomione tylko wtedy, gdy użytkownik "{0}" jest zalogowany do systemu.
ScheduledTaskCreatedNotification          = Utworzono zaplanowane zadanie "{0}".
CleanupTaskCLIDescription                 = Przejdź do folderu "Sophia" w Task Scheduler i uruchom zadanie "Windows Cleanup Notification", aby rozpocząć czyszczenie nieużywanych plików i aktualizacji systemu Windows.
SoftwareDistributionTaskCLIDescription    = Przejdź do folderu "Sophia" w Task Scheduler i uruchom zadanie "SoftwareDistribution", aby rozpocząć czyszczenie folderu pamięci podręcznej aktualizacji systemu Windows "{0}". 
TempTaskCLIDescription                    = Przejdź do folderu "Sophia" w Task Scheduler i uruchom zadanie "Temp", aby rozpocząć czyszczenie folderu plików tymczasowych "{0}" (%TEMP%).
EventViewerCustomViewName                 = Tworzenie procesu
EventViewerCustomViewDescription          = Tworzenie procesu i zdarzeń audytu.
ThirdPartyAVInstalled                     = Zainstalowano program antywirusowy innej firmy.
EnableHardwareVT                          = Włącz wirtualizację w UEFI.
ThirdPartyArchiverInstalled               = Zainstalowano archiwizator innej firmy.
RestartWarning                            = Pamiętaj o ponownym uruchomieniu komputera.
RestorePointVolume                        = Punkty przywracania dla dysku C zajmują {0} GB.
ErrorsLine                                = Linia
ErrorsMessage                             = Błędy, ostrzeżenia i powiadomienia
Disable                                   = Wyłączyć
Enable                                    = Włączać
Install                                   = Zainstalluj
Uninstall                                 = Odinstaluj
RestartFunction                           = Uruchom ponownie funkcję "{0}".
NoConnectionEstablished                   = Nie można nawiązać połączenia z {0}.
Run                                       = Uruchom
FunctionSkipped                           = Funkcja "{0}" pominięta.
DonateToastTitle                          = Darowizny są mile widziane!❤
DotSourcedFunction                        = Prosimy o "dot-source" funkcji (z kropką na początku):\n. .\\Import-TabCompletion.ps1
'@
