ConvertFrom-StringData -StringData @'
NewSophiaScriptFound                      = È disponibile una nuova versione: Sophia Script for Windows {0}. Si prega di effettuare l'aggiornamento.
UnsupportedPowerShell                     = Stai cercando di eseguire lo script tramite PowerShell {0}.{1}. Eseguire lo script in PowerShell {2}.
CodeCompilationFailed                     = Compilazione del codice non riuscita.
UnsupportedWindowsBitness                 = Lo script supporta solo Windows a 64 bit.
KeyboardArrows                            = Per selezionare la risposta, utilizzare i tasti freccia "{0}" e "{1}" della tastiera
UnsupportedLanguageMode                   = La sessione PowerShell è in esecuzione in modalità lingua limitata.
LoggedInUserNotAdmin                      = L'utente connesso "{0}" non dispone dei diritti di amministratore. Lo script è stato eseguito per conto di "{1}". Accedi a un account con diritti di amministratore ed esegui nuovamente lo script.
UnsupportedHost                           = Lo script non supporta l'esecuzione tramite {0}.
HarmfulTweakerFound                       = La stabilità del sistema operativo Windows potrebbe essere stata compromessa dall'utilizzo dello {0}.
HostsEntriesFound                         = Voci di terze parti trovate nel file %SystemRoot%\\System32\\drivers\\etc\\hosts.
WindowsComponentStabilityDisrupted        = È stato rilevato un problema di instabilità nel componente "{0}".
DisableControlledFolderAccess             = Hai attivato il controllo dell'accesso alle cartelle. Disattivalo ed esegui nuovamente lo script.
RebootPending                             = Il tuo PC è in attesa di essere riavviato.
SystemDriveEncryptedBitLockerDisabled     = L'unità C è crittografata, anche se BitLocker è disattivato. Vuoi decrittografare l'unità?
WrongSophiaScriptVersion                  = Lo script supporta solo Windows 10 22H2. Stai utilizzando {0} {1}. Esegui lo script corretto in base alla versione di Windows.
UpdateWindowsBuild                        = Windows 10 {0}.{1} rendszert használ. A támogatott verzió Windows 10 {0}.{2} vagy újabb. Futtassa a Windows Update programot, majd próbálja meg újra.
ESUProgramEnrollment                      = Il supporto per Windows 10 è scaduto il 14 ottobre 2025. Il tuo PC potrebbe essere esposto a software dannoso, trojan e vulnerabilità zero-day. Desideri iscriverti al programma Consumer Extended Security Updates (ESU) per ricevere aggiornamenti fino al 2028 utilizzando TSforge di Microsoft Activation Scripts (MAS)?
CheckSophiaScriptPreset                   = Sono state personalizzate tutte le funzioni nel file di configurazione {0} prima di eseguire Sophia Script for Windows?
ReinstallWindows                          = Reinstallare Windows utilizzando solo un'immagine ISO autentica.
CreatingRestorePoint                      = Si sta creando un punto di ripristino...
UWPComponentsMissing                      = Manca il componente UWP "{0}".
DefenderComponentsMissing                 = Manca il componente "{0}" di Microsoft Defender.
DiagTrackServiceNotFound                  = Il servizio "DiagTrackService" non è stato trovato.
NoScheduledTasksFound                     = Nessuna attività pianificata da disabilitare.
ScheduledTasks                            = Attività pianificate
TaskbarSmallIcons                         = Si utilizzano piccoli pulsanti sulla barra delle applicazioni.
SearchHighlightsDisabled                  = I risultati in evidenza della ricerca sono già nascosti nella schermata Start.
CustomStartMenuFound                      = È installato un menu Start di terze parti.
OneDriveNotInstalled                      = OneDrive è già stato disinstallato.
OneDriveAccountUsageFound                 = Prima di disinstallare OneDrive, esci dal tuo account Microsoft in OneDrive.
OneDriveInstalled                         = OneDrive è già installato.
UninstallingApplication                   = {0} è in fase di disinstallazione...
InstallingApplication                     = {0} è in fase di installazione...
NoWindowsFeaturesFound                    = Nessuna funzionalità di Windows da disattivare.
WindowsFeaturesTitle                      = Funzionalità di Windows
NoOptionalFeaturesFound                   = Nessuna funzione opzionale da disattivare.
NoSupportedNetworkAdaptersFound           = Nessuna scheda di rete che supporti la funzione "Consenti al computer di spegnere questo dispositivo per risparmiare energia".
LocationServicesDisabled                  = I comandi della shell di rete richiedono l'autorizzazione alla localizzazione per accedere alle informazioni WLAN. Attiva i servizi di localizzazione nella pagina Localizzazione delle impostazioni Privacy e sicurezza.
OptionalFeaturesTitle                     = Caratteristiche opzionali
UserShellFolderNotEmpty                   = Alcuni file rimasti nella cartella "{0}". Spostali manualmente in una nuova posizione.
UserFolderLocationMove                    = Non si dovrebbe modificare la posizione della cartella utente nella radice dell'unità C.
DriveSelect                               = Selezionare l'unità in cui verrà creata la cartella “{0}” nella directory principale.
CurrentUserFolderLocation                 = La posizione attuale della cartella "{0}": "{1}".
FilesWontBeMoved                          = I file non verranno spostati.
UserFolderMoveSkipped                     = Hai saltato la modifica della posizione della cartella "{0}" dell'utente.
FolderSelect                              = Seleziona una cartella
UserFolderRequest                         = Volete cambiare la posizione della cartella "{0}"?
UserDefaultFolder                         = Volete cambiare la posizione della cartella "{0}" al valore di default?
ReservedStorageIsInUse                    = Lo spazio di archiviazione riservato è in uso.
ProgramPathNotExists                      = Il percorso "{0}" non esiste.
ProgIdNotExists                           = ProgId "{0}" non esiste.
AllFilesFilter                            = Tutti i file
JSONNotValid                              = Il file JSON "{0}" non è valido.
PackageNotInstalled                       = L'applicazione "{0}" non è installata.
PackageIsInstalled                        = L'ultima versione di {0} è già installata.
UninstallUWPForAll                        = Per tutti gli utenti
NoUWPAppsFound                            = Nessuna app UWP da disinstallare.
UWPAppsTitle                              = UWP Apps
ScheduledTaskCreatedByAnotherUser         = La funzione "{0}" è già stata creata come "{1}".
CleanupTaskNotificationTitle              = Pulizia di Windows
CleanupTaskNotificationEvent              = Eseguire l'operazione di pulizia dei file inutilizzati e aggiornamenti di Windows?
CleanupTaskDescription                    = Pulizia dei file e degli aggiornamenti inutilizzati di Windows utilizzando l'app di pulizia del disco integrata.
CleanupNotificationTaskDescription        = Pop-up promemoria di pulizia dei file inutilizzati e degli aggiornamenti di Windows.
SoftwareDistributionTaskNotificationEvent = La cache degli aggiornamenti di Windows cancellata con successo.
SoftwareDistributionTaskDescription       = Pulizia della cartella della cache di Windows Update "{0}".
TempTaskNotificationEvent                 = I file cartella Temp puliti con successo.
TempTaskDescription                       = Pulizia della cartella temporanea "{0}" (%TEMP%)
ScheduledTaskLoggedInUserNotification     = L'attività pianificata può essere eseguita solo se l'utente "{0}" ha effettuato l'accesso al sistema.
ScheduledTaskCreatedNotification          = È stata creata l'attività pianificata "{0}".
CleanupTaskCLIDescription                 = Vai alla cartella "Sophia" in Task Scheduler ed esegui l'operazione "Windows Cleanup Notification" per avviare la pulizia dei file inutilizzati e degli aggiornamenti di Windows.
SoftwareDistributionTaskCLIDescription    = Vai alla cartella "Sophia" in Task Scheduler ed esegui l'operazione "SoftwareDistribution" per avviare la pulizia della cartella della cache di Windows Update "{0}". 
TempTaskCLIDescription                    = Vai alla cartella "Sophia" in Task Scheduler ed esegui l'operazione "Temp" per avviare la pulizia della cartella dei file temporanei "{0}" (%TEMP%).
EventViewerCustomViewName                 = Creazione del processo
EventViewerCustomViewDescription          = Creazione del processi e degli eventi di controllo della riga di comando.
ThirdPartyAVInstalled                     = È installato un antivirus di terze parti.
NoHomeWindowsEditionSupport               = Windows Home Edition non supporta la funzione "{0}".
EnableHardwareVT                          = Abilita virtualizzazione in UEFI.
PhotosNotInstalled                        = L'applicazione "Foto" non è installata.
HEVCInstalled                             = Estensioni video HEVC dal produttore del dispositivo è già installato.
HEVCInstallingApplication                 = Estensioni video HEVC dal produttore del dispositivo è in fase di installazione...
ThirdPartyArchiverInstalled               = È installato un programma di archiviazione di terze parti.
gpeditNotSupported                        = Windows Home Edition non supporta lo snap-in Editor criteri di gruppo locali (gpedit.msc).
RestartWarning                            = Assicurati di riavviare il PC.
RestorePointVolume                        = I punti di ripristino dell'unità C occupano {0} GB.
ErrorsLine                                = Linea
ErrorsMessage                             = Errori, avvisi e notifiche
Disable                                   = Disattivare
Enable                                    = Abilitare
Install                                   = Installare
Uninstall                                 = Disinstallare
RestartFunction                           = Si prega di riavviare la funzione "{0}".
NoConnectionEstablished                   = Non è stato possibile stabilire una connessione con {0}.
Run                                       = Eseguire
FunctionSkipped                           = Funzione "{0}" saltata.
DonateToastTitle                          = Le donazioni sono benvenute!❤
DotSourcedFunction                        = Si prega di "dot-source" la funzione (con un punto all'inizio):\n. .\\Import-TabCompletion.ps1
'@
