ConvertFrom-StringData -StringData @'
NewSophiaScriptFound                      = Está disponível uma nova versão: Sophia Script for Windows {0}. Por favor, atualize.
UnsupportedPowerShell                     = Você está tentando executar o script via PowerShell {0}.{1}. Execute o script no PowerShell {2}.
CodeCompilationFailed                     = Falha na compilação do código.
MicrosoftStorePowerShellWarning           = Não há suporte para o PowerShell baixado da Microsoft Store. Execute uma versão MSI.
PowerShellImportFailed                    = Falha ao importar módulos do PowerShell 5.1. Feche o console do PowerShell 7 e execute o script novamente.
UnsupportedWindowsBitness                 = O script suporta apenas Windows de 64 bits.
KeyboardArrows                            = Use as teclas de seta {0} e {1} do teclado para selecionar sua resposta
UnsupportedLanguageMode                   = A sessão do PowerShell está sendo executada em um modo de linguagem limitada.
LoggedInUserNotAdmin                      = O usuário conectado "{0}" não possui direitos de administrador. O script foi executado em nome de "{1}". Faça login em uma conta com direitos de administrador e execute o script novamente.
UnsupportedHost                           = O script não suporta a execução por meio do {0}.
HarmfulTweakerFound                       = A estabilidade do sistema operacional Windows pode ter sido comprometida pela utilização do {0}.
HostsEntriesFound                         = Entradas de terceiros encontradas no arquivo %SystemRoot%\\System32\\drivers\\etc\\hosts. Elas podem bloquear a conexão com recursos usados no script. Deseja continuar?
UWPComponentsMissing                      = O componente UWP "{0}" está faltando.
DefenderComponentsMissing                 = O componente "{0}" do Microsoft Defender está faltando.
WindowsComponentStabilityDisrupted        = Foi detectado um problema de instabilidade no componente "{0}".
DisableControlledFolderAccess             = Você tem o acesso controlado a pastas ativado. Desative-o e execute o script novamente.
RebootPending                             = Seu computador está aguardando para ser reiniciado.
SystemDriveEncryptedBitLockerDisabled     = A unidade C está criptografada, embora o BitLocker esteja desativado. Deseja descriptografar sua unidade?
WrongSophiaScriptVersion                  = O script é compatível apenas com o Windows 10 22H2. Você está usando o {0} {1}. Execute o script correto de acordo com a edição do Windows.
UpdateWindowsBuild                        = O script é compatível com o Windows 10 22H2 {0}.{1} e versões posteriores. Você está usando o {2} {3} {4}.{5}. Execute o Windows Update e tente novamente.
ESUProgramEnrollment                      = O Windows 10 chegou ao fim do suporte em 14 de outubro de 2025. Seu PC pode estar vulnerável a softwares maliciosos, trojans e vulnerabilidades de dia zero. Deseja se inscrever no programa de Atualizações de Segurança Estendidas para Consumidores (ESU) para receber atualizações até 2028 usando o TSforge do Microsoft Activation Scripts (MAS)?
AskQuestion                               = Caso tenha alguma dúvida, abra uma issue no GitHub ou pergunte à comunidade.
CheckSophiaScriptPreset                   = Você personalizou todas as funções no arquivo de predefinição {0} antes de executar o Sophia Script for Windows?
ReinstallWindows                          = Reinstale o Windows usando apenas uma imagem ISO genuína.
CreatingRestorePoint                      = O ponto de restauração está sendo criado...
WindowsServiceNotFound                    = O serviço "{0}" não foi encontrado.
NoScheduledTasksFound                     = Nenhuma tarefa agendada foi encontrada.
ScheduledTasks                            = Tarefas agendadas
BingSearchDisabled                        = A pesquisa na Web já está desativada no menu Iniciar.
TaskbarSmallIcons                         = Você usa botões pequenos na barra de tarefas.
SearchHighlightsDisabled                  = Os destaques da pesquisa já estão ocultos no Início.
CustomStartMenuFound                      = Um Menu Iniciar de terceiros está instalado.
OneDriveNotInstalled                      = O OneDrive já está desinstalado.
OneDriveAccountUsageFound                 = Antes de desinstalar o OneDrive, saia da sua conta da Microsoft no OneDrive.
OneDriveInstalled                         = O OneDrive já está instalado.
UninstallingApplication                   = O {0} está sendo desinstalado...
InstallingApplication                     = O {0} está sendo instalado...
NoWindowsFeaturesFound                    = Nenhum recurso do Windows foi encontrado.
WindowsFeaturesTitle                      = Recursos do Windows
NoOptionalFeaturesFound                   = Nenhum recurso opcional foi encontrado.
OptionalFeaturesTitle                     = Recursos opcionais
NoSupportedNetworkAdaptersFound           = Nenhum adaptador de rede compatível com a função "Permitir que o computador desligue este dispositivo para economizar energia" foi encontrado.
LocationServicesDisabled                  = Os comandos do shell de rede precisam de permissão de localização para acessar as informações da WLAN. Ative os serviços de localização na página Localização nas configurações de Privacidade e segurança.
UserFolderLocationMove                    = Você não deve alterar o local da pasta do usuário para a raiz da unidade C.
DriveSelect                               = Selecione a unidade na qual a pasta "{0}" será criada no diretório raiz.
CurrentUserFolderLocation                 = A localização atual da pasta "{0}": "{1}".
FilesWontBeMoved                          = Os arquivos não serão movidos.
UserFolderMoveSkipped                     = Você não alterou a localização da pasta "{0}" do usuário.
UserShellFolderNotEmpty                   = Alguns arquivos permaneceram na pasta "{0}". Mova-os manualmente para o novo local.
FolderSelect                              = Selecione uma pasta
UserFolderRequest                         = Gostaria de alterar a localização da pasta "{0}"?
UserDefaultFolder                         = Gostaria de alterar a localização da pasta "{0}" para o valor padrão?
ReservedStorageIsInUse                    = O espaço de armazenamento reservado está em uso.
ProgramPathNotExists                      = O caminho "{0}" não existe.
ProgIdNotExists                           = O ProgId "{0}" não existe.
AllFilesFilter                            = Todos os arquivos
JSONNotValid                              = O arquivo JSON "{0}" não é válido.
PackageNotInstalled                       = O aplicativo "{0}" não está instalado.
PackageIsInstalled                        = A versão mais recente do {0} já está instalada.
UWPAppsTitle                              = Apps UWP
UninstallUWPForAll                        = Para todos os usuários
NoUWPAppsFound                            = Não há aplicativos UWP para desinstalar.
WDDMVersionUnsupported                    = A versão mínima suportada do WDDM é a 2.7. A versão atual do WDDM é a {0}.
CleanupTaskNotificationTitle              = Limpeza do Windows
CleanupTaskNotificationEvent              = Executar tarefa para limpar arquivos e atualizações não utilizados do Windows?
CleanupTaskDescription                    = Limpeza de arquivos e atualizações não utilizados do Windows usando o aplicativo interno Limpeza de Disco.
CleanupNotificationTaskDescription        = Notificação pop-up com lembrete sobre a limpeza de arquivos e atualizações não utilizados do Windows.
SoftwareDistributionTaskNotificationEvent = O cache de atualizações do Windows foi excluído com sucesso.
SoftwareDistributionTaskDescription       = Limpeza da pasta de cache de atualizações do Windows "{0}".
TempTaskNotificationEvent                 = A pasta temporária foi limpa com sucesso.
TempTaskDescription                       = Limpeza da pasta temporária "{0}" (%TEMP%).
ScheduledTaskLoggedInUserNotification     = A tarefa agendada só pode ser executada se o usuário "{0}" estiver conectado ao sistema.
CleanupTaskCLIDescription                 = A tarefa agendada "Sophia\\Windows Cleanup Notification" foi criada no Agendador de Tarefas para limpar arquivos e atualizações não utilizados do Windows.
SoftwareDistributionTaskCLIDescription    = A tarefa agendada "Sophia\\SoftwareDistribution" foi criada no Agendador de Tarefas para limpar a pasta de cache de atualizações do Windows "{0}".
TempTaskCLIDescription                    = A tarefa agendada "Sophia\\Temp" foi criada no Agendador de Tarefas para limpar a pasta temporária "{0}" (%TEMP%).
EventViewerCustomViewName                 = Criação de processo
EventViewerCustomViewDescription          = Rastreamento dos processos iniciados e da atividade do PowerShell
EventViewerCustomViewNotification         = O modo de exibição personalizado "Modos de Exibição Personalizados\\{0}" foi criado no Visualizador de Eventos para rastrear os processos iniciados e a atividade do PowerShell.
ThirdPartyAVInstalled                     = Um antivírus de terceiros está instalado.
NoHomeWindowsEditionSupport               = A edição Windows Home não suporta a função "{0}".
EnableHardwareVT                          = Ative a virtualização no UEFI.
PhotosNotInstalled                        = O aplicativo "Fotos" não está instalado.
HEVCInstalled                             = As Extensões de Vídeo HEVC do fabricante do dispositivo já estão instaladas.
HEVCInstallingApplication                 = As Extensões de Vídeo HEVC do fabricante do dispositivo estão sendo instaladas...
ThirdPartyArchiverInstalled               = Um arquivador de terceiros está instalado.
gpeditNotSupported                        = A edição Windows Home não suporta o snap-in Editor de Política de Grupo Local (gpedit.msc).
RestartWarning                            = Certifique-se de reiniciar o PC.
RestorePointVolume                        = Os pontos de restauração da unidade C ocupam {0} GB.
ErrorsLine                                = Linha
ErrorsMessage                             = Erros, avisos e notificações
Disable                                   = Desativar
Enable                                    = Ativar
Install                                   = Instalar
Uninstall                                 = Desinstalar
RestartFunction                           = Execute a função "{0}" novamente.
NoConnectionEstablished                   = Uma conexão não pôde ser estabelecida com {0}.
Run                                       = Executar
FunctionSkipped                           = A função "{0}" foi ignorada.
DonateToastTitle                          = Doações são bem-vindas! ❤
DotSourceFunction                         = Faça o "dot-source" da função (com um ponto no início):\n. .\\Import-TabCompletion.ps1
'@
