ConvertFrom-StringData -StringData @'
PowerShellImportFailed                    = Импорт моделей из PowerShell 5.1 завершился ошибкой. Пожалуйста, закройте PowerShell 7 и запустите скрипт заново.
UnsupportedOSBitness                      = Скрипт поддерживает только 64-битную версию Windows.
UnsupportedOSBuild                        = Скрипт поддерживает только Windows 10 22H2. Вы используете {0} {1}. Обновите Windows и повторите попытку.
UnsupportedWindowsTerminal                = Версия Windows Terminal ниже 1.23. Пожалуйста, обновите его в Microsoft Store и повторите попытку.
UpdateWarning                             = Вы используете Windows 10 {0}.{1}. Поддерживаемые сборки: Windows 10 {0}.{2} и выше. Запустите обновление Windows и повторите попытку.
UnsupportedLanguageMode                   = Сессия PowerShell работает в ограниченном режиме.
LoggedInUserNotAdmin                      = Вошедший пользователь {0} не обладает правами администратора. Скрипт был запущен от имени {1}. Пожалуйста, войдите в профиль, обладающий правами администратора и запустите скрипт заново.
UnsupportedPowerShell                     = Вы пытаетесь запустить скрипт в PowerShell {0}.{1}. Запустите скрипт в PowerShell {2}.
CodeCompilationFailedWarning              = Компиляция кода завершилась с ошибкой.
UnsupportedHost                           = Скрипт не поддерживает работу через {0}.
Win10TweakerWarning                       = Windows была заражена трояном через бэкдор в Win 10 Tweaker. Переустановите Windows, используя только подлинный ISO-образ.
TweakerWarning                            = Стабильность Windows могла быть нарушена использованием {0}. Переустановите Windows, используя только подлинный ISO-образ.
HostsWarning                              = В файле %SystemRoot%\\System32\\drivers\\etc\\hosts обнаружены сторонние записи. Они могут блокировать соединение с ресурсами, используемыми в работе скрипта. Хотите продолжить?
RebootPending                             = Ваш компьютер ожидает перезагрузки.
BitLockerInOperation                      = Выполняется шифрование BitLocker. Завершите настройку BitLocker для диска и повторите попытку.
BitLockerAutomaticEncryption              = Диск C зашифрован, хотя BitLocker отключен. Хотите расшифровать диск?
UnsupportedRelease                        = Обнаружена новая версия Sophia Script: {0}. Пожалуйста, скачайте последнюю версию.
KeyboardArrows                            = Для выбора используйте на клавиатуре стрелки {0} и {1}
CustomizationWarning                      = Вы настроили все функции в пресет-файле {0} перед запуском Sophia Script?
WindowsComponentBroken                    = {0} сломан или удален из ОС. Переустановите Windows, используя только подлинный ISO-образ.
MicroSoftStorePowerShellWarning           = PowerShell, скачанный из Microsoft Store, не поддерживается. Пожалуйста, запустите MSI-версию.
ControlledFolderAccessEnabledWarning      = У вас включен контролируемый доступ. Пожалуйста, отключите его и повторите попытку.
NoScheduledTasks                          = Нет запланированных задач, которые необходимо отключить.
ScheduledTasks                            = Запланированные задания
TaskbarSmallIcons                         = Вы используете маленькие кнопки панели задач.
SearchHighlightsDisabled                  = Основные результаты поиска в меню "Пуск" уже скрыты.
CustomStartMenu                           = Установлено стороннее меню "Пуск".
OneDriveNotInstalled                      = OneDrive уже удален.
OneDriveAccountWarning                    = Перед удалением OneDrive выйдите из учетной записи Microsoft в OneDrive.
OneDriveInstalled                         = OneDrive уже установлен.
UninstallNotification                     = {0} удаляется...
InstallNotification                       = {0} устанавливается...
NoWindowsFeatures                         = Нет компонентов Windows, которые необходимо отключить.
WindowsFeaturesTitle                      = Компоненты Windows
NoOptionalFeatures                        = Нет дополнительных компонентов Windows, которые необходимо отключить.
NoSupportedNetworkAdapters                = Нет сетевых адаптеров, поддерживающих функцию "Разрешить компьютеру отключать это устройство для экономии энергии".
OptionalFeaturesTitle                     = Дополнительные компоненты
EnableHardwareVT                          = Включите виртуализацию в UEFI.
UserShellFolderNotEmpty                   = В папке "{0}" остались файлы. Переместите их вручную в новое расположение.
UserFolderLocationMove                    = Не следует перемещать пользовательские папки в корень диска C.
DriveSelect                               = Выберите диск, в корне которого будет создана папка "{0}".
CurrentUserFolderLocation                 = Текущее расположение папки "{0}": "{1}".
FilesWontBeMoved                          = Файлы не будут перенесены.
FolderSelect                              = Выберите папку
UserFolderRequest                         = Хотите изменить расположение папки "{0}"?
UserDefaultFolder                         = Хотите изменить расположение папки "{0}" на значение по умолчанию?
ReservedStorageIsInUse                    = Используется зарезервированное хранилище.
ProgramPathNotExists                      = Путь "{0}" не существует.
ProgIdNotExists                           = ProgId "{0}" не существует.
AllFilesFilter                            = Все файлы
JSONNotValid                              = Файл JSON "{0}" невалиден.
PackageNotInstalled                       = {0} не установлен.
PackageIsInstalled                        = Последняя версия {0} уже установлена.
UninstallUWPForAll                        = Для всех пользователей
NoUWPApps                                 = Нет UWP-приложений, которые необходимо удалить.
UWPAppsTitle                              = UWP-приложения
ScheduledTaskCreatedByAnotherUser         = Задание "{0}" в Планировщике заданий уже было создано от имени "{1}".
CleanupTaskNotificationTitle              = Очистка Windows
CleanupTaskNotificationEvent              = Запустить задание по очистке неиспользуемых файлов и обновлений Windows?
CleanupTaskDescription                    = Очистка неиспользуемых файлов и обновлений Windows, используя встроенную программу Очистка диска. Задание может быть запущено, только если пользователь "{0}" вошел в систему.
CleanupNotificationTaskDescription        = Всплывающее уведомление с напоминанием об очистке неиспользуемых файлов и обновлений Windows. Задание может быть запущено, только если пользователь "{0}" вошел в систему.
SoftwareDistributionTaskNotificationEvent = Кэш обновлений Windows успешно удален.
TempTaskNotificationEvent                 = Папка временных файлов успешно очищена.
FolderTaskDescription                     = Очистка папки {0}. Задание может быть запущено, только если пользователь "{1}" вошел в систему.
EventViewerCustomViewName                 = Создание процесса
EventViewerCustomViewDescription          = События создания нового процесса и аудит командной строки.
ThirdPartyAVInstalled                     = Установлен сторонний антивирус.
NoHomeWindowsEditionSupport               = Редакция Windows Домашняя не поддерживает функцию "{0}".
GeoIdNotSupported                         = Функция "{0}" применима только для России.
PhotosNotInstalled                        = Приложение "Фотографии" не установлено.
HEVCInstalled                             = Расширения видео HEVC от производителя устройства уже установлены.
HEVCInstallNotification                   = Расширения видео HEVC от производителя устройства устанавливаются...
ThirdPartyArchiverInstalled               = Установлен сторонний архиватор.
gpeditNotSupported                        = Редакция Windows Домашняя не поддерживает оснастку Редактора локальной групповой политики (gpedit.msc).
RestartWarning                            = Обязательно перезагрузите ваш ПК.
ErrorsLine                                = Строка
ErrorsMessage                             = Ошибки, предупреждения и уведомления
Disable                                   = Отключить
Enable                                    = Включить
Install                                   = Установить
Uninstall                                 = Удалить
RestartFunction                           = Пожалуйста, повторно запустите функцию "{0}".
NoResponse                                = Невозможно установить соединение с {0}.
Run                                       = Запустить
Skipped                                   = Функция "{0}" пропущена.
ThankfulToastTitle                        = Спасибо за использование Sophia Script ❤️
DonateToastTitle                          = Вы можете пожертвовать ниже 🕊️
DotSourcedWarning                         = Пожалуйста, запустите функцию через дот-сорсинг (с точкой в начале):\n. .\\Import-TabCompletion.ps1
'@
