ConvertFrom-StringData -StringData @'
PowerShellImportFailed                    = Lütfen PowerShell 7 yi kapatın ve komut dosyasını yeniden çalıştırın.
UnsupportedOSBitness                      = Komut dosyası yalnızca 64 bit Windows'u destekler.
UnsupportedOSBuild                        = Komut dosyası yalnızca Windows 10 22H2'yi destekler. Sizin işletim sisteminiz {0}. Windows'unuzu yükseltin ve tekrar deneyin.
UnsupportedWindowsTerminal                = Windows Terminal sürümü 1.20'den daha düşük. Lütfen Microsoft Store'da güncelleyin ve tekrar deneyin.
UpdateWarning                             = Windows 10 yapınız: {0}.{1}. Desteklenen yapılar: {2} ve üzeri sürümler.. Windows Update'i çalıştırın ve tekrar deneyin.
UnsupportedLanguageMode                   = Sınırlı bir dil modunda çalışan PowerShell oturumu.
LoggedInUserNotAdmin                      = Oturum açan kullanıcının yönetici hakları yok.
UnsupportedPowerShell                     = Komut dosyasını PowerShell {0}.{1} aracılığıyla çalıştırmaya çalışıyorsunuz. Komut dosyasını uygun PowerShell sürümünde çalıştırın.
UnsupportedHost                           = Komut dosyası, {0} üzerinden çalıştırmayı desteklemiyor.
Win10TweakerWarning                       = Muhtemelen işletim sisteminize Win 10 Tweaker arka kapısı yoluyla bulaştı.
TweakerWarning                            = Windows işletim sistemi kararlılığı, {0} betiği kullanılarak tehlikeye atılmış olabilir. Yalnızca orijinal bir ISO görüntüsü kullanarak Windows'u yeniden yükleyin.
Bin                                       = "{0}" klasöründe dosya yok. Lütfen arşivi yeniden indirin.
RebootPending                             = PC yeniden başlatılmayı bekliyor.
UnsupportedRelease                        = Yeni bir komut dosyası sürümü bulundu. Lütfen sadece en son Sophia Script'i kullanın.
KeyboardArrows                            = Lütfen cevabınızı seçmek için klavyenizdeki {0} ve {1} ok tuşlarını kullanın
CustomizationWarning                      = Sophia Script'i çalıştırmadan önce {0} ön ayar dosyasındaki her işlevi özelleştirdiniz mi?
WindowsComponentBroken                    = {0} bozuk veya işletim sisteminden kaldırıldı. Yalnızca orijinal bir ISO görüntüsü kullanarak Windows'u yeniden yükleyin.
MicroSoftStorePowerShellWarning           = Microsoft Store'dan indirilen PowerShell desteklenmez. Lütfen bir MSI sürümü çalıştırın.\nhttps://github.com/powershell/powershell/releases/latest
ControlledFolderAccessDisabled            = Kontrollü klasör erişimi devre dışı bırakıldı.
InitialActionsCheckFailed                 = InitialActions işlevi {0} ön ayar dosyasından yüklenemiyor. Lütfen ön ayar dosyasını kontrol edin ve tekrar deneyin.
ScheduledTasks                            = Zamanlanan görevler
OneDriveUninstalling                      = OneDrive kaldırılıyor...
OneDriveInstalling                        = OneDrive kuruluyor...
OneDriveDownloading                       = OneDrive indiriliyor...
OneDriveWarning                           = "WinPrtScrFolder -Desktop" işlevi yalnızca kullanıcı OneDrive'ı kaldırmak için komut dosyası yapılandırmışsa (veya OneDrive zaten kaldırılmışsa) uygulanır.\nAksi takdirde OneDrive'daki "Masaüstü" ve "Resimler" klasörleri için yedekleme işlevi bozulur.
WindowsFeaturesTitle                      = Características do Windows
OptionalFeaturesTitle                     = Opsiyonel özellikler
EnableHardwareVT                          = UEFI'dan sanallaştırmayı aktifleştirin.
UserShellFolderNotEmpty                   = "{0}" klasöründe bazı dosyalar kaldı. Kendiniz yeni konuma taşıyın.
UserFolderLocationMove                    = Kullanıcı klasörü konumunu C sürücüsü kökü olarak değiştirmemelisiniz.
DriveSelect                               = "{0}" klasörünün oluşturulacağı kök içindeki sürücüyü seçin.
CurrentUserFolderLocation                 = Geçerli "{0}" klasör konumu: "{1}".
UserFolderRequest                         = "{0}" klasörünün yerini değiştirmek ister misiniz?
UserDefaultFolder                         = "{0}" klasörünün konumunu varsayılan değerle değiştirmek ister misiniz?
ReservedStorageIsInUse                    = Ayrılmış depolama kullanımdayken bu işlem desteklenmez\nBilgisayar yeniden başlatıldıktan sonra lütfen "{0}" işlevini yeniden çalıştırın.
ShortcutPinning                           = "{0}" kısayolu Başlangıç sekmesine sabitlendi...
UninstallUWPForAll                        = Bütün kullanıcılar için
UWPAppsTitle                              = UWP Uygulamaları
HEVCDownloading                           = "Cihaz Üreticisinden HEVC Video Uzantıları" İndiriliyor...
GraphicsPerformanceTitle                  = Seçtiğiniz bir uygulamanın grafik performansı ayarını "Yüksek performans" olarak belirlemek ister misiniz?
ScheduledTaskPresented                    = "{0}" işlevi zaten "{1}" olarak oluşturulmuştu.
CleanupTaskNotificationTitle              = Windows temizliği
CleanupTaskNotificationEvent              = Windows kullanılmayan dosyaları ve güncellemeleri temizlemek için görev çalıştırılsın mı?
CleanupTaskDescription                    = Kullanılmayan Windows dosyaları ve güncellemeleri yerleşik Disk Temizleme uygulaması ile temizleniyor. Zamanlanmış görev yalnızca "{0}" kullanıcısı sisteme giriş yaptığında çalıştırılabilir.
CleanupNotificationTaskDescription        = Windows kullanılmayan dosyaları ve güncellemeleri temizleme hakkında açılır bildirim hatırlatıcısı. Zamanlanmış görev yalnızca "{0}" kullanıcısı sisteme giriş yaptığında çalıştırılabilir.
SoftwareDistributionTaskNotificationEvent = Windows güncelleme önbelleği başarıyla silindi.
TempTaskNotificationEvent                 = Geçici dosyalar klasörü başarıyla temizlendi.
FolderTaskDescription                     = "{0}" klasörü temizleniyor. Zamanlanmış görev yalnızca "{0}" kullanıcısı sisteme giriş yaptığında çalıştırılabilir.
EventViewerCustomViewName                 = Süreç Oluşturma
EventViewerCustomViewDescription          = Süreç oluşturma ve komut satırı denetleme olayları.
RestartWarning                            = Bilgisayarınızı yeniden başlattığınızdan emin olun.
ErrorsLine                                = Satır
ErrorsMessage                             = Hatalar/Uyarılar
DialogBoxOpening                          = İletişim kutusu görüntüleniyor...
Disable                                   = Devre dışı bırak
Enable                                    = Aktif et
AllFilesFilter                            = Tüm Dosyalar
FolderSelect                              = Klasör seç
FilesWontBeMoved                          = Dosyalar taşınmayacak.
Install                                   = Yükle
Uninstall                                 = Kaldır
NoData                                    = Görüntülenecek bir şey yok.
RestartFunction                           = Lütfen "{0}" işlevini yeniden çalıştırın.
NoResponse                                = {0} ile bağlantı kurulamadı.
Restore                                   = Onar
Run                                       = Başlat
Skipped                                   = "{0}" işlevi atlandı.
ThankfulToastTitle                        = Sophia Script kullandığınız için teşekkür ederiz ❤️
DonateToastTitle                          = Bu projeyi beğendiyseniz lütfen bağışta bulunun 🕊️
DotSourcedWarning                         = Lütfen işlevi "nokta-kaynaklı" (başında nokta olan) olarak yazın:\n. .\\Import-TabCompletion.ps1
'@
