ConvertFrom-StringData -StringData @'
UnsupportedArchitecture                   = "{0}" tabanlı mimari CPU kullanıyorsunuz. Bu komut dosyası yalnızca x64 mimari tabanlı CPU'ları destekler. Mimariniz için komut dosyası sürümünü indirin ve çalıştırın.
NewSophiaScriptFound                      = Yeni bir sürüm yayınlandı: Sophia Script for Windows {0}. Lütfen güncelleyin.
UnsupportedPowerShell                     = Komut dosyasını PowerShell {0}.{1} aracılığıyla çalıştırmaya çalışıyorsunuz. Lütfen komut dosyasını PowerShell {2} ile çalıştırın.
CodeCompilationFailed                     = Kod derleme başarısız oldu.
MicrosoftStorePowerShellWarning           = Microsoft Store'dan indirilen PowerShell desteklenmez. Lütfen bir MSI sürümü çalıştırın.
PowerShellImportFailed                    = PowerShell 5.1'den modül içe aktarma işlemi başarısız oldu. Lütfen PowerShell 7 konsolunu kapatın ve komut dosyasını yeniden çalıştırın.
KeyboardArrows                            = Lütfen cevabınızı seçmek için klavyenizdeki {0} ve {1} ok tuşlarını kullanın
UnsupportedLanguageMode                   = PowerShell oturumu sınırlı bir dil modunda çalışıyor.
LoggedInUserNotAdmin                      = Oturum açan "{0}" kullanıcısının yönetici hakları yok. Komut dosyası "{1}" adına çalıştırılmıştır. Yönetici haklarına sahip bir hesaba giriş yapın ve komut dosyasını tekrar çalıştırın.
UnsupportedHost                           = Komut dosyası, {0} üzerinden çalıştırmayı desteklemiyor.
HarmfulTweakerFound                       = Windows işletim sisteminin kararlılığı, {0} kullanımı nedeniyle tehlikeye atılmış olabilir.
HostsEntriesFound                         = %SystemRoot%\\System32\\drivers\\etc\\hosts dosyasında üçüncü taraf girdileri bulundu. Bunlar, komut dosyasında kullanılan kaynaklara bağlantıyı engelleyebilir. Devam etmek istiyor musunuz?
UWPComponentsMissing                      = "{0}" UWP bileşeni eksik.
DefenderComponentsMissing                 = Microsoft Defender "{0}" bileşeni eksik.
WindowsComponentStabilityDisrupted        = "{0}" bileşeninde bir kararsızlık sorunu tespit edildi.
DisableControlledFolderAccess             = Kontrollü klasör erişimi etkinleştirilmiştir. Lütfen bunu devre dışı bırakın ve komut dosyasını tekrar çalıştırın.
RebootPending                             = Bilgisayarınız yeniden başlatılmayı bekliyor.
SystemDriveEncryptedBitLockerDisabled     = BitLocker kapalı olmasına rağmen C sürücüsü şifrelenmiştir. Sürücünüzün şifresini çözmek ister misiniz?
UpdateUEFICertificates                    = "Microsoft Windows Production PCA 2011" Güvenli Önyükleme sertifikasının geçerlilik süresi 2026'da sona eriyor. Cihazınız henüz güncellenmiş "Windows UEFI CA 2023" sertifikalarını almadı. "Microsoft Windows UEFI CA 2023" sertifikalarını manuel olarak yüklemek istiyor musunuz?
EnableSecureBoot                          = Güvenli Önyükleme'yi etkinleştirin.
WrongSophiaScriptVersion                  = Komut dosyası Windows 11 25H2 ve üstünü destekler. {0} {1} kullanıyorsunuz. Windows sürümüne göre doğru komut dosyasını çalıştırın.
UpdateWindowsTerminal                     = Windows Terminal sürümü 1.24'ten daha düşük. Lütfen Microsoft Store'da güncelleyin ve tekrar deneyin.
UpdateWindowsBuild                        = Bu komut dosyası, Windows 11 25H2 {0}.{1} ve üzeri sürümleri desteklemektedir. Şu anda {2} {3} {4}.{5} sürümünü kullanıyorsunuz. Windows Update'i çalıştırın ve tekrar deneyin.
AskQuestion                               = Herhangi bir sorunuz olursa, GitHub'da bir issue açın veya topluluğa danışın.
CheckSophiaScriptPreset                   = Sophia Script for Windows'u çalıştırmadan önce {0} ön ayar dosyasındaki her işlevi özelleştirdiniz mi?
ReinstallWindows                          = Yalnızca orijinal bir ISO görüntüsü kullanarak Windows'u yeniden yükleyin.
CreatingRestorePoint                      = Geri yükleme noktası oluşturuluyor...
WindowsServiceNotFound                    = "{0}" hizmeti bulunamadı.
NoScheduledTasksFound                     = Zamanlanmış görev bulunamadı.
ScheduledTasks                            = Zamanlanmış görevler
WidgetNotInstalled                        = Widget yüklenmemiştir.
SearchHighlightsDisabled                  = Arama öne çıkanları Başlat'ta zaten gizlidir.
CustomStartMenuFound                      = Üçüncü taraf bir Başlat Menüsü yüklenmiştir.
OneDriveNotInstalled                      = OneDrive zaten kaldırılmıştır.
OneDriveAccountUsageFound                 = OneDrive'ı kaldırmadan önce, OneDrive'da Microsoft hesabınızdan çıkış yapın.
OneDriveInstalled                         = OneDrive zaten yüklü.
UninstallingApplication                   = {0} kaldırılıyor...
InstallingApplication                     = {0} yükleniyor...
NoWindowsFeaturesFound                    = Windows özelliği bulunamadı.
WindowsFeaturesTitle                      = Windows özellikleri
NoOptionalFeaturesFound                   = İsteğe bağlı özellik bulunamadı.
OptionalFeaturesTitle                     = İsteğe bağlı özellikler
NoSupportedNetworkAdaptersFound           = "Bilgisayarın güç tasarrufu için bu aygıtı kapatmasına izin ver" işlevini destekleyen ağ bağdaştırıcısı yok.
LocationServicesDisabled                  = Ağ kabuğu komutları, WLAN bilgilerine erişmek için konum iznine ihtiyaç duyar. Gizlilik ve güvenlik ayarlarının Konum sayfasında Konum hizmetlerini açın.
UserFolderLocationMove                    = Kullanıcı klasörü konumunu C sürücüsü kökü olarak değiştirmemelisiniz.
DriveSelect                               = Kök dizinde "{0}" klasörünün oluşturulacağı sürücüyü seçin.
CurrentUserFolderLocation                 = Geçerli "{0}" klasör konumu: "{1}".
FilesWontBeMoved                          = Dosyalar taşınmayacaktır.
UserFolderMoveSkipped                     = Kullanıcının "{0}" klasörünün konumunu değiştirmeyi atladınız.
UserShellFolderNotEmpty                   = "{0}" klasöründe bazı dosyalar kaldı. Kendiniz yeni konuma taşıyın.
FolderSelect                              = Bir klasör seçin
UserFolderRequest                         = "{0}" klasörünün konumunu değiştirmek ister misiniz?
UserDefaultFolder                         = "{0}" klasörünün konumunu varsayılan değerle değiştirmek ister misiniz?
ReservedStorageIsInUse                    = Ayrılmış depolama alanı kullanılıyor.
ProgramPathNotExists                      = "{0}" yolu mevcut değil.
ProgIdNotExists                           = ProgId "{0}" mevcut değildir.
AllFilesFilter                            = Tüm Dosyalar
JSONNotValid                              = JSON dosyası "{0}" geçerli değil.
PackageNotInstalled                       = "{0}" uygulaması yüklü değil.
PackageIsInstalled                        = {0}'ın en son sürümü zaten yüklü.
PCNPUSupport                              = Bilgisayarınızda yerleşik bir yapay zeka hızlandırıcısı (NPU) bulunmadığından, Windows'un yapay zeka ile ilgili işlevleri desteklenmemektedir. "Recall" işlevinin ve Copilot uygulamasının kaldırılması dışında hiçbir politika uygulanmayacaktır.
UWPAppsTitle                              = UWP Uygulamaları
UninstallUWPForAll                        = Bütün kullanıcılar için
NoUWPAppsFound                            = Kaldırılacak UWP uygulaması yok.
WDDMVersionUnsupported                    = Desteklenen WDDM sürümü 2.7 ve üzeridir. Mevcut WDDM sürümü {0}'dur.
CleanupTaskNotificationTitle              = Windows temizleme
CleanupTaskNotificationEvent              = Kullanılmayan Windows dosyalarını ve güncelleştirmelerini temizlemek için görev çalıştırılsın mı?
CleanupTaskDescription                    = Kullanılmayan Windows dosyaları ve güncelleştirmeleri yerleşik Disk Temizleme uygulaması ile temizleniyor.
CleanupNotificationTaskDescription        = Kullanılmayan Windows dosyalarını ve güncelleştirmelerini temizleme hakkında açılır bildirim hatırlatıcısı.
SoftwareDistributionTaskNotificationEvent = Windows güncelleştirme önbelleği başarıyla silindi.
SoftwareDistributionTaskDescription       = "{0}" adlı Windows Güncelleştirme önbellek klasörü temizleniyor.
TempTaskNotificationEvent                 = Geçici klasör başarıyla temizlendi.
TempTaskDescription                       = "{0}" geçici klasörü (%TEMP%) temizleniyor.
ScheduledTaskLoggedInUserNotification     = Zamanlanmış görev yalnızca "{0}" kullanıcısı sisteme giriş yaptığında çalıştırılabilir.
CleanupTaskCLIDescription                 = "Sophia\\Windows Cleanup Notification" zamanlanmış görevi, kullanılmayan Windows dosyalarını ve güncelleştirmelerini temizlemek için Görev Zamanlayıcı'da oluşturuldu.
SoftwareDistributionTaskCLIDescription    = "Sophia\\SoftwareDistribution" zamanlanmış görevi, Windows güncelleştirme önbellek klasörünü "{0}" temizlemek için Görev Zamanlayıcı'da oluşturuldu.
TempTaskCLIDescription                    = "Sophia\\Temp" zamanlanmış görevi, "{0}" geçici klasörünü (%TEMP%) temizlemek için Görev Zamanlayıcı'da oluşturuldu.
EventViewerCustomViewName                 = İşlem Oluşturma
EventViewerCustomViewDescription          = Başlatılan işlemleri ve PowerShell etkinliğini izleyin
EventViewerCustomViewNotification         = "Özel Görünümler\\{0}" özel görünümü, başlatılan işlemleri ve PowerShell etkinliğini izlemek için Olay Görüntüleyicisi'nde oluşturuldu.
ThirdPartyAVInstalled                     = Üçüncü taraf bir antivirüs yüklüdür.
NoHomeWindowsEditionSupport               = Windows Home sürümü "{0}" işlevini desteklemiyor.
EnableHardwareVT                          = UEFI'de sanallaştırmayı etkinleştirin.
ActiveNetworkAdapterNotFound              = Şu anda kullanılan ağ bağdaştırıcısı belirlenemedi: etkin ağ bağlantısı bulunamadı. Bir ağa bağlanın.
ThirdPartyArchiverInstalled               = Üçüncü taraf bir arşivleyici yüklenmiştir.
gpeditNotSupported                        = Windows Home sürümü, Yerel Grup İlkesi Düzenleyicisi ek bileşenini (gpedit.msc) desteklemez.
RestartWarning                            = Bilgisayarınızı yeniden başlatmayı unutmayın.
RestorePointVolume                        = C sürücüsündeki geri yükleme noktaları {0} GB yer kaplıyor.
ErrorsLine                                = Satır
ErrorsMessage                             = Hatalar, uyarılar ve bildirimler
Disable                                   = Devre dışı bırak
Enable                                    = Etkinleştir
Install                                   = Yükle
Uninstall                                 = Kaldır
RestartFunction                           = Lütfen "{0}" işlevini yeniden çalıştırın.
NoConnectionEstablished                   = {0} ile bağlantı kurulamadı.
Run                                       = Başlat
FunctionSkipped                           = "{0}" işlevi atlandı.
DonateToastTitle                          = Bağışlarınızı bekliyoruz! ❤
DotSourceFunction                         = Lütfen işlevi "nokta-kaynaklı" (başında nokta olan) olarak yazın:\n. .\\Import-TabCompletion.ps1
'@
