ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = El script sólo es compatible con Windows de 64 bits
UnsupportedOSBuild                        = \nEl script es compatible con versión Windows 10 Enterprise LTSC 2021
UpdateWarning                             = \nActualización acumulativa de Windows 10 instalada: {0}. Actualización acumulativa soportada: 2728 y superior. Ejecute Windows Update y vuelva a intentarlo
UnsupportedLanguageMode                   = \nSesión de PowerShell ejecutada en modo de lenguaje limitado
LoggedInUserNotAdmin                      = \nEl usuario que inició sesión no tiene derechos de administrador
UnsupportedPowerShell                     = \nEstás intentando ejecutar el script a través de PowerShell {0}.{1}. Ejecute el script en la versión apropiada de PowerShell
UnsupportedHost                           = \nEl script no es compatible con la ejecución a través de {0}
Win10TweakerWarning                       = \nProbablemente su sistema operativo fue infectado a través del backdoor Win 10 Tweaker
TweakerWarning                            = \nLa estabilidad del sistema operativo Windows puede haberse visto comprometida al utilizar el {0}. Por si acaso, reinstala Windows
bin                                       = \nNo hay archivos en la carpeta bin. Por favor, vuelva a descargar el archivo
RebootPending                             = \nEl PC está esperando a ser reiniciado
UnsupportedRelease                        = \nUna nueva versión encontrada
CustomizationWarning                      = \n¿Ha personalizado todas las funciones del archivo predeterminado {0} antes de ejecutar Sophia Script?
DefenderBroken                            = \nMicrosoft Defender dañado o eliminado del sistema operativo
UpdateDefender                            = \nLas definiciones de Microsoft Defender no están actualizadas. Ejecute Windows Update y vuelva a intentarlo
ControlledFolderAccessDisabled            = Acceso a la carpeta controlada deshabilitado
ScheduledTasks                            = Tareas programadas
WindowsFeaturesTitle                      = Características de Windows
OptionalFeaturesTitle                     = Características opcionales
EnableHardwareVT                          = Habilitar la virtualización en UEFI
UserShellFolderNotEmpty                   = Algunos archivos quedan en la carpeta "{0}". Moverlos manualmente a una nueva ubicación
RetrievingDrivesList                      = Recuperando lista de unidades...
DriveSelect                               = Seleccione la unidad dentro de la raíz de la cual se creó la carpeta "{0}"
CurrentUserFolderLocation                 = La ubicación actual de la carpeta "{0}": "{1}"
UserFolderRequest                         = ¿Le gustaría cambiar la ubicación de la "{0}" carpeta?
UserFolderSelect                          = Seleccione una carpeta para la carpeta "{0}"
UserDefaultFolder                         = ¿Le gustaría cambiar la ubicación de la carpeta "{0}" para el valor por defecto?
ReservedStorageIsInUse                    = Esta operación no es compatible cuando el almacenamiento reservada está en uso\nPor favor, vuelva a ejecutar la función "{0}" después de reiniciar el PC
ShortcutPinning                           = El acceso directo "{0}" está siendo clavado en Start...
GraphicsPerformanceTitle                  = Preferencia de rendimiento gráfico
GraphicsPerformanceRequest                = ¿Le gustaría establecer la configuración de rendimiento gráfico de una aplicación de su elección a "alto rendimiento"?
ScheduledTaskPresented                    = La función "{0}" ya fue creada como "{1}"
CleanupTaskNotificationTitle              = Limpieza de Windows
CleanupTaskNotificationEvent              = ¿Ejecutar la tarea de limpiar los archivos no utilizados y actualizaciones de Windows?
CleanupTaskDescription                    = La limpieza de Windows los archivos no utilizados y actualizaciones utilizando una función de aplicación de limpieza de discos
CleanupNotificationTaskDescription        = Pop-up recordatorio de notificaciones sobre la limpieza de archivos no utilizados de Windows y actualizaciones
SoftwareDistributionTaskNotificationEvent = La caché de actualización de Windows eliminado correctamente
TempTaskNotificationEvent                 = Los archivos de la carpeta Temp limpiados con éxito
FolderTaskDescription                     = La limpieza de la carpeta "{0}"
EventViewerCustomViewName                 = Creación de proceso
EventViewerCustomViewDescription          = Eventos de auditoría de línea de comandos y creación de procesos
RestartWarning                            = Asegúrese de reiniciar su PC
ErrorsLine                                = Línea
ErrorsMessage                             = Errores/Advertencias
DialogBoxOpening                          = Viendo el cuadro de diálogo...
Disable                                   = Desactivar
EXEFilesFilter                            = *.exe|*.exe|Todos los Archivos (*.*)|*.*
FolderSelect                              = Seleccione una carpeta
FilesWontBeMoved                          = Los archivos no se transferirán
Install                                   = Instalar
NoData                                    = Nada que mostrar
NoInternetConnection                      = No hay conexión a Internet
RestartFunction                           = Por favor, reinicie la función "{0}"
NoResponse                                = No se pudo establecer una conexión con {0}
Restore                                   = Restaurar
Run                                       = Iniciar
Skipped                                   = Omitido
GPOUpdate                                 = Actualización de GPO...
TelegramGroupTitle                        = Únete a nuestro grupo oficial de Telegram
TelegramChannelTitle                      = Únete a nuestro canal oficial de Telegram
DiscordChannelTitle                       = Únete a nuestro canal oficial de Discord
Uninstall                                 = Desinstalar
'@
