ConvertFrom-StringData -StringData @'
UnsupportedArchitecture                   = Vous utilisez un processeur basé sur l'architecture "{0}". Ce script ne prend en charge que les processeurs basés sur l'architecture x64. Téléchargez et exécutez la version du script adaptée à votre architecture.
NewSophiaScriptFound                      = Une nouvelle version est disponible: Sophia Script for Windows {0}. Veuillez effectuer la mise à jour.
UnsupportedPowerShell                     = Vous essayez d'exécuter le script via PowerShell {0}.{1}. Veuillez exécuter le script en PowerShell {2}.
CodeCompilationFailed                     = Échec de la compilation du code.
MicrosoftStorePowerShellWarning           = PowerShell téléchargé depuis le Microsoft Store n'est pas pris en charge. Veuillez exécuter une version MSI.
PowerShellImportFailed                    = L'importation des modules depuis PowerShell 5.1 a échoué. Veuillez fermer la console PowerShell 7 et relancer le script.
KeyboardArrows                            = Veuillez utiliser les touches fléchées {0} et {1} de votre clavier pour sélectionner votre réponse
UnsupportedLanguageMode                   = La session PowerShell s'exécute dans un mode de langue limité.
LoggedInUserNotAdmin                      = L'utilisateur connecté "{0}" ne dispose pas des droits d'administrateur. Le script a été exécuté au nom d'"{1}". Veuillez vous connecter à un compte disposant des droits d'administrateur et relancer le script.
UnsupportedHost                           = Le script ne supporte pas l'exécution via {0}.
HarmfulTweakerFound                       = La stabilité de l'OS Windows peut avoir été compromise par l'utilisation du {0}. 
HostsEntriesFound                         = Entrées tierces trouvées dans le fichier %SystemRoot%\\System32\\drivers\\etc\\hosts. Elles peuvent bloquer la connexion aux ressources utilisées dans le script. Voulez-vous continuer?
WindowsComponentStabilityDisrupted        = Un problème d'instabilité a été détecté dans le composant "{0}".
DisableControlledFolderAccess             = Vous avez activé le contrôle d'accès aux dossiers. Veuillez le désactiver et relancer le script.
RebootPending                             = Votre PC attend d'être redémarré.
SystemDriveEncryptedBitLockerDisabled     = Le lecteur C est chiffré, bien que BitLocker soit désactivé. Voulez-vous déchiffrer votre lecteur?
UpdateUEFICertificates                    = Le certificat Secure Boot "Microsoft Windows Production PCA 2011" expire en 2026. Votre appareil n'a pas encore reçu les certificats "Windows UEFI CA 2023" mis à jour. Souhaitez-vous installer manuellement les certificats "Microsoft Windows UEFI CA 2023" ?
UpdateWindowsTerminal                     = La version de Windows Terminal est inférieure à 1.23. Veuillez la mettre à jour dans le Microsoft Store et réessayer.
WrongSophiaScriptVersion                  = Le script ne supporte que Windows 11 25H2. Vous utilisez {0} {1}. Exécutez le script approprié en fonction de l'édition de Windows.
UpdateWindowsBuild                        = Vous utilisez Windows 11 {0}.{1}. La version prise en charge est Windows 11 {0}.{2} et supérieure. Exécutez Windows Update et réessayez.
CheckSophiaScriptPreset                   = Avez-vous personnalisé chaque fonction du fichier de préréglage {0} avant d'exécuter Sophia Script for Windows?
ReinstallWindows                          = Réinstallez Windows en utilisant uniquement une image ISO authentique.
CreatingRestorePoint                      = Un point de restauration est en cours de création...
UWPComponentsMissing                      = Le composant UWP "{0}" est manquant.
DefenderComponentsMissing                 = Le composant "{0}" de Microsoft Defender est manquant.
DiagTrackServiceNotFound                  = Le service "DiagTrackService" est introuvable.
NoScheduledTasksFound                     = Aucune tâche planifiée à désactiver.
ScheduledTasks                            = Tâches planifiées
WidgetNotInstalled                        = Le widget n'est pas installé.
SearchHighlightsDisabled                  = Les résultats de recherche sont déjà masqués dans Démarrer.
CustomStartMenuFound                      = Un menu Démarrer tiers est installé.
OneDriveNotInstalled                      = OneDrive est déjà désinstallé.
OneDriveAccountUsageFound                 = Avant de désinstaller OneDrive, déconnectez-vous de votre compte Microsoft dans OneDrive.
OneDriveInstalled                         = OneDrive est déjà installé.
UninstallingApplication                   = {0} est en cours de désinstallation...
InstallingApplication                     = {0} est en cours d'installation...
NoWindowsFeaturesFound                    = Aucune fonctionnalité Windows à désactiver.
WindowsFeaturesTitle                      = Fonctionnalités
NoOptionalFeaturesFound                   = Aucune fonctionnalité optionnelle à désactiver.
NoSupportedNetworkAdaptersFound           = Aucun adaptateur réseau ne prend en charge la fonction "Autoriser l'ordinateur à éteindre ce périphérique pour économiser l'énergie ".
LocationServicesDisabled                  = Los comandos de shell de red necesitan permiso de ubicación para acceder a la información de la red WLAN. Active los servicios de ubicación en la página Ubicación de la configuración de Privacidad y seguridad.
OptionalFeaturesTitle                     = Fonctionnalités optionnelles
UserShellFolderNotEmpty                   = Certains fichiers laissés dans le dossier "{0}". Déplacer les manuellement vers un nouvel emplacement.
UserFolderLocationMove                    = Vous ne devez pas changer l'emplacement du dossier de l'utilisateur pour la racine du lecteur C.
DriveSelect                               = Sélectionnez le disque sur lequel le dossier "{0}" sera créé dans le répertoire racine.
CurrentUserFolderLocation                 = L'emplacement actuel du dossier "{0}": "{1}".
FilesWontBeMoved                          = Les fichiers ne seront pas déplacés.
UserFolderMoveSkipped                     = Vous avez oublié de modifier l'emplacement du dossier "{0}" de l'utilisateur.
FolderSelect                              = Sélectionnez un dossier
UserFolderRequest                         = Voulez vous changer où est placé le dossier "{0}"?
UserDefaultFolder                         = Voulez vous changer où est placé le dossier "{0}" à sa valeur par défaut?
ReservedStorageIsInUse                    = L'espace de stockage réservé est utilisé.
ProgramPathNotExists                      = Le chemin "{0}" n'existe pas.
ProgIdNotExists                           = ProgId "{0}" n'existe pas.
AllFilesFilter                            = Tous les fichiers
JSONNotValid                              = Le fichier JSON "{0}" n'est pas valide.
PackageNotInstalled                       = L'application "{0}" n'est pas installée.
PackageIsInstalled                        = La dernière version de {0} est déjà installée.
CopilotPCSupport                          = Votre PC ne dispose pas d'un accélérateur IA intégré (NPU) ; par conséquent, les fonctionnalités liées à l'IA de Windows ne sont pas prises en charge. Il n'est pas nécessaire de désactiver quoi que ce soit via les stratégies Windows. Seules la fonction "Recall" et l'application Copilot seront supprimées.
UninstallUWPForAll                        = Pour tous les utilisateurs
NoUWPAppsFound                            = Aucune application UWP à désinstaller.
UWPAppsTitle                              = Applications UWP
ScheduledTaskCreatedByAnotherUser         = La tâche planifiée "{0}" a déjà été créée par l'utilisateur "{1}".
CleanupTaskNotificationTitle              = Nettoyer Windows
CleanupTaskNotificationEvent              = Exécuter la tâche pour nettoyer les fichiers et les mises à jour inutilisés de Windows?
CleanupTaskDescription                    = Nettoyage des fichiers Windows inutilisés et des mises à jour à l'aide de l'application intégrée pour le nettoyage de disque.
CleanupNotificationTaskDescription        = Rappel de notification contextuelle sur le nettoyage des fichiers et des mises à jour inutilisés de Windows.
SoftwareDistributionTaskNotificationEvent = Le cache de mise à jour Windows a bien été supprimé.
SoftwareDistributionTaskDescription       = Nettoyage du dossier cache de Windows Update "{0}".
TempTaskNotificationEvent                 = Le dossier des fichiers temporaires a été nettoyé avec succès.
TempTaskDescription                       = Nettoyage du dossier temporaire "{0}" (%TEMP%).
ScheduledTaskLoggedInUserNotification     = La tâche programmée ne peut être exécutée que si l'utilisateur "{0}" est connecté au système.
ScheduledTaskCreatedNotification          = La tâche planifiée "{0}" a été créée.
CleanupTaskCLIDescription                 = Accédez au dossier "Sophia" dans le Planificateur de tâches et exécutez la tâche "Windows Cleanup Notification" pour commencer le nettoyage des fichiers et mises à jour inutilisés de Windows.
SoftwareDistributionTaskCLIDescription    = Accédez au dossier "Sophia" dans le Planificateur de tâches et exécutez la tâche "SoftwareDistribution" pour lancer le nettoyage du dossier de cache des mises à jour Windows "{0}".
TempTaskCLIDescription                    = Accédez au dossier "Sophia" dans le Planificateur de tâches et exécutez la tâche "Temp" pour lancer le nettoyage du dossier des fichiers temporaires "{0}" (%TEMP%).
EventViewerCustomViewName                 = Création du processus
EventViewerCustomViewDescription          = Audit des événements de création du processus et de ligne de commande.
ThirdPartyAVInstalled                     = Un antivirus tiers est installé.
NoHomeWindowsEditionSupport               = Windows Home Edition ne prend pas en charge la fonction "{0}".
EnableHardwareVT                          = Activer la virtualisation dans UEFI.
PhotosNotInstalled                        = L'application "Photos" n'est pas installée.
ThirdPartyArchiverInstalled               = Un programme d'archivage tiers est installé.
gpeditNotSupported                        = Windows Home Edition ne prend pas en charge le composant logiciel enfichable Éditeur de stratégie de groupe locale (gpedit.msc).
RestartWarning                            = Assurez-vous de redémarrer votre PC.
RestorePointVolume                        = Les points de restauration du lecteur C occupent {0} Go.
ErrorsLine                                = Ligne
ErrorsMessage                             = Erreurs, avertissements et notifications
Disable                                   = Désactiver
Enable                                    = Activer
Install                                   = Installer
Uninstall                                 = Désinstaller
RestartFunction                           = Veuillez redémarrer la fonction "{0}".
NoConnectionEstablished                   = Une connexion n'a pas pu être établie avec {0}.
Run                                       = Démarrer
FunctionSkipped                           = Fonction "{0}" ignorée.
DonateToastTitle                          = Les dons sont les bienvenus!❤
DotSourcedFunction                        = Veuillez "dot-source" la fonction (avec un point au début):\n. .\\Import-TabCompletion.ps1
'@
