ConvertFrom-StringData -StringData @'
UnsupportedArchitecture                   = "{0}" tabanlı mimari CPU kullanıyorsunuz. Bu komut dosyası yalnızca x64 mimari tabanlı CPU'ları destekler. Mimariniz için komut dosyası sürümünü indirin ve çalıştırın.
NewSophiaScriptFound                      = Yeni bir sürüm yayınlandı: Windows için Sophia Script {0}. Lütfen güncelleyin.
UnsupportedPowerShell                     = Komut dosyasını PowerShell {0}.{1} aracılığıyla çalıştırmaya çalışıyorsunuz. Lütfen betiği PowerShell {2} ile çalıştırın.
CodeCompilationFailed                     = Kod derleme başarısız oldu.
MicrosoftStorePowerShellWarning           = Microsoft Store'dan indirilen PowerShell desteklenmez. Lütfen bir MSI sürümü çalıştırın.
PowerShellImportFailed                    = PowerShell 5.1'den modül içe aktarma işlemi başarısız oldu. Lütfen PowerShell 7 konsolunu kapatın ve komut dosyasını yeniden çalıştırın.
KeyboardArrows                            = Lütfen cevabınızı seçmek için klavyenizdeki {0} ve {1} ok tuşlarını kullanın
UnsupportedLanguageMode                   = Sınırlı bir dil modunda çalışan PowerShell oturumu.
LoggedInUserNotAdmin                      = Oturum açan kullanıcı "{0}"'in yönetici hakları yoktur. Komut dosyası "{1}" adına çalıştırılmıştır. Yönetici haklarına sahip bir hesaba giriş yapın ve komut dosyasını tekrar çalıştırın.
UnsupportedHost                           = Komut dosyası, {0} üzerinden çalıştırmayı desteklemiyor.
HarmfulTweakerFound                       = Windows işletim sistemi kararlılığı, {0} betiği kullanılarak tehlikeye atılmış olabilir.
HostsEntriesFound                         = %SystemRoot%\\System32\\drivers\\etc\\hosts dosyasında bulunan üçüncü taraf girdileri. Bunlar, komut dosyasında kullanılan kaynaklara bağlantıyı engelleyebilir. Devam etmek istiyor musunuz?
WindowsComponentStabilityDisrupted        = "{0}" bileşeninde bir kararsızlık sorunu tespit edildi.
DisableControlledFolderAccess             = Kontrollü klasör erişimi etkinleştirilmiştir. Lütfen bunu devre dışı bırakın ve komut dosyasını tekrar çalıştırın.
RebootPending                             = Bilgisayarınız yeniden başlatılmayı bekliyor.
SystemDriveEncryptedBitLockerDisabled     = BitLocker kapalı olmasına rağmen C sürücüsü şifrelenmiştir. Sürücünüzün şifresini çözmek ister misiniz?
UpdateUEFICertificates                    = "Microsoft Windows Production PCA 2011" Güvenli Önyükleme sertifikasının geçerlilik süresi 2026'da sona eriyor. Cihazınız henüz güncellenmiş "Windows UEFI CA 2023" sertifikalarını almadı. "Microsoft Windows UEFI CA 2023" sertifikalarını manuel olarak yüklemek istiyor musunuz?
UpdateWindowsTerminal                     = Windows Terminal sürümü 1.23'den daha düşük. Lütfen Microsoft Store'da güncelleyin ve tekrar deneyin.
WrongSophiaScriptVersion                  = Komut dosyası yalnızca Windows 11 Enterprise LTSC 2024'yi destekler. {0} {1} kullanıyorsunuz. Windows sürümüne göre doğru komut dosyasını çalıştırın.
UpdateWindowsBuild                        = Windows 11 Enterprise LTSC 2024 {0}.{1} rendszert használ. A támogatott verzió Windows 11 Enterprise LTSC 2024 {0}.{2} vagy újabb. Futtassa a Windows Update programot, majd próbálja meg újra.
CheckSophiaScriptPreset                   = Sophia Script for Windows'i çalıştırmadan önce {0} ön ayar dosyasındaki her işlevi özelleştirdiniz mi?
ReinstallWindows                          = Yalnızca orijinal bir ISO görüntüsü kullanarak Windows'u yeniden yükleyin.
CreatingRestorePoint                      = Geri yükleme noktası oluşturuluyor...
UWPComponentsMissing                      = O componente UWP "{0}" está faltando.
DefenderComponentsMissing                 = O componente "{0}" do Microsoft Defender está faltando.
DiagTrackServiceNotFound                  = "DiagTrackService" hizmeti bulunamadı.
NoScheduledTasksFound                     = Devre dışı bırakılacak zamanlanmış görev yok.
ScheduledTasks                            = Zamanlanan görevler
SearchHighlightsDisabled                  = Arama öne çıkanları Başlat'ta zaten gizlidir.
CustomStartMenuFound                      = Üçüncü taraf bir Başlat Menüsü yüklenmiştir.
InstallingApplication                     = {0} yükleniyor...
NoWindowsFeaturesFound                    = Devre dışı bırakılacak Windows özelliği yok.
WindowsFeaturesTitle                      = Windows özellikleri
NoOptionalFeaturesFound                   = Devre dışı bırakılacak isteğe bağlı özellik yok.
NoSupportedNetworkAdaptersFound           = "Bilgisayarın güç tasarrufu için bu aygıtı kapatmasına izin ver" işlevini destekleyen ağ bağdaştırıcısı yok.
LocationServicesDisabled                  = Ağ kabuğu komutları, WLAN bilgilerine erişmek için konum iznine ihtiyaç duyar. Gizlilik ve güvenlik ayarlarının Konum sayfasında Konum hizmetlerini açın.
OptionalFeaturesTitle                     = Opsiyonel özellikler
UserShellFolderNotEmpty                   = "{0}" klasöründe bazı dosyalar kaldı. Kendiniz yeni konuma taşıyın.
UserFolderLocationMove                    = Kullanıcı klasörü konumunu C sürücüsü kökü olarak değiştirmemelisiniz.
DriveSelect                               = Kök dizinde "{0}" klasörünün oluşturulacağı sürücüyü seçin.
CurrentUserFolderLocation                 = Geçerli "{0}" klasör konumu: "{1}".
FilesWontBeMoved                          = Dosyalar taşınmayacaktır.
UserFolderMoveSkipped                     = Kullanıcının "{0}" klasörünün konumunu değiştirmeyi atladınız.
FolderSelect                              = Bir klasör seçin
UserFolderRequest                         = "{0}" klasörünün yerini değiştirmek ister misiniz?
UserDefaultFolder                         = "{0}" klasörünün konumunu varsayılan değerle değiştirmek ister misiniz?
ReservedStorageIsInUse                    = Ayrılmış depolama alanı kullanılıyor.
ProgramPathNotExists                      = "{0}" yolu mevcut değil.
ProgIdNotExists                           = ProgId "{0}" mevcut değildir.
AllFilesFilter                            = Tüm Dosyalar
JSONNotValid                              = JSON dosyası "{0}" geçerli değil.
PackageNotInstalled                       = "{0}" uygulaması yüklü değil.
PackageIsInstalled                        = {0}'ın en son sürümü zaten yüklü.
UninstallUWPForAll                        = Bütün kullanıcılar için
NoUWPAppsFound                            = Kaldırılacak UWP uygulaması yok.
UWPAppsTitle                              = UWP Uygulamaları
ScheduledTaskCreatedByAnotherUser         = "{0}" adlı zamanlanmış görev, "{1}" kullanıcısı tarafından zaten oluşturulmuştur.
CleanupTaskNotificationTitle              = Windows temizleme
CleanupTaskNotificationEvent              = Windows kullanılmayan dosyaları ve güncellemeleri temizlemek için görev çalıştırılsın mı?
CleanupTaskDescription                    = Kullanılmayan Windows dosyaları ve güncellemeleri yerleşik Disk Temizleme uygulaması ile temizleniyor.
CleanupNotificationTaskDescription        = Windows kullanılmayan dosyaları ve güncellemeleri temizleme hakkında açılır bildirim hatırlatıcısı.
SoftwareDistributionTaskNotificationEvent = Windows güncelleme önbelleği başarıyla silindi.
SoftwareDistributionTaskDescription       = "{0}" adlı Windows Güncelleştirme önbellek klasörü temizleniyor.
TempTaskNotificationEvent                 = Geçici dosyalar klasörü başarıyla temizlendi.
TempTaskDescription                       = "{0}" (%TEMP%) geçici klasörü temizleniyor.
ScheduledTaskLoggedInUserNotification     = Zamanlanmış görev yalnızca "{0}" kullanıcısı sisteme giriş yaptığında çalıştırılabilir.
ScheduledTaskCreatedNotification          = "{0}" adlı zamanlanmış görev oluşturuldu.
CleanupTaskCLIDescription                 = Görev Zamanlayıcı'daki "Sophia" klasörüne gidin ve "Windows Cleanup Notification" görevini çalıştırarak Windows'un kullanılmayan dosyalarını ve güncellemelerini temizlemeye başlayın.
SoftwareDistributionTaskCLIDescription    = Görev Zamanlayıcı'daki "Sophia" klasörüne gidin ve "SoftwareDistribution" görevini çalıştırarak Windows güncelleme önbellek klasörü "{0}"yi temizlenmesini başlatın.
TempTaskCLIDescription                    = Görev Zamanlayıcı'daki "Sophia" klasörüne gidin ve "Temp" görevini çalıştırarak "{0}" (%TEMP%) geçici dosyalar klasörünü temizlemeye başlayın.
EventViewerCustomViewName                 = Süreç Oluşturma
EventViewerCustomViewDescription          = Süreç oluşturma ve komut satırı denetleme olayları.
ThirdPartyAVInstalled                     = Üçüncü taraf bir antivirüs yüklüdür.
EnableHardwareVT                          = UEFI'dan sanallaştırmayı aktifleştirin.
ThirdPartyArchiverInstalled               = Üçüncü taraf bir arşivleyici yüklenmiştir.
RestartWarning                            = Bilgisayarınızı yeniden başlatmayı unutmayın.
RestorePointVolume                        = C sürücüsündeki geri yükleme noktaları {0} GB yer kaplıyor.
ErrorsLine                                = Satır
ErrorsMessage                             = Hatalar, uyarılar ve bildirimler
Disable                                   = Devre dışı bırak
Enable                                    = Aktif et
Install                                   = Yükle
Uninstall                                 = Kaldır
RestartFunction                           = Lütfen "{0}" işlevini yeniden çalıştırın.
NoConnectionEstablished                   = {0} ile bağlantı kurulamadı.
Run                                       = Başlat
FunctionSkipped                           = "{0}" işlevi atlandı.
DonateToastTitle                          = Bağışlarınızı bekliyoruz!❤
DotSourcedFunction                        = Lütfen işlevi "nokta-kaynaklı" (başında nokta olan) olarak yazın:\n. .\\Import-TabCompletion.ps1
'@
