ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Este script solo soporta Windows 10 x64
UnsupportedOSBuild                        = Este script solo soporta Windows 10 1809 Enterprise LTSC
UnsupportedRelease                        = Nueva versión encontrada
ControlledFolderAccessDisabled            = Acceso a carpetas controlado desactivado
ScheduledTasks                            = Tareas programadas
WindowsFeaturesTitle                      = Características de Windows
OptionalFeaturesTitle                     = Características opcionales
EnableHardwareVT                          = Activar virtualización en UEFI
UserShellFolderNotEmpty                   = Quedan algunos archivos en  la carpeta "{0}". Muévalos manualmente a la nueva ubicación
RetrievingDrivesList                      = Recuperando lista de unidades de disco...
DriveSelect                               = Seleccione la unidad dentro de la raíz de la cual se creará la carpeta "{0}"
UserFolderRequest                         = ¿Le gustaría cambiar la ubicación de la carpeta "{0}"?
UserFolderSelect                          = Seleccione una carpeta para la carpeta "{0}"
UserDefaultFolder                         = ¿Le gustaría cambiar la ubicación de la carpeta "{0}" al valor predeterminado?
GraphicsPerformanceTitle                  = Preferencia de rendimiento de gráficos
GraphicsPerformanceRequest                = Quieres establecer el nivel de rendimiento de gráficos a "Alto rendimiento" en alguna aplicación?
TaskNotificationTitle                     = Notificación
CleanupTaskNotificationTitle              = Información importante
CleanupTaskDescription                    = Limpiando archivos de Windows no usados y actualizaciones usando la aplicación de limpieza de disco incorporada
CleanupTaskNotificationEventTitle         = ¿Ejecutar la tarea para limpiar archivos y actualizaciones no utilizados de Windows?
CleanupTaskNotificationEvent              = La limpieza de Windows no tardará mucho. La próxima vez, la notificación aparecerá en 30 días
CleanupTaskNotificationSnoozeInterval     = Seleccione un intervalo de recordatorio
CleanupNotificationTaskDescription        = Recordatorio de notificación emergente sobre la limpieza de archivos y actualizaciones no utilizados de Windows
SoftwareDistributionTaskNotificationEvent = La caché de actualización de Windows se eliminó correctamente
TempTaskNotificationEvent                 = La carpeta de archivos temporales se limpió correctamente
FolderTaskDescription                     = Limpieza de la carpeta "{0}"
ControlledFolderAccess                    = Acceso controlado a carpetas
ProtectedFoldersRequest                   = ¿Quieres añadir control de acceso a carpeta y especificar que carpeta Microsoft Defender protegerá de aplicaciones maliciosas y amenazas?
ProtectedFoldersListRemoved               = Carpetas eliminadas
AppControlledFolderRequest                = Quieres especificar una aplicación para que sea permitida a través del acceso controlado de carpetas?
AllowedControlledFolderAppsRemoved        = Eliminar aplicaciones permitidas
DefenderExclusionFolderRequest            = ¿Quieres especificar una carpeta para ser excluida por Microsoft Defender?
DefenderExclusionFoldersListRemoved       = Quitadas carpetas excluidas
AddDefenderExclusionFileRequest           = ¿Quieres especificar un archivo para ser excluido por Microsoft Defender?
DefenderExclusionFilesRemoved             = Quitados archivos excluidos
EventViewerCustomViewName                 = Creación de procesos
EventViewerCustomViewDescription          = Creación de procesos y eventos de auditoria de línea de comandos
RestartWarning                            = Asegúrese de reiniciar su PC
ErrorsLine                                = Línea
ErrorsFile                                = Archivo
ErrorsMessage                             = Errores/Advertencias
Add                                       = Añadir
AllFilesFilter                            = Tutti i file (*.*)|*.*
Change                                    = Cambiar
DialogBoxOpening                          = Mostrando caja de diálogo...
Disable                                   = Desactivar
Dismiss                                   = Despedir
Enable                                    = Activar
EXEFilesFilter                            = *.exe|*.exe|Todos los Archivos (*.*)|*.*
FolderSelect                              = Seleccione una carpeta
FilesWontBeMoved                          = Los archivos no se moverán
FourHours                                 = 4 horas
HalfHour                                  = 30 minutos
Install                                   = Instalar
Minute                                    = 1 minuto
NoData                                    = Nada que mostrar
NoInternetConnection                      = No hay conexión a Internet
NoResponse                                = No se pudo establecer una conexión con https://store.rg-adguard.net
Patient                                   = Por favor espere...
Run                                       = Iniciar
Select                                    = Seleccionar
SelectAll                                 = Seleccionar todo
Skip                                      = Omitir
Skipped                                   = Omitido
Snooze                                    = Posponer
SymbolicSkipped                           = Se omitió la creación de un enlace simbólico
Uninstall                                 = Desinstalar
'@
