ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                  = Este script solo soporta Windows 10 x64
UnsupportedOSBuild                    = Este script solo soporta Windows 10 1809 Enterprise LTSC
UnsupportedRelease                    = Nueva versión encontrada
ControlledFolderAccessDisabled        = Acceso a carpetas controlado desactivado
ScheduledTasks                        = Tareas programadas
ClearFolder                           = Elimine todos los archivos en la carpeta "{0}"?
FilesBlocked                          = Los siguientes archivos están siendo bloqueados por una aplicación de terceros. Elimínelos manualmente y continúe
TempNotEmpty                          = La carpeta "{0}" no está vacía. Límpiela manualmente
WindowsFeaturesTitle                  = Características de Windows
OptionalFeaturesTitle                 = Características opcionales
EnableHardwareVT                      = Activar virtualización en UEFI
UserShellFolderNotEmpty               = Quedan algunos archivos en  la carpeta "{0}". Muévalos manualmente a la nueva ubicación
RetrievingDrivesList                  = Recuperando lista de unidades de disco...
NewUserShellFolderLocation            = Nueva ubicación: "{0}"
DesktopDriveSelect                    = Selecciona la raíz del disco en la cual se creará la carpeta del Escritorio
DocumentsDriveSelect                  = Selecciona la raíz del disco en la cual se creará la carpeta de Documentos
DownloadsDriveSelect                  = Selecciona la raíz del disco en la cual se creará la carpeta de Descargas
MusicDriveSelect                      = Selecciona la raíz del disco en la cual se creará la carpeta de Música
PicturesDriveSelect                   = Selecciona la raíz del disco en la cual se creará la carpeta de Imágenes
VideosDriveSelect                     = Selecciona la raíz del disco en la cual se creará la carpeta de Vídeos
DesktopRequest                        = ¿Quieres cambiar la ubicación de la carpeta del Escritorio?
DocumentsRequest                      = ¿Quieres cambiar la ubicación de la carpeta de Documentos?
DownloadsRequest                      = ¿Quieres cambiar la ubicación de la carpeta de Descargas?
MusicRequest                          = ¿Quieres cambiar la ubicación de la carpeta de Música?
PicturesRequest                       = ¿Quieres cambiar la ubicación de la carpeta de Imágenes?
VideosRequest                         = ¿Quieres cambiar la ubicación de la carpeta de Vídeos?
DesktopFolderSelect                   = Selecciona una carpeta para la carpeta del Escritorio
DocumentsFolderSelect                 = Selecciona una carpeta para la carpeta de Documentos
DownloadsFolderSelect                 = Selecciona una carpeta para la carpeta de Descargas
MusicFolderSelect                     = Selecciona una carpeta para la carpeta de Música
PicturesFolderSelect                  = Selecciona una carpeta para la carpeta de Imágenes
VideosFolderSelect                    = Selecciona una carpeta para la carpeta de Vídeos
DesktopDefaultFolder                  = ¿Quieres cambiar la ubicación de la carpeta del Escritorio por la de defecto?
DocumentsDefaultFolder                = ¿Quieres cambiar la ubicación de la carpeta de Documentos por la de defecto?
DownloadsDefaultFolder                = ¿Quieres cambiar la ubicación de la carpeta de Descargas por la de defecto?
MusicDefaultFolder                    = ¿Quieres cambiar la ubicación de la carpeta de Música por la de defecto?
PicturesDefaultFolder                 = ¿Quieres cambiar la ubicación de la carpeta de Imágenes por la de defecto?
VideosDefaultFolder                   = ¿Quieres cambiar la ubicación de la carpeta de Vídeos por la de defecto?
GraphicsPerformanceTitle              = Preferencia de rendimiento de gráficos
GraphicsPerformanceRequest            = Quieres establecer el nivel de rendimiento de gráficos a "Alto rendimiento" en alguna aplicación?
CleanupTaskDescription                = Limpiando archivos de Windows no usados y actualizaciones usando la aplicación de limpieza de disco incorporada
CleanupTaskNotificationTitle          = Información importante
CleanupTaskNotificationEventTitle     = ¿Ejecutar la tarea para limpiar archivos y actualizaciones no utilizados de Windows?
CleanupTaskNotificationEvent          = La limpieza de Windows no tardará mucho. La próxima vez, la notificación aparecerá en 30 días
CleanupTaskNotificationSnoozeInterval = Seleccione un intervalo de recordatorio
CleanupNotificationTaskDescription    = Recordatorio de notificación emergente sobre la limpieza de archivos y actualizaciones no utilizados de Windows
FolderTaskDescription                 = Limpieza de la carpeta "{0}"
ControlledFolderAccess                = Acceso controlado a carpetas
ProtectedFoldersRequest               = ¿Quieres añadir control de acceso a carpeta y especificar que carpeta Microsoft Defender protegerá de aplicaciones maliciosas y amenazas?
ProtectedFoldersListRemoved           = Carpetas eliminadas
AppControlledFolderRequest            = Quieres especificar una aplicación para que sea permitida a través del acceso controlado de carpetas?
AllowedControlledFolderAppsRemoved    = Eliminar aplicaciones permitidas
DefenderExclusionFolderRequest        = ¿Quieres especificar una carpeta para ser excluida por Microsoft Defender?
DefenderExclusionFoldersListRemoved   = Quitadas carpetas excluidas
AddDefenderExclusionFileRequest       = ¿Quieres especificar un archivo para ser excluido por Microsoft Defender?
DefenderExclusionFilesRemoved         = Quitados archivos excluidos
EventViewerCustomViewName             = Creación de procesos
EventViewerCustomViewDescription      = Creación de procesos y eventos de auditoria de línea de comandos
RestartWarning                        = Asegúrese de reiniciar su PC
ErrorsLine                            = Línea
ErrorsFile                            = Archivo
ErrorsMessage                         = Errores/Advertencias
Add                                   = Añadir
AllFilesFilter                        = Tutti i file (*.*)|*.*
Change                                = Cambiar
Continue                              = Continuar
DialogBoxOpening                      = Mostrando caja de diálogo...
Disable                               = Desactivar
Dismiss                               = Despedir
Enable                                = Activar
EXEFilesFilter                        = *.exe|*.exe|Todos los Archivos (*.*)|*.*
FolderSelect                          = Seleccione una carpeta
FilesWontBeMoved                      = Los archivos no se moverán
Minute                                = 1 minuto
NoData                                = Nada que mostrar
NoInternetConnection                  = No hay conexión a Internet
NoResponse                            = No se pudo establecer una conexión con https://store.rg-adguard.net
Patient                               = Por favor espere...
Run                                   = Iniciar
Select                                = Seleccionar
Skip                                  = Omitir
Skipped                               = Omitido
Snooze                                = Posponer
SymbolicSkipped                       = Se omitió la creación de un enlace simbólico
Uninstall                             = Desinstalar
Install                               = Instalar
HalfHour                              = 30 minutos
FourHours                             = 4 horas
'@
