ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Este script solo soporta Windows 10 x64
UnsupportedOSBuild                        = Este script solo soporta Windows 10 1809 Enterprise LTSC
UnsupportedRelease                        = Nueva versión encontrada
ControlledFolderAccessDisabled            = Acceso a la carpeta controlada deshabilitado
ScheduledTasks                            = Tareas programadas
WindowsFeaturesTitle                      = Características de Windows
OptionalFeaturesTitle                     = Características opcionales
EnableHardwareVT                          = Habilitar la virtualización en UEFI
UserShellFolderNotEmpty                   = Algunos archivos quedan en la carpeta "{0}". Moverlos manualmente a una nueva ubicación
RetrievingDrivesList                      = Recuperando lista de unidades...
DriveSelect                               = Seleccione la unidad dentro de la raíz de la cual se creó la carpeta "{0}"
UserFolderRequest                         = ¿Le gustaría cambiar la ubicación de la "{0}" carpeta?
UserFolderSelect                          = Seleccione una carpeta para la carpeta "{0}"
UserDefaultFolder                         = ¿Le gustaría cambiar la ubicación de la carpeta "{0}" al valor predeterminado?
GraphicsPerformanceTitle                  = Preferencia de rendimiento gráfico
GraphicsPerformanceRequest                = ¿Le gustaría establecer la configuración de rendimiento gráfico de una aplicación de su elección a "alto rendimiento"?
TaskNotificationTitle                     = Notificación
CleanupTaskNotificationTitle              = Información importante
CleanupTaskDescription                    = La limpieza de Windows los archivos no utilizados y actualizaciones utilizando una función de aplicación de limpieza de discos
CleanupTaskNotificationEventTitle         = ¿Ejecutar la tarea de limpiar los archivos no utilizados y actualizaciones de Windows?
CleanupTaskNotificationEvent              = Ventanas de limpieza no tomará mucho tiempo. La próxima vez que esta notificación aparecerá en 30 días
CleanupTaskNotificationSnoozeInterval     = Seleccionar un recordatorio del intervalo
CleanupNotificationTaskDescription        = Pop-up recordatorio de notificaciones sobre la limpieza de archivos no utilizados de Windows y actualizaciones
SoftwareDistributionTaskNotificationEvent = La caché de actualización de Windows eliminado correctamente
TempTaskNotificationEvent                 = Los archivos de la carpeta Temp limpiados con éxito
FolderTaskDescription                     = La limpieza de la carpeta "{0}"
ControlledFolderAccess                    = Acceso a la carpeta controlada
ProtectedFoldersRequest                   = ¿Le gustaría permitir el acceso controlado carpeta y especifique la carpeta que Microsoft Defender protegerá de aplicaciones maliciosas y amenazas?
ProtectedFoldersListRemoved               = Se han eliminado las carpetas
AppControlledFolderRequest                = ¿Le gustaría especificar una aplicación que se le permite el acceso a través de carpetas controladas?
AllowedControlledFolderAppsRemoved        = Aplicaciones permitidas eliminadas
DefenderExclusionFolderRequest            = ¿Le gustaría especificar una carpeta que se excluyen del análisis de malware Microsoft Defender?
DefenderExclusionFoldersListRemoved       = Carpetas excluidas removidas
AddDefenderExclusionFileRequest           = ¿Le gustaría especificar un archivo que se excluyen del análisis de malware Microsoft Defender?
DefenderExclusionFilesRemoved             = Archivos excluidos eliminados
EventViewerCustomViewName                 = Creación de proceso
EventViewerCustomViewDescription          = Eventos de auditoría de línea de comandos y creación de procesos
RestartWarning                            = Asegúrese de reiniciar su PC
ErrorsLine                                = Línea
ErrorsFile                                = Archivo
ErrorsMessage                             = Errores/Advertencias
Add                                       = Agregar
AllFilesFilter                            = Todos los archivos (*.*)|*.*
Change                                    = Cambio
DialogBoxOpening                          = Viendo el cuadro de diálogo...
Disable                                   = Desactivar
Enable                                    = Habilitar
EXEFilesFilter                            = *.exe|*.exe|Todos los Archivos (*.*)|*.*
FolderSelect                              = Seleccione una carpeta
FilesWontBeMoved                          = Los archivos no se transferirán
FourHours                                 = 4 horas
HalfHour                                  = 30 minutos
Install                                   = Instalar
Minute                                    = 1 minuto
NoData                                    = Nada que mostrar
NoInternetConnection                      = No hay conexión a Internet
NoResponse                                = No se pudo establecer una conexión con https://store.rg-adguard.net
Open                                      = Abierta
Patient                                   = Por favor espere...
Restore                                   = Restaurar
Run                                       = Iniciar
Select                                    = Seleccionar
SelectAll                                 = Seleccionar todo
Skip                                      = Omitir
Skipped                                   = Omitido
TelegramTitle                             = Únete a nuestro canal oficial de Telegram
Uninstall                                 = Desinstalar
'@
