ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Lo script supporta solo Windows 10 x64
UnsupportedOSBuild                        = Lo script supporta Windows 10 versione 1809 Enterprise LTSC
UnsupportedRelease                        = Nuova versione trovata
ControlledFolderAccessDisabled            = l'accesso alle cartelle controllata disattivata
ScheduledTasks                            = Attività pianificate
WindowsFeaturesTitle                      = Funzionalità di Windows
OptionalFeaturesTitle                     = Caratteristiche opzionali
EnableHardwareVT                          = Abilita virtualizzazione in UEFI
UserShellFolderNotEmpty                   = Alcuni file lasciati nella cartella "{0}". li spostare manualmente in una nuova posizione
RetrievingDrivesList                      = Recupero lista unità...
DriveSelect                               = Selezionare l'unità all'interno della radice del quale verrà creato il "{0}" cartella
UserFolderRequest                         = Volete cambiare la posizione del "{0}" cartella?
UserFolderSelect                          = Selezionare una cartella per la cartella "{0}"
UserDefaultFolder                         = Volete cambiare la posizione della cartella "{0}" al valore di default?
GraphicsPerformanceTitle                  = Preferenza per le prestazioni grafiche
GraphicsPerformanceRequest                = Volete impostare l'impostazione prestazioni grafiche di un app di vostra scelta per "performance High"?
TaskNotificationTitle                     = Notifica
CleanupTaskNotificationTitle              = Informazioni importanti
CleanupTaskDescription                    = Pulizia di Windows i file inutilizzati e aggiornamenti utilizzando built-in Disk pulizia app
CleanupTaskNotificationEventTitle         = Eseguire compito di ripulire i file inutilizzati e aggiornamenti di Windows?
CleanupTaskNotificationEvent              = Di Windows pulizia non ci vorrà molto. La prossima volta che verrà visualizzata la notifica in 30 giorni
CleanupTaskNotificationSnoozeInterval     = Selezionare un promemoria intervallo
CleanupNotificationTaskDescription        = Pop-up promemoria notifica di pulizia di Windows file inutilizzati e aggiornamenti
SoftwareDistributionTaskNotificationEvent = La cache di aggiornamento di Windows cancellato con successo
TempTaskNotificationEvent                 = I file cartella Temp puliti con successo
FolderTaskDescription                     = La pulizia della cartella "{0}"
ControlledFolderAccess                    = l'accesso alle cartelle Controlled
ProtectedFoldersRequest                   = Vuoi per consentire l'accesso alle cartelle Controllata e specificare la cartella in cui Microsoft Defender protegge dalle applicazioni malevoli e minacce?
ProtectedFoldersListRemoved               = Cartelle rimossi
AppControlledFolderRequest                = Volete specificare un app che è consentito attraverso l'accesso controllato cartella?
AllowedControlledFolderAppsRemoved        = Applicazioni consentite rimosse
DefenderExclusionFolderRequest            = Volete specificare una cartella da escludere dalla Microsoft Defender scansioni di malware?
DefenderExclusionFoldersListRemoved       = Cartelle escluse rimossi
AddDefenderExclusionFileRequest           = Volete specificare un file da escludere dalla Microsoft Defender scansioni di malware?
DefenderExclusionFilesRemoved             = File esclusi rimossi
EventViewerCustomViewName                 = Creazione di processo
EventViewerCustomViewDescription          = Creazione di processi ed eventi di controllo della riga di comando
RestartWarning                            = Assicurarsi di riavviare il PC
ErrorsLine                                = Linea
ErrorsFile                                = File
ErrorsMessage                             = Errori/avvisi
Add                                       = Inserisci
AllFilesFilter                            = Tutti i file (*.*)|*.*
Change                                    = Modificare
DialogBoxOpening                          = Visualizzazione della finestra di dialogo...
Disable                                   = Disattivare
Enable                                    = Abilitare
EXEFilesFilter                            = *.exe|*.exe|Tutti i file (*.*)|*.*
FolderSelect                              = Selezionare una cartella
FilesWontBeMoved                          = I file non verranno trasferiti
FourHours                                 = 4 ore
HalfHour                                  = 30 minuti
Install                                   = Installare
Minute                                    = 1 minuto
NoData                                    = Niente da esposizione
NoInternetConnection                      = Nessuna connessione Internet
NoResponse                                = Non è stato possibile stabilire una connessione con https://store.rg-adguard.net
Open                                      = Aperto
Patient                                   = Attendere prego...
Restore                                   = Ristabilire
Run                                       = Eseguire
Select                                    = Selezionare
SelectAll                                 = Seleziona tutto
Skip                                      = Salta
Skipped                                   = Saltato
TelegramTitle                             = Unisciti al nostro canale ufficiale di Telegram
Uninstall                                 = Disinstallare
'@
