ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                   = Questo script supporta solo Windows 10 x64
UnsupportedOSBuild                     = Lo script supporta le versioni di Windows 10 1809 Enterprise LTSC
UnsupportedRelease                     = Nuova versione trovata
ControlledFolderAccessDisabled         = Accesso controllato alle cartelle disabilitato
ScheduledTasks                         = Attività pianificate
ClearFolder                            = Elimina tutti i file nella cartella "{0}"?
FilesBlocked                           = I seguenti file sono bloccati da app di terze parti. Rimuoverli manualmente e continua
TempNotEmpty                           = La cartella "{0}" non è vuota. Pulirla manualmente
WindowsFeaturesWindowTitle             = Funzionalità Windows
FODWindowTitle                         = Funzionalità facoltative (FODv2)
EnableHardwareVT                       = Attiva Virtualizzazione in UEFI
UserShellFolderNotEmpty                = Sono rimasti alcuni file nella cartella "{0}". Spostarli manualmente in una nuova posizione.
RetrievingDrivesList                   = Recupero lista delle unità...
NewUserShellFolderLocation             = Nuova posizione: "{0}"
DesktopDriveSelect                     = Seleziona l'unità all'interno della radice nella quale verrà creata la cartella Dekstop
DocumentsDriveSelect                   = Seleziona l'unità all'interno della radice nella quale verrà creata la cartella Documenti
DownloadsDriveSelect                   = Seleziona l'unità all'interno della radice nella quale verrà creata la cartella Download
MusicDriveSelect                       = Seleziona l'unità all'interno della radice nella quale verrà creata la cartella Musica
PicturesDriveSelect                    = Seleziona l'unità all'interno della radice nella quale verrà creata la cartella Immagini
VideosDriveSelect                      = Seleziona l'unità all'interno della radice della quale verrà creata la cartella Video
DesktopRequest                         = Desideri cambiare la posizione della cartella Desktop?
DocumentsRequest                       = Desideri cambiare la posizione della cartella Documenti?
DownloadsRequest                       = Desideri cambiare la posizione della cartella Download?
MusicRequest                           = Desideri cambiare la posizione della cartella Musica?
PicturesRequest                        = Desideri cambiare la posizione della cartella Immagini?
VideosRequest                          = Desideri cambiare la posizione della cartella Video?
DesktopFolderSelect                    = Seleziona una cartella per Desktop
DocumentsFolderSelect                  = Seleziona una cartella per Documenti
DownloadsFolderSelect                  = Seleziona una cartella per Download
MusicFolderSelect                      = Seleziona una cartella per Musica
PicturesFolderSelect                   = Seleziona una cartella per Immagini
VideosFolderSelect                     = Seleziona una cartella per Video
DesktopDefaultFolder                   = Desideri modificare la posizione della cartella Desktop sul valore predefinito?
DocumentsDefaultFolder                 = Desideri modificare la posizione della cartella Documenti sul valore predefinito?
DownloadsDefaultFolder                 = Desideri modificare la posizione della cartella Download sul valore predefinito?
MusicDefaultFolder                     = Desideri modificare la posizione della cartella Musica sul valore predefinito?
PicturesDefaultFolder                  = Desideri modificare la posizione della cartella Immagini sul valore predefinito?
VideosDefaultFolder                    = Desideri modificare la posizione della cartella Video sul valore predefinito?
GraphicsPerformanceTitle               = Preferenze prestazioni della Grafica
GraphicsPerformanceRequest             = Desideri impostare le prestazioni grafiche di un app di tua scelta su "Prestazioni elevate"?
CleanUpTaskToast                       = La pulizia dei file e degli aggiornamenti di Windows inutilizzati inizia in un minuto
CleanUpTaskDescription                 = Pulizia di file e aggiornamenti di Windows inutilizzati utilizzando l'app di pulizia del disco incorporata
FolderTaskDescription                  = Pulizia della cartella "{0}"
ControlledFolderAccess                 = Accesso controllato alle cartelle
ProtectedFoldersRequest                = Desideri abilitare l'accesso controllato alle cartelle e specificare la cartella che Microsoft Defender proteggerà dalle app dannose e dalle minacce?
ProtectedFoldersListRemoved            = Cartelle rimosse
AppControlledFolderRequest             = Desideri specificare un'app consentita tramite l'accesso alle cartelle controllate?
AllowedControlledFolderAppsRemoved     = App consentite rimosse
DefenderTitle                          = Microsoft Defender
DefenderExclusionFolderRequest         = Desideri specificare una cartella da escludere dalle scansioni del malware di Microsoft Defender?
DefenderExclusionFoldersListRemoved    = Cartelle escluse rimosse
AddDefenderExclusionFileRequest        = Desideri specificare un file da escludere dalle scansioni del malware di Microsoft Defender?
DefenderExclusionFilesRemoved          = File esclusi rimossi
EventViewerCustomViewName              = Creazione del Processo
EventViewerCustomViewDescription       = Creazione di Processi ed Eventi di Controllo dalla riga di comando
RestartWarning                         = Assicurati di riavviare il PC
ErrorsLine                             = Linea
ErrorsFile                             = File
ErrorsMessage                          = Errori/Avvisi
Add                                    = Aggiungi
AllFilesFilter                         = Tutti i file (*.*)|*.*
Change                                 = Cambia
Continue                               = Continua
DialogBoxOpening                       = Visualizzazione della finestra di dialogo...
Disable                                = Disinstalla
Enable                                 = Abilita
EXEFilesFilter                         = *.exe|*.exe|Tutti i file (*.*)|*.*
FolderSelect                           = Seleziona una cartella
FilesWontBeMoved                       = I file non verranno spostati
NoData                                 = Nulla da visualizzare
NoInternetConnection                   = Nessuna connessione Internet
Patient                                = Attendere prego...
Select                                 = Selezionare
Skip                                   = Salta
Skipped                                = Saltato
SymbolicSkipped                        = È stata saltata la creazione di un collegamento simbolico
Uninstall                              = Rimuovi
Install                                = Installare
'@
