ConvertFrom-StringData -StringData @'
PowerShellImportFailed                    = A modulok importálása a PowerShell 5.1-ből sikertelen volt. Zárja be a PowerShell 7 konzolt, és futtassa újra a szkriptet.
UnsupportedArchitecture                   = Ön "{0}" alapú architektúrájú CPU-t használ. Ez a szkript csak x64 architektúrájú CPU-kat támogat. Töltse le és futtassa az Ön architektúrájához megfelelő szkript verziót.
UnsupportedOSBitness                      = A szkript csak a 64 bites Windows-t támogatja.
UnsupportedOSBuild                        = A szkript csak a Windows 10 22H2 rendszert támogatja. {0} {1}-et használsz. Frissítse a Windows-t, és próbálja meg újra.
UnsupportedWindowsTerminal                = A Windows Terminal verziója alacsonyabb, mint 1.23. Kérjük, frissítse azt a Microsoft Store-ban, és próbálja meg újra.
UpdateWarning                             = Vous utilisez Windows 10 {0}.{1}. La version prise en charge est Windows 10 {0}.{2} et supérieure. Exécutez Windows Update et réessayez.
UnsupportedLanguageMode                   = A PowerShell munkamenet korlátozott nyelvi üzemmódban fut.
LoggedInUserNotAdmin                      = A bejelentkezett felhasználó, {0}, nem rendelkezik rendszergazdai jogokkal. A szkript {1} nevében futott. Kérjük, jelentkezzen be egy rendszergazdai jogokkal rendelkező fiókba, és futtassa újra a szkriptet.
UnsupportedPowerShell                     = A PowerShell {0}.{1} segítségével próbálja futtatni a szkriptet. Kérjük, futtassa a szkriptet a PowerShell {2}-ben.
CodeCompilationFailedWarning              = A kód fordítása sikertelen volt.
UnsupportedHost                           = A szkript nem támogatja a {0} futtatását.
Win10TweakerWarning                       = Valószínűleg az operációs rendszerét a Win 10 Tweaker backdoor segítségével fertőzték meg.
TweakerWarning                            = A Windows operációs rendszer stabilitását veszélyeztethette a {0}. Ponovno instalirajte Windows koristeći samo originalnu ISO sliku.
HostsWarning                              = A {0} fájlban található harmadik féltől származó bejegyzések. Ezek blokkolhatják a szkriptben használt erőforrásokhoz való kapcsolódást. Folytatni szeretné?
RebootPending                             = A számítógép újraindításra vár.
BitLockerWarning                          = A BitLocker titkosítás folyamatban van. Végezze el a BitLocker meghajtó konfigurálását, majd próbálkozzon újra.
UnsupportedRelease                        = Újabb Sophia Script verzió található: {0}. Kérjük, töltse le a legújabb verziót.
KeyboardArrows                            = Kérjük, használja a billentyűzet {0} és {1} nyílbillentyűit a válasz kiválasztásához
CustomizationWarning                      = Személyre szabott minden opciót a {0} preset fájlban, mielőtt futtatni kívánja a Sophia szkriptet?
WindowsComponentBroken                    = A {0} elromlott vagy eltávolították az operációs rendszerből. Ponovno instalirajte Windows koristeći samo originalnu ISO sliku.
MicroSoftStorePowerShellWarning           = A Microsoft Store-ból letöltött PowerShell nem támogatott. Kérjük, futtasson egy MSI verziót.\nhttps://github.com/powershell/powershell/releases/latest
ControlledFolderAccessDisabled            = Vezérelt mappához való hozzáférés kikapcsolva.
ScheduledTasks                            = Ütemezett feladatok
UninstallNotification                     = A {0} eltávolításra kerül...
DownloadNotification                      = A {0} letöltése folyamatban van...
InstallNotification                       = A {0} telepítése folyamatban van...
OneDriveUsageWarning                      = Kérjük, jelentkezzen ki a OneDrive-fiókjából, mielőtt eltávolítja az alkalmazást.
WindowsFeaturesTitle                      = Windows szolgáltatások
OptionalFeaturesTitle                     = Opcionális szolgáltatások
EnableHardwareVT                          = Virtualizáció engedélyezése UEFI-ben.
UserShellFolderNotEmpty                   = Néhány fájl maradt a "{0}" könyvtárban. Kérem helyezze át ezeket egy új helyre.
UserFolderLocationMove                    = Nem szabad megváltoztatni a felhasználói mappa helyét a C meghajtó gyökerére.
DriveSelect                               = Válassza ki a meghajtó jelét a gyökérkönyvtárban ahol a "{0}" könyvtár létre lesz hozva.
CurrentUserFolderLocation                 = Az aktuális "{0}" mappa helye: "{1}".
UserFolderRequest                         = Kívánja megváltoztatni a "{0}" könyvtár helyét?
UserDefaultFolder                         = Szeretné visszaállítani a "{0}" könyvtár helyét a gyári értékekre?
ReservedStorageIsInUse                    = Ez a művelet nem hajtható végre, amíg a fenntartott tárhely használatban van\nPonovno pokrenite funkciju "{0}" nakon ponovnog pokretanja računala.
ShortcutPinning                           = A gyorsindító ikon "{0}" Startmenüre helyezése...
UninstallUWPForAll                        = Az összes felhasználó számára
UWPAppsTitle                              = UWP Alkalmazások
GraphicsPerformanceTitle                  = Szeretné megváltoztatni a grafikus teljesítmény beállítást az ön által kiválasztott alkalmazásban "Nagy teljesítményre"?
ScheduledTaskPresented                    = A "{0}" funkciót már létrehoztuk "{1}" néven.
CleanupTaskNotificationTitle              = Windows tisztítása
CleanupTaskNotificationEvent              = Szeretné a nem használt fájlokat es frissitéseket eltávolítani?
CleanupTaskDescription                    = A nem használt Windows fájlok és frissítések eltávolítása a beépített lemezkarbantartó alkalmazással. Az ütemezett feladat csak akkor futtatható, ha "{0}" felhasználó bejelentkezett a rendszerbe.
CleanupNotificationTaskDescription        = Előugró emlékeztető figyelmeztetés a nem használt Windows fájlok és frissítések törléséről. Az ütemezett feladat csak akkor futtatható, ha "{0}" felhasználó bejelentkezett a rendszerbe.
SoftwareDistributionTaskNotificationEvent = A Windows frissités számára fenntartott ideiglenes tárhely sikeresen megtisztítva.
TempTaskNotificationEvent                 = Az ideiglenes fájlok tárolására szolgáló könyvtár tisztítása sikeresen megtörtént.
FolderTaskDescription                     = A {0} könyvtár tisztítása. Az ütemezett feladat csak akkor futtatható, ha "{0}" felhasználó bejelentkezett a rendszerbe.
EventViewerCustomViewName                 = Folyamatok
EventViewerCustomViewDescription          = Folyamatok létrehozása és parancssor ellenőrző események.
RestartWarning                            = Kérem ne felejtse el újraindítani a számítógépét.
ErrorsLine                                = Sor
ErrorsMessage                             = Hibák/Figyelmeztetések
DialogBoxOpening                          = Párbeszédablak megjelenítése...
Disable                                   = Kikapcsolás
Enable                                    = Engedélyezés
AllFilesFilter                            = Minden fájl
FolderSelect                              = Válasszon ki egy könyvtárat
FilesWontBeMoved                          = A fájlok nem lesznek áthelyezve.
Install                                   = Telepítés
Uninstall                                 = Eltávolít
NoData                                    = Nincs megjeleníthető információ.
RestartFunction                           = Ponovo pokrenite funkciju "{0}".
NoResponse                                = Nem hozható létre kapcsolat a {0} weboldallal.
Restore                                   = Visszaállítás
Run                                       = Futtatás
Skipped                                   = Az "{0}" funkció kihagyva.
ThankfulToastTitle                        = Köszönjük, hogy használta a Sophia Script ❤️
DonateToastTitle                          = Az alábbi linken keresztül adományozhat 🕊
DotSourcedWarning                         = Kérjük, "dot-source"-olja a függvényt (egy ponttal az elején):\n. .\\Import-TabCompletion.ps1
'@
