ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = A szkript csak a 64 bites Windows-t támogatja
UnsupportedOSBuild                        = \nA szkript támogatja a Windows 10 Enterprise LTSC 2019 kiadást
UpdateWarning                             = \nA Windows 10 összesített frissítése telepítve: {0}. Támogatott kumulatív frissítés: 4131 és magasabb verziószámok. Futtassa a Windows Update programot, és próbálja meg újra
UnsupportedLanguageMode                   = \nA PowerShell munkamenet korlátozott nyelvi üzemmódban fut
LoggedInUserNotAdmin                      = \nA bejelentkezett felhasználó nem rendelkezik admin jogokkal
UnsupportedPowerShell                     = \nA PowerShell {0}.{1} segítségével próbálja futtatni a szkriptet. Futtassa a szkriptet a megfelelő PowerShell-verzióban
UnsupportedHost                           = \nA szkript nem támogatja a {0} futtatását
Win10TweakerWarning                       = \nValószínűleg az operációs rendszerét a Win 10 Tweaker backdoor segítségével fertőzték meg
TweakerWarning                            = \nA Windows operációs rendszer stabilitását veszélyeztethette a {0}. A biztonság kedvéért telepítse újra a Windowst
bin                                       = \nA bin mappában nincsenek fájlok. Kérjük, töltse le újra az archívumot
RebootPending                             = \nA számítógép újraindításra vár
UnsupportedRelease                        = \nÚj verzió érhető el
CustomizationWarning                      = \nSzemélyre szabott minden opciót a {0} preset fájlban, mielőtt futtatni kívánja a Sophia szkriptet?
DefenderBroken                            = \nA Microsoft Defender elromlott vagy eltávolították az operációs rendszerből
UpdateDefender                            = \nA Microsoft Defender definíciói elavultak. Futtassa a Windows Update programot, és próbálja meg újra
ControlledFolderAccessDisabled            = Vezérelt mappához való hozzáférés kikapcsolva
ScheduledTasks                            = Ütemezett feladatok
WindowsFeaturesTitle                      = Windows szolgáltatások
OptionalFeaturesTitle                     = Opcionális szolgáltatások
EnableHardwareVT                          = Virtualizáció engedélyezése UEFI-ben
UserShellFolderNotEmpty                   = Néhány fájl maradt a "{0}" könyvtárban. Kérem helyezze át ezeket egy új helyre
RetrievingDrivesList                      = A meghajtók listájának lekérése...
DriveSelect                               = Válassza ki a meghajtó jelét a gyökérkönyvtárban ahol a "{0}" könyvtár létre lesz hozva
CurrentUserFolderLocation                 = Az aktuális "{0}" mappa helye: "{1}"
UserFolderRequest                         = Kívánja megváltoztatni a "{0}" könyvtár helyét?
UserFolderSelect                          = Válasszon ki egy könyvtárat a "{0}" könyvtárhoz
UserDefaultFolder                         = Szeretné visszaállítani a "{0}" könyvtár helyét a gyári értékekre?
GraphicsPerformanceTitle                  = Grafikus teljesítmény tulajdonság
GraphicsPerformanceRequest                = Szeretné megváltoztatni a grafikus teljesítmény beállítást az ön által kiválasztott alkalmazásban "Nagy teljesítményre"?
ScheduledTaskPresented                    = A "{0}" funkciót már létrehoztuk "{1}" néven
CleanupTaskNotificationTitle              = Windows tisztítása
CleanupTaskNotificationEvent              = Szeretné a nem használt fájlokat es frissitéseket eltávolítani?
CleanupTaskDescription                    = A nem használt Windows fájlok és frissítések eltávolítása a beépített lemezkarbantartó alkalmazással
CleanupNotificationTaskDescription        = Előugró emlékeztető figyelmeztetés a nem használt Windows fájlok és frissítések törléséről
SoftwareDistributionTaskNotificationEvent = A Windows frissités számára fenntartott ideiglenes tárhely sikeresen megtisztítva
TempTaskNotificationEvent                 = Az ideiglenes fájlok tárolására szolgáló könyvtár tisztítása sikeresen megtörtént
FolderTaskDescription                     = A {0} könyvtár tisztítása
EventViewerCustomViewName                 = Folyamatok
EventViewerCustomViewDescription          = Folyamatok létrehozása és parancssor ellenőrző események
RestartWarning                            = Kérem ne felejtse el újraindítani a számítógépét
ErrorsLine                                = Sor
ErrorsMessage                             = Hibák/Figyelmeztetések
DialogBoxOpening                          = Párbeszédablak megjelenítése...
Disable                                   = Kikapcsolás
EXEFilesFilter                            = *.exe|*.exe|Minden fájl (*.*)|*.*
FolderSelect                              = Válasszon ki egy könyvtárat
FilesWontBeMoved                          = A fájlok nem lesznek áthelyezve
Install                                   = Telepítés
NoData                                    = Nincs megjeleníthető információ
NoInternetConnection                      = Nincs internetkapcsolat
RestartFunction                           = Ponovo pokrenite funkciju "{0}"
NoResponse                                = Nem hozható létre kapcsolat a {0} weboldallal
Restore                                   = Visszaállítás
Run                                       = Futtatás
Skipped                                   = Átugorva
GPOUpdate                                 = GPO frissítése...
TelegramGroupTitle                        = Pridružite se našoj službenoj grupi Telegram
TelegramChannelTitle                      = Pridružite se našem službenom kanalu Telegram
DiscordChannelTitle                       = Pridružite se našem službenom kanalu Discord
Uninstall                                 = Eltávolít
'@
