ConvertFrom-StringData -StringData @'
NewSophiaScriptFound                      = Elérhető egy új verzió: Sophia Script for Windows {0}. Kérjük, frissítse a programot.
UnsupportedPowerShell                     = A PowerShell {0}.{1} segítségével próbálja futtatni a szkriptet. Kérjük, futtassa a szkriptet a PowerShell {2}-ben.
CodeCompilationFailed                     = A kód fordítása sikertelen volt.
UnsupportedWindowsBitness                 = A szkript csak a 64 bites Windows-t támogatja.
KeyboardArrows                            = Kérjük, használja a billentyűzet {0} és {1} nyílbillentyűit a válasz kiválasztásához
UnsupportedLanguageMode                   = A PowerShell munkamenet korlátozott nyelvi üzemmódban fut.
LoggedInUserNotAdmin                      = A bejelentkezett felhasználó, "{0}", nem rendelkezik rendszergazdai jogokkal. A szkript "{1}" nevében futott. Kérjük, jelentkezzen be egy rendszergazdai jogokkal rendelkező fiókba, és futtassa újra a szkriptet.
UnsupportedHost                           = A szkript nem támogatja a {0} futtatását.
HarmfulTweakerFound                       = A Windows operációs rendszer stabilitását veszélyeztethette a {0}.
HostsEntriesFound                         = Harmadik féltől származó bejegyzések találhatóak a %SystemRoot%\\System32\\drivers\\etc\\hosts fájlban. Ezek blokkolhatják a szkriptben használt erőforrásokhoz való csatlakozást. Folytatni kívánja?
WindowsComponentStabilityDisrupted        = A "{0}" komponensben instabilitási problémát észleltek.
DisableControlledFolderAccess             = A mappákhoz való hozzáférés ellenőrzése engedélyezve van. Kérjük, tiltsa le, és futtassa újra a szkriptet.
RebootPending                             = A számítógép újraindításra vár.
SystemDriveEncryptedBitLockerDisabled     = A C meghajtó titkosítva van, bár a BitLocker ki van kapcsolva. Szeretné dekódolni a meghajtót?
WrongSophiaScriptVersion                  = A szkript csak a Windows 10 Enterprise LTSC 2019 rendszert támogatja. {0} {1}-et használsz. A Windows-verziónak megfelelő szkriptet futtassa.
UpdateWindowsBuild                        = Vous utilisez Windows 10 Enterprise LTSC 2019 {0}.{1}. La version prise en charge est Windows 11 {0}.{2} et supérieure. Exécutez Windows Update et réessayez.
CheckSophiaScriptPreset                   = A "Sophia Script for Windows" futtatása előtt testreszabta-e a {0} beállítási fájl összes funkcióját?
ReinstallWindows                          = Ponovno instalirajte Windows koristeći samo originalnu ISO sliku.
CreatingRestorePoint                      = Visszaállítási pont létrehozása folyamatban...
UWPComponentsMissing                      = Hiányzik a "{0}" UWP-komponens.
DefenderComponentsMissing                 = A Microsoft Defender "{0}" összetevője hiányzik.
DiagTrackServiceNotFound                  = A "DiagTrackService" szolgáltatás nem található.
NoScheduledTasksFound                     = Nincs letiltandó ütemezett feladat.
ScheduledTasks                            = Ütemezett feladatok
TaskbarSmallIcons                         = Kis tálca gombokat használ.
InstallingApplication                     = A {0} telepítése folyamatban van...
NoWindowsFeaturesFound                    = Nincs letiltandó Windows-funkció.
WindowsFeaturesTitle                      = Windows szolgáltatások
NoOptionalFeaturesFound                   = Nincs letiltható opcionális funkció.
NoSupportedNetworkAdaptersFound           = Nincs olyan hálózati adapter, amely támogatná az "Engedélyezze a számítógépnek, hogy energiatakarékossági okokból kikapcsolja ezt az eszközt" funkciót.
LocationServicesDisabled                  = A hálózati shell parancsokhoz helymeghatározási engedély szükséges a WLAN-adatok eléréséhez. Kapcsolja be a Helymeghatározás szolgáltatásokat a Adatvédelem és biztonság beállítások Helymeghatározás oldalon.
OptionalFeaturesTitle                     = Opcionális szolgáltatások
UserShellFolderNotEmpty                   = Néhány fájl maradt a "{0}" könyvtárban. Kérem helyezze át ezeket egy új helyre.
UserFolderLocationMove                    = Nem szabad megváltoztatni a felhasználói mappa helyét a C meghajtó gyökerére.
DriveSelect                               = Válassza ki azt a meghajtót, amelynek gyökérkönyvtárában a "{0}" mappa létrehozásra kerül.
CurrentUserFolderLocation                 = Az aktuális "{0}" mappa helye: "{1}".
FilesWontBeMoved                          = A fájlok nem kerülnek áthelyezésre.
UserFolderMoveSkipped                     = A felhasználó "{0}" mappájának helyét nem módosította.
FolderSelect                              = Válasszon ki egy mappát
UserFolderRequest                         = Kívánja megváltoztatni a "{0}" könyvtár helyét?
UserDefaultFolder                         = Szeretné visszaállítani a "{0}" könyvtár helyét a gyári értékekre?
ProgramPathNotExists                      = A "{0}" elérési út nem létezik.
ProgIdNotExists                           = A ProgId "{0}" nem létezik.
AllFilesFilter                            = Minden fájl
JSONNotValid                              = A JSON fájl "{0}" érvénytelen.
PackageNotInstalled                       = Az "{0}" alkalmazás nincs telepítve.
PackageIsInstalled                        = A {0} legújabb verziója már telepítve van.
ScheduledTaskCreatedByAnotherUser         = A "{0}" ütemezett feladatot már létrehozta a "{1}" felhasználó.
CleanupTaskNotificationTitle              = Windows tisztítása
CleanupTaskNotificationEvent              = Szeretné a nem használt fájlokat es frissitéseket eltávolítani?
CleanupTaskDescription                    = A nem használt Windows fájlok és frissítések eltávolítása a beépített lemezkarbantartó alkalmazással.
CleanupNotificationTaskDescription        = Előugró emlékeztető figyelmeztetés a nem használt Windows fájlok és frissítések törléséről.
SoftwareDistributionTaskNotificationEvent = A Windows frissités számára fenntartott ideiglenes tárhely sikeresen megtisztítva.
SoftwareDistributionTaskDescription       = A Windows Update "{0}" gyorsítótár-mappájának törlése.
TempTaskNotificationEvent                 = Az ideiglenes fájlok tárolására szolgáló könyvtár tisztítása sikeresen megtörtént.
TempTaskDescription                       = A "{0}" (%TEMP%) ideiglenes mappa törlése.
ScheduledTaskLoggedInUserNotification     = Az ütemezett feladat csak akkor futtatható, ha "{0}" felhasználó bejelentkezett a rendszerbe.
ScheduledTaskCreatedNotification          = Létrehozták a "{0}" nevű ütemezett feladatot.
CleanupTaskCLIDescription                 = Nyissa meg a Feladatütemező "Sophia" mappáját, és futtassa a "Windows Cleanup Notification" feladatot a Windows által nem használt fájlok és frissítések törlésének megkezdéséhez.
SoftwareDistributionTaskCLIDescription    = Nyissa meg a Feladatütemező "Sophia" mappáját, és futtassa a "SoftwareDistribution" feladatot a Windows Update "{0}" gyorsítótár-mappájának tisztításához.
TempTaskCLIDescription                    = Nyissa meg a Feladatütemező "Sophia" mappáját, és futtassa a "Temp" feladatot az "{0}" (%TEMP%) ideiglenes fájlok mappájának tisztításához.
EventViewerCustomViewName                 = Folyamatok
EventViewerCustomViewDescription          = Folyamatok létrehozása és parancssor ellenőrző események.
ThirdPartyAVInstalled                     = Harmadik féltől származó vírusirtó van telepítve.
EnableHardwareVT                          = Virtualizáció engedélyezése UEFI-ben.
ThirdPartyArchiverInstalled               = Egy harmadik fél által készített archívum van telepítve.
RestartWarning                            = Indítsa újra a számítógépet.
RestorePointVolume                        = A C meghajtó visszaállítási pontjai {0} GB helyet foglalnak.
ErrorsLine                                = Sor
ErrorsMessage                             = Hibák, figyelmeztetések és értesítések
Disable                                   = Kikapcsolás
Enable                                    = Engedélyezés
Install                                   = Telepítés
Uninstall                                 = Eltávolít
RestartFunction                           = Ponovo pokrenite funkciju "{0}".
NoConnectionEstablished                   = Nem hozható létre kapcsolat a {0} weboldallal.
Run                                       = Futtatás
FunctionSkipped                           = Az "{0}" funkció kihagyva.
DonateToastTitle                          = Adományokat szívesen fogadunk!❤
DotSourcedFunction                        = Kérjük, "dot-source"-olja a függvényt (egy ponttal az elején):\n. .\\Import-TabCompletion.ps1
'@
