ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = A szkript csak a 64 bites Windows-t támogatja.
UnsupportedOSBuild                        = A szkript támogatja a Windows 10 Enterprise LTSC 2019 kiadást.
UpdateWarning                             = Az Ön Windows 10 építése: {0}.{1}. Támogatott buildek: {2}+. Futtassa a Windows Update programot, és próbálja meg újra.
UnsupportedLanguageMode                   = A PowerShell munkamenet korlátozott nyelvi üzemmódban fut.
LoggedInUserNotAdmin                      = A bejelentkezett felhasználó nem rendelkezik admin jogokkal.
UnsupportedPowerShell                     = A PowerShell {0}.{1} segítségével próbálja futtatni a szkriptet. Futtassa a szkriptet a megfelelő PowerShell-verzióban.
UnsupportedHost                           = A szkript nem támogatja a {0} futtatását.
Win10TweakerWarning                       = Valószínűleg az operációs rendszerét a Win 10 Tweaker backdoor segítségével fertőzték meg.
TweakerWarning                            = A Windows operációs rendszer stabilitását veszélyeztethette a {0}. Ponovno instalirajte Windows koristeći samo originalnu ISO sliku.\nhttps://www.microsoft.com/software-download/windows10
Bin                                       = A bin mappában nincsenek fájlok. Kérjük, töltse le újra az archívumot.
RebootPending                             = A számítógép újraindításra vár.
UnsupportedRelease                        = Egy új szkriptverzió található. Kérjük, csak a legújabb Sophia Scriptet használja.
KeyboardArrows                            = Kérjük, használja a billentyűzet {0} és {1} nyílbillentyűit a válasz kiválasztásához
CustomizationWarning                      = Személyre szabott minden opciót a {0} preset fájlban, mielőtt futtatni kívánja a Sophia szkriptet?
WindowsComponentBroken                    = A {0} elromlott vagy eltávolították az operációs rendszerből.
UpdateDefender                            = A Microsoft Defender definíciói elavultak. Futtassa a Windows Update programot, és próbálja meg újra.
ControlledFolderAccessDisabled            = Vezérelt mappához való hozzáférés kikapcsolva.
InitialActionsCheckFailed                 = Az InitialActions funkció nem tölthető be a {0} előre beállított fájlból. Kérjük, ellenőrizze az előre beállított fájlt, és próbálja meg újra.
ScheduledTasks                            = Ütemezett feladatok
WindowsFeaturesTitle                      = Windows szolgáltatások
OptionalFeaturesTitle                     = Opcionális szolgáltatások
EnableHardwareVT                          = Virtualizáció engedélyezése UEFI-ben.
UserShellFolderNotEmpty                   = Néhány fájl maradt a "{0}" könyvtárban. Kérem helyezze át ezeket egy új helyre.
UserFolderLocationMove                    = Nem szabad megváltoztatni a felhasználói mappa helyét a C meghajtó gyökerére.
DriveSelect                               = Válassza ki a meghajtó jelét a gyökérkönyvtárban ahol a "{0}" könyvtár létre lesz hozva.
CurrentUserFolderLocation                 = Az aktuális "{0}" mappa helye: "{1}".
UserFolderRequest                         = Kívánja megváltoztatni a "{0}" könyvtár helyét?
UserDefaultFolder                         = Szeretné visszaállítani a "{0}" könyvtár helyét a gyári értékekre?
GraphicsPerformanceTitle                  = Szeretné megváltoztatni a grafikus teljesítmény beállítást az ön által kiválasztott alkalmazásban "Nagy teljesítményre"?
ScheduledTaskPresented                    = A "{0}" funkciót már létrehoztuk "{1}" néven.
CleanupTaskNotificationTitle              = Windows tisztítása
CleanupTaskNotificationEvent              = Szeretné a nem használt fájlokat es frissitéseket eltávolítani?
CleanupTaskDescription                    = A nem használt Windows fájlok és frissítések eltávolítása a beépített lemezkarbantartó alkalmazással. Az ütemezett feladat csak akkor futtatható, ha "{0}" felhasználó bejelentkezett a rendszerbe.
CleanupNotificationTaskDescription        = Előugró emlékeztető figyelmeztetés a nem használt Windows fájlok és frissítések törléséről. Az ütemezett feladat csak akkor futtatható, ha "{0}" felhasználó bejelentkezett a rendszerbe.
SoftwareDistributionTaskNotificationEvent = A Windows frissités számára fenntartott ideiglenes tárhely sikeresen megtisztítva.
TempTaskNotificationEvent                 = Az ideiglenes fájlok tárolására szolgáló könyvtár tisztítása sikeresen megtörtént.
FolderTaskDescription                     = A {0} könyvtár tisztítása. Az ütemezett feladat csak akkor futtatható, ha "{0}" felhasználó bejelentkezett a rendszerbe.
EventViewerCustomViewName                 = Folyamatok
EventViewerCustomViewDescription          = Folyamatok létrehozása és parancssor ellenőrző események.
RestartWarning                            = Kérem ne felejtse el újraindítani a számítógépét.
ErrorsLine                                = Sor
ErrorsMessage                             = Hibák/Figyelmeztetések
DialogBoxOpening                          = Párbeszédablak megjelenítése...
Disable                                   = Kikapcsolás
Enable                                    = Engedélyezés
AllFilesFilter                            = Minden fájl
FolderSelect                              = Válasszon ki egy könyvtárat
FilesWontBeMoved                          = A fájlok nem lesznek áthelyezve.
Install                                   = Telepítés
NoData                                    = Nincs megjeleníthető információ.
RestartFunction                           = Ponovo pokrenite funkciju "{0}".
NoResponse                                = Nem hozható létre kapcsolat a {0} weboldallal.
Restore                                   = Visszaállítás
Run                                       = Futtatás
Skipped                                   = Az "{0}" funkció kihagyva.
GPOUpdate                                 = GPO frissítése...
TelegramGroupTitle                        = Pridružite se našoj službenoj grupi Telegram.
TelegramChannelTitle                      = Pridružite se našem službenom kanalu Telegram.
DiscordChannelTitle                       = Pridružite se našem službenom kanalu Discord.
Uninstall                                 = Eltávolít
'@
