ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Скрипт підтримує тільки Windows 10 x64
UnsupportedOSBuild                        = Скрипт підтримує тільки Windows 10 1809 версії Enterprise LTSC
UnsupportedRelease                        = Виявлено нову версію
ControlledFolderAccessDisabled            = Контрольований доступ до папок вимкнений
ScheduledTasks                            = Заплановані задачі
WindowsFeaturesTitle                      = Компоненти Windows
OptionalFeaturesTitle                     = Додаткові компоненти
EnableHardwareVT                          = Увімкніть віртуалізацію в UEFI
UserShellFolderNotEmpty                   = У папці "{0}" залишились файли. Перемістіть їх вручну у нове розташування
RetrievingDrivesList                      = Отримання списку дисків...
DriveSelect                               = Виберіть диск, в корні якого буде створена папка для "{0}"
UserFolderRequest                         = Хочете змінити розташування папки "{0}"?
UserFolderSelect                          = Виберіть папку для "{0}"
UserDefaultFolder                         = Хочете змінити розташування папки "{0}" на значення за замовчуванням?
GraphicsPerformanceTitle                  = Налаштування продуктивності графіки
GraphicsPerformanceRequest                = Встановити для будь-якої програми за вашим вибором налаштування продуктивності графіки на "Висока продуктивність"?
TaskNotificationTitle                     = Cповіщення
CleanupTaskNotificationTitle              = Важлива інформація
CleanupTaskDescription                    = Очищення зайвих файлів і оновлень Windows, використовуючи вбудовану програму очищення диска
CleanupTaskNotificationEventTitle         = Запустити задачу по очищенню зайвих файлів і оновлень Windows?
CleanupTaskNotificationEvent              = Очищення Windows не займе багато часу. Наступний раз це повідомлення з'явиться через 30 днів
CleanupTaskNotificationSnoozeInterval     = Виберіть інтервал повтору повідомлення
CleanupNotificationTaskDescription        = Спливаюче повідомлення про нагадуванні з очищення зайвих файлів і оновлень Windows
SoftwareDistributionTaskNotificationEvent = Кеш оновлень Windows успішно видалений
TempTaskNotificationEvent                 = Папка тимчасових файлів успішно очищена
FolderTaskDescription                     = Очищення папки "{0}"
ControlledFolderAccess                    = Контрольований доступ до папок
ProtectedFoldersRequest                   = Бажаєте увімкнути контрольований доступ до папок і вказати папку, яку Microsoft Defender буде захищати від шкідливих додатків і загроз?
ProtectedFoldersListRemoved               = Видалення папки
AppControlledFolderRequest                = Вказати додаток, якому дозволена робота через контрольований доступ до папок
AllowedControlledFolderAppsRemoved        = Видалені дозволені додатки
DefenderExclusionFolderRequest            = Вказати папку, щоб виключити її зі списку сканування Microsoft Defender?
DefenderExclusionFoldersListRemoved       = Виключені папки видалені
AddDefenderExclusionFileRequest           = Вказати файл, щоб виключити його зі списку сканування Microsoft Defender?
DefenderExclusionFilesRemoved             = Виключені файли видалені
EventViewerCustomViewName                 = Створення процесу
EventViewerCustomViewDescription          = Події створення нового процесу і аудит командного рядка
RestartWarning                            = Обов'язково перезавантажте ваш ПК
ErrorsLine                                = Рядок
ErrorsFile                                = Файл
ErrorsMessage                             = Помилки/попередження
Add                                       = Додати
AllFilesFilter                            = Усі файли (*.*)|*.*
Change                                    = Змінити
DialogBoxOpening                          = Діалогове вікно відкривається...
Disable                                   = Вимкнути
Enable                                    = Увімкнути
EXEFilesFilter                            = *.exe|*.exe|Усі файли (*.*)|*.*
FolderSelect                              = Виберіть папку
FilesWontBeMoved                          = Файли не будуть перенесені
FourHours                                 = 4 години
HalfHour                                  = 30 хвилин
Install                                   = Встановити
Minute                                    = 1 хвилина
NoData                                    = Відсутні дані
NoInternetConnection                      = Відсутнє інтернет-з'єднання
NoResponse                                = Не вдалося встановити зв’язок із https://store.rg-adguard.net
Open                                      = Відкрити
Patient                                   = Будь ласка, зачекайте...
Restore                                   = Відновити
Run                                       = Запустити
Select                                    = Вибрати
SelectAll                                 = Вибрати все
Skip                                      = Пропустити
Skipped                                   = Пропущено
TelegramTitle                             = Приєднуйтесь до нашої офіційної групи Telegram
Uninstall                                 = Видалити
'@
