ConvertFrom-StringData -StringData @'
NewSophiaScriptFound                      = Elérhető egy új verzió: Sophia Script for Windows {0}. Kérjük, frissítse a programot.
UnsupportedPowerShell                     = A PowerShell {0}.{1} segítségével próbálja futtatni a szkriptet. Kérjük, futtassa a szkriptet a PowerShell {2}-ben.
CodeCompilationFailed                     = A kód fordítása sikertelen volt.
MicrosoftStorePowerShellWarning           = A Microsoft Store-ból letöltött PowerShell nem támogatott. Kérjük, futtasson egy MSI verziót.
PowerShellImportFailed                    = A modulok importálása a PowerShell 5.1-ből sikertelen volt. Zárja be a PowerShell 7 konzolt, és futtassa újra a szkriptet.
UnsupportedWindowsBitness                 = A szkript csak a 64 bites Windows-t támogatja.
KeyboardArrows                            = Kérjük, használja a billentyűzet {0} és {1} nyílbillentyűit a válasz kiválasztásához
UnsupportedLanguageMode                   = A PowerShell munkamenet korlátozott nyelvi üzemmódban fut.
LoggedInUserNotAdmin                      = A bejelentkezett felhasználó, "{0}", nem rendelkezik rendszergazdai jogokkal. A szkript "{1}" nevében futott. Kérjük, jelentkezzen be egy rendszergazdai jogokkal rendelkező fiókba, és futtassa újra a szkriptet.
UnsupportedHost                           = A szkript nem támogatja a(z) {0} használatával történő futtatást.
HarmfulTweakerFound                       = A Windows operációs rendszer stabilitását veszélyeztethette a {0}.
HostsEntriesFound                         = Harmadik féltől származó bejegyzések találhatóak a %SystemRoot%\\System32\\drivers\\etc\\hosts fájlban. Ezek blokkolhatják a szkriptben használt erőforrásokhoz való csatlakozást. Folytatni kívánja?
UWPComponentsMissing                      = Hiányzik a "{0}" UWP-komponens.
DefenderComponentsMissing                 = A Microsoft Defender "{0}" összetevője hiányzik.
WindowsComponentStabilityDisrupted        = A "{0}" komponensben instabilitási problémát észleltek.
DisableControlledFolderAccess             = A mappákhoz való hozzáférés ellenőrzése engedélyezve van. Kérjük, tiltsa le, és futtassa újra a szkriptet.
RebootPending                             = A számítógép újraindításra vár.
SystemDriveEncryptedBitLockerDisabled     = A C meghajtó titkosítva van, bár a BitLocker ki van kapcsolva. Szeretné dekódolni a meghajtót?
WrongSophiaScriptVersion                  = A szkript kizárólag a Windows 10 22H2 verziót támogatja. Ön jelenleg a(z) {0} {1} rendszert használja. A Windows-verziónak megfelelő szkriptet futtassa.
UpdateWindowsBuild                        = A szkript támogatja a Windows 10 22H2 {0}.{1} és újabb verzióit. Ön jelenleg a {2} {3} {4}.{5} verziót használja. Indítsa el a Windows Update szolgáltatást, majd próbálja meg újra.
ESUProgramEnrollment                      = A Windows 10 támogatása 2025. október 14-én lejárt. A számítógépe sebezhetővé válhat a rosszindulatú szoftverek, trójai programok és zero-day sebezhetőségek számára. Szeretne csatlakozni a Consumer Extended Security Updates (ESU) programhoz, hogy a Microsoft Activation Scripts (MAS) TSforge szolgáltatásának segítségével 2028-ig frissítéseket kapjon?
AskQuestion                               = Ha bármilyen kérdése van, nyisson egy issue-t a GitHubon, vagy forduljon a közösséghez.
CheckSophiaScriptPreset                   = A "Sophia Script for Windows" futtatása előtt testreszabta-e a {0} beállítási fájl összes funkcióját?
ReinstallWindows                          = Telepítse újra a Windows-t, kizárólag eredeti ISO-lemezkép használatával.
CreatingRestorePoint                      = Visszaállítási pont létrehozása folyamatban...
WindowsServiceNotFound                    = A "{0}" szolgáltatás nem található.
NoScheduledTasksFound                     = Nem található ütemezett feladat.
ScheduledTasks                            = Ütemezett feladatok
BingSearchDisabled                        = A webes keresés már le van tiltva a Start menüben.
TaskbarSmallIcons                         = Kis tálcagombokat használ.
SearchHighlightsDisabled                  = A keresési kiemelt elemek már el vannak rejtve a Start menüben.
CustomStartMenuFound                      = Egy harmadik fél Start menüje van telepítve.
OneDriveNotInstalled                      = A OneDrive már eltávolítva van.
OneDriveAccountUsageFound                 = A OneDrive eltávolítása előtt jelentkezzen ki a Microsoft-fiókjából a OneDrive-ban.
OneDriveInstalled                         = A OneDrive már telepítve van.
UninstallingApplication                   = A {0} eltávolításra kerül...
InstallingApplication                     = A {0} telepítése folyamatban van...
NoWindowsFeaturesFound                    = Nem található Windows-szolgáltatás.
WindowsFeaturesTitle                      = Windows-szolgáltatások
NoOptionalFeaturesFound                   = Nem található opcionális szolgáltatás.
OptionalFeaturesTitle                     = Opcionális szolgáltatások
NoSupportedNetworkAdaptersFound           = Nincs olyan hálózati adapter, amely támogatná az "Engedélyezze a számítógépnek, hogy energiatakarékossági okokból kikapcsolja ezt az eszközt" funkciót.
LocationServicesDisabled                  = A hálózati shell parancsokhoz helymeghatározási engedély szükséges a WLAN-adatok eléréséhez. Kapcsolja be a Helymeghatározás szolgáltatásokat az Adatvédelem és biztonság beállítások Helymeghatározás oldalon.
UserFolderLocationMove                    = Nem szabad megváltoztatni a felhasználói mappa helyét a C meghajtó gyökerére.
DriveSelect                               = Válassza ki azt a meghajtót, amelynek gyökérkönyvtárában a "{0}" mappa létrehozásra kerül.
CurrentUserFolderLocation                 = Az aktuális "{0}" mappa helye: "{1}".
FilesWontBeMoved                          = A fájlok nem kerülnek áthelyezésre.
UserFolderMoveSkipped                     = A felhasználó "{0}" mappájának helyét nem módosította.
UserShellFolderNotEmpty                   = Néhány fájl maradt a "{0}" mappában. Kérjük, helyezze át ezeket egy új helyre.
FolderSelect                              = Válasszon ki egy mappát
UserFolderRequest                         = Kívánja megváltoztatni a "{0}" mappa helyét?
UserDefaultFolder                         = Szeretné visszaállítani a "{0}" mappa alapértelmezett helyét?
ReservedStorageIsInUse                    = A fenntartott tárhely jelenleg használatban van.
ProgramPathNotExists                      = A "{0}" elérési út nem létezik.
ProgIdNotExists                           = A ProgId "{0}" nem létezik.
AllFilesFilter                            = Minden fájl
JSONNotValid                              = A JSON fájl "{0}" érvénytelen.
PackageNotInstalled                       = A(z) "{0}" alkalmazás nincs telepítve.
PackageIsInstalled                        = A {0} legújabb verziója már telepítve van.
UWPAppsTitle                              = UWP-alkalmazások
UninstallUWPForAll                        = Minden felhasználó számára
NoUWPAppsFound                            = Nincs eltávolítandó UWP-alkalmazás.
WDDMVersionUnsupported                    = A támogatott WDDM verziók a 2.7-es és újabbak. A jelenlegi WDDM verzió a {0}.
CleanupTaskNotificationTitle              = Windows tisztítása
CleanupTaskNotificationEvent              = Szeretné a nem használt Windows-fájlokat és -frissítéseket eltávolítani?
CleanupTaskDescription                    = A nem használt Windows-fájlok és -frissítések eltávolítása a beépített lemezkarbantartó alkalmazással.
CleanupNotificationTaskDescription        = Előugró emlékeztető figyelmeztetés a nem használt Windows-fájlok és -frissítések törléséről.
SoftwareDistributionTaskNotificationEvent = A Windows-frissítések gyorsítótára sikeresen törölve.
SoftwareDistributionTaskDescription       = A Windows Update "{0}" gyorsítótár-mappájának törlése.
TempTaskNotificationEvent                 = Az ideiglenes mappa tisztítása sikeresen megtörtént.
TempTaskDescription                       = A(z) "{0}" ideiglenes mappa (%TEMP%) tisztítása.
ScheduledTaskLoggedInUserNotification     = Az ütemezett feladat csak akkor futtatható, ha "{0}" felhasználó bejelentkezett a rendszerbe.
CleanupTaskCLIDescription                 = A(z) "Sophia\\Windows Cleanup Notification" ütemezett feladat létrejött a Feladatütemezőben a nem használt Windows-fájlok és -frissítések törléséhez.
SoftwareDistributionTaskCLIDescription    = A(z) "Sophia\\SoftwareDistribution" ütemezett feladat létrejött a Feladatütemezőben a Windows-frissítések gyorsítótármappájának ("{0}") törléséhez.
TempTaskCLIDescription                    = A(z) "Sophia\\Temp" ütemezett feladat létrejött a Feladatütemezőben a(z) "{0}" ideiglenes mappa (%TEMP%) tisztításához.
EventViewerCustomViewName                 = Folyamat létrehozása
EventViewerCustomViewDescription          = Az elindított folyamatok és a PowerShell-tevékenység nyomon követése
EventViewerCustomViewNotification         = Az "Egyéni nézetek\\{0}" egyéni nézet létrejött az Eseménynaplóban az elindított folyamatok és a PowerShell-tevékenység nyomon követéséhez.
ThirdPartyAVInstalled                     = Harmadik féltől származó vírusirtó van telepítve.
NoHomeWindowsEditionSupport               = A Windows Home Edition nem támogatja a "{0}" funkciót.
EnableHardwareVT                          = Engedélyezze a virtualizációt az UEFI-ben.
PhotosNotInstalled                        = A "Fotók" alkalmazás nincs telepítve.
HEVCInstalled                             = Az eszköz gyártójától származó HEVC-videobővítmények már telepítve vannak.
HEVCInstallingApplication                 = Az eszköz gyártójától származó HEVC-videobővítmények telepítése folyamatban van...
ThirdPartyArchiverInstalled               = Harmadik féltől származó tömörítőprogram van telepítve.
gpeditNotSupported                        = A Windows Home Edition nem támogatja a Helyi csoportházirend-szerkesztő beépülő modult (gpedit.msc).
RestartWarning                            = Indítsa újra a számítógépet.
RestorePointVolume                        = A C meghajtó visszaállítási pontjai {0} GB helyet foglalnak.
ErrorsLine                                = Sor
ErrorsMessage                             = Hibák, figyelmeztetések és értesítések
Disable                                   = Letiltás
Enable                                    = Engedélyezés
Install                                   = Telepítés
Uninstall                                 = Eltávolítás
RestartFunction                           = Kérjük, futtassa újra a(z) "{0}" funkciót.
NoConnectionEstablished                   = Nem hozható létre kapcsolat a {0} weboldallal.
Run                                       = Futtatás
FunctionSkipped                           = A(z) "{0}" funkció kihagyva.
DonateToastTitle                          = Adományokat szívesen fogadunk! ♥
DotSourceFunction                         = Kérjük, "dot-source"-olja a függvényt (egy ponttal az elején):\n. .\\Import-TabCompletion.ps1
'@
