ConvertFrom-StringData -StringData @'
UnsupportedArchitecture                   = Korzystasz z procesora opartego na architekturze "{0}". Ten skrypt obsługuje wyłącznie procesory oparte na architekturze Arm. Pobierz i uruchom wersję skryptu odpowiednią dla swojej architektury.
UnsupportedOSBuild                        = Skrypt obsługuje system Windows 11 24H2 i nowsze wersje. Używasz systemu {0} {1}. Zaktualizuj system Windows i spróbuj ponownie.
UnsupportedWindowsTerminal                = Wersja Windows Terminal jest niższa niż 1.23. Zaktualizuj ją w Microsoft Store i spróbuj ponownie.
UpdateWarning                             = Windows 11 {0}.{1} rendszert használ. A támogatott verzió Windows 11 {0}.{2} vagy újabb. Futtassa a Windows Update programot, majd próbálja meg újra.
UnsupportedLanguageMode                   = Sesja PowerShell działa w trybie ograniczonego języka.
LoggedInUserNotAdmin                      = Zalogowany użytkownik {0} nie ma uprawnień administratora. Skrypt został uruchomiony w imieniu {1}. Zaloguj się na konto z uprawnieniami administratora i uruchom skrypt ponownie.
UnsupportedPowerShell                     = Próbujesz uruchomić skrypt przy użyciu PowerShell {0}.{1}. Uruchom skrypt w PowerShell {2}.
CodeCompilationFailedWarning              = Kompilacja kodu nie powiodła się.
UnsupportedHost                           = Skrypt nie może być uruchamiany w {0}.
Win10TweakerWarning                       = Prawdopodobnie twój system operacyjny został zainfekowany przez backdoora pochodzącego z Win 10 Tweaker.
TweakerWarning                            = Stabilność systemu Windows mogła zostać naruszona przez użycie {0}. Zainstaluj ponownie system Windows, używając tylko oryginalnego obrazu ISO.
HostsWarning                              = W pliku %SystemRoot%\\System32\\drivers\\etc\\hosts znaleziono wpisy stron trzecich. Mogą one blokować połączenie z zasobami używanymi w skrypcie. Czy chcesz kontynuować?
RebootPending                             = Twój komputer czeka na ponowne uruchomienie.
BitLockerInOperation                      = Trwa szyfrowanie za pomocą funkcji BitLocker. Zakończ konfigurację dysku BitLocker i spróbuj ponownie.
BitLockerAutomaticEncryption              = Dysk C jest zaszyfrowany, mimo że funkcja BitLocker jest wyłączona. Czy chcesz odszyfrować dysk?
UnsupportedRelease                        = Znaleziono nowszą wersję skryptu Sophia: {0}. Proszę pobrać najnowszą wersję.
KeyboardArrows                            = Użyj klawiszy strzałek {0} i {1} na klawiaturze, aby wybrać odpowiedź
CustomizationWarning                      = Czy dostosowałeś funkcje w predefiniowanym pliku {0} przed uruchomieniem Sophia Script?
WindowsComponentBroken                    = {0} jest uszkodzony lub usunięty z systemu operacyjnego. Zainstaluj ponownie system Windows, używając tylko oryginalnego obrazu ISO.
ControlledFolderAccessEnabledWarning      = Włączono kontrolę dostępu do folderów. Proszę ją wyłączyć i ponownie uruchomić skrypt.
NoScheduledTasks                          = Brak zaplanowanych zadań do wyłączenia.
ScheduledTasks                            = Zaplanowane zadania
WidgetNotInstalled                        = Widżet nie jest zainstalowany.
SearchHighlightsDisabled                  = Najważniejsze wyniki wyszukiwania są już ukryte w menu Start.
CustomStartMenu                           = Zainstalowano menu Start innej firmy.
OneDriveNotInstalled                      = OneDrive został już odinstalowany.
OneDriveAccountWarning                    = Przed odinstalowaniem aplikacji OneDrive wyloguj się ze swojego konta Microsoft w aplikacji OneDrive.
OneDriveInstalled                         = Usługa OneDrive jest już zainstalowana.
UninstallNotification                     = Usuwanie programu {0}...
InstallNotification                       = Trwa instalacja usługi {0}...
NoWindowsFeatures                         = Nincs letiltandó Windows-funkció.
WindowsFeaturesTitle                      = Funkcje Windows
NoOptionalFeatures                        = Nincs letiltható opcionális funkció.
NoSupportedNetworkAdapters                = Brak kart sieciowych obsługujących funkcję "Zezwól komputerowi na wyłączenie tego urządzenia w celu oszczędzania energii".
OptionalFeaturesTitle                     = Funkcje opcjonalne
EnableHardwareVT                          = Włącz wirtualizację w UEFI.
UserShellFolderNotEmpty                   = Niektóre pliki pozostały w folderze "{0}". Przenieś je ręcznie w nowe miejsce.
UserFolderLocationMove                    = Nie należy zmieniać lokalizacji folderu użytkownika na katalog główny dysku C.
DriveSelect                               = Wybierz dysk w katalogu głównym, w którym zostanie utworzony folder "{0}".
CurrentUserFolderLocation                 = Lokalizacja folderu "{0}": "{1}".
FilesWontBeMoved                          = Pliki nie zostaną przeniesione.
FolderSelect                              = Wybierz folder
UserFolderRequest                         = Czy chcesz zmienić lokalizację folderu "{0}"?
UserDefaultFolder                         = Czy chcesz zmienić lokalizację folderu "{0}" na wartość domyślną?
ReservedStorageIsInUse                    = Zarezerwowana pamięć jest używana.
ProgramPathNotExists                      = Ścieżka "{0}" nie istnieje.
ProgIdNotExists                           = ProgId "{0}" nie istnieje.
AllFilesFilter                            = Wszystkie pliki
JSONNotValid                              = Plik JSON "{0}" jest nieprawidłowy.
PackageNotInstalled                       = {0} nie jest zainstalowany.
PackageIsInstalled                        = Najnowsza wersja {0} jest już zainstalowana.
UninstallUWPForAll                        = Dla wszystkich użytkowników
NoUWPApps                                 = Brak aplikacji UWP do odinstalowania.
UWPAppsTitle                              = Aplikacje UWP
ScheduledTaskCreatedByAnotherUser         = Zaplanowane zadanie "{0}" zostało już utworzone przez użytkownika "{1}".
CleanupTaskNotificationTitle              = Oczyszczanie system Windows
CleanupTaskNotificationEvent              = Uruchomić zadanie w celu usunięcia nieużywanych plików i aktualizacji systemu Windows?
CleanupTaskDescription                    = Czyszczenie nieużywanych plików i aktualizacji systemu Windows za pomocą wbudowanej aplikacji do czyszczenia dysku. Zaplanowane zadanie może zostać uruchomione tylko wtedy, gdy użytkownik "{0}" jest zalogowany do systemu.
CleanupNotificationTaskDescription        = Powiadomienie przypominające o czyszczeniu nieużywanych plików i aktualizacji systemu Windows. Zaplanowane zadanie może zostać uruchomione tylko wtedy, gdy użytkownik "{0}" jest zalogowany do systemu.
SoftwareDistributionTaskNotificationEvent = Pomyślnie usunięto pamięć podręczną aktualizacji systemu Windows.
TempTaskNotificationEvent                 = Folder plików tymczasowych został pomyślnie wyczyszczony.
FolderTaskDescription                     = Czyszczenie folderu {0}. Zaplanowane zadanie może zostać uruchomione tylko wtedy, gdy użytkownik "{0}" jest zalogowany do systemu.
EventViewerCustomViewName                 = Tworzenie procesu
EventViewerCustomViewDescription          = Tworzenie procesu i zdarzeń audytu.
ThirdPartyAVInstalled                     = Zainstalowano program antywirusowy innej firmy.
NoHomeWindowsEditionSupport               = Wersja Windows Home nie obsługuje funkcji "{0}".
GeoIdNotSupported                         = Funkcja "{0}" ma zastosowanie wyłącznie w Rosji.
PhotosNotInstalled                        = Aplikacja Zdjęcia nie jest zainstalowana.
ThirdPartyArchiverInstalled               = Zainstalowano archiwizator innej firmy.
gpeditNotSupported                        = Wersja Windows Home nie obsługuje przystawki Edytor lokalnych zasad grupy (gpedit.msc).
RestartWarning                            = Pamiętaj o ponownym uruchomieniu komputera.
ErrorsLine                                = Linia
ErrorsMessage                             = Błędy, ostrzeżenia i powiadomienia
Disable                                   = Wyłączyć
Enable                                    = Włączać
Install                                   = Zainstalluj
Uninstall                                 = Odinstaluj
RestartFunction                           = Uruchom ponownie funkcję "{0}".
NoResponse                                = Nie można nawiązać połączenia z {0}.
Run                                       = Uruchom
Skipped                                   = Pominięto.
ThankfulToastTitle                        = Dziękujemy za korzystanie z Sophia Script ❤️
DonateToastTitle                          = Możesz przekazać darowiznę poniżej 🕊
DotSourcedWarning                         = Prosimy o "dot-source" funkcji (z kropką na początku):\n. .\\Import-TabCompletion.ps1
'@
