ConvertFrom-StringData -StringData @'
PowerShellImportFailed                    = PowerShell 5.1'den modül içe aktarma işlemi başarısız oldu. Lütfen PowerShell 7 konsolunu kapatın ve komut dosyasını yeniden çalıştırın.
UnsupportedArchitecture                   = "{0}" tabanlı mimari CPU kullanıyorsunuz. Bu komut dosyası yalnızca Arm mimari tabanlı CPU'ları destekler. Mimariniz için komut dosyası sürümünü indirin ve çalıştırın.
UnsupportedOSBuild                        = Komut dosyası Windows 11 24H2 ve üstünü destekler. {0} {1} kullanıyorsunuz. Windows'unuzu yükseltin ve tekrar deneyin.
UnsupportedWindowsTerminal                = Windows Terminal sürümü 1.23'den daha düşük. Lütfen Microsoft Store'da güncelleyin ve tekrar deneyin.
UpdateWarning                             = Windows 11 {0}.{1} rendszert használ. A támogatott verzió Windows 11 {0}.{2} vagy újabb. Futtassa a Windows Update programot, majd próbálja meg újra.
UnsupportedLanguageMode                   = Sınırlı bir dil modunda çalışan PowerShell oturumu.
LoggedInUserNotAdmin                      = Oturum açan kullanıcı {0}'in yönetici hakları yoktur. Komut dosyası {1} adına çalıştırılmıştır. Yönetici haklarına sahip bir hesaba giriş yapın ve komut dosyasını tekrar çalıştırın.
UnsupportedPowerShell                     = Komut dosyasını PowerShell {0}.{1} aracılığıyla çalıştırmaya çalışıyorsunuz. Lütfen betiği PowerShell {2} ile çalıştırın.
CodeCompilationFailedWarning              = Kod derleme başarısız oldu.
UnsupportedHost                           = Komut dosyası, {0} üzerinden çalıştırmayı desteklemiyor.
Win10TweakerWarning                       = Muhtemelen işletim sisteminize Win 10 Tweaker arka kapısı yoluyla bulaştı.
TweakerWarning                            = Windows işletim sistemi kararlılığı, {0} betiği kullanılarak tehlikeye atılmış olabilir. Yalnızca orijinal bir ISO görüntüsü kullanarak Windows'u yeniden yükleyin.
HostsWarning                              = {0} dosyasında bulunan üçüncü taraf girişleri. Bunlar, betikte kullanılan kaynaklara bağlantıları engelleyebilir. Devam etmek istiyor musunuz?
RebootPending                             = PC yeniden başlatılmayı bekliyor.
BitLockerWarning                          = BitLocker şifreleme işlemi devam ediyor. BitLocker sürücü yapılandırmasını tamamlayın ve tekrar deneyin.
UnsupportedRelease                        = Daha yeni bir Sophia Script sürümü bulundu: {0}. Lütfen en son sürümü indirin.
KeyboardArrows                            = Lütfen cevabınızı seçmek için klavyenizdeki {0} ve {1} ok tuşlarını kullanın
CustomizationWarning                      = Sophia Script'i çalıştırmadan önce {0} ön ayar dosyasındaki her işlevi özelleştirdiniz mi?
WindowsComponentBroken                    = {0} bozuk veya işletim sisteminden kaldırıldı. Yalnızca orijinal bir ISO görüntüsü kullanarak Windows'u yeniden yükleyin.
MicroSoftStorePowerShellWarning           = Microsoft Store'dan indirilen PowerShell desteklenmez. Lütfen bir MSI sürümü çalıştırın.\nhttps://github.com/powershell/powershell/releases/latest
ControlledFolderAccessDisabled            = Kontrollü klasör erişimi devre dışı bırakıldı.
ScheduledTasks                            = Zamanlanan görevler
UninstallNotification                     = {0} kaldırılıyor...
DownloadNotification                      = {0} indiriliyor...
InstallNotification                       = {0} yükleniyor...
OneDriveUsageWarning                      = Uygulamayı kaldırmadan önce OneDrive hesabından çıkış yapın.
WindowsFeaturesTitle                      = Características do Windows
OptionalFeaturesTitle                     = Opsiyonel özellikler
EnableHardwareVT                          = UEFI'dan sanallaştırmayı aktifleştirin.
UserShellFolderNotEmpty                   = "{0}" klasöründe bazı dosyalar kaldı. Kendiniz yeni konuma taşıyın.
UserFolderLocationMove                    = Kullanıcı klasörü konumunu C sürücüsü kökü olarak değiştirmemelisiniz.
DriveSelect                               = "{0}" klasörünün oluşturulacağı kök içindeki sürücüyü seçin.
CurrentUserFolderLocation                 = Geçerli "{0}" klasör konumu: "{1}".
UserFolderRequest                         = "{0}" klasörünün yerini değiştirmek ister misiniz?
UserDefaultFolder                         = "{0}" klasörünün konumunu varsayılan değerle değiştirmek ister misiniz?
ReservedStorageIsInUse                    = Ayrılmış depolama kullanımdayken bu işlem desteklenmez\nBilgisayar yeniden başlatıldıktan sonra lütfen "{0}" işlevini yeniden çalıştırın.
UninstallUWPForAll                        = Bütün kullanıcılar için
UWPAppsTitle                              = UWP Uygulamaları
GraphicsPerformanceTitle                  = Seçtiğiniz bir uygulamanın grafik performansı ayarını "Yüksek performans" olarak belirlemek ister misiniz?
ScheduledTaskPresented                    = "{0}" işlevi zaten "{1}" olarak oluşturulmuştu.
CleanupTaskNotificationTitle              = Windows temizliği
CleanupTaskNotificationEvent              = Windows kullanılmayan dosyaları ve güncellemeleri temizlemek için görev çalıştırılsın mı?
CleanupTaskDescription                    = Kullanılmayan Windows dosyaları ve güncellemeleri yerleşik Disk Temizleme uygulaması ile temizleniyor. Zamanlanmış görev yalnızca "{0}" kullanıcısı sisteme giriş yaptığında çalıştırılabilir.
CleanupNotificationTaskDescription        = Windows kullanılmayan dosyaları ve güncellemeleri temizleme hakkında açılır bildirim hatırlatıcısı. Zamanlanmış görev yalnızca "{0}" kullanıcısı sisteme giriş yaptığında çalıştırılabilir.
SoftwareDistributionTaskNotificationEvent = Windows güncelleme önbelleği başarıyla silindi.
TempTaskNotificationEvent                 = Geçici dosyalar klasörü başarıyla temizlendi.
FolderTaskDescription                     = "{0}" klasörü temizleniyor. Zamanlanmış görev yalnızca "{0}" kullanıcısı sisteme giriş yaptığında çalıştırılabilir.
EventViewerCustomViewName                 = Süreç Oluşturma
EventViewerCustomViewDescription          = Süreç oluşturma ve komut satırı denetleme olayları.
RestartWarning                            = Bilgisayarınızı yeniden başlattığınızdan emin olun.
ErrorsLine                                = Satır
ErrorsMessage                             = Hatalar/Uyarılar
DialogBoxOpening                          = İletişim kutusu görüntüleniyor...
Disable                                   = Devre dışı bırak
Enable                                    = Aktif et
AllFilesFilter                            = Tüm Dosyalar
FolderSelect                              = Klasör seç
FilesWontBeMoved                          = Dosyalar taşınmayacak.
Install                                   = Yükle
Uninstall                                 = Kaldır
NoData                                    = Görüntülenecek bir şey yok.
RestartFunction                           = Lütfen "{0}" işlevini yeniden çalıştırın.
NoResponse                                = {0} ile bağlantı kurulamadı.
Restore                                   = Onar
Run                                       = Başlat
Skipped                                   = "{0}" işlevi atlandı.
ThankfulToastTitle                        = Sophia Script kullandığınız için teşekkür ederiz ❤️
DonateToastTitle                          = Aşağıdan bağış yapabilirsiniz 🕊️
DotSourcedWarning                         = Lütfen işlevi "nokta-kaynaklı" (başında nokta olan) olarak yazın:\n. .\\Import-TabCompletion.ps1
'@
