ConvertFrom-StringData -StringData @'
PowerShellImportFailed                    = PowerShell 5.1'den modül içe aktarma işlemi başarısız oldu. Lütfen PowerShell 7 konsolunu kapatın ve komut dosyasını yeniden çalıştırın.
UnsupportedArchitecture                   = "{0}" tabanlı mimari CPU kullanıyorsunuz. Bu komut dosyası yalnızca Arm mimari tabanlı CPU'ları destekler. Mimariniz için komut dosyası sürümünü indirin ve çalıştırın.
UnsupportedOSBuild                        = Komut dosyası Windows 11 24H2 ve üstünü destekler. {0} {1} kullanıyorsunuz. Windows'unuzu yükseltin ve tekrar deneyin.
UnsupportedWindowsTerminal                = Windows Terminal sürümü 1.23'den daha düşük. Lütfen Microsoft Store'da güncelleyin ve tekrar deneyin.
UpdateWarning                             = Windows 11 {0}.{1} rendszert használ. A támogatott verzió Windows 11 {0}.{2} vagy újabb. Futtassa a Windows Update programot, majd próbálja meg újra.
UnsupportedLanguageMode                   = Sınırlı bir dil modunda çalışan PowerShell oturumu.
LoggedInUserNotAdmin                      = Oturum açan kullanıcı {0}'in yönetici hakları yoktur. Komut dosyası {1} adına çalıştırılmıştır. Yönetici haklarına sahip bir hesaba giriş yapın ve komut dosyasını tekrar çalıştırın.
UnsupportedPowerShell                     = Komut dosyasını PowerShell {0}.{1} aracılığıyla çalıştırmaya çalışıyorsunuz. Lütfen betiği PowerShell {2} ile çalıştırın.
CodeCompilationFailedWarning              = Kod derleme başarısız oldu.
UnsupportedHost                           = Komut dosyası, {0} üzerinden çalıştırmayı desteklemiyor.
Win10TweakerWarning                       = Muhtemelen işletim sisteminize Win 10 Tweaker arka kapısı yoluyla bulaştı.
TweakerWarning                            = Windows işletim sistemi kararlılığı, {0} betiği kullanılarak tehlikeye atılmış olabilir. Yalnızca orijinal bir ISO görüntüsü kullanarak Windows'u yeniden yükleyin.
HostsWarning                              = %SystemRoot%\\System32\\drivers\\etc\\hosts dosyasında bulunan üçüncü taraf girdileri. Bunlar, komut dosyasında kullanılan kaynaklara bağlantıyı engelleyebilir. Devam etmek istiyor musunuz?
RebootPending                             = Bilgisayarınız yeniden başlatılmayı bekliyor.
BitLockerInOperation                      = BitLocker çalışıyor. C sürücünüz %{0} oranında şifrelenmiştir. BitLocker sürücü yapılandırmasını tamamlayın ve tekrar deneyin.
BitLockerAutomaticEncryption              = BitLocker kapalı olmasına rağmen C sürücüsü şifrelenmiştir. Sürücünüzün şifresini çözmek ister misiniz?
UnsupportedRelease                        = Daha yeni bir Sophia Script for Windows sürümü bulundu: {0}. Lütfen en son sürümü indirin.
KeyboardArrows                            = Lütfen cevabınızı seçmek için klavyenizdeki {0} ve {1} ok tuşlarını kullanın
CustomizationWarning                      = Sophia Script for Windows'i çalıştırmadan önce {0} ön ayar dosyasındaki her işlevi özelleştirdiniz mi?
WindowsComponentBroken                    = {0} bozuk veya işletim sisteminden kaldırıldı. Yalnızca orijinal bir ISO görüntüsü kullanarak Windows'u yeniden yükleyin.
MicroSoftStorePowerShellWarning           = Microsoft Store'dan indirilen PowerShell desteklenmez. Lütfen bir MSI sürümü çalıştırın.
ControlledFolderAccessEnabledWarning      = Kontrollü klasör erişimi etkinleştirilmiştir. Lütfen bunu devre dışı bırakın ve komut dosyasını tekrar çalıştırın.
NoScheduledTasks                          = Devre dışı bırakılacak zamanlanmış görev yok.
ScheduledTasks                            = Zamanlanan görevler
WidgetNotInstalled                        = Widget yüklenmemiştir.
SearchHighlightsDisabled                  = Arama öne çıkanları Başlat'ta zaten gizlidir.
CustomStartMenu                           = Üçüncü taraf bir Başlat Menüsü yüklenmiştir.
OneDriveNotInstalled                      = OneDrive zaten kaldırılmıştır.
OneDriveAccountWarning                    = OneDrive'ı kaldırmadan önce, OneDrive'da Microsoft hesabınızdan çıkış yapın.
OneDriveInstalled                         = OneDrive zaten yüklü.
UninstallNotification                     = {0} kaldırılıyor...
InstallNotification                       = {0} yükleniyor...
NoWindowsFeatures                         = Devre dışı bırakılacak Windows özelliği yok.
WindowsFeaturesTitle                      = Windows özellikleri
NoOptionalFeatures                        = Devre dışı bırakılacak isteğe bağlı özellik yok.
NoSupportedNetworkAdapters                = "Bilgisayarın güç tasarrufu için bu aygıtı kapatmasına izin ver" işlevini destekleyen ağ bağdaştırıcısı yok.
LocationServicesDisabled                  = Ağ kabuğu komutları, WLAN bilgilerine erişmek için konum iznine ihtiyaç duyar. Gizlilik ve güvenlik ayarlarının Konum sayfasında Konum hizmetlerini açın.
OptionalFeaturesTitle                     = Opsiyonel özellikler
UserShellFolderNotEmpty                   = "{0}" klasöründe bazı dosyalar kaldı. Kendiniz yeni konuma taşıyın.
UserFolderLocationMove                    = Kullanıcı klasörü konumunu C sürücüsü kökü olarak değiştirmemelisiniz.
DriveSelect                               = "{0}" klasörünün oluşturulacağı kök içindeki sürücüyü seçin.
CurrentUserFolderLocation                 = Geçerli "{0}" klasör konumu: "{1}".
FilesWontBeMoved                          = Dosyalar taşınmayacaktır.
UserFolderMoveSkipped                     = Kullanıcının "{0}" klasörünün konumunu değiştirmeyi atladınız.
FolderSelect                              = Bir klasör seçin
UserFolderRequest                         = "{0}" klasörünün yerini değiştirmek ister misiniz?
UserDefaultFolder                         = "{0}" klasörünün konumunu varsayılan değerle değiştirmek ister misiniz?
ReservedStorageIsInUse                    = Rezerve edilmiş depolama alanı kullanılıyor.
ProgramPathNotExists                      = "{0}" yolu mevcut değil.
ProgIdNotExists                           = ProgId "{0}" mevcut değildir.
AllFilesFilter                            = Tüm Dosyalar
JSONNotValid                              = JSON dosyası "{0}" geçerli değil.
PackageNotInstalled                       = {0} yüklü değildir.
PackageIsInstalled                        = {0}'ın en son sürümü zaten yüklü.
CopilotPCSupport                          = CPU'nuzda yerleşik NPU bulunmadığından, Windows AI işlevlerini desteklemez. GPO ilkelerini kullanarak herhangi bir şeyi devre dışı bırakmanıza gerek yoktur. Recall işlevi ve Copilot uygulaması kaldırılmıştır.
UninstallUWPForAll                        = Bütün kullanıcılar için
NoUWPApps                                 = Kaldırılacak UWP uygulaması yok.
UWPAppsTitle                              = UWP Uygulamaları
ScheduledTaskCreatedByAnotherUser         = "{0}" adlı zamanlanmış görev, "{1}" kullanıcısı tarafından zaten oluşturulmuştur.
CleanupTaskNotificationTitle              = Windows temizleme
CleanupTaskNotificationEvent              = Windows kullanılmayan dosyaları ve güncellemeleri temizlemek için görev çalıştırılsın mı?
CleanupTaskDescription                    = Kullanılmayan Windows dosyaları ve güncellemeleri yerleşik Disk Temizleme uygulaması ile temizleniyor. Zamanlanmış görev yalnızca "{0}" kullanıcısı sisteme giriş yaptığında çalıştırılabilir.
CleanupNotificationTaskDescription        = Windows kullanılmayan dosyaları ve güncellemeleri temizleme hakkında açılır bildirim hatırlatıcısı. Zamanlanmış görev yalnızca "{0}" kullanıcısı sisteme giriş yaptığında çalıştırılabilir.
SoftwareDistributionTaskNotificationEvent = Windows güncelleme önbelleği başarıyla silindi.
TempTaskNotificationEvent                 = Geçici dosyalar klasörü başarıyla temizlendi.
FolderTaskDescription                     = "{0}" klasörü temizleniyor. Zamanlanmış görev yalnızca "{0}" kullanıcısı sisteme giriş yaptığında çalıştırılabilir.
EventViewerCustomViewName                 = Süreç Oluşturma
EventViewerCustomViewDescription          = Süreç oluşturma ve komut satırı denetleme olayları.
ThirdPartyAVInstalled                     = Üçüncü taraf bir antivirüs yüklüdür.
NoHomeWindowsEditionSupport               = Windows Home sürümü "{0}" işlevini desteklemiyor.
GeoIdNotSupported                         = "{0}" işlevi yalnızca Rusya için geçerlidir.
EnableHardwareVT                          = UEFI'dan sanallaştırmayı aktifleştirin.
PhotosNotInstalled                        = Fotoğraflar uygulaması yüklü değil.
ThirdPartyArchiverInstalled               = Üçüncü taraf bir arşivleyici yüklenmiştir.
gpeditNotSupported                        = Windows Home sürümü, Yerel Grup İlkesi Düzenleyicisi ek bileşenini (gpedit.msc) desteklemez.
RestartWarning                            = Bilgisayarınızı yeniden başlatmayı unutmayın.
ErrorsLine                                = Satır
ErrorsMessage                             = Hatalar, uyarılar ve bildirimler
Disable                                   = Devre dışı bırak
Enable                                    = Aktif et
Install                                   = Yükle
Uninstall                                 = Kaldır
RestartFunction                           = Lütfen "{0}" işlevini yeniden çalıştırın.
NoResponse                                = {0} ile bağlantı kurulamadı.
Run                                       = Başlat
Skipped                                   = "{0}" işlevi atlandı.
ThankfulToastTitle                        = Sophia Script for Windows kullandığınız için teşekkür ederiz ❤️
DonateToastTitle                          = Aşağıdan bağış yapabilirsiniz 🕊️
DotSourcedWarning                         = Lütfen işlevi "nokta-kaynaklı" (başında nokta olan) olarak yazın:\n. .\\Import-TabCompletion.ps1
'@
