ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Le script supporte uniquement Windows 10 x64
UnsupportedOSBuild                        = Le script supporte les versions Windows 10 2004/20H2/21H1/21H2
UpdateWarning                             = La mise à jour cumulative de Windows 10 est installée : {0}. Mise à jour cumulative prise en charge : 1151 et plus
UnsupportedLanguageMode                   = La session PowerShell s'exécute dans un mode de langue limité
LoggedInUserNotAdmin                      = L'utilisateur connecté n'a pas de droits d'administrateur
UnsupportedPowerShell                     = Vous essayez d'exécuter le script via PowerShell {0}.{1}. Exécutez le script dans la version appropriée de PowerShell
UnsupportedISE                            = Le script ne supporte pas l'exécution via Windows PowerShell ISE
Win10TweakerWarning                       = Votre système d'exploitation a probablement été infecté par la porte dérobée Win 10 Tweaker
PowerShellLibraries                       = Il n'y a pas de fichiers dans le dossier Bibliothèques. Veuillez retélécharger l'archive
UnsupportedRelease                        = Nouvelle version trouvée
CustomizationWarning                      = \nAvez-vous personnalisé chaque fonction du fichier de préréglage Sophia.ps1 avant d'exécuter Sophia Script?
ControlledFolderAccessDisabled            = Contrôle d'accès aux dossiers désactivé
ScheduledTasks                            = Tâches planifiées
OneDriveUninstalling                      = Désinstalltion de OneDrive...
OneDriveInstalling                        = Installation de OneDrive...
OneDriveDownloading                       = Téléchargement de OneDrive... ~33 Mo
WindowsFeaturesTitle                      = Fonctionnalités
OptionalFeaturesTitle                     = Fonctionnalités optionnelles
EnableHardwareVT                          = Activer la virtualisation dans UEFI
UserShellFolderNotEmpty                   = Certains fichiers laissés dans le dossier "{0}". Déplacer les manuellement vers un nouvel emplacement
RetrievingDrivesList                      = Récupération de la liste des lecteurs...
DriveSelect                               = Sélectionnez le disque à la racine dans lequel le dossier "{0}" sera créé.
CurrentUserFolderLocation                 = L'emplacement actuel du dossier "{0}": "{1}"
UserFolderRequest                         = Voulez vous changer où est placé le dossier "{0}" ?
UserFolderSelect                          = Sélectionnez un dossier pour le dossier "{0}"
UserDefaultFolder                         = Voulez vous changer où est placé le dossier "{0}" à sa valeur par défaut?
ReservedStorageIsInUse                    = Cette opération n'est pas suppportée le stockage réservé est en cours d'utilisation\nVeuillez réexécuter la fonction "{0}" après le redémarrage du PC
ShortcutPinning                           = Le raccourci "{0}" est épinglé sur Démarrer...
UninstallUWPForAll                        = Pour tous les utilisateurs
UWPAppsTitle                              = Applications UWP
HEVCDownloading                           = Téléchargement de Extensions vidéo HEVC du fabricant de l'appareil... ~2,8 MB
GraphicsPerformanceTitle                  = Préférence de performances graphiques
GraphicsPerformanceRequest                = Souhaitez-vous définir le paramètre de performances graphiques d'une application de votre choix sur "Haute performance"?
TaskNotificationTitle                     = Notificacion
CleanupTaskNotificationTitle              = Une information important
CleanupTaskDescription                    = Nettoyage des fichiers Windows inutilisés et des mises à jour à l'aide de l'application intégrée pour le nettoyage de disque
CleanupTaskNotificationEventTitle         = Exécuter la tâche pour nettoyer les fichiers et les mises à jour inutilisés de Windows?
CleanupTaskNotificationEvent              = Le nettoyage de Windows ne prendra pas longtemps. La prochaine fois que la notification apparaîtra dans 30 jours
CleanupTaskNotificationSnoozeInterval     = Sélectionnez un intervalle de rappel
CleanupNotificationTaskDescription        = Rappel de notification contextuelle sur le nettoyage des fichiers et des mises à jour inutilisés de Windows
SoftwareDistributionTaskNotificationEvent = Le cache de mise à jour Windows a bien été supprimé
TempTaskNotificationEvent                 = Le dossier des fichiers temporaires a été nettoyé avec succès
FolderTaskDescription                     = Nettoyage du dossier "{0}"
EventViewerCustomViewName                 = Création du processus
EventViewerCustomViewDescription          = Audit des événements de création du processus et de ligne de commande
RestartWarning                            = Assurez-vous de redémarrer votre PC
ErrorsLine                                = Ligne
ErrorsFile                                = Fichier
ErrorsMessage                             = Erreurs/Avertissements
Add                                       = Ajouter
AllFilesFilter                            = Tous les Fichiers (*.*)|*.*
Browse                                    = Parcourir
Change                                    = Changer
DialogBoxOpening                          = Afficher la boîte de dialogue...
Disable                                   = Désactiver
Enable                                    = Activer
EXEFilesFilter                            = *.exe|*.exe|Tous les Fichiers (*.*)|*.*
FolderSelect                              = Sélectionner un dossier
FilesWontBeMoved                          = Les fichiers ne seront pas déplacés
FourHours                                 = 4 heures
HalfHour                                  = 30 minutes
Install                                   = Installer
Minute                                    = 1 minute
NoData                                    = Rien à afficher
NoInternetConnection                      = Pas de connexion Internet
RestartFunction                           = Veuillez redémarrer la fonction "{0}"
NoResponse                                = Une connexion n'a pas pu être établie avec {0}
No                                        = Non
Yes                                       = Oui
Open                                      = Ouvert
Patient                                   = Veuillez patienter...
Restore                                   = Restaurer
Run                                       = Démarrer
SelectAll                                 = Tout sélectionner
Skip                                      = Passer
Skipped                                   = Passé
TelegramGroupTitle                        = Rejoignez notre groupe Telegram officiel
TelegramChannelTitle                      = Rejoignez notre canal Telegram officiel
Uninstall                                 = Désinstaller
'@
