ConvertFrom-StringData -StringData @'
UnsupportedArchitecture                   = Você está usando uma CPU com arquitetura baseada em "{0}". Este script suporta apenas CPUs com arquitetura Arm. Baixe e execute a versão do script para a sua arquitetura.
NewSophiaScriptFound                      = Está disponível uma nova versão: Sophia Script for Windows {0}. Por favor, atualize.
UnsupportedPowerShell                     = Você está tentando executar o script via PowerShell {0}.{1}. Execute o script no PowerShell {2}.
CodeCompilationFailed                     = Falha na compilação do código.
KeyboardArrows                            = Use as teclas de seta {0} e {1} do teclado para selecionar sua resposta
UnsupportedLanguageMode                   = A sessão do PowerShell está sendo executada em um modo de linguagem limitada.
LoggedInUserNotAdmin                      = O usuário conectado "{0}" não possui direitos de administrador. O script foi executado em nome de "{1}". Faça login em uma conta com direitos de administrador e execute o script novamente.
UnsupportedHost                           = O script não suporta a execução por meio do {0}.
HarmfulTweakerFound                       = A estabilidade do sistema operacional Windows pode ter sido comprometida pela utilização do {0}.
HostsEntriesFound                         = Entradas de terceiros encontradas no arquivo %SystemRoot%\\System32\\drivers\\etc\\hosts. Elas podem bloquear a conexão com recursos usados no script. Deseja continuar?
UWPComponentsMissing                      = O componente UWP "{0}" está faltando.
DefenderComponentsMissing                 = O componente "{0}" do Microsoft Defender está faltando.
WindowsComponentStabilityDisrupted        = Foi detectado um problema de instabilidade no componente "{0}".
DisableControlledFolderAccess             = Você tem o acesso controlado a pastas ativado. Desative-o e execute o script novamente.
RebootPending                             = Seu computador está aguardando para ser reiniciado.
SystemDriveEncryptedBitLockerDisabled     = A unidade C está criptografada, embora o BitLocker esteja desativado. Deseja descriptografar sua unidade?
UpdateUEFICertificates                    = O certificado de inicialização segura "Microsoft Windows Production PCA 2011" expira em 2026. Seu dispositivo ainda não recebeu os certificados atualizados "Windows UEFI CA 2023". Deseja instalar manualmente os certificados "Microsoft Windows UEFI CA 2023"?
EnableSecureBoot                          = Ative a inicialização segura.
WrongSophiaScriptVersion                  = O script é compatível com o Windows 11 25H2 e versões posteriores. Você está usando o {0} {1}. Execute o script correto de acordo com a edição do Windows.
UpdateWindowsTerminal                     = A versão do Windows Terminal é inferior a 1.24. Atualize-a na Microsoft Store e tente novamente.
UpdateWindowsBuild                        = O script é compatível com o Windows 11 25H2 {0}.{1} e versões posteriores. Você está usando o {2} {3} {4}.{5}. Execute o Windows Update e tente novamente.
AskQuestion                               = Caso tenha alguma dúvida, abra uma issue no GitHub ou pergunte à comunidade.
CheckSophiaScriptPreset                   = Você personalizou todas as funções no arquivo de predefinição {0} antes de executar o Sophia Script for Windows?
ReinstallWindows                          = Reinstale o Windows usando apenas uma imagem ISO genuína.
CreatingRestorePoint                      = O ponto de restauração está sendo criado...
WindowsServiceNotFound                    = O serviço "{0}" não foi encontrado.
NoScheduledTasksFound                     = Nenhuma tarefa agendada foi encontrada.
ScheduledTasks                            = Tarefas agendadas
WidgetNotInstalled                        = O widget não está instalado.
SearchHighlightsDisabled                  = Os destaques da pesquisa já estão ocultos no Início.
CustomStartMenuFound                      = Um Menu Iniciar de terceiros está instalado.
OneDriveNotInstalled                      = O OneDrive já está desinstalado.
OneDriveAccountUsageFound                 = Antes de desinstalar o OneDrive, saia da sua conta da Microsoft no OneDrive.
OneDriveInstalled                         = O OneDrive já está instalado.
UninstallingApplication                   = O {0} está sendo desinstalado...
InstallingApplication                     = O {0} está sendo instalado...
NoWindowsFeaturesFound                    = Nenhum recurso do Windows foi encontrado.
WindowsFeaturesTitle                      = Recursos do Windows
NoOptionalFeaturesFound                   = Nenhum recurso opcional foi encontrado.
OptionalFeaturesTitle                     = Recursos opcionais
NoSupportedNetworkAdaptersFound           = Nenhum adaptador de rede compatível com a função "Permitir que o computador desligue este dispositivo para economizar energia" foi encontrado.
LocationServicesDisabled                  = Os comandos do shell de rede precisam de permissão de localização para acessar as informações da WLAN. Ative os serviços de localização na página Localização nas configurações de Privacidade e segurança.
UserFolderLocationMove                    = Você não deve alterar o local da pasta do usuário para a raiz da unidade C.
DriveSelect                               = Selecione a unidade na qual a pasta "{0}" será criada no diretório raiz.
CurrentUserFolderLocation                 = A localização atual da pasta "{0}": "{1}".
FilesWontBeMoved                          = Os arquivos não serão movidos.
UserFolderMoveSkipped                     = Você não alterou a localização da pasta "{0}" do usuário.
UserShellFolderNotEmpty                   = Alguns arquivos permaneceram na pasta "{0}". Mova-os manualmente para o novo local.
FolderSelect                              = Selecione uma pasta
UserFolderRequest                         = Gostaria de alterar a localização da pasta "{0}"?
UserDefaultFolder                         = Gostaria de alterar a localização da pasta "{0}" para o valor padrão?
ReservedStorageIsInUse                    = O espaço de armazenamento reservado está em uso.
ProgramPathNotExists                      = O caminho "{0}" não existe.
ProgIdNotExists                           = O ProgId "{0}" não existe.
AllFilesFilter                            = Todos os arquivos
JSONNotValid                              = O arquivo JSON "{0}" não é válido.
PackageNotInstalled                       = O aplicativo "{0}" não está instalado.
PackageIsInstalled                        = A versão mais recente do {0} já está instalada.
PCNPUSupport                              = O seu PC não possui um acelerador de IA integrado (NPU), portanto não há suporte para funções relacionadas à IA do Windows. Nenhuma das políticas será aplicada, exceto a remoção da função "Recall" e do aplicativo Copilot.
UWPAppsTitle                              = Apps UWP
UninstallUWPForAll                        = Para todos os usuários
NoUWPAppsFound                            = Não há aplicativos UWP para desinstalar.
WDDMVersionUnsupported                    = A versão mínima suportada do WDDM é a 2.7. A versão atual do WDDM é a {0}.
CleanupTaskNotificationTitle              = Limpeza do Windows
CleanupTaskNotificationEvent              = Executar tarefa para limpar arquivos e atualizações não utilizados do Windows?
CleanupTaskDescription                    = Limpeza de arquivos e atualizações não utilizados do Windows usando o aplicativo interno Limpeza de Disco.
CleanupNotificationTaskDescription        = Notificação pop-up com lembrete sobre a limpeza de arquivos e atualizações não utilizados do Windows.
SoftwareDistributionTaskNotificationEvent = O cache de atualizações do Windows foi excluído com sucesso.
SoftwareDistributionTaskDescription       = Limpeza da pasta de cache de atualizações do Windows "{0}".
TempTaskNotificationEvent                 = A pasta temporária foi limpa com sucesso.
TempTaskDescription                       = Limpeza da pasta temporária "{0}" (%TEMP%).
ScheduledTaskLoggedInUserNotification     = A tarefa agendada só pode ser executada se o usuário "{0}" estiver conectado ao sistema.
CleanupTaskCLIDescription                 = A tarefa agendada "Sophia\\Windows Cleanup Notification" foi criada no Agendador de Tarefas para limpar arquivos e atualizações não utilizados do Windows.
SoftwareDistributionTaskCLIDescription    = A tarefa agendada "Sophia\\SoftwareDistribution" foi criada no Agendador de Tarefas para limpar a pasta de cache de atualizações do Windows "{0}".
TempTaskCLIDescription                    = A tarefa agendada "Sophia\\Temp" foi criada no Agendador de Tarefas para limpar a pasta temporária "{0}" (%TEMP%).
EventViewerCustomViewName                 = Criação de processo
EventViewerCustomViewDescription          = Rastreamento dos processos iniciados e da atividade do PowerShell
EventViewerCustomViewNotification         = O modo de exibição personalizado "Modos de Exibição Personalizados\\{0}" foi criado no Visualizador de Eventos para rastrear os processos iniciados e a atividade do PowerShell.
ThirdPartyAVInstalled                     = Um antivírus de terceiros está instalado.
NoHomeWindowsEditionSupport               = A edição Windows Home não suporta a função "{0}".
EnableHardwareVT                          = Ative a virtualização no UEFI.
ActiveNetworkAdapterNotFound              = Não foi possível determinar o adaptador de rede em uso: nenhuma conexão de rede ativa foi encontrada. Conecte-se a uma rede.
ThirdPartyArchiverInstalled               = Um arquivador de terceiros está instalado.
gpeditNotSupported                        = A edição Windows Home não suporta o snap-in Editor de Política de Grupo Local (gpedit.msc).
RestartWarning                            = Certifique-se de reiniciar o PC.
RestorePointVolume                        = Os pontos de restauração da unidade C ocupam {0} GB.
ErrorsLine                                = Linha
ErrorsMessage                             = Erros, avisos e notificações
Disable                                   = Desativar
Enable                                    = Ativar
Install                                   = Instalar
Uninstall                                 = Desinstalar
RestartFunction                           = Execute a função "{0}" novamente.
NoConnectionEstablished                   = Uma conexão não pôde ser estabelecida com {0}.
Run                                       = Executar
FunctionSkipped                           = A função "{0}" foi ignorada.
DonateToastTitle                          = Doações são bem-vindas! ❤
DotSourceFunction                         = Faça o "dot-source" da função (com um ponto no início):\n. .\\Import-TabCompletion.ps1
'@
