ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                   = Скрипт підтримує тільки Windows 10 x64
UnsupportedOSBuild                     = Скрипт підтримує тільки Windows 10 1809 Enterprise LTSC
UnsupportedRelease                     = Виявлено нову версію
ControlledFolderAccessDisabled         = Контрольований доступ до папок вимкнений
ScheduledTasks                         = Заплановані задачі
ClearFolder                            = Видаліть всі файли у папці "{0}"?
FilesBlocked                           = Наступні файли блокуються сторонніми програмами\nВидаліть їх вручну та продовжуйте
TempNotEmpty                           = Папка "{0}" не порожня. Очистіть її вручну
WindowsFeaturesWindowTitle             = Компоненти Windows
FODWindowTitle                         = Додаткові компоненти (FODv2)
EnableHardwareVT                       = Увімкніть віртуалізацію в UEFI
UserShellFolderNotEmpty                = У папці "{0}" залишились файли. Перемістіть їх вручну у нове розташування
RetrievingDrivesList                   = Отримання списку дисків...
NewUserShellFolderLocation             = Нове розташування: "{0}"
DesktopDriveSelect                     = Виберіть диск, в корні якого буде створена папка для "Робочий стіл"
DocumentsDriveSelect                   = Виберіть диск, в корні якого буде створена папка для "Документи"
DownloadsDriveSelect                   = Виберіть диск, в корні якого буде створена папка для "Завантаження"
MusicDriveSelect                       = Виберіть диск, в корні якого буде створена папка для "Музика"
PicturesDriveSelect                    = Виберіть диск, в корні якого буде створена папка для "Зображения"
VideosDriveSelect                      = Виберіть диск, в корні якого буде створена папка для "Відео"
DesktopRequest                         = Хочете змінити розташування папки "Робочий стіл"?
DocumentsRequest                       = Хочете змінити розташування папки "Документи"?
DownloadsRequest                       = Хочете змінити розташування папки "Завантаження"?
MusicRequest                           = Хочете змінити розташування папки "Музика"?
PicturesRequest                        = Хочете змінити розташування папки "Зображения"?
VideosRequest                          = Хочете змінити розташування папки "Відео"?
DesktopFolderSelect                    = Виберіть папку для "Робочий стіл"
DocumentsFolderSelect                  = Виберіть папку для "Документи"
DownloadsFolderSelect                  = Виберіть папку для "Завантаження"
MusicFolderSelect                      = Виберіть папку для "Музика"
PicturesFolderSelect                   = Виберіть папку для "Зображения"
VideosFolderSelect                     = Виберіть папку для "Відео"
DesktopDefaultFolder                   = Хочете змінити розташування папки "Робочий стіл" на значення за замовчуванням?
DocumentsDefaultFolder                 = Хочете змінити розташування папки "Документи" на значення за замовчуванням?
DownloadsDefaultFolder                 = Хочете змінити розташування папки "Завантаження" на значення за замовчуванням?
MusicDefaultFolder                     = Хочете змінити розташування папки "Музика" на значення за замовчуванням?
PicturesDefaultFolder                  = Хочете змінити розташування папки "Зображения" на значення за замовчуванням?
VideosDefaultFolder                    = Хочете змінити розташування папки "Відео" на значення за замовчуванням?
GraphicsPerformanceTitle               = Налаштування продуктивності графіки
GraphicsPerformanceRequest             = Встановити для будь-якої програми за вашим вибором налаштування продуктивності графіки на "Висока продуктивність"?
CleanUpTaskToast                       = Очищення зайвих файлів і оновлень Windows почнеться через хвилину
CleanUpTaskDescription                 = Очищення зайвих файлів і оновлень Windows, використовуючи вбудовану програму очищення диска
FolderTaskDescription                  = Очищення папки "{0}"
ControlledFolderAccess                 = Контрольований доступ до папок
ProtectedFoldersRequest                = Бажаєте увімкнути контрольований доступ до папок і вказати папку, яку Microsoft Defender буде захищати від шкідливих додатків і загроз?
ProtectedFoldersListRemoved            = Видалення папки
AppControlledFolderRequest             = Вказати додаток, якому дозволена робота через контрольований доступ до папок
AllowedControlledFolderAppsRemoved     = Видалені дозволені додатки
DefenderTitle                          = Microsoft Defender
DefenderExclusionFolderRequest         = Вказати папку, щоб виключити її зі списку сканування Microsoft Defender?
DefenderExclusionFoldersListRemoved    = Виключені папки видалені
AddDefenderExclusionFileRequest        = Вказати файл, щоб виключити його зі списку сканування Microsoft Defender?
DefenderExclusionFilesRemoved          = Виключені файли видалені
EventViewerCustomViewName              = Створення процесу
EventViewerCustomViewDescription       = Події створення нового процесу і аудит командного рядка
RestartWarning                         = Обов'язково перезавантажте ваш ПК
ErrorsLine                             = Рядок
ErrorsFile                             = Файл
ErrorsMessage                          = Помилки/попередження
Add                                    = Додати
AllFilesFilter                         = Усі файли (*.*)|*.*
Change                                 = Змінити
Continue                               = Продовжити
DialogBoxOpening                       = Діалогове вікно відкривається...
Disable                                = Вимкнути
Enable                                 = Увімкнути
EXEFilesFilter                         = *.exe|*.exe|Усі файли (*.*)|*.*
FolderSelect                           = Виберіть папку
FilesWontBeMoved                       = Файли не будуть перенесені
NoData                                 = Відсутні дані
NoInternetConnection                   = Відсутнє інтернет-з'єднання
Patient                                = Будь ласка, зачекайте...
Select                                 = Вибрати
Skip                                   = Пропустити
Skipped                                = Пропущено
SymbolicSkipped                        = Пропущено створення символічного посилання
Uninstall                              = Видалити
Install                                = Встановити
'@
