ConvertFrom-StringData -StringData @'
NewSophiaScriptFound                      = Hay una nueva versión disponible: Sophia Script for Windows {0}. Por favor, actualízala.
UnsupportedPowerShell                     = Estás intentando ejecutar el script a través de PowerShell {0}.{1}. Por favor, ejecute el script en PowerShell {2}.
CodeCompilationFailed                     = La compilación del código ha fallado.
UnsupportedWindowsBitness                 = El script sólo es compatible con Windows de 64 bits.
KeyboardArrows                            = Utilice las flechas {0} y {1} de su teclado para seleccionar la respuesta
UnsupportedLanguageMode                   = Sesión de PowerShell ejecutada en modo de lenguaje limitado.
LoggedInUserNotAdmin                      = El usuario "{0}" que ha iniciado sesión no tiene derechos de administrador. El script se ha ejecutado en nombre de "{1}". Inicie sesión en una cuenta con derechos de administrador y vuelva a ejecutar el script.
UnsupportedHost                           = El script no es compatible con la ejecución a través de {0}.
HarmfulTweakerFound                       = La estabilidad del sistema operativo Windows puede haberse visto comprometida al utilizar el {0}.
HostsEntriesFound                         = Entradas de terceros encontradas en el archivo %SystemRoot%\\System32\\drivers\\etc\\hosts. Pueden bloquear la conexión a los recursos utilizados en el script. ¿Desea continuar?
WindowsComponentStabilityDisrupted        = Se ha detectado un problema de inestabilidad en el componente "{0}".
DisableControlledFolderAccess             = Tienes habilitado el acceso controlado a carpetas. Desactívalo y vuelve a ejecutar el script.
RebootPending                             = Tu PC está esperando a que lo reinicies.
SystemDriveEncryptedBitLockerDisabled     = La unidad C está cifrada, aunque BitLocker está desactivado. ¿Desea descifrar la unidad?
WrongSophiaScriptVersion                  = El script sólo es compatible con Windows 10 Enterprise LTSC 2019. Estás usando Windows {0} {1}. Ejecuta el script adecuado según la edición de Windows.
UpdateWindowsBuild                        = Estás utilizando Windows 10 Enterprise LTSC 2019 {0}.{1}. La versión compatible es Windows 10 Enterprise LTSC 2019 {0}.{2} y superior. Ejecuta Windows Update e inténtalo de nuevo.
CheckSophiaScriptPreset                   = ¿Ha personalizado todas las funciones del archivo predeterminado {0} antes de ejecutar Sophia Script for Windows?
ReinstallWindows                          = Reinstale Windows utilizando sólo una imagen ISO original.
CreatingRestorePoint                      = Se está creando un punto de restauración...
UWPComponentsMissing                      = Falta el componente UWP "{0}".
DefenderComponentsMissing                 = Falta el componente "{0}" de Microsoft Defender.
DiagTrackServiceNotFound                  = No se ha encontrado el servicio "DiagTrackService".
NoScheduledTasksFound                     = No hay tareas programadas que desactivar.
ScheduledTasks                            = Tareas programadas
TaskbarSmallIcons                         = Utilizas botones pequeños en la barra de tareas.
InstallingApplication                     = Se está instalando {0}...
NoWindowsFeaturesFound                    = No hay funciones de Windows que desactivar.
WindowsFeaturesTitle                      = Características de Windows
NoOptionalFeaturesFound                   = No hay funciones opcionales que desactivar.
NoSupportedNetworkAdaptersFound           = No hay adaptadores de red que admitan la función "Permitir que el equipo apague este dispositivo para ahorrar energía".
LocationServicesDisabled                  = Los comandos de shell de red necesitan permiso de ubicación para acceder a la información de la red WLAN. Active los servicios de ubicación en la página Ubicación de la configuración de Privacidad y seguridad.
OptionalFeaturesTitle                     = Características opcionales
UserShellFolderNotEmpty                   = Algunos archivos quedan en la carpeta "{0}". Moverlos manualmente a una nueva ubicación.
UserFolderLocationMove                    = No deberías cambiar la ubicación de la carpeta de usuario a la raíz de la unidad C.
DriveSelect                               = Seleccione la unidad dentro de la raíz de la cual se creó la carpeta "{0}".
CurrentUserFolderLocation                 = La ubicación actual de la carpeta "{0}": "{1}".
FilesWontBeMoved                          = Los archivos no se moverán.
UserFolderMoveSkipped                     = Selecciona la unidad en la que se creará la carpeta "{0}" en el directorio raíz.
FolderSelect                              = Seleccionar una carpeta
UserFolderRequest                         = ¿Le gustaría cambiar la ubicación de la "{0}" carpeta?
UserDefaultFolder                         = ¿Le gustaría cambiar la ubicación de la carpeta "{0}" para el valor por defecto?
ProgramPathNotExists                      = La ruta "{0}" no existe.
ProgIdNotExists                           = La ProgId "{0}" no existe.
AllFilesFilter                            = Todos los archivos
JSONNotValid                              = El archivo JSON "{0}" no es válido.
PackageNotInstalled                       = La aplicación "{0}" no está instalada.
PackageIsInstalled                        = La última versión de {0} ya está instalada.
ScheduledTaskCreatedByAnotherUser         = La tarea programada "{0}" ya fue creada por el usuario "{1}".
CleanupTaskNotificationTitle              = Limpieza de Windows
CleanupTaskNotificationEvent              = ¿Ejecutar la tarea de limpiar los archivos no utilizados y actualizaciones de Windows?
CleanupTaskDescription                    = La limpieza de Windows los archivos no utilizados y actualizaciones utilizando una función de aplicación de limpieza de discos.
CleanupNotificationTaskDescription        = Pop-up recordatorio de notificaciones sobre la limpieza de archivos no utilizados de Windows y actualizaciones.
SoftwareDistributionTaskNotificationEvent = La caché de actualización de Windows eliminado correctamente.
SoftwareDistributionTaskDescription       = Limpiando la carpeta de caché de actualización de Windows "{0}".
TempTaskNotificationEvent                 = Los archivos de la carpeta Temp limpiados con éxito.
TempTaskDescription                       = Limpiando la carpeta temporal "{0}" (%TEMP%).
ScheduledTaskLoggedInUserNotification     = La tarea programada sólo puede ejecutarse si el usuario "{1}" ha iniciado sesión en el sistema.
ScheduledTaskCreatedNotification          = Se creó la tarea programada "{0}".
CleanupTaskCLIDescription                 = Ve a la carpeta "Sophia" en el Programador de tareas y ejecuta la tarea "Windows Cleanup Notification" para comenzar a limpiar los archivos y actualizaciones no utilizados de Windows.
SoftwareDistributionTaskCLIDescription    = Vaya a la carpeta "Sophia" en el Programador de tareas y ejecute la tarea "SoftwareDistribution" para comenzar a limpiar la carpeta de caché de actualización de Windows "{0}".
TempTaskCLIDescription                    = Ve a la carpeta "Sophia" en el Programador de tareas y ejecuta la tarea "Temp" para comenzar a limpiar la carpeta de archivos temporales "{0}" (%TEMP%).
EventViewerCustomViewName                 = Creación de proceso
EventViewerCustomViewDescription          = Eventos de auditoría de línea de comandos y creación de procesos.
ThirdPartyAVInstalled                     = Se ha instalado un antivirus de terceros.
EnableHardwareVT                          = Habilitar la virtualización en UEFI.
ThirdPartyArchiverInstalled               = Se ha instalado un archivador de terceros.
RestartWarning                            = Asegúrese de reiniciar su PC.
RestorePointVolume                        = Los puntos de restauración de la unidad C ocupan {0} GB.
ErrorsLine                                = Línea
ErrorsMessage                             = Errores, advertencias y notificaciones
Disable                                   = Desactivar
Enable                                    = Habilitar
Install                                   = Instalar
Uninstall                                 = Desinstalar
RestartFunction                           = Por favor, reinicie la función "{0}".
NoConnectionEstablished                   = No se pudo establecer una conexión con {0}.
Run                                       = Iniciar
FunctionSkipped                           = Función "{0}" omitida.
DonateToastTitle                          = ¡Se aceptan donaciones!❤
DotSourcedFunction                        = Por favor, "dot-source" la función (con un punto al principio):\n. .\\Import-TabCompletion.ps1
'@
