ConvertFrom-StringData -StringData @'
UnsupportedOSBuild                        = \n脚本支持Windows 11 22H2+
UpdateWarning                             = \n您的Windows 11构建: {0}.{1}。支持的构建: 22621.1413和更高版本。运行Windows Update并再次尝试
UnsupportedLanguageMode                   = \nPowerShell会话在有限的语言模式下运行
LoggedInUserNotAdmin                      = \n登录的用户没有管理员的权利
UnsupportedPowerShell                     = \n你想通过PowerShell {0}.{1}运行脚本。在适当的PowerShell版本中运行该脚本
UnsupportedHost                           = \n该脚本不支持通过{0}运行
Win10TweakerWarning                       = \n可能你的操作系统是通过"Win 10 Tweaker"后门感染的
TweakerWarning                            = \nWindows的稳定性可能已被{0}所破坏。预防性地，重新安装整个操作系统
bin                                       = \nbin文件夹中没有文件。请重新下载该档案
RebootPending                             = \n计算机正在等待重新启动
UnsupportedRelease                        = \n找到新版本
CustomizationWarning                      = \n在运行Sophia Script之前，您是否已自定义{0}预设文件中的每个函数？
WindowsComponentBroken                    = \n{0} 损坏或从操作系统中删除
UpdateDefender                            = \nMicrosoft Defender的定义已经过期。运行Windows Update并再次尝试
ControlledFolderAccessDisabled            = "受控文件夹访问"已禁用
ScheduledTasks                            = 计划任务
OneDriveUninstalling                      = 卸载OneDrive……
OneDriveInstalling                        = OneDrive正在安装……
OneDriveDownloading                       = 正在下载OneDrive…… ~33 MB
OneDriveWarning                           = 只有当预设被配置为删除OneDrive（或应用程序已经被删除）时，才会应用"{0}"功能，否则OneDrive中 "桌面 "和 "图片 "文件夹的备份功能就会中断
WindowsFeaturesTitle                      = Windows功能
OptionalFeaturesTitle                     = 可选功能
EnableHardwareVT                          = UEFI中开启虚拟化
UserShellFolderNotEmpty                   = 一些文件留在了"{0}"文件夹。请手动将它们移到一个新位置
RetrievingDrivesList                      = 取得驱动器列表……
DriveSelect                               = 选择将在其根目录中创建"{0}"文件夹的驱动器
CurrentUserFolderLocation                 = 当前"{0}"文件夹的位置:"{1}"
UserFolderRequest                         = 是否要更改"{0}"文件夹位置？
UserFolderSelect                          = 为"{0}"文件夹选择一个文件夹
UserDefaultFolder                         = 您想将"{0}"文件夹的位置更改为默认值吗？
ReservedStorageIsInUse                    = 保留存储空间正在使用时不支持此操作\n请在电脑重启后重新运行"{0}"功能
ShortcutPinning                           = "{0}"快捷方式将被固定到开始菜单……
SSDRequired                               = 要在您的设备上使用Windows Subsystem for Android™，您的电脑需要安装固态驱动器（SSD）
UninstallUWPForAll                        = 对于所有用户
UWPAppsTitle                              = UWP应用
HEVCDownloading                           = 下载"HEVC Video Extensions from Device Manufacturer"…… ~2,8 MB
GraphicsPerformanceTitle                  = 图形性能偏好
GraphicsPerformanceRequest                = 是否将所选应用程序的图形性能设置设为"高性能"？
ScheduledTaskPresented                    = "{0}"函数已经被创建为"{1}"
CleanupTaskNotificationTitle              = Windows清理
CleanupTaskNotificationEvent              = 运行任务以清理Windows未使用的文件和更新？
CleanupTaskDescription                    = 使用内置磁盘清理工具清理未使用的Windows文件和更新
CleanupNotificationTaskDescription        = 关于清理Windows未使用的文件和更新的弹出通知提醒
SoftwareDistributionTaskNotificationEvent = Windows更新缓存已成功删除
TempTaskNotificationEvent                 = 临时文件文件夹已成功清理
FolderTaskDescription                     = "{0}"文件夹清理
EventViewerCustomViewName                 = 进程创建
EventViewerCustomViewDescription          = 进程创建和命令行审核事件
RestartWarning                            = 确保重启电脑
ErrorsLine                                = 行
ErrorsMessage                             = 错误/警告
DialogBoxOpening                          = 显示对话窗口……
Disable                                   = 禁用
EXEFilesFilter                            = *.exe|*.exe|所有文件 (*.*)|*.*
FolderSelect                              = 选择一个文件夹
FilesWontBeMoved                          = 文件将不会被移动
Install                                   = 安装
NoData                                    = 无数据
NoInternetConnection                      = 无网络连接
RestartFunction                           = 请重新运行"{0}"函数
NoResponse                                = 无法建立{0}
Restore                                   = 恢复
Run                                       = 运行
Skipped                                   = 已跳过
GPOUpdate                                 = GPO更新……
TelegramGroupTitle                        = 加入我们的官方Telegram 群
TelegramChannelTitle                      = 加入我们的官方Telegram 频道
DiscordChannelTitle                       = 加入我们的官方Discord 频道
Uninstall                                 = 卸载
'@
