ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Lo script supporta solo Windows a 64 bit.
UnsupportedOSBuild                        = Lo script supporta Windows 10 Enterprise LTSC 2021.
UpdateWarning                             = La tua build di Windows 10 {0}.{1} non è supportata. Build supportate: {2}+. Eseguire Windows Update e riprovare.
UnsupportedLanguageMode                   = La sessione PowerShell è in esecuzione in modalità lingua limitata.
LoggedInUserNotAdmin                      = L'utente in suo non ha i diritti di amministratore.
UnsupportedPowerShell                     = Stai cercando di eseguire lo script tramite PowerShell {0}.{1}. Esegui lo script nella versione di PowerShell appropriata.
PowerShellx86Warning                      = Si sta cercando di eseguire lo script tramite PowerShell (x86). Eseguire lo script in PowerShell (x64).
UnsupportedHost                           = Lo script non supporta l'esecuzione tramite {0}.
Win10TweakerWarning                       = Probabilmente il tuo sistema operativo è stato infettato tramite una backdoor in Win 10 Tweaker.
TweakerWarning                            = La stabilità del sistema operativo Windows potrebbe essere stata compromessa dall'utilizzo dello {0}. Per sicurezza, reinstallare Windows.
Bin                                       = Non ci sono file nella cartella bin. Per favore, scarica di nuovo l'archivio.
RebootPending                             = Il PC è in attesa di essere riavviato.
UnsupportedRelease                        = Nuova versione trovata.
KeyboardArrows                            = Per selezionare la risposta, utilizzare i tasti freccia "{0}" e "{1}" della tastiera
CustomizationWarning                      = Sono state personalizzate tutte le funzioni nel file di configurazione {0} prima di eseguire Sophia Script?
WindowsComponentBroken                    = {0} rimosso dal sistema.
UpdateDefender                            = Le definizioni di Microsoft Defender non sono aggiornate. Eseguire Windows Update e riprovare.
ControlledFolderAccessDisabled            = l'accesso alle cartelle controllata disattivata.
InitialActionsCheckFailed                 = La funzione "InitialActions" non può essere caricata dal file di preselezione {0}.
ScheduledTasks                            = Attività pianificate
WindowsFeaturesTitle                      = Funzionalità di Windows
OptionalFeaturesTitle                     = Caratteristiche opzionali
EnableHardwareVT                          = Abilita virtualizzazione in UEFI.
UserShellFolderNotEmpty                   = Alcuni file rimasti nella cartella "{0}". Spostali manualmente in una nuova posizione.
UserFolderLocationMove                    = Non si dovrebbe modificare la posizione della cartella utente nella radice dell'unità C.
RetrievingDrivesList                      = Recupero lista unità...
DriveSelect                               = Selezionare l'unità all'interno della radice del quale verrà creato la cartella "{0}" .
CurrentUserFolderLocation                 = La posizione attuale della cartella "{0}": "{1}".
UserFolderRequest                         = Volete cambiare la posizione della cartella "{0}"?
UserDefaultFolder                         = Volete cambiare la posizione della cartella "{0}" al valore di default?
ReservedStorageIsInUse                    = Questa operazione non è supportata quando spazio riservato è in uso Si prega di eseguire nuovamente la funzione "{0}" dopo il riavvio del PC.
ShortcutPinning                           = Il collegamento "{0}" è stato bloccato...
GraphicsPerformanceTitle                  = Volete impostare l'impostazione delle prestazioni grafiche di un app di vostra scelta a "Prestazioni elevate"?
ActionCenter                              = Per utilizzare la funzione "{0}" è necessario attivare il Centro operativo.
WindowsScriptHost                         = Accesso a Windows Script Host disabilitato sul computer in uso. Per utilizzare la funzione "{0}" è necessario abilitare Windows Script Host.
ScheduledTaskPresented                    = La funzione "{0}" è già stata creata come "{1}".
CleanupTaskNotificationTitle              = Pulizia di Windows
CleanupTaskNotificationEvent              = Eseguire l'operazione di pulizia dei file inutilizzati e aggiornamenti di Windows?
CleanupTaskDescription                    = Pulizia di Windows e dei file inutilizzati degli aggiornamenti utilizzando l'app built-in ""pulizia disco".
CleanupNotificationTaskDescription        = Pop-up promemoria di pulizia dei file inutilizzati e degli aggiornamenti di Windows.
SoftwareDistributionTaskNotificationEvent = La cache degli aggiornamenti di Windows cancellata con successo.
TempTaskNotificationEvent                 = I file cartella Temp puliti con successo.
FolderTaskDescription                     = Pulizia della cartella "{0}".
EventViewerCustomViewName                 = Creazione del processo
EventViewerCustomViewDescription          = Creazione del processi e degli eventi di controllo della riga di comando.
RestartWarning                            = Assicurarsi di riavviare il PC.
ErrorsLine                                = Linea
ErrorsMessage                             = Errori/avvisi
DialogBoxOpening                          = Visualizzazione della finestra di dialogo...
Disable                                   = Disattivare
Enable                                    = Abilitare
UserChoiceWarning                         = Microsoft ha bloccato l'accesso in scrittura alla chiave UserChoice per l'estensione .pdf e il protocollo http/https con il rilascio della KB5034765.
AllFilesFilter                            = Tutti i file
FolderSelect                              = Selezionare una cartella
FilesWontBeMoved                          = I file non verranno trasferiti.
Install                                   = Installare
NoData                                    = Niente da esposizione.
NoInternetConnection                      = Nessuna connessione Internet.
RestartFunction                           = Si prega di riavviare la funzione "{0}".
NoResponse                                = Non è stato possibile stabilire una connessione con {0}.
Restore                                   = Ristabilire
Run                                       = Eseguire
Skipped                                   = Saltato.
GPOUpdate                                 = Aggiornamento GPO...
TelegramGroupTitle                        = Unisciti al nostro gruppo ufficiale Telegram.
TelegramChannelTitle                      = Unisciti al nostro canale ufficiale di Telegram.
DiscordChannelTitle                       = Unisciti al nostro canale ufficiale di Discord.
Uninstall                                 = Disinstallare
'@
