ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Скрипт поддерживает только Windows 10 x64
UnsupportedOSBuild                        = Скрипт поддерживает только Windows 10 Enterprise LTSC 2019
UpdateWarning                             = Установленный накопительный пакет обновления Windows 10: {0}. Поддерживаемый накопительный пакет обновления: 3770 и выше. Запустите обновление Windows и попробуйте заново
UnsupportedLanguageMode                   = Сессия PowerShell работает в ограниченном режиме
LoggedInUserNotAdmin                      = Текущий вошедший пользователь не обладает правами администратора
UnsupportedPowerShell                     = Вы пытаетесь запустить скрипт в PowerShell {0}.{1}. Запустите скрипт в соответствующей версии PowerShell
UnsupportedISE                            = Скрипт не поддерживает работу через Windows PowerShell ISE
Win10TweakerWarning                       = Ваша ОС, возможно, через бэкдор в Win 10 Tweaker была заражена трояном. Подробнее: https://itnan.ru/post.php?c=1&p=557388
SycnexWarning                             = Стабильность Windows могла быть нарушена использованием скрипта Windows10Debloater от Sycnex. В целях профилактики переустановите ОС
Fs00Warning                               = Стабильность Windows могла быть нарушена использованием "Windows 10 Bloat Remover and Tweaker". В целях профилактики переустановите ОС
bin                                       = В папке bin отсутствутствуют файлы. Пожалуйста, перекачайте архив
RebootPending                             = Компьютер ожидает перезагрузки
UnsupportedRelease                        = Обнаружена новая версия
CustomizationWarning                      = \nВы настроили все функции в пресет-файле {0} перед запуском Sophia Script?
DefenderBroken                            = Microsoft Defender сломан или удален из ОС
UpdateDefender                            = Определения Microsoft Defender устарели. Запустите обновление Windows
ControlledFolderAccessDisabled            = Контролируемый доступ к папкам выключен
ScheduledTasks                            = Запланированные задания
WindowsFeaturesTitle                      = Компоненты Windows
OptionalFeaturesTitle                     = Дополнительные компоненты
EnableHardwareVT                          = Включите виртуализацию в UEFI
UserShellFolderNotEmpty                   = В папке "{0}" остались файлы. Переместите их вручную в новое расположение
RetrievingDrivesList                      = Получение списка дисков...
DriveSelect                               = Выберите диск, в корне которого будет создана папка "{0}"
CurrentUserFolderLocation                 = Текущее расположение папки "{0}": "{1}"
UserFolderRequest                         = Хотите изменить расположение папки "{0}"?
UserFolderSelect                          = Выберите папку для "{0}"
UserDefaultFolder                         = Хотите изменить расположение папки "{0}" на значение по умолчанию?
GraphicsPerformanceTitle                  = Настройка производительности графики
GraphicsPerformanceRequest                = Установить для любого приложения по вашему выбору настройки производительности графики на "Высокая производительность"?
ScheduledTaskPresented                    = Функция "{0}" уже была создана от имени "{1}"
CleanupTaskNotificationTitle              = Очистка Windows
CleanupTaskNotificationEvent              = Запустить задание по очистке неиспользуемых файлов и обновлений Windows?
CleanupTaskDescription                    = Очистка неиспользуемых файлов и обновлений Windows, используя встроенную программу Очистка диска
CleanupNotificationTaskDescription        = Всплывающее уведомление с напоминанием об очистке неиспользуемых файлов и обновлений Windows
SoftwareDistributionTaskNotificationEvent = Кэш обновлений Windows успешно удален
TempTaskNotificationEvent                 = Папка временных файлов успешно очищена
FolderTaskDescription                     = Очистка папки {0}
EventViewerCustomViewName                 = Создание процесса
EventViewerCustomViewDescription          = События содания нового процесса и аудит командной строки
RestartWarning                            = Обязательно перезагрузите ваш ПК
ErrorsLine                                = Строка
ErrorsFile                                = Файл
ErrorsMessage                             = Ошибки/предупреждения
Add                                       = Добавить
AllFilesFilter                            = Все файлы (*.*)|*.*
Browse                                    = Обзор
DialogBoxOpening                          = Диалоговое окно открывается...
Disable                                   = Отключить
Enable                                    = Включить
EXEFilesFilter                            = *.exe|*.exe|Все файлы (*.*)|*.*
FolderSelect                              = Выберите папку
FilesWontBeMoved                          = Файлы не будут перенесены
Install                                   = Установить
NoData                                    = Отсутствуют данные
NoInternetConnection                      = Отсутствует интернет-соединение
RestartFunction                           = Пожалуйста, повторно запустите функцию "{0}"
NoResponse                                = Невозможно установить соединение с {0}
No                                        = Нет
Yes                                       = Да
Open                                      = Открыть
Patient                                   = Пожалуйста, подождите...
Restore                                   = Восстановить
Run                                       = Запустить
SelectAll                                 = Выбрать всё
Skipped                                   = Пропущено
GPOUpdate                                 = Обновление GPO...
TelegramGroupTitle                        = Присоединяйтесь к нашей официальной группе в Telegram
TelegramChannelTitle                      = Присоединяйтесь к нашему официальному каналу в Telegram
DiscordChannelTitle                       = Присоединяйтесь к нашему официальному каналу в Discord
Uninstall                                 = Удалить
'@
