ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Skrypt obsługuje tylko 64-bitowe systemy Windows.
UnsupportedOSBuild                        = Skrypt obsługuje tylko system Windows 10 Enterprise LTSC 2019. Używasz systemu {0} {1}. Zaktualizuj system Windows i spróbuj ponownie.
UnsupportedWindowsTerminal                = Wersja Windows Terminal jest niższa niż 1.23. Zaktualizuj ją w Microsoft Store i spróbuj ponownie.
UpdateWarning                             = Windows 10 {0}.{1} rendszert használ. A támogatott verzió Windows 10 {0}.{2} vagy újabb. Futtassa a Windows Update programot, majd próbálja meg újra.
UnsupportedLanguageMode                   = Sesja PowerShell działa w trybie ograniczonego języka.
LoggedInUserNotAdmin                      = Zalogowany użytkownik nie posiada uprawnień administratora.
UnsupportedPowerShell                     = Próbujesz uruchomić skrypt przy użyciu PowerShell {0}.{1}. Uruchom skrypt w PowerShell {2}.
CodeCompilationFailedWarning              = Kompilacja kodu nie powiodła się.
UnsupportedHost                           = Skrypt nie może być uruchamiany w {0}.
Win10TweakerWarning                       = Prawdopodobnie twój system operacyjny został zainfekowany przez backdoora pochodzącego z Win 10 Tweaker.
TweakerWarning                            = Stabilność systemu Windows mogła zostać naruszona przez użycie {0}. Zainstaluj ponownie system Windows, używając tylko oryginalnego obrazu ISO.
HostsWarning                              = Voci di terze parti presenti nel file {0}. Potrebbero bloccare le connessioni alle risorse utilizzate nello script. Volete continuare?
RebootPending                             = Komputer oczekuje na ponowne uruchomienie.
BitLockerWarning                          = Trwa szyfrowanie za pomocą funkcji BitLocker. Zakończ konfigurację dysku BitLocker i spróbuj ponownie.
UnsupportedRelease                        = Znaleziono nowszą wersję skryptu Sophia: {0}. Proszę pobrać najnowszą wersję.
KeyboardArrows                            = Użyj klawiszy strzałek {0} i {1} na klawiaturze, aby wybrać odpowiedź
CustomizationWarning                      = Czy dostosowałeś funkcje w predefiniowanym pliku {0} przed uruchomieniem Sophia Script?
WindowsComponentBroken                    = {0} jest uszkodzony lub usunięty z systemu operacyjnego. Zainstaluj ponownie system Windows, używając tylko oryginalnego obrazu ISO.
ControlledFolderAccessDisabled            = Kontrolowany dostęp do folderów został wyłączony.
ScheduledTasks                            = Zaplanowane zadania
WindowsFeaturesTitle                      = Funkcje Windows
OptionalFeaturesTitle                     = Funkcje opcjonalne
EnableHardwareVT                          = Włącz wirtualizację w UEFI.
UserShellFolderNotEmpty                   = Niektóre pliki pozostały w folderze "{0}". Przenieś je ręcznie w nowe miejsce.
UserFolderLocationMove                    = Nie należy zmieniać lokalizacji folderu użytkownika na katalog główny dysku C.
DriveSelect                               = Wybierz dysk w katalogu głównym, w którym zostanie utworzony folder "{0}".
CurrentUserFolderLocation                 = Lokalizacja folderu "{0}": "{1}".
UserFolderRequest                         = Czy chcesz zmienić lokalizację folderu "{0}"?
UserDefaultFolder                         = Czy chcesz zmienić lokalizację folderu "{0}" na wartość domyślną?
GraphicsPerformanceTitle                  = Czy chcesz ustawić wydajność grafiki wybranej aplikacji na "Wysoka wydajność"?
ScheduledTaskPresented                    = Funkcja "{0}" została już utworzona jako "{1}".
CleanupTaskNotificationTitle              = Oczyszczanie system Windows
CleanupTaskNotificationEvent              = Uruchomić zadanie w celu usunięcia nieużywanych plików i aktualizacji systemu Windows?
CleanupTaskDescription                    = Czyszczenie nieużywanych plików i aktualizacji systemu Windows za pomocą wbudowanej aplikacji do czyszczenia dysku. Zaplanowane zadanie może zostać uruchomione tylko wtedy, gdy użytkownik "{0}" jest zalogowany do systemu.
CleanupNotificationTaskDescription        = Powiadomienie przypominające o czyszczeniu nieużywanych plików i aktualizacji systemu Windows. Zaplanowane zadanie może zostać uruchomione tylko wtedy, gdy użytkownik "{0}" jest zalogowany do systemu.
SoftwareDistributionTaskNotificationEvent = Pomyślnie usunięto pamięć podręczną aktualizacji systemu Windows.
TempTaskNotificationEvent                 = Folder plików tymczasowych został pomyślnie wyczyszczony.
FolderTaskDescription                     = Czyszczenie folderu {0}. Zaplanowane zadanie może zostać uruchomione tylko wtedy, gdy użytkownik "{0}" jest zalogowany do systemu.
EventViewerCustomViewName                 = Tworzenie procesu
EventViewerCustomViewDescription          = Tworzenie procesu i zdarzeń audytu.
RestartWarning                            = Pamiętaj o ponownym uruchomieniu komputera.
ErrorsLine                                = Linia
ErrorsMessage                             = Błędy/Ostrzeżenia
DialogBoxOpening                          = Wyświetlanie okna dialogowego...
Disable                                   = Wyłączyć
Enable                                    = Włączać
AllFilesFilter                            = Wszystkie pliki
FolderSelect                              = Wybierz folder
FilesWontBeMoved                          = Pliki nie zostaną przeniesione.
Install                                   = Zainstalluj
Uninstall                                 = Odinstaluj
NoData                                    = Nic do wyświetlenia.
RestartFunction                           = Uruchom ponownie funkcję "{0}".
NoResponse                                = Nie można nawiązać połączenia z {0}.
Restore                                   = Przywróć
Run                                       = Uruchom
Skipped                                   = Pominięto.
ThankfulToastTitle                        = Dziękujemy za korzystanie z Sophia Script ❤️
DonateToastTitle                          = Możesz przekazać darowiznę poniżej 🕊
DotSourcedWarning                         = Prosimy o "dot-source" funkcji (z kropką na początku):\n. .\\Import-TabCompletion.ps1
'@
