ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Das Skript unterstützt nur 64-Bit-Windows.
UnsupportedOSBuild                        = Das Skript unterstützt Windows 10 22H2.
UpdateWarning                             = Ihr Windows 10-Build: {0}.{1}. Unterstützter Builds: {2}+. Führen Sie Windows Update aus und versuchen Sie es erneut.
UnsupportedLanguageMode                   = Die PowerShell-Sitzung wird in einem eingeschränkten Sprachmodus ausgeführt.
LoggedInUserNotAdmin                      = Der angemeldete Benutzer hat keine Administratorrechte.
UnsupportedPowerShell                     = Sie versuchen ein Skript über PowerShell {0}.{1} auszuführen. Das Skript in der entsprechenden PowerShell-Version ausführen.
PowerShellx86Warning                      = Sie versuchen ein Skript über PowerShell (x86). Führen Sie das Skript in PowerShell (x64) aus.
UnsupportedHost                           = Das Skript unterstützt nicht die Ausführung über {0}.
Win10TweakerWarning                       = Wahrscheinlich wurde Ihr Betriebssystem über die Win 10 Tweaker-Hintertür infiziert.
TweakerWarning                            = Die Stabilität des Windows-Betriebssystems kann durch die Verwendung des {0} beeinträchtigt worden sein. Installieren Sie Windows vorsichtshalber neu.
Bin                                       = Im Ordner "bin" befinden sich keine Dateien. Bitte das Archiv erneut herunterladen.
RebootPending                             = Der PC wartet darauf, neu gestartet zu werden.
UnsupportedRelease                        = Neue Version gefunden.
KeyboardArrows                            = Bitte verwenden Sie die Pfeiltasten {0} und {1} auf Ihrer Tastatur, um Ihre Antwort auszuwählen
CustomizationWarning                      = Haben Sie alle Funktionen in der voreingestellten Datei {0} angepasst, bevor Sie Sophia Script ausführen?
WindowsComponentBroken                    = {0} defekt oder aus dem Betriebssystem entfernt.
UpdateDefender                            = Die Microsoft Defender-Definitionen sind veraltet. Führen Sie Windows Update aus und versuchen Sie es erneut.
ControlledFolderAccessDisabled            = Kontrollierter Ordnerzugriff deaktiviert.
InitialActionsCheckFailed                 = Die Funktion "InitialActions" kann nicht aus der Voreinstellungsdatei {0} geladen werden.
ScheduledTasks                            = Geplante Aufgaben
OneDriveUninstalling                      = OneDrive deinstallieren...
OneDriveInstalling                        = OneDrive installieren...
OneDriveDownloading                       = OneDrive herunterladen...
OneDriveWarning                           = Die "{0}"-Funktion wird nur angewendet, wenn die Voreinstellung so konfiguriert ist, dass OneDrive entfernt wird (oder die App bereits entfernt wurde), andernfalls wird die Backup-Funktionalität für die Ordner "Desktop" und "Bilder" in OneDrive unterbrochen.
WindowsFeaturesTitle                      = Windows-Features
OptionalFeaturesTitle                     = Optionale Features
EnableHardwareVT                          = Virtualisierung in UEFI aktivieren.
UserShellFolderNotEmpty                   = Im Ordner "{0}" befinden sich noch Dateien \nVerschieben Sie sie manuell an einen neuen Ort.
UserFolderLocationMove                    = Sie sollten den Speicherort des Benutzerordners nicht in das Stammverzeichnis des Laufwerks C ändern.
RetrievingDrivesList                      = Laufwerksliste abrufen...
DriveSelect                               = Wählen Sie das Laufwerk aus, in dessen Stammverzeichnis der Ordner "{0}" erstellt werden soll.
CurrentUserFolderLocation                 = Der aktuelle Speicherort des Ordners "{0}" lautet: "{1}".
UserFolderRequest                         = Möchten Sie den Speicherort des Ordners "{0}" ändern?
UserDefaultFolder                         = Möchten Sie den Speicherort des Ordners "{0}" auf den Standardwert ändern?
ReservedStorageIsInUse                    = Dieser Vorgang wird nicht unterstützt, wenn reservierter Speicher verwendet wird\nBitte führen Sie die Funktion "{0}" nach dem PC-Neustart erneut aus.
ShortcutPinning                           = Die Verknüpfung "{0}" wird an Start angeheftet...
UninstallUWPForAll                        = Für alle Benutzer
UWPAppsTitle                              = UWP-Apps
HEVCDownloading                           = HEVC-Videoerweiterungen vom Gerätehersteller herunterladen...
GraphicsPerformanceTitle                  = Möchten Sie die Einstellung der Grafikleistung einer App Ihrer Wahl auf "Hohe Leistung" einstellen?
ActionCenter                              = Um die Funktion "{0}" nutzen zu können, müssen Sie das Action Center aktivieren.
WindowsScriptHost                         = Der Zugriff auf Windows Script Host wurde für diesem Computer deaktiviert. Um die Funktion "{0}" nutzen zu können, müssen Sie den Windows Script Host aktivieren.
ScheduledTaskPresented                    = Die Funktion "{0}" wurde bereits als "{1}" angelegt.
CleanupTaskNotificationTitle              = Windows aufräumen
CleanupTaskNotificationEvent              = Aufgabe zum Bereinigen nicht verwendeter Windows-Dateien und -Updates ausführen?
CleanupTaskDescription                    = Bereinigung von nicht verwendeten Windows-Dateien und Updates mit der integrierten Festplattenbereinigung.
CleanupNotificationTaskDescription        = Popup-Benachrichtigung zur Erinnerung an die Bereinigung von nicht verwendeten Windows-Dateien und Updates.
SoftwareDistributionTaskNotificationEvent = Der Windows Update-Cache wurde erfolgreich gelöscht.
TempTaskNotificationEvent                 = Der Ordner mit den temporären Dateien wurde erfolgreich bereinigt.
FolderTaskDescription                     = Ordner "{0}" bereinigen.
EventViewerCustomViewName                 = Prozesserstellung
EventViewerCustomViewDescription          = Prozesserstellungen und Befehlszeilen-Auditing-Ereignisse.
RestartWarning                            = Sicherstellen, dass Sie Ihren PC neu starten.
ErrorsLine                                = Zeile
ErrorsMessage                             = Fehler/Warnungen
DialogBoxOpening                          = Anzeigen des Dialogfensters...
Disable                                   = Deaktivieren
Enable                                    = Aktivieren
UserChoiceWarning                         = Microsoft hat den Schreibzugriff auf den UserChoice-Schlüssel für die .pdf-Erweiterung und das http/https-Protokoll mit der Version KB5034765 gesperrt.
AllFilesFilter                            = Alle Dateien
FolderSelect                              = Einen Ordner auswählen
FilesWontBeMoved                          = Dateien werden nicht verschoben.
Install                                   = Installieren
NoData                                    = Nichts anzuzeigen.
NoInternetConnection                      = Keine Internetverbindung.
RestartFunction                           = Bitte die Funktion "{0}" neustarten.
NoResponse                                = Eine Verbindung mit {0} konnte nicht hergestellt werden.
Restore                                   = Wiederherstellen
Run                                       = Starten
Skipped                                   = Übersprungen.
GPOUpdate                                 = GPO-Aktualisierung...
TelegramGroupTitle                        = Treten Sie unserer offiziellen Telegram-Gruppe bei.
TelegramChannelTitle                      = Treten Sie unserem offiziellen Telegram-Kanal bei.
DiscordChannelTitle                       = Treten Sie unserem offiziellen Discord-Kanal bei.
Uninstall                                 = Deinstallieren
'@
