ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Le script supporte uniquement Windows 10 x64
UnsupportedOSBuild                        = Le script supporte le version Windows 10 1809 Enterprise LTSC
UnsupportedLanguageMode                   = La session PowerShell s'exécute dans un mode de langue limité
LoggedInUserNotAdmin                      = L'utilisateur connecté n'a pas de droits d'administrateur
UnsupportedISE                            = Le script ne supporte pas l'exécution via Windows PowerShell ISE
Win10TweakerWarning                       = Votre système d'exploitation a probablement été infecté par la porte dérobée Win 10 Tweaker
UnsupportedRelease                        = Nouvelle version trouvée
CustomizationWarning                      = \nAvez-vous personnalisé chaque fonction du fichier de préréglage Sophia.ps1 avant d'exécuter Sophia Script?
ControlledFolderAccessDisabled            = Contrôle d'accès aux dossiers désactivé
ScheduledTasks                            = Tâches planifiées
WindowsFeaturesTitle                      = Fonctionnalités
OptionalFeaturesTitle                     = Fonctionnalités optionnelles
EnableHardwareVT                          = Activer la virtualisation dans UEFI
UserShellFolderNotEmpty                   = Certains fichiers laissés dans le dossier "{0}" \nDéplacer les manuellement vers un nouvel emplacement
RetrievingDrivesList                      = Récupération de la liste des lecteurs...
DriveSelect                               = Sélectionnez le disque à la racine dans lequel le dossier "{0}" sera créé.
UserFolderRequest                         = Voulez vous changer où est placé le dossier "{0}" ?
UserFolderSelect                          = Sélectionnez un dossier pour le dossier "{0}"
UserDefaultFolder                         = Voulez vous changer où est placé le dossier "{0}" à sa valeur par défaut?
GraphicsPerformanceTitle                  = Préférence de performances graphiques
GraphicsPerformanceRequest                = Souhaitez-vous définir le paramètre de performances graphiques d'une application de votre choix sur "Haute performance"?
TaskNotificationTitle                     = Notificacion
CleanupTaskNotificationTitle              = Une information important
CleanupTaskDescription                    = Nettoyage des fichiers Windows inutilisés et des mises à jour à l'aide de l'application intégrée pour le nettoyage de disque
CleanupTaskNotificationEventTitle         = Exécuter la tâche pour nettoyer les fichiers et les mises à jour inutilisés de Windows?
CleanupTaskNotificationEvent              = Le nettoyage de Windows ne prendra pas longtemps. La prochaine fois que la notification apparaîtra dans 30 jours
CleanupTaskNotificationSnoozeInterval     = Sélectionnez un intervalle de rappel
CleanupNotificationTaskDescription        = Rappel de notification contextuelle sur le nettoyage des fichiers et des mises à jour inutilisés de Windows
SoftwareDistributionTaskNotificationEvent = Le cache de mise à jour Windows a bien été supprimé
TempTaskNotificationEvent                 = Le dossier des fichiers temporaires a été nettoyé avec succès
FolderTaskDescription                     = Nettoyage du dossier "{0}"
EventViewerCustomViewName                 = Création du processus
EventViewerCustomViewDescription          = Audit des événements de création du processus et de ligne de commande
RestartWarning                            = \nAssurez-vous de redémarrer votre PC
ErrorsLine                                = Ligne
ErrorsFile                                = Fichier
ErrorsMessage                             = Erreurs/Avertissements
Add                                       = Ajouter
AllFilesFilter                            = Tous les Fichiers (*.*)|*.*
Browse                                    = Parcourir
Change                                    = Changer
DialogBoxOpening                          = Afficher la boîte de dialogue...
Disable                                   = Désactiver
Enable                                    = Activer
EXEFilesFilter                            = *.exe|*.exe|Tous les Fichiers (*.*)|*.*
FolderSelect                              = Sélectionner un dossier
FilesWontBeMoved                          = Les fichiers ne seront pas déplacés
FourHours                                 = 4 heures
HalfHour                                  = 30 minutes
Install                                   = Installer
Minute                                    = 1 minute
NoData                                    = Rien à afficher
NoInternetConnection                      = Pas de connexion Internet
NoResponse                                = Une connexion n'a pas pu être établie avec https://store.rg-adguard.net
No                                        = Non
Yes                                       = Oui
Open                                      = Ouvert
Patient                                   = Veuillez patienter...
Restore                                   = Restaurer
Run                                       = Démarrer
SelectAll                                 = Tout sélectionner
Skip                                      = Passer
Skipped                                   = Passé
TelegramTitle                             = Rejoignez notre canal Telegram officiel
Uninstall                                 = Désinstaller
'@
