ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Le script supporte uniquement Windows 10 x64
UnsupportedOSBuild                        = Le script supporte le version Windows 10 1809 Enterprise LTSC
UnsupportedRelease                        = Nouvelle version trouvée
ControlledFolderAccessDisabled            = Contrôle d'accès aux dossiers désactivé
ScheduledTasks                            = Tâches planifiées
WindowsFeaturesTitle                      = Fonctionnalités
OptionalFeaturesTitle                     = Fonctionnalités optionnelles
EnableHardwareVT                          = Activer la virtualisation dans UEFI
UserShellFolderNotEmpty                   = Certains fichiers laissés dans le dossier "{0}" \nDéplacer les manuellement vers un nouvel emplacement
RetrievingDrivesList                      = Récupération de la liste des lecteurs...
DriveSelect                               = Seleccione la unidad dentro de la raíz de la cual se creará la carpeta "{0}"
UserFolderRequest                         = ¿Le gustaría cambiar la ubicación de la carpeta "{0}"?
UserFolderSelect                          = Seleccione una carpeta para la carpeta "{0}"
UserDefaultFolder                         = ¿Le gustaría cambiar la ubicación de la carpeta "{0}" al valor predeterminado?
GraphicsPerformanceTitle                  = Préférence de performances graphiques
GraphicsPerformanceRequest                = Souhaitez-vous définir le paramètre de performances graphiques d'une application de votre choix sur "Haute performance"?
TaskNotificationTitle                     = Notificación
CleanupTaskNotificationTitle              = Une information important
CleanupTaskDescription                    = Nettoyage des fichiers Windows inutilisés et des mises à jour à l'aide de l'application intégrée pour le nettoyage de disque
CleanupTaskNotificationEventTitle         = Exécuter la tâche pour nettoyer les fichiers et les mises à jour inutilisés de Windows?
CleanupTaskNotificationEvent              = Le nettoyage de Windows ne prendra pas longtemps. La prochaine fois que la notification apparaîtra dans 30 jours
CleanupTaskNotificationSnoozeInterval     = Sélectionnez un intervalle de rappel
CleanupNotificationTaskDescription        = Rappel de notification contextuelle sur le nettoyage des fichiers et des mises à jour inutilisés de Windows
SoftwareDistributionTaskNotificationEvent = Le cache de mise à jour Windows a bien été supprimé
TempTaskNotificationEvent                 = Le dossier des fichiers temporaires a été nettoyé avec succès
FolderTaskDescription                     = Nettoyage du dossier "{0}"
ControlledFolderAccess                    = Contrôle d'accès aux dossiers
ProtectedFoldersRequest                   = Souhaitez-vous activer le contrôle d'accès aux dossiers et spécifier le dossier que Microsoft Defender protégera contre les applications malveillantes et les menaces?
ProtectedFoldersListRemoved               = Dossiers supprimés
AppControlledFolderRequest                = Souhaitez-vous spécifier une application autorisée via le contrôle d'accès aux dossiers?
AllowedControlledFolderAppsRemoved        = Applications autorisées supprimées
DefenderExclusionFolderRequest            = Souhaitez-vous spécifier un dossier à exclure des analyses de logiciels malveillants de Microsoft Defender?
DefenderExclusionFoldersListRemoved       = Dossiers exclus supprimés
AddDefenderExclusionFileRequest           = Souhaitez-vous spécifier un fichier à exclure des analyses de logiciels malveillants de Microsoft Defender?
DefenderExclusionFilesRemoved             = Fichiers exclus supprimés
EventViewerCustomViewName                 = Création du processus
EventViewerCustomViewDescription          = Audit des événements de création du processus et de ligne de commande
RestartWarning                            = Assurez-vous de redémarrer votre PC
ErrorsLine                                = Ligne
ErrorsFile                                = Fichier
ErrorsMessage                             = Erreurs/Avertissements
Add                                       = Ajouter
AllFilesFilter                            = Tous les Fichiers (*.*)|*.*
Change                                    = Changer
DialogBoxOpening                          = Afficher la boîte de dialogue...
Disable                                   = Désactiver
Enable                                    = Activer
EXEFilesFilter                            = *.exe|*.exe|Tous les Fichiers (*.*)|*.*
FolderSelect                              = Sélectionner un dossier
FilesWontBeMoved                          = Les fichiers ne seront pas déplacés
FourHours                                 = 4 heures
HalfHour                                  = 30 minutes
Install                                   = Installer
Minute                                    = 1 minute
NoData                                    = Rien à afficher
NoInternetConnection                      = Pas de connexion Internet
NoResponse                                = Une connexion n'a pas pu être établie avec https://store.rg-adguard.net
Open                                      = Ouvert
Patient                                   = Veuillez patienter...
Restore                                   = Restaurer
Run                                       = Démarrer
Select                                    = Sélectionner
SelectAll                                 = Tout sélectionner
Skip                                      = Passer
Skipped                                   = Passé
TelegramTitle                             = Rejoignez notre chaîne Telegram officielle
Uninstall                                 = Désinstaller
'@
