ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = A szkript csak a Windows 10 64 bites verziót támogatja
UnsupportedOSBuild                        = A szkript támogatja a Windows 10 21H2/22H2+ verziókat
UpdateWarning                             = A Windows 10 összesített frissítése telepítve: {0}. Támogatott kumulatív frissítés: 2364 és magasabb verziószámok. Futtassa a Windows Update programot, és próbálja meg újra
UnsupportedLanguageMode                   = A PowerShell munkamenet korlátozott nyelvi üzemmódban fut
LoggedInUserNotAdmin                      = A bejelentkezett felhasználó nem rendelkezik admin jogokkal
UnsupportedPowerShell                     = A PowerShell {0}.{1} segítségével próbálja futtatni a szkriptet. Futtassa a szkriptet a megfelelő PowerShell-verzióban
UnsupportedISE                            = A szkript nem támogatja a Windows PowerShell ISE futtatását
Win10TweakerWarning                       = Valószínűleg az operációs rendszerét a Win 10 Tweaker backdoor segítségével fertőzték meg
SycnexWarning                             = A Windows operációs rendszer stabilitását veszélyeztethette a Sycnex Windows10Debloater PowerShell szkriptje. Megelőzésképpen telepítse újra a Windows
Fs00Warning                               = A Windows operációs rendszer stabilitását veszélyeztethette a "Windows 10 Bloat Remover and Tweaker". Preventively, reinstall Windows
bin                                       = A bin mappában nincsenek fájlok. Kérjük, töltse le újra az archívumot
RebootPending                             = A számítógép újraindításra vár
UnsupportedRelease                        = Új verzió érhető el
CustomizationWarning                      = \nSzemélyre szabott minden opciót a {0} preset fájlban, mielőtt futtatni kívánja a Sophia szkriptet?
DefenderBroken                            = A Microsoft Defender elromlott vagy eltávolították az operációs rendszerből
UpdateDefender                            = A Microsoft Defender definíciói elavultak. Futtassa a Windows Update programot, és próbálja meg újra
ControlledFolderAccessDisabled            = Vezérelt mappához való hozzáférés kikapcsolva
ScheduledTasks                            = Ütemezett feladatok
OneDriveUninstalling                      = OneDrive eltávolítása...
OneDriveInstalling                        = OneDrive telepítése...
OneDriveDownloading                       = OneDrive letöltése... ~33 MB
OneDriveWarning                           = A "{0}" funkció csak akkor kerül alkalmazásra, ha az előbeállítás a OneDrive eltávolítására van beállítva (vagy az alkalmazás már eltávolításra került), különben a OneDrive "Desktop" és "Pictures" mappáinak biztonsági mentési funkciója megszakad.
WindowsFeaturesTitle                      = Windows szolgáltatások
OptionalFeaturesTitle                     = Opcionális szolgáltatások
EnableHardwareVT                          = Virtualizáció engedélyezése UEFI-ben
UserShellFolderNotEmpty                   = Néhány fájl maradt a "{0}" könyvtárban. Kérem helyezze át ezeket egy új helyre
RetrievingDrivesList                      = A meghajtók listájának lekérése...
DriveSelect                               = Válassza ki a meghajtó jelét a gyökérkönyvtárban ahol a "{0}" könyvtár létre lesz hozva
CurrentUserFolderLocation                 = Az aktuális "{0}" mappa helye: "{1}"
UserFolderRequest                         = Kívánja megváltoztatni a "{0}" könyvtár helyét?
UserFolderSelect                          = Válasszon ki egy könyvtárat a "{0}" könyvtárhoz
UserDefaultFolder                         = Szeretné visszaállítani a "{0}" könyvtár helyét a gyári értékekre?
ReservedStorageIsInUse                    = Ez a művelet nem hajtható végre, amíg a fenntartott tárhely használatban van\nPonovno pokrenite funkciju "{0}" nakon ponovnog pokretanja računala
ShortcutPinning                           = A gyorsindító ikon "{0}" Startmenüre helyezése...
UninstallUWPForAll                        = Az összes felhasználó számára
UWPAppsTitle                              = UWP Alkalmazások
HEVCDownloading                           = A HEVC Videobővítmények letöltése a gyártói oldalról... ~2,8 MB
GraphicsPerformanceTitle                  = Grafikus teljesítmény tulajdonság
GraphicsPerformanceRequest                = Szeretné megváltoztatni a grafikus teljesítmény beállítást az ön által kiválasztott alkalmazásban "Nagy teljesítményre"?
ScheduledTaskPresented                    = A "{0}" funkciót már létrehoztuk "{1}" néven
CleanupTaskNotificationTitle              = Windows tisztítása
CleanupTaskNotificationEvent              = Szeretné a nem használt fájlokat es frissitéseket eltávolítani?
CleanupTaskDescription                    = A nem használt Windows fájlok és frissítések eltávolítása a beépített lemezkarbantartó alkalmazással
CleanupNotificationTaskDescription        = Előugró emlékeztető figyelmeztetés a nem használt Windows fájlok és frissítések törléséről
SoftwareDistributionTaskNotificationEvent = A Windows frissités számára fenntartott ideiglenes tárhely sikeresen megtisztítva
TempTaskNotificationEvent                 = Az ideiglenes fájlok tárolására szolgáló könyvtár tisztítása sikeresen megtörtént
FolderTaskDescription                     = A {0} könyvtár tisztítása
EventViewerCustomViewName                 = Folyamatok
EventViewerCustomViewDescription          = Folyamatok létrehozása és parancssor ellenőrző események
RestartWarning                            = Kérem ne felejtse el újraindítani a számítógépét
ErrorsLine                                = Sor
ErrorsFile                                = Fájl
ErrorsMessage                             = Hibák/Figyelmeztetések
Add                                       = Hozzáadás
AllFilesFilter                            = Összes fájl (*.*)|*.*
Browse                                    = Pregledavati
DialogBoxOpening                          = Párbeszédablak megjelenítése...
Disable                                   = Kikapcsolás
Enable                                    = Engedélyezés
EXEFilesFilter                            = *.exe|*.exe|Minden fájl (*.*)|*.*
FolderSelect                              = Válasszon ki egy könyvtárat
FilesWontBeMoved                          = A fájlok nem lesznek áthelyezve
Install                                   = Telepítés
NoData                                    = Nincs megjeleníthető információ
NoInternetConnection                      = Nincs internetkapcsolat
RestartFunction                           = Ponovo pokrenite funkciju "{0}"
NoResponse                                = Nem hozható létre kapcsolat a {0} weboldallal
No                                        = Nem
Yes                                       = Igen
Open                                      = Megnyitás
Patient                                   = Kérem várjon...
Restore                                   = Visszaállítás
Run                                       = Futtatás
SelectAll                                 = Összes kijelölése
Skipped                                   = Átugorva
GPOUpdate                                 = GPO frissítése...
TelegramGroupTitle                        = Pridružite se našoj službenoj grupi Telegram
TelegramChannelTitle                      = Pridružite se našem službenom kanalu Telegram
DiscordChannelTitle                       = Pridružite se našem službenom kanalu Discord
Uninstall                                 = Eltávolít
'@
