ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                   = 该脚本仅支持Windows 10 x64
UnsupportedOSBuild                     = 该脚本支持Windows 10版本2004 / 20H1和更高版本
UnsupportedRelease                     = 找到新版本
ControlledFolderAccessDisabled         = “受控文件夹访问”禁用
ScheduledTasks                         = 计划任务
OneDriveUninstalling                   = 卸载OneDrive...
OneDriveNotEmptyFolder                 = "{0}"文件夹不为空。手动将其删除
OneDriveFileSyncShell64dllBlocked      = "{0}"被阻止。手动将其删除。
OneDriveInstalling                     = OneDrive正在安装...
OneDriveDownloading                    = 正在下载OneDrive ... ~33 MB
ClearFolder                            = 删除"{0}"文件夹中的所有文件?
FilesBlocked                           = 以下文件被第三方应用程序阻止。手动删除它们并继续
TempNotEmpty                           = "{0}"文件夹不为空。 手动清除
WindowsFeaturesWindowTitle             = Windows功能
FODWindowTitle                         = 移除可选功能 (FODv2)
EnableHardwareVT                       = UEFI中开启虚拟化
UserShellFolderNotEmpty                = 一些文件留在了"{0}"文件夹.请手动将它们移到一个新位置
RetrievingDrivesList                   = 取得驱动器列表...
NewUserShellFolderLocation             = 新位置："{0}"
DesktopDriveSelect                     = 请选择一个驱动器,桌面文件夹将创建在其根目录
DocumentsDriveSelect                   = 请选择一个驱动器,文档文件夹将创建在其根目录
DownloadsDriveSelect                   = 请选择一个驱动器,下载文件夹将创建在其根目录
MusicDriveSelect                       = 请选择一个驱动器,音乐文件夹将创建在其根目录
PicturesDriveSelect                    = 请选择一个驱动器,图片文件夹将创建在其根目录
VideosDriveSelect                      = 请选择一个驱动器,视频文件夹将创建在其根目录
DesktopRequest                         = 是否要更改桌面文件夹位置?
DocumentsRequest                       = 是否要更改文档文件夹位置?
DownloadsRequest                       = 是否要更改下载文件夹位置?
MusicRequest                           = 是否要更改音乐文件夹位置?
PicturesRequest                        = 是否要更改图片文件夹位置?
VideosRequest                          = 是否要更改视频文件夹位置?
DesktopFolderSelect                    = 为“桌面”文件夹选择一个文件夹
DocumentsFolderSelect                  = 为“文档”文件夹选择一个文件夹
DownloadsFolderSelect                  = 为“下载”文件夹选择一个文件夹
MusicFolderSelect                      = 为“音乐”文件夹选择一个文件夹
PicturesFolderSelect                   = 为“图片”文件夹选择一个文件夹
VideosFolderSelect                     = 为“视频”文件夹选择一个文件夹
DesktopDefaultFolder                   = 是否要将桌面文件夹位置改为默认值?
DocumentsDefaultFolder                 = 是否要将文档文件夹位置改为默认值?
DownloadsDefaultFolder                 = 是否要将下载文件夹位置改为默认值?
MusicDefaultFolder                     = 是否要将音乐文件夹位置改为默认值?
PicturesDefaultFolder                  = 是否要将图片文件夹位置改为默认值??
VideosDefaultFolder                    = 是否要将视频文件夹位置改为默认值?
ReservedStorageIsInUse                 = 保留存储空间正在使用时不支持此操作. 请等待所有服务操作完成后再重试
syspinDownloading                      = syspin下载中... ~20 KB
ShortcutPinning                        = "{0}"快捷方式将被固定到开始菜单
UninstallUWPForAll                     = 为所有用户卸载
UninstallUWPTitle                      = 需要卸载的UWP应用
WSLUpdateDownloading                   = Linux内核更新包下载中... ~14 MB
WSLUpdateInstalling                    = 安装Linux内核更新包...
GraphicsPerformanceTitle               = 图形性能偏好
GraphicsPerformanceRequest             = 是否将所选应用程序的图形性能设置设为"高性能"?
CleanUpTaskToast                       = 将在一分钟内清理未使用的Windows文件和更新
CleanUpTaskDescription                 = 使用内置磁盘清理工具清理未使用的Windows文件和更新
FolderTaskDescription                  = 定时清理"{0}"
ControlledFolderAccess                 = 受控文件夹访问
ProtectedFoldersRequest                = 是否启用受控文件夹访问权限并指定文件夹,由微软Defender保护其免受恶意应用程序威胁?
ProtectedFoldersListRemoved            = 已被移除的文件夹
AppControlledFolderRequest             = 是否指定应用获取受控文件夹访问权限?
AllowedControlledFolderAppsRemoved     = 删除了允许的应用
DefenderTitle                          = Microsoft Defender
DefenderExclusionFolderRequest         = 是否要添加指定文件夹到微软Defender的恶意软件扫描白名单?
DefenderExclusionFoldersListRemoved    = 排除的文件夹已删除
AddDefenderExclusionFileRequest        = 是否要添加指定文件到微软Defender的恶意软件扫描白名单?
DefenderExclusionFilesRemoved          = 排除文件已删除
EventViewerCustomViewName              = 进程创建
EventViewerCustomViewDescription       = 进程创建和命令行审核事件
RestartWarning                         = 确保重启电脑
ErrorsLine                             = 行
ErrorsFile                             = 文件
ErrorsMessage                          = 错误/警告
Add                                    = 添加
AllFilesFilter                         = 所有文件 (*.*)|*.*
Change                                 = 更改
Continue                               = 接续
DialogBoxOpening                       = 显示对话窗口...
Disable                                = 禁用
Enable                                 = 启用
EXEFilesFilter                         = *.exe|*.exe|所有文件 (*.*)|*.*
FolderSelect                           = 选择一个文件夹
FilesWontBeMoved                       = 文件将不会被移动
NoData                                 = 无数据
NoInternetConnection                   = 无网络连接
Patient                                = 请等待...
Select                                 = 选择
Skip                                   = 跳过
Skipped                                = 已跳过
SymbolicSkipped                        = 跳过创建符号链接
Uninstall                              = 卸载
Install                                = 安装
'@
