ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Скрипт підтримує тільки 64-розрядну версію Windows.
UnsupportedOSBuild                        = Скрипт підтримує тільки Windows 10 Enterprise LTSC 2021. Ви використовуєте {0} {1}. Оновіть Windows і спробуйте ще раз.
UnsupportedWindowsTerminal                = Версія Windows Terminal нижча за 1.23. Будь ласка, оновіть його в Microsoft Store і спробуйте заново.
UpdateWarning                             = Ви використовуєте Windows 10 {0}.{1}. Підтримувані збірки: Windows 10 {0}.{2} і вище. Запустіть оновлення Windows і спробуйте ще раз.
UnsupportedLanguageMode                   = Сесія PowerShell працює в обмеженому режимі.
LoggedInUserNotAdmin                      = Користувач {0}, що увійшов, не має прав адміністратора. Скрипт був запущений від імені {1}. Будь ласка, увійдіть в профіль, що має права адміністратора, і запустіть скрипт заново.
UnsupportedPowerShell                     = Ви намагаєтеся запустити скрипт в PowerShell {0}.{1}. Запустіть скрипт в PowerShell {2}.
CodeCompilationFailedWarning              = Компіляція коду завершилася з помилкою.
UnsupportedHost                           = Скрипт не підтримує роботу через {0}.
Win10TweakerWarning                       = Windows була заражена трояном через бекдор у Win 10 Tweaker. Перевстановіть Windows, використовуючи тільки справжній ISO-образ.
TweakerWarning                            = Стабільність вашої ОС могла бути порушена використанням {0}. Перевстановіть Windows, використовуючи тільки справжній ISO-образ.
HostsWarning                              = У файлі {0} виявлено сторонні записи. Вони можуть блокувати з'єднання з ресурсами, використовуваними в роботі скрипта. Хочете продовжити?
RebootPending                             = Комп'ютер очікує на перезавантаження.
BitLockerWarning                          = Виконується шифрування BitLocker. Завершіть налаштування BitLocker для диска та спробуйте ще раз.
UnsupportedRelease                        = Виявлено нову версію Sophia Script: {0}. Будь ласка, завантажте останню версію.
KeyboardArrows                            = Для вибору відповіді використовуйте на клавіатурі стрілки  {0} і {1}
CustomizationWarning                      = Ви налаштували всі функції в пресет-файлі {0} перед запуском Sophia Script?
WindowsComponentBroken                    = {0} пошкоджено або видалено з ОС. Перевстановіть Windows, використовуючи тільки справжній ISO-образ.
ControlledFolderAccessDisabled            = Контрольований доступ до папок вимкнений.
ScheduledTasks                            = Заплановані задачі
WindowsFeaturesTitle                      = Компоненти Windows
OptionalFeaturesTitle                     = Додаткові компоненти
EnableHardwareVT                          = Увімкніть віртуалізацію в UEFI.
UserShellFolderNotEmpty                   = У папці "{0}" залишилися файли. Перемістіть їх вручну в нове розташування.
UserFolderLocationMove                    = Не слід переміщати користувацькі папки в корінь диска C.
DriveSelect                               = Виберіть диск, в корні якого буде створена папка для "{0}".
CurrentUserFolderLocation                 = Поточне розташування папки "{0}": "{1}".
UserFolderRequest                         = Бажаєте змінити розташування папки "{0}"?
UserDefaultFolder                         = Бажаєте змінити розташування папки "{0}" на значення за замовчуванням?
ReservedStorageIsInUse                    = Операція не підтримується, поки використовується зарезервоване сховище\nБудь ласка, повторно запустіть функцію "{0}" після перезавантаження.
ShortcutPinning                           = Ярлик "{0}" закріплюється на початковому екрані...
GraphicsPerformanceTitle                  = Встановити для будь-якої програми за вашим вибором налаштування продуктивності графіки на "Висока продуктивність"?
ScheduledTaskPresented                    = Функцію "{0}" уже було створено від імені "{1}".
CleanupTaskNotificationTitle              = Очищення Windows
CleanupTaskNotificationEvent              = Запустити завдання з очищення невикористовуваних файлів і оновлень Windows?
CleanupTaskDescription                    = Очищення невикористовуваних файлів і оновлень Windows, використовуючи вбудовану програму Очищення диска. Завдання може бути запущено, тільки якщо користувач "{0}" увійшов у систему.
CleanupNotificationTaskDescription        = Спливаюче повідомлення з нагадуванням про очищення невикористовуваних файлів і оновлень Windows. Завдання може бути запущено, тільки якщо користувач "{0}" увійшов у систему.
SoftwareDistributionTaskNotificationEvent = Кеш оновлень Windows успішно видалено.
TempTaskNotificationEvent                 = Папка тимчасових файлів успішно очищена.
FolderTaskDescription                     = Очищення папки "{0}". Завдання може бути запущено, тільки якщо користувач "{0}" увійшов у систему.
EventViewerCustomViewName                 = Створення процесу
EventViewerCustomViewDescription          = Події створення нового процесу і аудит командного рядка.
RestartWarning                            = Обов'язково перезавантажте ваш ПК.
ErrorsLine                                = Рядок
ErrorsMessage                             = Помилки/попередження
DialogBoxOpening                          = Діалогове вікно відкривається...
Disable                                   = Вимкнути
Enable                                    = Увімкнути
AllFilesFilter                            = Усі файли
FolderSelect                              = Виберіть папку
FilesWontBeMoved                          = Файли не будуть перенесені.
Install                                   = Встановити
Uninstall                                 = Видалити
NoData                                    = Відсутні дані.
RestartFunction                           = Будь ласка, повторно запустіть функцію "{0}".
NoResponse                                = Не вдалося встановити зв’язок із {0}.
Restore                                   = Відновити
Run                                       = Запустити
Skipped                                   = Функцію "{0}" пропущено.
ThankfulToastTitle                        = Дякуємо за використання Sophia Script ❤️
DonateToastTitle                          = Ви можете зробити пожертву нижче 🕊️
DotSourcedWarning                         = Будь ласка, запустіть функцію через дот-сорсинг (з крапкою на початку):\n. .\\Import-TabCompletion.ps1
'@
