ConvertFrom-StringData -StringData @'
PowerShellImportFailed                    = No se han podido importar los módulos de PowerShell 5.1. Cierre la consola de PowerShell 7 y vuelva a ejecutar el script.
UnsupportedArchitecture                   = Estás utilizando una CPU con arquitectura basada en "{0}". Este script solo es compatible con CPU con arquitectura x64. Descarga y ejecuta la versión del script adecuada para tu arquitectura.
UnsupportedOSBuild                        = El script es compatible con Windows 11 24H2 y superiores. Estás usando Windows {0} {1}. Actualiza tu Windows e inténtalo de nuevo.
UnsupportedWindowsTerminal                = La versión de Windows Terminal es inferior a la 1.23. Por favor, actualízala en la Microsoft Store e inténtalo de nuevo.
UpdateWarning                             = Estás utilizando Windows 11 {0}.{1}. La versión compatible es Windows 11 {0}.{2} y superior. Ejecuta Windows Update e inténtalo de nuevo.
UnsupportedLanguageMode                   = Sesión de PowerShell ejecutada en modo de lenguaje limitado.
LoggedInUserNotAdmin                      = El usuario {0} que ha iniciado sesión no tiene derechos de administrador. El script se ha ejecutado en nombre de {1}. Inicie sesión en una cuenta con derechos de administrador y vuelva a ejecutar el script.
UnsupportedPowerShell                     = Estás intentando ejecutar el script a través de PowerShell {0}.{1}. Por favor, ejecute el script en PowerShell {2}.
CodeCompilationFailedWarning              = La compilación del código ha fallado.
UnsupportedHost                           = El script no es compatible con la ejecución a través de {0}.
Win10TweakerWarning                       = Probablemente su sistema operativo fue infectado a través del backdoor Win 10 Tweaker.
TweakerWarning                            = La estabilidad del sistema operativo Windows puede haberse visto comprometida al utilizar el {0}. Reinstale Windows utilizando sólo una imagen ISO original.
HostsWarning                              = Entradas de terceros encontradas en el archivo %SystemRoot%\\System32\\drivers\\etc\\hosts. Pueden bloquear la conexión a los recursos utilizados en el script. ¿Desea continuar?
RebootPending                             = Tu PC está esperando a que lo reinicies.
BitLockerInOperation                      = El cifrado de BitLocker está en curso. Complete la configuración de la unidad BitLocker e inténtelo de nuevo.
BitLockerAutomaticEncryption              = La unidad C está cifrada, aunque BitLocker está desactivado. ¿Desea descifrar la unidad?
UnsupportedRelease                        = Se ha encontrado una versión más reciente de Sophia Script: {0}. Descargue la última versión.
KeyboardArrows                            = Utilice las flechas {0} y {1} de su teclado para seleccionar la respuesta
CustomizationWarning                      = ¿Ha personalizado todas las funciones del archivo predeterminado {0} antes de ejecutar Sophia Script?
WindowsComponentBroken                    = {0} dañado o eliminado del sistema operativo. Reinstale Windows utilizando sólo una imagen ISO original.
MicroSoftStorePowerShellWarning           = PowerShell téléchargé depuis le Microsoft Store n'est pas pris en charge. Veuillez exécuter une version MSI.
ControlledFolderAccessEnabledWarning      = Tienes habilitado el acceso controlado a carpetas. Desactívalo y vuelve a ejecutar el script.
NoScheduledTasks                          = No hay tareas programadas que desactivar.
ScheduledTasks                            = Tareas programadas
WidgetNotInstalled                        = El widget no está instalado.
SearchHighlightsDisabled                  = Los resultados destacados de la búsqueda ya están ocultos en Inicio.
CustomStartMenu                           = Se ha instalado un menú de inicio de terceros.
OneDriveNotInstalled                      = OneDrive ya está desinstalado.
OneDriveAccountWarning                    = Antes de desinstalar OneDrive, cierra sesión en tu cuenta de Microsoft en OneDrive.
OneDriveInstalled                         = OneDrive ya está instalado.
UninstallNotification                     = Se está desinstalando {0}...
InstallNotification                       = Se está instalando {0}...
NoWindowsFeatures                         = No hay funciones de Windows que desactivar.
WindowsFeaturesTitle                      = Características de Windows
NoOptionalFeatures                        = No hay funciones opcionales que desactivar.
NoSupportedNetworkAdapters                = No hay adaptadores de red que admitan la función "Permitir que el equipo apague este dispositivo para ahorrar energía".
OptionalFeaturesTitle                     = Características opcionales
EnableHardwareVT                          = Habilitar la virtualización en UEFI.
UserShellFolderNotEmpty                   = Algunos archivos quedan en la carpeta "{0}". Moverlos manualmente a una nueva ubicación.
UserFolderLocationMove                    = No deberías cambiar la ubicación de la carpeta de usuario a la raíz de la unidad C.
DriveSelect                               = Seleccione la unidad dentro de la raíz de la cual se creó la carpeta "{0}".
CurrentUserFolderLocation                 = La ubicación actual de la carpeta "{0}": "{1}".
FilesWontBeMoved                          = Los archivos no se moverán.
FolderSelect                              = Seleccionar una carpeta
UserFolderRequest                         = ¿Le gustaría cambiar la ubicación de la "{0}" carpeta?
UserDefaultFolder                         = ¿Le gustaría cambiar la ubicación de la carpeta "{0}" para el valor por defecto?
ReservedStorageIsInUse                    = Se está utilizando el almacenamiento reservado.
ProgramPathNotExists                      = La ruta "{0}" no existe.
ProgIdNotExists                           = La ProgId "{0}" no existe.
AllFilesFilter                            = Todos los archivos
JSONNotValid                              = El archivo JSON "{0}" no es válido.
PackageNotInstalled                       = {0} no está instalado.
PackageIsInstalled                        = La última versión de {0} ya está instalada.
UninstallUWPForAll                        = Para todos los usuarios
NoUWPApps                                 = No hay aplicaciones UWP que desinstalar.
UWPAppsTitle                              = Aplicaciones UWP
ScheduledTaskCreatedByAnotherUser         = La tarea programada "{0}" ya fue creada por el usuario "{1}".
CleanupTaskNotificationTitle              = Limpieza de Windows
CleanupTaskNotificationEvent              = ¿Ejecutar la tarea de limpiar los archivos no utilizados y actualizaciones de Windows?
CleanupTaskDescription                    = La limpieza de Windows los archivos no utilizados y actualizaciones utilizando una función de aplicación de limpieza de discos. La tarea programada sólo puede ejecutarse si el usuario "{0}" ha iniciado sesión en el sistema.
CleanupNotificationTaskDescription        = Pop-up recordatorio de notificaciones sobre la limpieza de archivos no utilizados de Windows y actualizaciones. La tarea programada sólo puede ejecutarse si el usuario "{0}" ha iniciado sesión en el sistema.
SoftwareDistributionTaskNotificationEvent = La caché de actualización de Windows eliminado correctamente.
TempTaskNotificationEvent                 = Los archivos de la carpeta Temp limpiados con éxito.
FolderTaskDescription                     = La limpieza de la carpeta "{0}". La tarea programada sólo puede ejecutarse si el usuario "{0}" ha iniciado sesión en el sistema.
EventViewerCustomViewName                 = Creación de proceso
EventViewerCustomViewDescription          = Eventos de auditoría de línea de comandos y creación de procesos.
ThirdPartyAVInstalled                     = Se ha instalado un antivirus de terceros.
NoHomeWindowsEditionSupport               = La edición Windows Home no es compatible con la función "{0}".
GeoIdNotSupported                         = La función "{0}" solo es aplicable en Rusia.
PhotosNotInstalled                        = La aplicación Fotos no está instalada.
ThirdPartyArchiverInstalled               = Se ha instalado un archivador de terceros.
gpeditNotSupported                        = La edición Windows Home no es compatible con el complemento Editor de directivas de grupo local (gpedit.msc).
RestartWarning                            = Asegúrese de reiniciar su PC.
ErrorsLine                                = Línea
ErrorsMessage                             = Errores, advertencias y notificaciones
Disable                                   = Desactivar
Enable                                    = Habilitar
Install                                   = Instalar
Uninstall                                 = Desinstalar
RestartFunction                           = Por favor, reinicie la función "{0}".
NoResponse                                = No se pudo establecer una conexión con {0}.
Run                                       = Iniciar
Skipped                                   = Función "{0}" omitida.
ThankfulToastTitle                        = Gracias por utilizar Sophia Script ❤️
DonateToastTitle                          = Puede hacer su donación a continuación 🕊
DotSourcedWarning                         = Por favor, "dot-source" la función (con un punto al principio):\n. .\\Import-TabCompletion.ps1
'@
