ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = A szkript csak a Windows 10 64 bites verziót támogatja
UnsupportedOSBuild                        = A szkript a Windows 10 2004/20H2/21H1 és újabb kiadásokat támogatja
UnsupportedLanguageMode                   = A PowerShell munkamenet korlátozott nyelvi üzemmódban fut
LoggedInUserNotAdmin                      = A bejelentkezett felhasználó nem rendelkezik admin jogokkal
UnsupportedISE                            = A szkript nem támogatja a "Windows PowerShell ISE" futtatását
Win10TweakerWarning                       = Valószínűleg az operációs rendszerét a Win 10 Tweaker backdoor segítségével fertőzték meg.
UpdateWarning                             = Az Ön Windows 10 építése: {0}.{1}.{2}.{3}. Támogatott build: 10.0.19043.1052 és magasabb verziószámok
UnsupportedRelease                        = Új verzió érhető el
CustomizationWarning                      = \nSzemélyre szabott minden opciót a Sophia.ps1 preset fájlban, mielőtt futtatni kívánja a Sophia szkriptet?
ControlledFolderAccessDisabled            = Vezérelt mappához való hozzáférés kikapcsolva
ScheduledTasks                            = Ütemezett feladatok
OneDriveUninstalling                      = OneDrive eltávolítása...
OneDriveInstalling                        = OneDrive telepítése folyamatban...
OneDriveDownloading                       = OneDrive letöltése... ~33 MB
WindowsFeaturesTitle                      = Windows szolgáltatások
OptionalFeaturesTitle                     = Opcionális szolgáltatások
EnableHardwareVT                          = Virtualizáció engedélyezése UEFI-ben
UserShellFolderNotEmpty                   = Néhány fájl maradt a "{0}" könyvtárban. Kérem helyezze át ezeket egy új helyre
RetrievingDrivesList                      = A meghajtók listájának lekérése...
DriveSelect                               = Válassza ki a meghajtó jelét a gyökérkönyvtárban ahol a "{0}" könyvtár létre lesz hozva
UserFolderRequest                         = Kívánja megváltoztatni a "{0}" könyvtár helyét?
UserFolderSelect                          = Válasszon ki egy könyvtárat a "{0}" könyvtárhoz
UserDefaultFolder                         = Szeretné visszaállítani a "{0}" könyvtár helyét a gyári értékekre?
ReservedStorageIsInUse                    = Ez a művelet nem hajtható végre, amíg a fenntartott tárhely használatban van\nKérem várja meg, míg a folyamatok befejeződnek és próbálja meg késöbb újra
ShortcutPinning                           = A gyorsindító ikon "{0}" Startmenüre helyezése
UninstallUWPForAll                        = Az összes felhasználó számára
UWPAppsTitle                              = UWP Alkalmazások
WSLUpdateDownloading                      = A Linux kernel frissitő csomag letöltése... ~14 MB
WSLUpdateInstalling                       = A Linux kernel frissítő csomag telepítése...
HEVCDownloading                           = A HEVC Videobővítmények letöltése a gyártói oldalról... ~2,8 MB
GraphicsPerformanceTitle                  = Grafikus teljesítmény tulajdonság
GraphicsPerformanceRequest                = Szeretné megváltoztatni a grafikus teljesítmény beállítást az ön által kiválasztott alkalmazásban "Nagy teljesítményre"?
TaskNotificationTitle                     = Értesítés
CleanupTaskNotificationTitle              = Fontos Információ
CleanupTaskDescription                    = A nem használt Windows fájlok és frissítések eltávolítása a beépített lemezkarbantartó alkalmazással
CleanupTaskNotificationEventTitle         = Szeretné a nem használt fájlokat es frissitéseket eltávolítani?
CleanupTaskNotificationEvent              = A Windows megtisztítása nem tart már sokáig. Legközelebb 30 nap múlva jelenik meg ez a figyelmeztetés
CleanupTaskNotificationSnoozeInterval     = Válasszon ki egy emlékeztető időintervallumot
CleanupNotificationTaskDescription        = Előugró emlékeztető figyelmeztetés a nem használt Windows fájlok és frissítések törléséről
SoftwareDistributionTaskNotificationEvent = A Windows frissités számára fenntartott ideiglenes tárhely sikeresen megtisztítva
TempTaskNotificationEvent                 = Az ideiglenes fájlok tárolására szolgáló könyvtár tisztítása sikeresen megtörtént
FolderTaskDescription                     = A {0} könyvtár tisztítása
EventViewerCustomViewName                 = Folyamatok
EventViewerCustomViewDescription          = Folyamatok létrehozása és parancssor ellenőrző események
RestartWarning                            = \nKérem ne felejtse el újraindítani a számítógépét
ErrorsLine                                = Sor
ErrorsFile                                = Fájl
ErrorsMessage                             = Hibák/Figyelmeztetések
Add                                       = Hozzáadás
AllFilesFilter                            = Összes fájl (*.*)|*.*
Browse                                    = Pregledavati
Change                                    = Szerkesztés
DialogBoxOpening                          = Párbeszédablak megjelenítése...
Disable                                   = Kikapcsolás
Enable                                    = Engedélyezés
EXEFilesFilter                            = *.exe|*.exe|Minden fájl (*.*)|*.*
FolderSelect                              = Válasszon ki egy könyvtárat
FilesWontBeMoved                          = A fájlok nem lesznek áthelyezve
FourHours                                 = 4 óra
HalfHour                                  = 30 perc
Install                                   = Telepítés
Minute                                    = 1 perc
NoData                                    = Nincs megjeleníthető információ
NoInternetConnection                      = Nincs internetkapcsolat
NoResponse                                = Nem hozható létre kapcsolat a https://store.rg-adguard.net weboldallal
No                                        = Nem
Yes                                       = Igen
Open                                      = Megnyitás
Patient                                   = Kérem várjon...
Restore                                   = Visszaállítás
Run                                       = Futtatás
SelectAll                                 = Összes kijelölése
Skip                                      = Átugrás
Skipped                                   = Átugorva
TelegramTitle                             = Csatlakozzon a hivatalos Telegram csoportunkhoz
Uninstall                                 = Eltávolít
'@
