ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Le script n'est compatible qu'avec Windows 64 bits
UnsupportedOSBuild                        = \nLe script supporte le version Windows 10 Enterprise LTSC 2019
UpdateWarning                             = \nLa mise à jour cumulative de Windows 10 est installée : {0}. Mise à jour cumulative prise en charge: 4131 et plus. Exécutez Windows Update et réessayez
UnsupportedLanguageMode                   = \nLa session PowerShell s'exécute dans un mode de langue limité
LoggedInUserNotAdmin                      = \nL'utilisateur connecté n'a pas de droits d'administrateur
UnsupportedPowerShell                     = \nVous essayez d'exécuter le script via PowerShell {0}.{1}. Exécutez le script dans la version appropriée de PowerShell
UnsupportedHost                           = \nLe script ne supporte pas l'exécution via {0}
Win10TweakerWarning                       = \nVotre système d'exploitation a probablement été infecté par la porte dérobée Win 10 Tweaker
TweakerWarning                            = \nLa stabilité de l'OS Windows peut avoir été compromise par l'utilisation du {0}. Au cas où, réinstallez Windows
bin                                       = \nIl n'y a pas de fichiers dans le dossier bin. Veuillez retélécharger l'archive
RebootPending                             = \nLe PC attend d'être redémarré
UnsupportedRelease                        = \nNouvelle version trouvée
CustomizationWarning                      = \nAvez-vous personnalisé chaque fonction du fichier de préréglage {0} avant d'exécuter Sophia Script?
DefenderBroken                            = \nMicrosoft Defender cassé ou supprimé du système d'exploitation
UpdateDefender                            = \nLes définitions de Microsoft Defender ne sont pas à jour. Exécutez Windows Update et réessayez
ControlledFolderAccessDisabled            = Contrôle d'accès aux dossiers désactivé
ScheduledTasks                            = Tâches planifiées
WindowsFeaturesTitle                      = Fonctionnalités
OptionalFeaturesTitle                     = Fonctionnalités optionnelles
EnableHardwareVT                          = Activer la virtualisation dans UEFI
UserShellFolderNotEmpty                   = Certains fichiers laissés dans le dossier "{0}". Déplacer les manuellement vers un nouvel emplacement
RetrievingDrivesList                      = Récupération de la liste des lecteurs...
DriveSelect                               = Sélectionnez le disque à la racine dans lequel le dossier "{0}" sera créé.
CurrentUserFolderLocation                 = L'emplacement actuel du dossier "{0}": "{1}"
UserFolderRequest                         = Voulez vous changer où est placé le dossier "{0}" ?
UserFolderSelect                          = Sélectionnez un dossier pour le dossier "{0}"
UserDefaultFolder                         = Voulez vous changer où est placé le dossier "{0}" à sa valeur par défaut?
GraphicsPerformanceTitle                  = Préférence de performances graphiques
GraphicsPerformanceRequest                = Souhaitez-vous définir le paramètre de performances graphiques d'une application de votre choix sur "Haute performance"?
ScheduledTaskPresented                    = La fonction "{0}" a déjà été créée en tant que "{1}"
CleanupTaskNotificationTitle              = Nettoyer Windows
CleanupTaskNotificationEvent              = Exécuter la tâche pour nettoyer les fichiers et les mises à jour inutilisés de Windows?
CleanupTaskDescription                    = Nettoyage des fichiers Windows inutilisés et des mises à jour à l'aide de l'application intégrée pour le nettoyage de disque
CleanupNotificationTaskDescription        = Rappel de notification contextuelle sur le nettoyage des fichiers et des mises à jour inutilisés de Windows
SoftwareDistributionTaskNotificationEvent = Le cache de mise à jour Windows a bien été supprimé
TempTaskNotificationEvent                 = Le dossier des fichiers temporaires a été nettoyé avec succès
FolderTaskDescription                     = Nettoyage du dossier "{0}"
EventViewerCustomViewName                 = Création du processus
EventViewerCustomViewDescription          = Audit des événements de création du processus et de ligne de commande
RestartWarning                            = Assurez-vous de redémarrer votre PC
ErrorsLine                                = Ligne
ErrorsMessage                             = Erreurs/Avertissements
DialogBoxOpening                          = Afficher la boîte de dialogue...
Disable                                   = Désactiver
EXEFilesFilter                            = *.exe|*.exe|Tous les Fichiers (*.*)|*.*
FolderSelect                              = Sélectionner un dossier
FilesWontBeMoved                          = Les fichiers ne seront pas déplacés
Install                                   = Installer
NoData                                    = Rien à afficher
NoInternetConnection                      = Pas de connexion Internet
RestartFunction                           = Veuillez redémarrer la fonction "{0}"
NoResponse                                = Une connexion n'a pas pu être établie avec {0}
Restore                                   = Restaurer
Run                                       = Démarrer
Skipped                                   = Passé
GPOUpdate                                 = Mise à jour de la GPO...
TelegramGroupTitle                        = Rejoignez notre groupe Telegram officiel
TelegramChannelTitle                      = Rejoignez notre canal Telegram officiel
DiscordChannelTitle                       = Rejoignez notre canal Discord officiel
Uninstall                                 = Désinstaller
'@
