ConvertFrom-StringData -StringData @'
UnsupportedArchitecture                   = Stai utilizzando una CPU con architettura basata su "{0}". Questo script supporta solo CPU con architettura Arm. Scarica ed esegui la versione dello script adatta alla tua architettura.
NewSophiaScriptFound                      = È disponibile una nuova versione: Sophia Script for Windows {0}. Esegui l'aggiornamento.
UnsupportedPowerShell                     = Stai cercando di eseguire lo script tramite PowerShell {0}.{1}. Esegui lo script in PowerShell {2}.
CodeCompilationFailed                     = Compilazione del codice non riuscita.
KeyboardArrows                            = Per selezionare la risposta, utilizza i tasti freccia {0} e {1} della tastiera
UnsupportedLanguageMode                   = La sessione PowerShell è in esecuzione in modalità di linguaggio limitata.
LoggedInUserNotAdmin                      = L'utente connesso "{0}" non dispone dei diritti di amministratore. Lo script è stato eseguito per conto di "{1}". Accedi a un account con diritti di amministratore ed esegui nuovamente lo script.
UnsupportedHost                           = Lo script non supporta l'esecuzione tramite {0}.
HarmfulTweakerFound                       = La stabilità del sistema operativo Windows potrebbe essere stata compromessa dall'utilizzo dello {0}.
HostsEntriesFound                         = Voci di terze parti trovate nel file %SystemRoot%\\System32\\drivers\\etc\\hosts. Potrebbero bloccare la connessione alle risorse utilizzate nello script. Vuoi continuare?
UWPComponentsMissing                      = Manca il componente UWP "{0}".
DefenderComponentsMissing                 = Manca il componente "{0}" di Microsoft Defender.
WindowsComponentStabilityDisrupted        = È stato rilevato un problema di instabilità nel componente "{0}".
DisableControlledFolderAccess             = Hai attivato l'accesso alle cartelle controllato. Disattivalo ed esegui nuovamente lo script.
RebootPending                             = Il tuo PC è in attesa di essere riavviato.
SystemDriveEncryptedBitLockerDisabled     = L'unità C è crittografata, anche se BitLocker è disattivato. Vuoi decrittografare l'unità?
UpdateUEFICertificates                    = Il certificato Secure Boot "Microsoft Windows Production PCA 2011" scade nel 2026. Il tuo dispositivo non ha ancora ricevuto i certificati aggiornati "Windows UEFI CA 2023". Vuoi installare manualmente i certificati "Microsoft Windows UEFI CA 2023"?
EnableSecureBoot                          = Attiva Secure Boot.
WrongSophiaScriptVersion                  = Lo script supporta Windows 11 25H2 e versioni successive. Stai utilizzando {0} {1}. Esegui lo script corretto in base alla versione di Windows.
UpdateWindowsTerminal                     = La versione di Windows Terminal è inferiore a 1.24. Aggiornala nel Microsoft Store e riprova.
UpdateWindowsBuild                        = Lo script è compatibile con Windows 11 25H2 {0}.{1} e versioni successive. Stai utilizzando {2} {3} {4}.{5}. Esegui Windows Update e riprova.
AskQuestion                               = Se hai qualche domanda, apri un issue su GitHub o chiedi alla community.
CheckSophiaScriptPreset                   = Hai personalizzato tutte le funzioni nel file di configurazione {0} prima di eseguire Sophia Script for Windows?
ReinstallWindows                          = Reinstalla Windows utilizzando solo un'immagine ISO autentica.
CreatingRestorePoint                      = Si sta creando un punto di ripristino...
WindowsServiceNotFound                    = Il servizio "{0}" non è stato trovato.
NoScheduledTasksFound                     = Nessuna attività pianificata trovata.
ScheduledTasks                            = Attività pianificate
WidgetNotInstalled                        = Il widget non è installato.
SearchHighlightsDisabled                  = I risultati in evidenza della ricerca sono già nascosti nella schermata Start.
CustomStartMenuFound                      = È installato un menu Start di terze parti.
OneDriveNotInstalled                      = OneDrive è già stato disinstallato.
OneDriveAccountUsageFound                 = Prima di disinstallare OneDrive, esci dal tuo account Microsoft in OneDrive.
OneDriveInstalled                         = OneDrive è già installato.
UninstallingApplication                   = {0} è in fase di disinstallazione...
InstallingApplication                     = {0} è in fase di installazione...
NoWindowsFeaturesFound                    = Nessuna funzionalità di Windows trovata.
WindowsFeaturesTitle                      = Funzionalità di Windows
NoOptionalFeaturesFound                   = Nessuna funzionalità facoltativa trovata.
OptionalFeaturesTitle                     = Funzionalità facoltative
NoSupportedNetworkAdaptersFound           = Nessuna scheda di rete che supporti la funzione "Consenti al computer di spegnere questo dispositivo per risparmiare energia".
LocationServicesDisabled                  = I comandi della shell di rete richiedono l'autorizzazione alla localizzazione per accedere alle informazioni WLAN. Attiva i servizi di localizzazione nella pagina Localizzazione delle impostazioni Privacy e sicurezza.
UserFolderLocationMove                    = Non dovresti modificare la posizione della cartella utente nella radice dell'unità C.
DriveSelect                               = Seleziona l'unità in cui verrà creata la cartella "{0}" nella directory principale.
CurrentUserFolderLocation                 = La posizione attuale della cartella "{0}": "{1}".
FilesWontBeMoved                          = I file non verranno spostati.
UserFolderMoveSkipped                     = Hai saltato la modifica della posizione della cartella "{0}" dell'utente.
UserShellFolderNotEmpty                   = Alcuni file sono rimasti nella cartella "{0}". Spostali manualmente in una nuova posizione.
FolderSelect                              = Seleziona una cartella
UserFolderRequest                         = Vuoi cambiare la posizione della cartella "{0}"?
UserDefaultFolder                         = Vuoi ripristinare la posizione predefinita della cartella "{0}"?
ReservedStorageIsInUse                    = Lo spazio di archiviazione riservato è in uso.
ProgramPathNotExists                      = Il percorso "{0}" non esiste.
ProgIdNotExists                           = ProgId "{0}" non esiste.
AllFilesFilter                            = Tutti i file
JSONNotValid                              = Il file JSON "{0}" non è valido.
PackageNotInstalled                       = L'applicazione "{0}" non è installata.
PackageIsInstalled                        = L'ultima versione di {0} è già installata.
PCNPUSupport                              = Il tuo PC non dispone di un acceleratore AI integrato (NPU), quindi non supporta le funzioni di Windows relative all'intelligenza artificiale. Non verrà applicata alcuna politica, ad eccezione della rimozione della funzione Recall e dell'applicazione Copilot.
UWPAppsTitle                              = App UWP
UninstallUWPForAll                        = Per tutti gli utenti
NoUWPAppsFound                            = Nessuna app UWP da disinstallare.
WDDMVersionUnsupported                    = La versione di WDDM supportata è la 2.7 e successive. La versione attuale di WDDM è la {0}.
CleanupTaskNotificationTitle              = Pulizia di Windows
CleanupTaskNotificationEvent              = Eseguire l'operazione di pulizia dei file e degli aggiornamenti inutilizzati di Windows?
CleanupTaskDescription                    = Pulizia dei file e degli aggiornamenti inutilizzati di Windows utilizzando l'app di pulizia del disco integrata.
CleanupNotificationTaskDescription        = Notifica pop-up di promemoria sulla pulizia dei file e degli aggiornamenti inutilizzati di Windows.
SoftwareDistributionTaskNotificationEvent = La cache degli aggiornamenti di Windows è stata eliminata correttamente.
SoftwareDistributionTaskDescription       = Pulizia della cartella della cache di Windows Update "{0}".
TempTaskNotificationEvent                 = La cartella temporanea è stata pulita correttamente.
TempTaskDescription                       = Pulizia della cartella temporanea "{0}" (%TEMP%).
ScheduledTaskLoggedInUserNotification     = L'attività pianificata può essere eseguita solo se l'utente "{0}" ha effettuato l'accesso al sistema.
CleanupTaskCLIDescription                 = L'attività pianificata "Sophia\\Windows Cleanup Notification" è stata creata nell'Utilità di pianificazione per pulire i file e gli aggiornamenti di Windows inutilizzati.
SoftwareDistributionTaskCLIDescription    = L'attività pianificata "Sophia\\SoftwareDistribution" è stata creata nell'Utilità di pianificazione per pulire la cartella della cache degli aggiornamenti di Windows "{0}".
TempTaskCLIDescription                    = L'attività pianificata "Sophia\\Temp" è stata creata nell'Utilità di pianificazione per pulire la cartella temporanea "{0}" (%TEMP%).
EventViewerCustomViewName                 = Creazione di processi
EventViewerCustomViewDescription          = Tenere traccia dei processi avviati e dell'attività di PowerShell
EventViewerCustomViewNotification         = La visualizzazione personalizzata "Visualizzazioni personalizzate\\{0}" è stata creata nel Visualizzatore eventi per tenere traccia dei processi avviati e dell'attività di PowerShell.
ThirdPartyAVInstalled                     = È installato un antivirus di terze parti.
NoHomeWindowsEditionSupport               = Windows Home Edition non supporta la funzione "{0}".
EnableHardwareVT                          = Attiva la virtualizzazione nell'UEFI.
ActiveNetworkAdapterNotFound              = Impossibile determinare la scheda di rete attualmente in uso: non è stata trovata alcuna connessione di rete attiva. Connettiti a una rete.
ThirdPartyArchiverInstalled               = È installato un programma di archiviazione di terze parti.
gpeditNotSupported                        = Windows Home Edition non supporta lo snap-in Editor criteri di gruppo locali (gpedit.msc).
RestartWarning                            = Assicurati di riavviare il PC.
RestorePointVolume                        = I punti di ripristino dell'unità C occupano {0} GB.
ErrorsLine                                = Riga
ErrorsMessage                             = Errori, avvisi e notifiche
Disable                                   = Disattiva
Enable                                    = Attiva
Install                                   = Installa
Uninstall                                 = Disinstalla
RestartFunction                           = Esegui nuovamente la funzione "{0}".
NoConnectionEstablished                   = Non è stato possibile stabilire una connessione con {0}.
Run                                       = Esegui
FunctionSkipped                           = Funzione "{0}" saltata.
DonateToastTitle                          = Le donazioni sono benvenute! ❤
DotSourceFunction                         = Esegui il "dot-source" della funzione (con un punto all'inizio):\n. .\\Import-TabCompletion.ps1
'@
