ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Das Skript unterstützt nur Windows 10 x64
UnsupportedOSBuild                        = Das Skript unterstützt Windows 10 1809 Enterprise LTSC
UnsupportedLanguageMode                   = Die PowerShell-Sitzung wird in einem eingeschränkten Sprachmodus ausgeführt
LoggedInUserNotAdmin                      = Der angemeldete Benutzer hat keine Administratorrechte
UnsupportedPowerShell                     = Sie versuchen, ein Skript über PowerShell {0}.{1} auszuführen. Führen Sie das Skript in der entsprechenden PowerShell-Version aus
UnsupportedISE                            = Das Skript unterstützt nicht die Ausführung über Windows PowerShell ISE
Win10TweakerWarning                       = Wahrscheinlich wurde Ihr Betriebssystem über die Win 10 Tweaker-Hintertür infiziert
UnsupportedRelease                        = Neue Version gefunden
CustomizationWarning                      = \nHaben Sie alle Funktionen in der voreingestellten Datei Sophia.ps1 angepasst, bevor Sie Sophia Script ausführen?
ControlledFolderAccessDisabled            = Kontrollierter Ordnerzugriff deaktiviert
ScheduledTasks                            = Geplante Aufgaben
WindowsFeaturesTitle                      = Windows Eigenschaften
OptionalFeaturesTitle                     = Optionale Eigenschaften
EnableHardwareVT                          = Virtualisierung in UEFI aktivieren
UserShellFolderNotEmpty                   = Im Ordner "{0}" befinden sich noch Dateien \nVerschieben Sie sie manuell an einen neuen Ort
RetrievingDrivesList                      = Abrufen der Laufwerksliste...
DriveSelect                               = Wählen Sie das Laufwerk aus, in dessen Stammverzeichnis der Ordner "{0}" erstellt werden soll
CurrentUserFolderLocation                 = Der aktuelle Speicherort des Ordners "{0}" lautet: "{1}"
UserFolderRequest                         = Möchten Sie den Speicherort des Ordners "{0}" ändern?
UserFolderSelect                          = Wählen Sie einen Ordner für den Ordner "{0}"
UserDefaultFolder                         = Möchten Sie den Speicherort des "{0}"-Ordners auf den Standardwert ändern?
GraphicsPerformanceTitle                  = Bevorzugte Grafikleistung
GraphicsPerformanceRequest                = Möchten Sie die Einstellung der Grafikleistung einer App Ihrer Wahl auf "Hohe Leistung" setzen?
TaskNotificationTitle                     = Benachrichtigung
CleanupTaskNotificationTitle              = Wichtige informationen
CleanupTaskDescription                    = Bereinigung ungenutzter Windows-Dateien und -Updates mit der integrierten Datenträgerbereinigung
CleanupTaskNotificationEventTitle         = Aufgabe ausführen, um nicht verwendete Windows-Dateien und -Updates zu bereinigen?
CleanupTaskNotificationEvent              = Die Datenträgerbereinigung dauert nicht lange. Das nächste Mal wird die Benachrichtigung in 30 Tagen angezeigt
CleanupTaskNotificationSnoozeInterval     = Wählen Sie einen Erinnerungsintervall
CleanupNotificationTaskDescription        = Bereinigung ungenutzter Windows-Dateien und -Updates mit der integrierten Datenträgerbereinigung
SoftwareDistributionTaskNotificationEvent = Der Cache von Windows Update wurde erfolgreich gelöscht
TempTaskNotificationEvent                 = Der Ordner mit den temporären Dateien wurde erfolgreich bereinigt
FolderTaskDescription                     = Die Bereinigung des Ordners "{0}"
EventViewerCustomViewName                 = Prozess-Erstellung
EventViewerCustomViewDescription          = Ereignisse zur Prozesserstellung und Befehlszeilen-Auditierung
RestartWarning                            = Achten Sie darauf, Ihren PC neu zu starten
ErrorsLine                                = Zeile
ErrorsFile                                = Datei
ErrorsMessage                             = Fehler/Warnungen
Add                                       = Hinzufügen
AllFilesFilter                            = Alle Dateien (*.*)|*.*
Browse                                    = Durchsuchen
Change                                    = Ändern
DialogBoxOpening                          = Anzeigen des Dialogfensters...
Disable                                   = Deaktivieren
Enable                                    = Aktivieren
EXEFilesFilter                            = *.exe|*.exe|Alle Dateien (*.*)|*.*
FolderSelect                              = Wählen Sie einen Ordner aus
FilesWontBeMoved                          = Dateien werden nicht verschoben
FourHours                                 = 4 Stunden
HalfHour                                  = 30 Minuten
Install                                   = Installieren
Minute                                    = 1 Minute
NoData                                    = Nichts anzuzeigen
NoInternetConnection                      = Keine Internetverbindung
RestartFunction                           = Bitte starten Sie die Funktion "{0}" neu
NoResponse                                = Eine Verbindung mit {0} konnte nicht hergestellt werden
No                                        = Nein
Yes                                       = Ja
Open                                      = Öffnen
Patient                                   = Bitte Warten...
Restore                                   = Wiederherstellen
Run                                       = Starten
SelectAll                                 = Wählen Sie Alle
Skip                                      = Überspringen
Skipped                                   = Übersprungen
FileExplorerRestartPrompt                 = \nManchmal muss der Datei-Explorer neu gestartet werden, damit die Änderungen wirksam werden
TelegramGroupTitle                        = Treten Sie unserer offiziellen Telegram-Gruppe bei
TelegramChannelTitle                      = Treten Sie unserem offiziellen Telegram-Kanal bei
Uninstall                                 = Deinstallieren
'@