ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Bu betik sadece Windows 10 x64 destekliyor
UnsupportedOSBuild                        = Komut dosyası, Windows 10 Enterprise LTSC 2021
UpdateWarning                             = Windows 10 toplu güncelleştirmesi yüklendi: {0}. Desteklenen toplu güncelleme: 2364 ve üstü. Windows Update'i çalıştırın ve tekrar deneyin
UnsupportedLanguageMode                   = Sınırlı bir dil modunda çalışan PowerShell oturumu
LoggedInUserNotAdmin                      = Oturum açan kullanıcının yönetici hakları yok
UnsupportedPowerShell                     = Komut dosyasını PowerShell {0}.{1} aracılığıyla çalıştırmaya çalışıyorsunuz. Komut dosyasını uygun PowerShell sürümünde çalıştırın
UnsupportedISE                            = Komut dosyası, Windows PowerShell ISE üzerinden çalıştırmayı desteklemiyor
Win10TweakerWarning                       = Muhtemelen işletim sisteminize Win 10 Tweaker arka kapısı yoluyla bulaştı
SycnexWarning                             = Windows işletim sistemi kararlılığı, Sycnex'in Windows10Debloater PowerShell betiği kullanılarak tehlikeye atılmış olabilir. Önleyici olarak, Windows'u yeniden yükleyin
Fs00Warning                               = Windows işletim sistemi kararlılığı, "Windows 10 Bloat Remover and Tweaker" betiği kullanılarak tehlikeye atılmış olabilir. Önleyici olarak, Windows'u yeniden yükleyin
bin                                       = bin klasöründe dosya yok. Lütfen arşivi yeniden indirin
RebootPending                             = PC yeniden başlatılmayı bekliyor
UnsupportedRelease                        = Yeni sürüm bulundu
CustomizationWarning                      = \nSophia Script'i çalıştırmadan önce {0} ön ayar dosyasındaki her işlevi özelleştirdiniz mi?
DefenderBroken                            = Microsoft Defender bozuk veya işletim sisteminden kaldırıldı
UpdateDefender                            = Microsoft Defender tanımları güncel değil. Windows Update'i çalıştırın ve tekrar deneyin
ControlledFolderAccessDisabled            = Kontrollü klasör erişimi devre dışı bırakıldı
ScheduledTasks                            = Zamanlanan görevler
WindowsFeaturesTitle                      = Características do Windows
OptionalFeaturesTitle                     = Opsiyonel özellikler
EnableHardwareVT                          = UEFI'dan sanallaştırmayı aktifleştirin
UserShellFolderNotEmpty                   = "{0}" klasöründe bazı dosyalar kaldı. \nKendiniz yeni konuma taşıyın
RetrievingDrivesList                      = Sürücü listesi alınıyor...
DriveSelect                               = "{0}" klasörünün oluşturulacağı kök içindeki sürücüyü seçin
CurrentUserFolderLocation                 = Geçerli "{0}" klasör konumu: "{1}"
UserFolderRequest                         = "{0}" klasörünün yerini değiştirmek ister misiniz?
UserFolderSelect                          = "{0}" klasörü için bir klasör seçin
UserDefaultFolder                         = "{0}" klasörünün konumunu varsayılan değerle değiştirmek ister misiniz?
ReservedStorageIsInUse                    = Ayrılmış depolama kullanımdayken bu işlem desteklenmez\nBilgisayar yeniden başlatıldıktan sonra lütfen "{0}" işlevini yeniden çalıştırın
ShortcutPinning                           = "{0}" kısayolu Başlangıç sekmesine sabitlendi...
GraphicsPerformanceTitle                  = Grafik performans tercihi
GraphicsPerformanceRequest                = Seçtiğiniz bir uygulamanın grafik performansı ayarını "Yüksek performans" olarak belirlemek ister misiniz?
ScheduledTaskPresented                    = "{0}" işlevi zaten "{1}" olarak oluşturulmuştu
CleanupTaskNotificationTitle              = Windows temizliği
CleanupTaskNotificationEvent              = Windows kullanılmayan dosyaları ve güncellemeleri temizlemek için görev çalıştırılsın mı?
CleanupTaskDescription                    = Kullanılmayan Windows dosyaları ve güncellemeleri yerleşik Disk Temizleme uygulaması ile temizleniyor
CleanupNotificationTaskDescription        = Windows kullanılmayan dosyaları ve güncellemeleri temizleme hakkında açılır bildirim hatırlatıcısı
SoftwareDistributionTaskNotificationEvent = Windows güncelleme önbelleği başarıyla silindi
TempTaskNotificationEvent                 = Geçici dosyalar klasörü başarıyla temizlendi
FolderTaskDescription                     = "{0}" klasörü temizleniyor
EventViewerCustomViewName                 = Süreç Oluşturma
EventViewerCustomViewDescription          = Süreç oluşturma ve komut satırı denetleme olayları
RestartWarning                            = Bilgisayarınızı yeniden başlattığınızdan emin olun
ErrorsLine                                = Satır
ErrorsFile                                = Dosya
ErrorsMessage                             = Hatalar/Uyarılar
Add                                       = Ekle
AllFilesFilter                            = Tüm Dosyalar (*.*)|*.*
Browse                                    = Gözat
DialogBoxOpening                          = İletişim kutusu görüntüleniyor...
Disable                                   = Devre dışı bırak
Enable                                    = Aktif et
EXEFilesFilter                            = *.exe|*.exe|Tüm Dosyalar (*.*)|*.*
FolderSelect                              = Klasör seç
FilesWontBeMoved                          = Dosyalar taşınmayacak
Install                                   = Yükle
NoData                                    = Görüntülenecek bir şey yok
NoInternetConnection                      = İnternet bağlantısı yok
RestartFunction                           = Lütfen "{0}" işlevini yeniden çalıştırın
NoResponse                                = {0} ile bağlantı kurulamadı
No                                        = Hayır
Yes                                       = Evet
Open                                      = Açık
Patient                                   = Lütfen bekleyin...
Restore                                   = Onar
Run                                       = Başlat
SelectAll                                 = Hepsini seç
Skipped                                   = Atlandı
GPOUpdate                                 = GPO Güncelleniyor...
TelegramGroupTitle                        = Resmi Telegram grubumuza katılın
TelegramChannelTitle                      = Resmi Telegram kanalımıza katılın
DiscordChannelTitle                       = Resmi Discord kanalımıza katılın
Uninstall                                 = Kaldır
'@
