ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = The script supports Windows 10 x64 only
UnsupportedOSBuild                        = The script supports Windows 10 2004/20H1 versions and higher
UnsupportedRelease                        = A new version found
ControlledFolderAccessDisabled            = Controlled folder access disabled
ScheduledTasks                            = Scheduled tasks
OneDriveUninstalling                      = Uninstalling OneDrive...
OneDriveInstalling                        = OneDrive is installing...
OneDriveDownloading                       = Downloading OneDrive... ~33 MB
WindowsFeaturesTitle                      = Windows features
OptionalFeaturesTitle                     = Optional features
EnableHardwareVT                          = Enable Virtualization in UEFI
UserShellFolderNotEmpty                   = Some files left in the "{0}" folder. Move them manually to a new location
RetrievingDrivesList                      = Retrieving drives list...
DriveSelect                               = Select the drive within the root of which the "{0}" folder will be created
UserFolderRequest                         = Would you like to change the location of the "{0}" folder?
UserFolderSelect                          = Select a folder for the "{0}" folder
UserDefaultFolder                         = Would you like to change the location of the "{0}" folder to the default value?
ReservedStorageIsInUse                    = This operation is not supported when reserved storage is in use\nPlease wait for any servicing operations to complete and then try again later
ShortcutPinning                           = The "{0}" shortcut is being pinned to Start
UninstallUWPForAll                        = For All Users
UWPAppsTitle                              = UWP Apps
WSLUpdateDownloading                      = Downloading the Linux kernel update package... ~14 MB
WSLUpdateInstalling                       = Installing the Linux kernel update package...
HEVCDownloading                           = Downloading HEVC Video Extensions from Device Manufacturer... ~2,8 MB
GraphicsPerformanceTitle                  = Graphics performance preference
GraphicsPerformanceRequest                = Would you like to set the graphics performance setting of an app of your choice to "High performance"?
TaskNotificationTitle                     = Notification
CleanupTaskNotificationTitle              = Important Information
CleanupTaskDescription                    = Cleaning up Windows unused files and updates using built-in Disk cleanup app
CleanupTaskNotificationEventTitle         = Run task to clean up Windows unused files and updates?
CleanupTaskNotificationEvent              = Windows cleanup won't take long. Next time this notification will appear in 30 days
CleanupTaskNotificationSnoozeInterval     = Select a Reminder Interval
CleanupNotificationTaskDescription        = Pop-up notification reminder about cleaning up Windows unused files and updates
SoftwareDistributionTaskNotificationEvent = The Windows update cache successfully deleted
TempTaskNotificationEvent                 = The temp files folder successfully cleaned up
FolderTaskDescription                     = The {0} folder cleanup
ControlledFolderAccess                    = Controlled folder access
ProtectedFoldersRequest                   = Would you like to enable Controlled folder access and specify the folder that Microsoft Defender will protect from malicious apps and threats?
ProtectedFoldersListRemoved               = Removed folders
AppControlledFolderRequest                = Would you like to specify an app that is allowed through Controlled Folder access?
AllowedControlledFolderAppsRemoved        = Removed allowed apps
DefenderExclusionFolderRequest            = Would you like to specify a folder to be excluded from Microsoft Defender malware scans?
DefenderExclusionFoldersListRemoved       = Excluded folders removed
AddDefenderExclusionFileRequest           = Would you like to specify a file to be excluded from Microsoft Defender malware scans?
DefenderExclusionFilesRemoved             = Excluded files removed
EventViewerCustomViewName                 = Process Creation
EventViewerCustomViewDescription          = Process creation and command-line auditing events
RestartWarning                            = Make sure to restart your PC
ErrorsLine                                = Line
ErrorsFile                                = File
ErrorsMessage                             = Errors/Warnings
Add                                       = Add
AllFilesFilter                            = All Files (*.*)|*.*
Change                                    = Change
DialogBoxOpening                          = Displaying the dialog box...
Disable                                   = Disable
Enable                                    = Enable
EXEFilesFilter                            = *.exe|*.exe|All Files (*.*)|*.*
FolderSelect                              = Select a folder
FilesWontBeMoved                          = Files will not be moved
FourHours                                 = 4 Hours
HalfHour                                  = 30 Minutes
Install                                   = Install
Minute                                    = 1 Minute
NoData                                    = Nothing to display
NoInternetConnection                      = No Internet connection
NoResponse                                = A connection could not be established with https://store.rg-adguard.net
Open                                      = Open
Patient                                   = Please wait...
Restore                                   = Restore
Run                                       = Run
Select                                    = Select
SelectAll                                 = Select all
Skip                                      = Skip
Skipped                                   = Skipped
TelegramTitle                             = Join our official Telegram group
Uninstall                                 = Uninstall
'@
