ConvertFrom-StringData -StringData @'
NewSophiaScriptFound                      = Обнаружена новая версия: Sophia Script for Windows {0}. Пожалуйста, скачайте последнюю версию.
UnsupportedPowerShell                     = Вы пытаетесь запустить скрипт в PowerShell {0}.{1}. Запустите скрипт в PowerShell {2}.
CodeCompilationFailed                     = Компиляция кода завершилась с ошибкой.
UnsupportedWindowsBitness                 = Скрипт поддерживает только 64-битную версию Windows.
KeyboardArrows                            = Для выбора используйте стрелки на клавиатуре {0} и {1}
UnsupportedLanguageMode                   = Сессия PowerShell работает в ограниченном режиме.
LoggedInUserNotAdmin                      = Вошедший пользователь "{0}" не обладает правами администратора. Скрипт был запущен от имени "{1}". Пожалуйста, войдите в профиль, обладающий правами администратора, и запустите скрипт заново.
UnsupportedHost                           = Скрипт не поддерживает работу через {0}.
HarmfulTweakerFound                       = Стабильность Windows могла быть нарушена использованием {0}.
HostsEntriesFound                         = В файле %SystemRoot%\\System32\\drivers\\etc\\hosts обнаружены сторонние записи. Они могут блокировать соединение с ресурсами, используемыми в работе скрипта. Хотите продолжить?
UWPComponentsMissing                      = Отсутствует UWP-компонент "{0}".
DefenderComponentsMissing                 = Отсутствует компонент "{0}" для Microsoft Defender.
WindowsComponentStabilityDisrupted        = Обнаружено нарушение стабильности работы компонента "{0}".
DisableControlledFolderAccess             = Вы включили Контролируемый доступ к папкам. Пожалуйста, отключите его и повторите попытку.
RebootPending                             = Ваш компьютер ожидает перезагрузки.
SystemDriveEncryptedBitLockerDisabled     = Диск C зашифрован, хотя BitLocker отключен. Хотите расшифровать диск?
WrongSophiaScriptVersion                  = Скрипт поддерживает только Windows 10 Enterprise LTSC 2019. Вы используете {0} {1}. Запустите версию скрипта, соответствующую вашей редакции Windows.
UpdateWindowsBuild                        = Скрипт поддерживает Windows 10 Enterprise LTSC 2019 {0}.{1} и выше. Вы используете {2} {3} {4}.{5}. Запустите обновление Windows и повторите попытку.
AskQuestion                               = Если у вас возникнут вопросы, создайте issue на GitHub или обратитесь к сообществу.
CheckSophiaScriptPreset                   = Вы настроили все функции в пресет-файле {0} перед запуском Sophia Script for Windows?
ReinstallWindows                          = Переустановите Windows, используя только подлинный ISO-образ.
CreatingRestorePoint                      = Создается точка восстановления...
WindowsServiceNotFound                    = Отсутствует служба "{0}".
NoScheduledTasksFound                     = Запланированные задачи не найдены.
ScheduledTasks                            = Запланированные задачи
TaskbarSmallIcons                         = Вы используете маленькие кнопки панели задач.
CustomStartMenuFound                      = Установлено стороннее меню "Пуск".
InstallingApplication                     = {0} устанавливается...
NoWindowsFeaturesFound                    = Компоненты Windows не найдены.
WindowsFeaturesTitle                      = Компоненты Windows
NoOptionalFeaturesFound                   = Дополнительные компоненты не найдены.
OptionalFeaturesTitle                     = Дополнительные компоненты
NoSupportedNetworkAdaptersFound           = Нет сетевых адаптеров, поддерживающих функцию "Разрешить компьютеру отключать это устройство для экономии энергии".
LocationServicesDisabled                  = Командам сетевой оболочки требуется разрешение на определение местоположения для доступа к сведениям о беспроводной сети. Включите службы определения местоположения на странице "Расположение" в параметрах конфиденциальности и защиты.
UserFolderLocationMove                    = Не следует перемещать пользовательские папки в корень диска C.
DriveSelect                               = Выберите диск, в корне которого будет создана папка "{0}".
CurrentUserFolderLocation                 = Текущее расположение папки "{0}": "{1}".
FilesWontBeMoved                          = Файлы не будут перенесены.
UserFolderMoveSkipped                     = Вы пропустили изменение расположения пользовательской папки "{0}".
UserShellFolderNotEmpty                   = В папке "{0}" остались файлы. Переместите их вручную в новое расположение.
FolderSelect                              = Выберите папку
UserFolderRequest                         = Хотите изменить расположение папки "{0}"?
UserDefaultFolder                         = Хотите изменить расположение папки "{0}" на значение по умолчанию?
ProgramPathNotExists                      = Путь "{0}" не существует.
ProgIdNotExists                           = ProgId "{0}" не существует.
AllFilesFilter                            = Все файлы
JSONNotValid                              = Файл JSON "{0}" некорректен.
PackageIsInstalled                        = Последняя версия {0} уже установлена.
CleanupTaskNotificationTitle              = Очистка Windows
CleanupTaskNotificationEvent              = Запустить задачу по очистке неиспользуемых файлов и обновлений Windows?
CleanupTaskDescription                    = Очистка неиспользуемых файлов и обновлений Windows с помощью встроенной программы "Очистка диска".
CleanupNotificationTaskDescription        = Всплывающее уведомление с напоминанием об очистке неиспользуемых файлов и обновлений Windows.
SoftwareDistributionTaskNotificationEvent = Кэш обновлений Windows успешно удален.
SoftwareDistributionTaskDescription       = Очистка папки кэша обновлений Windows "{0}".
TempTaskNotificationEvent                 = Временная папка успешно очищена.
TempTaskDescription                       = Очистка временной папки "{0}" (%TEMP%).
ScheduledTaskLoggedInUserNotification     = Задача может быть запущена, только если пользователь "{0}" вошел в систему.
CleanupTaskCLIDescription                 = Запланированная задача "Sophia\\Windows Cleanup Notification" создана в Планировщике заданий для очистки неиспользуемых файлов и обновлений Windows.
SoftwareDistributionTaskCLIDescription    = Запланированная задача "Sophia\\SoftwareDistribution" создана в Планировщике заданий для очистки папки кэша обновлений Windows "{0}".
TempTaskCLIDescription                    = Запланированная задача "Sophia\\Temp" создана в Планировщике заданий для очистки временной папки "{0}" (%TEMP%).
EventViewerCustomViewName                 = Создание процесса
EventViewerCustomViewDescription          = Отслеживание запускаемых процессов и активности PowerShell
EventViewerCustomViewNotification         = Настраиваемое представление "Настраиваемые представления\\{0}" создано в Просмотре событий для отслеживания запускаемых процессов и активности PowerShell.
ThirdPartyAVInstalled                     = Установлен сторонний антивирус.
EnableHardwareVT                          = Включите виртуализацию в UEFI.
ThirdPartyArchiverInstalled               = Установлен сторонний архиватор.
RestartWarning                            = Обязательно перезагрузите ваш ПК.
RestorePointVolume                        = Точки восстановления на диске C занимают {0} ГБ.
ErrorsLine                                = Строка
ErrorsMessage                             = Ошибки, предупреждения и уведомления
Disable                                   = Отключить
Enable                                    = Включить
Install                                   = Установить
Uninstall                                 = Удалить
RestartFunction                           = Пожалуйста, повторно запустите функцию "{0}".
NoConnectionEstablished                   = Невозможно установить соединение с {0}.
Run                                       = Запустить
FunctionSkipped                           = Функция "{0}" пропущена.
DonateToastTitle                          = Вы можете пожертвовать! ♥
DotSourceFunction                         = Пожалуйста, запустите функцию через дот-сорсинг (с точкой в начале):\n. .\\Import-TabCompletion.ps1
'@
