ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Скрипт підтримує тільки Windows 10 x64
UnsupportedOSBuild                        = Скрипт підтримує тільки Windows 10 1809 версії Enterprise LTSC
UnsupportedLanguageMode                   = Сесія PowerShell працює в обмеженому режимі
LoggedInUserNotAdmin                      = Поточний увійшов користувач не володіє правами адміністратора
UnsupportedPowerShell                     = Ви намагаєтеся запустити скрипт в PowerShell {0}.{1}. Запустіть скрипт у відповідній версії PowerShell
UnsupportedISE                            = Скрипт не підтримує роботу через Windows PowerShell ISE
Win10TweakerWarning                       = Ваша ОС, можливо, через бекдор в Win 10 Tweaker заражена трояном
UnsupportedRelease                        = Виявлено нову версію
CustomizationWarning                      = \nВи налаштували всі функції в пресет-файлі Sophia.ps1 перед запуском Sophia Script?
ControlledFolderAccessDisabled            = Контрольований доступ до папок вимкнений
ScheduledTasks                            = Заплановані задачі
WindowsFeaturesTitle                      = Компоненти Windows
OptionalFeaturesTitle                     = Додаткові компоненти
EnableHardwareVT                          = Увімкніть віртуалізацію в UEFI
UserShellFolderNotEmpty                   = У папці "{0}" залишились файли. Перемістіть їх вручну у нове розташування
RetrievingDrivesList                      = Отримання списку дисків...
DriveSelect                               = Виберіть диск, в корні якого буде створена папка для "{0}"
CurrentUserFolderLocation                 = Текуще розташування папок "{0}": "{1}"
UserFolderRequest                         = Хочете змінити розташування папки "{0}"?
UserFolderSelect                          = Виберіть папку для "{0}"
UserDefaultFolder                         = Хочете змінити розташування папки "{0}" на значення за замовчуванням?
GraphicsPerformanceTitle                  = Налаштування продуктивності графіки
GraphicsPerformanceRequest                = Встановити для будь-якої програми за вашим вибором налаштування продуктивності графіки на "Висока продуктивність"?
TaskNotificationTitle                     = Cповіщення
CleanupTaskNotificationTitle              = Важлива інформація
CleanupTaskDescription                    = Очищення зайвих файлів і оновлень Windows, використовуючи вбудовану програму очищення диска
CleanupTaskNotificationEventTitle         = Запустити задачу по очищенню зайвих файлів і оновлень Windows?
CleanupTaskNotificationEvent              = Очищення Windows не займе багато часу. Наступний раз це повідомлення з'явиться через 30 днів
CleanupTaskNotificationSnoozeInterval     = Виберіть інтервал повтору повідомлення
CleanupNotificationTaskDescription        = Спливаюче повідомлення про нагадуванні з очищення зайвих файлів і оновлень Windows
SoftwareDistributionTaskNotificationEvent = Кеш оновлень Windows успішно видалений
TempTaskNotificationEvent                 = Папка тимчасових файлів успішно очищена
FolderTaskDescription                     = Очищення папки "{0}"
EventViewerCustomViewName                 = Створення процесу
EventViewerCustomViewDescription          = Події створення нового процесу і аудит командного рядка
RestartWarning                            = Обов'язково перезавантажте ваш ПК
ErrorsLine                                = Рядок
ErrorsFile                                = Файл
ErrorsMessage                             = Помилки/попередження
Add                                       = Додати
AllFilesFilter                            = Усі файли (*.*)|*.*
Browse                                    = Переглядати
Change                                    = Змінити
DialogBoxOpening                          = Діалогове вікно відкривається...
Disable                                   = Вимкнути
Enable                                    = Увімкнути
EXEFilesFilter                            = *.exe|*.exe|Усі файли (*.*)|*.*
FolderSelect                              = Виберіть папку
FilesWontBeMoved                          = Файли не будуть перенесені
FourHours                                 = 4 години
HalfHour                                  = 30 хвилин
Install                                   = Встановити
Minute                                    = 1 хвилина
NoData                                    = Відсутні дані
NoInternetConnection                      = Відсутнє інтернет-з'єднання
RestartFunction                           = Будь ласка, повторно запустіть функцію "{0}"
NoResponse                                = Не вдалося встановити зв’язок із {0}
No                                        = Немає
Yes                                       = Так
Open                                      = Відкрити
Patient                                   = Будь ласка, зачекайте...
Restore                                   = Відновити
Run                                       = Запустити
SelectAll                                 = Вибрати все
Skip                                      = Пропустити
Skipped                                   = Пропущено
FileExplorerRestartPrompt                 = \nІноді для того, щоб зміни вступили в силу, процес провідника необхідно перезапустити
TelegramGroupTitle                        = Приєднуйтесь до нашої офіційної групи в Telegram
TelegramChannelTitle                      = Приєднуйтесь до нашого офіційного каналу в Telegram
Uninstall                                 = Видалити
'@
