ConvertFrom-StringData -StringData @'
NewSophiaScriptFound                      = Обнаружена новая версия: Sophia Script for Windows {0}. Пожалуйста, скачайте последнюю версию.
UnsupportedPowerShell                     = Вы пытаетесь запустить скрипт в PowerShell {0}.{1}. Запустите скрипт в PowerShell {2}.
CodeCompilationFailed                     = Компиляция кода завершилась с ошибкой.
UnsupportedWindowsBitness                 = Скрипт поддерживает только 64-битную версию Windows.
KeyboardArrows                            = Для выбора используйте стрелки на клавиатуре {0} и {1}
UnsupportedLanguageMode                   = Сессия PowerShell работает в ограниченном режиме.
LoggedInUserNotAdmin                      = Вошедший пользователь "{0}" не обладает правами администратора. Скрипт был запущен от имени "{1}". Пожалуйста, войдите в профиль, обладающий правами администратора и запустите скрипт заново.
UnsupportedHost                           = Скрипт не поддерживает работу через {0}.
HarmfulTweakerFound                       = Стабильность Windows могла быть нарушена использованием {0}.
HostsEntriesFound                         = В файле %SystemRoot%\\System32\\drivers\\etc\\hosts обнаружены сторонние записи. Они могут блокировать соединение с ресурсами, используемыми в работе скрипта. Хотите продолжить?
WindowsComponentStabilityDisrupted        = Обнаружено нарушение стабильности работы компонента "{0}".
DisableControlledFolderAccess             = Вы включили Контролируемый доступ к папкам. Пожалуйста, отключите его и повторите попытку.
RebootPending                             = Ваш компьютер ожидает перезагрузки.
SystemDriveEncryptedBitLockerDisabled     = Диск C зашифрован, хотя BitLocker отключен. Хотите расшифровать диск?
WrongSophiaScriptVersion                  = Скрипт поддерживает только Windows 10 22H2. Вы используете {0} {1}. Запустите скрипт в зависимости от вашей версии Windows.
UpdateWindowsBuild                        = Вы используете Windows 10 {0}.{1}. Поддерживаемые сборки: Windows 10 {0}.{2} и выше. Запустите обновление Windows и повторите попытку.
ESUProgramEnrollment                      = Срок поддержки Windows 10 истек 14 октября 2025 года. Ваш компьютер может быть уязвим для вредоносного ПО, троянских программ и уязвимостей нулевого дня. Хотите присоединиться к программе Расширенных обновлений безопасности (ESU), чтобы получать обновления до 2028 года с помощью TSforge из Microsoft Activation Scripts (MAS)?
CheckSophiaScriptPreset                   = Вы настроили все функции в пресет-файле {0} перед запуском Sophia Script for Windows?
ReinstallWindows                          = Переустановите Windows, используя только подлинный ISO-образ.
CreatingRestorePoint                      = Создается точка восстановления...
UWPComponentsMissing                      = Отсутствует UWP-компонент "{0}".
DefenderComponentsMissing                 = Отсутствует компонент "{0}" для Microsoft Defender.
DiagTrackServiceNotFound                  = Отсутствует служба "DiagTrackService".
NoScheduledTasksFound                     = Нет запланированных задач, которые необходимо отключить.
ScheduledTasks                            = Запланированные задания
TaskbarSmallIcons                         = Вы используете маленькие кнопки панели задач.
SearchHighlightsDisabled                  = Основные результаты поиска в меню "Пуск" уже скрыты.
CustomStartMenuFound                      = Установлено стороннее меню "Пуск".
OneDriveNotInstalled                      = OneDrive уже удален.
OneDriveAccountUsageFound                 = Перед удалением OneDrive выйдите из учетной записи Microsoft в OneDrive.
OneDriveInstalled                         = OneDrive уже установлен.
UninstallingApplication                   = {0} удаляется...
InstallingApplication                     = {0} устанавливается...
NoWindowsFeaturesFound                    = Нет компонентов Windows, которые необходимо отключить.
WindowsFeaturesTitle                      = Компоненты Windows
NoOptionalFeaturesFound                   = Нет дополнительных компонентов Windows, которые необходимо отключить.
NoSupportedNetworkAdaptersFound           = Нет сетевых адаптеров, поддерживающих функцию "Разрешить компьютеру отключать это устройство для экономии энергии".
LocationServicesDisabled                  = Командам сетевой оболочки требуется разрешение на доступ к сведениям беспроводной сети. Включите службы определения местоположения на странице "Расположение" в параметрах конфиденциальности и защиты.
OptionalFeaturesTitle                     = Дополнительные компоненты
UserShellFolderNotEmpty                   = В папке "{0}" остались файлы. Переместите их вручную в новое расположение.
UserFolderLocationMove                    = Не следует перемещать пользовательские папки в корень диска C.
DriveSelect                               = Выберите диск, в корне которого будет создана папка "{0}".
CurrentUserFolderLocation                 = Текущее расположение папки "{0}": "{1}".
FilesWontBeMoved                          = Файлы не будут перенесены.
UserFolderMoveSkipped                     = Вы пропустили изменение расположения пользовательской папки "{0}".
FolderSelect                              = Выберите папку
UserFolderRequest                         = Хотите изменить расположение папки "{0}"?
UserDefaultFolder                         = Хотите изменить расположение папки "{0}" на значение по умолчанию?
ReservedStorageIsInUse                    = Используется зарезервированное хранилище.
ProgramPathNotExists                      = Путь "{0}" не существует.
ProgIdNotExists                           = ProgId "{0}" не существует.
AllFilesFilter                            = Все файлы
JSONNotValid                              = Файл JSON "{0}" невалиден.
PackageNotInstalled                       = Приложение "{0}" не установлено.
PackageIsInstalled                        = Последняя версия {0} уже установлена.
UninstallUWPForAll                        = Для всех пользователей
NoUWPAppsFound                            = Нет UWP-приложений, которые необходимо удалить.
UWPAppsTitle                              = UWP-приложения
ScheduledTaskCreatedByAnotherUser         = Задание "{0}" в Планировщике заданий уже было создано от имени "{1}".
CleanupTaskNotificationTitle              = Очистка Windows
CleanupTaskNotificationEvent              = Запустить задание по очистке неиспользуемых файлов и обновлений Windows?
CleanupTaskDescription                    = Очистка неиспользуемых файлов и обновлений Windows, используя встроенную программу Очистка диска.
CleanupNotificationTaskDescription        = Всплывающее уведомление с напоминанием об очистке неиспользуемых файлов и обновлений Windows.
SoftwareDistributionTaskNotificationEvent = Кэш обновлений Windows успешно удален.
SoftwareDistributionTaskDescription       = Очистка папки кэша обновлений Windows "{0}".
TempTaskNotificationEvent                 = Папка временных файлов успешно очищена.
TempTaskDescription                       = Очистка папки временных файлов "{0}" (%TEMP%).
ScheduledTaskLoggedInUserNotification     = Задание может быть запущено, только если пользователь "{0}" вошел в систему.
ScheduledTaskCreatedNotification          = Создано задание "{0}" в Планировщике заданий.
CleanupTaskCLIDescription                 = Перейдите в папку "Sophia" в Планировщике заданий и запустите задание "Windows Cleanup Notification", чтобы начать очистку неиспользуемых файлов и обновлений Windows.
SoftwareDistributionTaskCLIDescription    = Перейдите в папку "Sophia" в Планировщике заданий и запустите задание "SoftwareDistribution", чтобы начать очистку папки кэша обновлений Windows "{0}".
TempTaskCLIDescription                    = Перейдите в папку "Sophia" в Планировщике заданий и запустите задание "Temp", чтобы начать очистку папки временных файлов "{0}" (%TEMP%).
EventViewerCustomViewName                 = Создание процесса
EventViewerCustomViewDescription          = События создания нового процесса и аудит командной строки.
ThirdPartyAVInstalled                     = Установлен сторонний антивирус.
NoHomeWindowsEditionSupport               = Редакция Windows Домашняя не поддерживает функцию "{0}".
EnableHardwareVT                          = Включите виртуализацию в UEFI.
PhotosNotInstalled                        = Приложение "Фотографии" не установлено.
HEVCInstalled                             = Расширения видео HEVC от производителя устройства уже установлены.
HEVCInstallingApplication                 = Расширения видео HEVC от производителя устройства устанавливаются...
ThirdPartyArchiverInstalled               = Установлен сторонний архиватор.
gpeditNotSupported                        = Редакция Windows Домашняя не поддерживает оснастку Редактора локальной групповой политики (gpedit.msc).
RestartWarning                            = Обязательно перезагрузите ваш ПК.
RestorePointVolume                        = Точки восстановления на диске C занимают {0} ГБ.
ErrorsLine                                = Строка
ErrorsMessage                             = Ошибки, предупреждения и уведомления
Disable                                   = Отключить
Enable                                    = Включить
Install                                   = Установить
Uninstall                                 = Удалить
RestartFunction                           = Пожалуйста, повторно запустите функцию "{0}".
NoConnectionEstablished                   = Невозможно установить соединение с {0}.
Run                                       = Запустить
FunctionSkipped                           = Функция "{0}" пропущена.
DonateToastTitle                          = Вы можете пожертвовать!❤
DotSourcedFunction                        = Пожалуйста, запустите функцию через дот-сорсинг (с точкой в начале):\n. .\\Import-TabCompletion.ps1
'@
