ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                   = The script supports Windows 10 x64 only
UnsupportedOSBuild                     = The script supports Windows 10 1809 Enterprise LTSC
UnsupportedRelease                     = New version found
ControlledFolderAccessDisabled         = Controlled folder access disabled
ScheduledTasks                         = Scheduled tasks
ClearFolder                            = Delete all files in the "{0}" folder?
FilesBlocked                           = The following files are being blocked by third-party party apps. Remove them manually and continue
TempNotEmpty                           = The "{0}" folder is not empty. Clear it manually
WindowsFeaturesWindowTitle             = Windows features
FODWindowTitle                         = Optional features (FODv2)
EnableHardwareVT                       = Enable Virtualization in UEFI
UserShellFolderNotEmpty                = Some files left in the "{0}" folder. Move them manually to a new location
RetrievingDrivesList                   = Retrieving drives list...
NewUserShellFolderLocation             = New location: "{0}"
DesktopDriveSelect                     = Select the drive within the root of which the Desktop folder will be created
DocumentsDriveSelect                   = Select the drive within the root of which the Documents folder will be created
DownloadsDriveSelect                   = Select the drive within the root of which the Downloads folder will be created
MusicDriveSelect                       = Select the drive within the root of which the Music folder will be created
PicturesDriveSelect                    = Select the drive within the root of which the Pictures folder will be created
VideosDriveSelect                      = Select the drive within the root of which the Videos folder will be created
DesktopRequest                         = Would you like to change the location of the Desktop folder?
DocumentsRequest                       = Would you like to change the location of the Documents folder?
DownloadsRequest                       = Would you like to change the location of the Downloads folder?
MusicRequest                           = Would you like to change the location of the Music folder?
PicturesRequest                        = Would you like to change the location of the Pictures folder?
VideosRequest                          = Would you like to change the location of the Videos folder?
DesktopFolderSelect                    = Select a folder for the Desktop folder
DocumentsFolderSelect                  = Select a folder for the Documents folder
DownloadsFolderSelect                  = Select a folder for the Downloads folder
MusicFolderSelect                      = Select a folder for the Music folder
PicturesFolderSelect                   = Select a folder for the Pictures folder
VideosFolderSelect                     = Select a folder for the Videos folder
DesktopDefaultFolder                   = Would you like to change the location of the Desktop folder to the default value?
DocumentsDefaultFolder                 = Would you like to change the location of the Documents folder to the default value?
DownloadsDefaultFolder                 = Would you like to change the location of the Downloads folder to the default value?
MusicDefaultFolder                     = Would you like to change the location of the Music folder to the default value?
PicturesDefaultFolder                  = Would you like to change the location of the Pictures folder to the default value?
VideosDefaultFolder                    = Would you like to change the location of the Videos folder to the default value?
GraphicsPerformanceTitle               = Graphics performance preference
GraphicsPerformanceRequest             = Would you like to set the graphics performance setting of an app of your choice to "High performance"?
CleanUpTaskToast                       = Cleaning up unused Windows files and updates starts in a minute
CleanUpTaskDescription                 = Cleaning up unused Windows files and updates using built-in Disk cleanup app
FolderTaskDescription                  = The "{0}" folder cleaning
ControlledFolderAccess                 = Controlled folder access
ProtectedFoldersRequest                = Would you like to enable Controlled folder access and specify the folder that Microsoft Defender will protect from malicious apps and threats?
ProtectedFoldersListRemoved            = Removed folders
AppControlledFolderRequest             = Would you like to specify an app that is allowed through Controlled Folder access?
AllowedControlledFolderAppsRemoved     = Removed allowed apps
DefenderTitle                          = Microsoft Defender
DefenderExclusionFolderRequest         = Would you like to specify a folder to be excluded from Microsoft Defender malware scans?
DefenderExclusionFoldersListRemoved    = Excluded folders removed
AddDefenderExclusionFileRequest        = Would you like to specify a file to be excluded from Microsoft Defender malware scans?
DefenderExclusionFilesRemoved          = Excluded files removed
EventViewerCustomViewName              = Process Creation
EventViewerCustomViewDescription       = Process creation and command-line auditing events
RestartWarning                         = Make sure to restart your PC
ErrorsLine                             = Line
ErrorsFile                             = File
ErrorsMessage                          = Errors/Warnings
Add                                    = Add
AllFilesFilter                         = All Files (*.*)|*.*
Change                                 = Change
Continue                               = Continue
DialogBoxOpening                       = Displaying the dialog box...
Disable                                = Disable
Enable                                 = Enable
EXEFilesFilter                         = *.exe|*.exe|All Files (*.*)|*.*
FolderSelect                           = Select a folder
FilesWontBeMoved                       = Files will not be moved
NoData                                 = Nothing to display
NoInternetConnection                   = No Internet connection
Patient                                = Please wait...
Select                                 = Select
Skip                                   = Skip
Skipped                                = Skipped
SymbolicSkipped                        = Skipped creating a symbolic link
Uninstall                              = Uninstall
Install                                = Install
'@
