name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # tags:
    # - '*.*.*'
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Run Lint
        run: |
          . "Scripts\Lint.ps1"
