name: Build

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag"
        required: true

jobs:
  build-sophia:
    runs-on: windows-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Download Dependencies
        run: |
          . "Scripts\Building\Dependencies.ps1"

      - name: Windows 10
        run: |
          . "Scripts\Building\Windows_10.ps1"

      - name: Windows 10 PowerShell 7
        run: |
          . "Scripts\Building\Windows_10_PS_7.ps1"

      - name: Windows 10 LTSC 2019
        run: |
          . "Scripts\Building\Windows_10_LTSC_2019.ps1"

      - name: Windows 10 LTSC 2021
        run: |
          . "Scripts\Building\Windows_10_LTSC_2021.ps1"

      - name: Windows 11
        run: |
          . "Scripts\Building\Windows_11.ps1"

      - name: Windows 11 PowerShell 7
        run: |
          . "Scripts\Building\Windows_11_PS_7.ps1"

      - name: Sophia Script for Windows 11 Arm
        run: |
          . "Scripts\Building\Windows_11_Arm.ps1"

      - name: Windows 11 Arm PowerShell 7
        run: |
          . "Scripts\Building\Windows_11_Arm_PS_7.ps1"

      - name: Windows 11 LTSC 2024
        run: |
          . "Scripts\Building\Windows_11_LTSC_2024.ps1"

      - name: Windows 11 LTSC 2024 PowerShell 7
        run: |
          . "Scripts\Building\Windows_11_LTSC_2024_PS7.ps1"

      - name: Sophia Script Wrapper
        run: |
          . "Scripts\Building\Wrapper.ps1"

      - name: SFX Archive
        run: |
          . "Scripts\Building\WinGet_SFX.ps1"

      - name: VirusTotal check
        timeout-minutes: 60
        env:
          VirusTotal_API_Key: ${{ secrets.VIRUSTOTAL_API_KEY }}
        run: |
          . "Scripts\VirusTotal.ps1"

      - name: Release Notes Template
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_TAG: ${{ github.event.inputs.tag }}
        run: |
          . "Scripts\ReleaseNotesTemplate.ps1"

      - name: Uploading
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $Tag   = "${{ inputs.tag }}"
          $ZIP   = @((Get-Item -Path "Sophia_Script\Sophia*.zip").FullName)
          $EXE   = @((Get-Item -Path "Sophia_Script\Sophia*.exe").FullName)
          $Files = $ZIP + $EXE
          $Title = $env:RELEASE_NAME

          gh release create $Tag $Files --title $Title --notes-file ReleaseNotesTemplate.md
