ConvertFrom-StringData -StringData @'
UnsupportedOSBitness                      = Скрипт підтримує тільки Windows 10 x64
UnsupportedOSBuild                        = Скрипт підтримує Windows 10 21H2/22H2+
UpdateWarning                             = Встановлений накопичувальний пакет оновлення Windows 10: {0}. Підтримуваний накопичувальний пакет оновлення: 2006 і вище
UnsupportedLanguageMode                   = Сесія PowerShell працює в обмеженому режимі
LoggedInUserNotAdmin                      = Поточний користувач, що увійшов до системи, не має прав адміністратора
UnsupportedPowerShell                     = Ви намагаєтеся запустити скрипт в PowerShell {0}.{1}. Запустіть скрипт у відповідній версії PowerShell
UnsupportedISE                            = Скрипт не підтримує роботу через Windows PowerShell ISE
Win10TweakerWarning                       = Ваша ОС, можливо, через бекдор в Win 10 Tweaker інфікована трояном. Детальніше: https://itnan.ru/post.php?c=1&p=557388
Windows10DebloaterWarning                 = Стабільність вашої ОС могла бути порушена використанням скрипту Windows10Debloater від Sycnex. З метою профілактики перевстановіть ОС
bin                                       = У папці bin немає файлів. Будь ласка, повторно завантажте архів
RebootPending                             = Комп'ютер очікує на перезавантаження
UnsupportedRelease                        = Виявлено нову версію
CustomizationWarning                      = \nВи налаштували всі функції в пресет-файлі {0} перед запуском Sophia Script?
WindowsBroken                             = \nДеякі компоненти Windows можуть бути пошкоджені
ControlledFolderAccessDisabled            = Контрольований доступ до папок вимкнений
ScheduledTasks                            = Заплановані задачі
OneDriveUninstalling                      = Видалення OneDrive...
OneDriveInstalling                        = OneDrive встановлюється...
OneDriveDownloading                       = Завантажується OneDrive... ~33 МБ
OneDriveWarning                           = Функція "{0}" буде застосована тільки в разі, якщо в пресеті налаштоване видалення програми OneDrive (або програму вже видалено), інакше ламається функціонал резервного копіювання для папок "Робочий стіл" і "Зображення" у OneDrive
WindowsFeaturesTitle                      = Компоненти Windows
OptionalFeaturesTitle                     = Додаткові компоненти
EnableHardwareVT                          = Увімкніть віртуалізацію в UEFI
UserShellFolderNotEmpty                   = У папці "{0}" залишились файли. Перемістіть їх вручну у нове розташування
RetrievingDrivesList                      = Отримання списку дисків...
DriveSelect                               = Виберіть диск, в корні якого буде створена папка для "{0}"
CurrentUserFolderLocation                 = Поточне розташування папок "{0}": "{1}"
UserFolderRequest                         = Хочете змінити розташування папки "{0}"?
UserFolderSelect                          = Виберіть папку для "{0}"
UserDefaultFolder                         = Хочете змінити розташування папки "{0}" на значення за замовчуванням?
ReservedStorageIsInUse                    = Операція не підтримується, поки використовується зарезервоване сховище\nБудь ласка, повторно запустіть функцію "{0}" після перезавантаження
ShortcutPinning                           = Ярлик "{0}" закріплюється на початковому екрані...
UninstallUWPForAll                        = Для всіх користувачів
UWPAppsTitle                              = Програми UWP
HEVCDownloading                           = Завантаження "Розширення відео HEVC від виробника пристрою"... ~2,8 МБ
GraphicsPerformanceTitle                  = Налаштування продуктивності графіки
GraphicsPerformanceRequest                = Встановити для будь-якої програми за вашим вибором налаштування продуктивності графіки на "Висока продуктивність"?
TaskNotificationTitle                     = Cповіщення
CleanupTaskNotificationTitle              = Важлива інформація
CleanupTaskDescription                    = Очищення зайвих файлів і оновлень Windows, використовуючи вбудовану програму очищення дисків
CleanupTaskNotificationEventTitle         = Запустити задачу з очищення зайвих файлів і оновлень Windows?
CleanupTaskNotificationEvent              = Очищення Windows не займе багато часу. Наступний раз це повідомлення з'явиться через 30 днів
CleanupTaskNotificationSnoozeInterval     = Виберіть інтервал повтору повідомлення
CleanupNotificationTaskDescription        = Спливаюче повідомлення з нагадуванням про очищення зайвих файлів і оновлень Windows
SoftwareDistributionTaskNotificationEvent = Кеш оновлень Windows успішно видалений
TempTaskNotificationEvent                 = Папка тимчасових файлів успішно очищена
FolderTaskDescription                     = Очищення папки "{0}"
EventViewerCustomViewName                 = Створення процесу
EventViewerCustomViewDescription          = Події створення нового процесу і аудит командного рядка
RestartWarning                            = Обов'язково перезавантажте ваш ПК
ErrorsLine                                = Рядок
ErrorsFile                                = Файл
ErrorsMessage                             = Помилки/попередження
Add                                       = Додати
AllFilesFilter                            = Усі файли (*.*)|*.*
Browse                                    = Огляд
DialogBoxOpening                          = Діалогове вікно відкривається...
Disable                                   = Вимкнути
Enable                                    = Увімкнути
EXEFilesFilter                            = *.exe|*.exe|Усі файли (*.*)|*.*
FolderSelect                              = Оберіть папку
FilesWontBeMoved                          = Файли не будуть перенесені
FourHours                                 = 4 години
HalfHour                                  = 30 хвилин
Install                                   = Встановити
Minute                                    = 1 хвилина
NoData                                    = Відсутні дані
NoInternetConnection                      = Відсутнє інтернет-з'єднання
RestartFunction                           = Будь ласка, повторно запустіть функцію "{0}"
NoResponse                                = Не вдалося встановити зв’язок із {0}
No                                        = Ні
Yes                                       = Так
Open                                      = Відкрити
Patient                                   = Будь ласка, зачекайте...
Restore                                   = Відновити
Run                                       = Запустити
SelectAll                                 = Обрати все
Skipped                                   = Пропущено
TelegramGroupTitle                        = Приєднуйтесь до нашої офіційної групи в Telegram
TelegramChannelTitle                      = Приєднуйтесь до нашого офіційного каналу в Telegram
DiscordChannelTitle                       = Приєднуйтесь до нашого офіційного каналу в Discord
Uninstall                                 = Видалити
'@
