ConvertFrom-StringData -StringData @'
PowerShellImportFailed                    = Importing modules from PowerShell 5.1 failed. Please close PowerShell 7 console and re-run the script again.
UnsupportedArchitecture                   = Your're using "{0}" based architecture CPU. This script supports x64 architecture based CPU only. Download and run script version for your archicture.
UnsupportedOSBuild                        = The script supports Windows 11 24H2 and higher. You're using {0} {1}. Upgrade your Windows and try again.
UnsupportedWindowsTerminal                = Windows Terminal version is lower than 1.23. Please update it in the Microsoft Store and try again.
UpdateWarning                             = You're using Windows 11 {0}.{1}. Supported builds are Windows 11 {0}.{2} and higher. Run Windows Update and try again.
UnsupportedLanguageMode                   = The PowerShell session is running in a limited language mode.
LoggedInUserNotAdmin                      = The logged-in user {0} doesn't have admin rights. Script was ran on behalf of {1}. Please log into account which has admin rights and run script again.
UnsupportedPowerShell                     = You're trying to run script via PowerShell {0}.{1}. Please run the script in PowerShell {2}.
UnsupportedHost                           = The script doesn't support running via {0}.
Win10TweakerWarning                       = Windows has been infected with a trojan via a Win 10 Tweaker backdoor. Reinstall Windows using only a genuine ISO image.
TweakerWarning                            = The Windows stability may have been compromised by using {0}. Reinstall Windows using only a genuine ISO image.
HostsWarning                              = Third-party entries found in the {0} file. They may block connections to resources used in the script. Do you want to continue?
RebootPending                             = The PC is waiting to be restarted.
BitLockerWarning                          = BitLocker encryption is in progress. Complete BitLocker drive configuration and try again.
UnsupportedRelease                        = A newer Sophia Script version found: {0}. Please download the latest version.
KeyboardArrows                            = Please use the arrow keys {0} and {1} on your keyboard to select your answer
CustomizationWarning                      = Have you customized every function in the {0} preset file before running Sophia Script?
WindowsComponentBroken                    = {0} broken or removed from Windows. Reinstall Windows using only a genuine ISO image.
MicroSoftStorePowerShellWarning           = PowerShell downloaded from the Microsoft Store is not supported. Please run an MSI version.\nhttps://github.com/powershell/powershell/releases/latest
ControlledFolderAccessDisabled            = Controlled folder access disabled.
ScheduledTasks                            = Scheduled tasks
UninstallNotification                     = {0} is being uninstalled...
DownloadNotification                      = {0} is being downloaded...
InstallNotification                       = {0} is being installed...
OneDriveUsageWarning                      = Please log out from OneDrive account before uninstalling the application.
WindowsFeaturesTitle                      = Windows features
OptionalFeaturesTitle                     = Optional features
EnableHardwareVT                          = Enable Virtualization in UEFI.
UserShellFolderNotEmpty                   = Some files left in the "{0}" folder. Move them manually to a new location.
UserFolderLocationMove                    = You shouldn't change user folder location to C drive root.
DriveSelect                               = Select the drive within the root of which the "{0}" folder will be created.
CurrentUserFolderLocation                 = The current "{0}" folder location: "{1}".
UserFolderRequest                         = Would you like to change the location of the "{0}" folder?
UserDefaultFolder                         = Would you like to change the location of the "{0}" folder to the default value?
ReservedStorageIsInUse                    = This operation is not supported when reserved storage is in use\nPlease re-run the "{0}" function again after PC restart.
UninstallUWPForAll                        = For all users
UWPAppsTitle                              = UWP Apps
GraphicsPerformanceTitle                  = Would you like to set the graphics performance setting of an app of your choice to "High performance"?
ScheduledTaskPresented                    = The "{0}" function was already created as "{1}".
CleanupTaskNotificationTitle              = Windows clean up
CleanupTaskNotificationEvent              = Run task to clean up Windows unused files and updates?
CleanupTaskDescription                    = Cleaning up Windows unused files and updates using built-in Disk cleanup app. Scheduled task can be run only if user "{0}" logged into the system.
CleanupNotificationTaskDescription        = Pop-up notification reminder about cleaning up Windows unused files and updates. Scheduled task can be run only if user "{0}" logged into the system.
SoftwareDistributionTaskNotificationEvent = Windows update cache successfully deleted.
TempTaskNotificationEvent                 = Temporary files folder successfully cleaned up.
FolderTaskDescription                     = The {0} folder cleanup. Scheduled task can be run only if user "{0}" logged into the system.
EventViewerCustomViewName                 = Process Creation
EventViewerCustomViewDescription          = Process creation and command-line auditing events.
RestartWarning                            = Make sure to restart your PC.
ErrorsLine                                = Line
ErrorsMessage                             = Errors/Warnings
DialogBoxOpening                          = Displaying dialog box...
Disable                                   = Disable
Enable                                    = Enable
AllFilesFilter                            = All Files
FolderSelect                              = Select a folder
FilesWontBeMoved                          = Files will not be moved.
Install                                   = Install
Uninstall                                 = Uninstall
NoData                                    = Nothing to display.
RestartFunction                           = Please re-run the "{0}" function.
NoResponse                                = A connection could not be established with {0}.
Restore                                   = Restore
Run                                       = Run
Skipped                                   = Function "{0}" skipped.
ThankfulToastTitle                        = Thank you for using Sophia Script ❤️
DonateToastTitle                          = You may donate below 🕊️
DotSourcedWarning                         = Please dot-source the function (with a dot at the beginning):\n. .\\Import-TabCompletion.ps1
'@
